dmlc/xgboost

R-package/R/xgb.model.dt.tree.R

https://github.com/tqchen/xgboost/issues/141

avoid warning message when a tree is just made of one leaf

---

multi-node/hadoop/README.md
multi-node/hadoop/mushroom.hadoop.conf
multi-node/hadoop/run_hadoop_mushroom.sh

revise README and add more details

doc modification

---

.gitignore
R-package/R/xgb.cv.R
R-package/R/xgb.dump.R
R-package/R/xgb.importance.R
R-package/R/xgb.model.dt.tree.R
R-package/R/xgb.plot.tree.R
src/tree/updater_colmaker-inl.hpp

https://github.com/tqchen/xgboost/issues/147

Fix global variable message (Cran Checks)

---

R-package/R/xgb.cv.R
R-package/man/xgb.cv.Rd
README.md

Please check the detail part documentation I added is correct before accepting the pull request.
Moreover it was indicated as accepting only xgb.DMatrix as input but obviously it can accept sparse Matrix (I tested + nothing in the code indicates it can't).

Cross validation documentation improvement

---

demo/guide-python/sklearn_examples.py
wrapper/xgboost.py

Thanks for your feedback, Tianqi. A clean fork fixed the readme issue, and the code is now catching import errors if the user doesn't have sklearn installed.

Scikit-Learn Wrapper For XGBoost

---

wrapper/xgboost.py

Whoops, sorry, forgot to test predict_proba() for the multiclass case, and left a line of old code in there.

Bugfix for multiclass sklearn wrapper

---

wrapper/xgboost.py

*Fix XGBClassifier super()

---

wrapper/xgboost.py

not a clever solution, but it should fix #221

*Fix Sklearn.grid_search error

---

R-package/R/utils.R

Fix length check in utils.R

---

R-package/R/xgb.model.dt.tree.R

Fixed parsing of negative reals, integers and scientific notation which
can occur in the model dump.

Fixing parsing of model dump text file in R

---

doc/parameter.md

add default value of gamma in parameter.md, which is zero.

add default value of gamma in parameter.md

---

wrapper/xgboost.py

record the evaluation results in train()
Associated issue: #250

Python: record evaluation results in train()

---

doc/python.md

add documentation on how to predict with the best iteration from training

add doc for Python wrapper

---

wrapper/xgboost.py

Makes the estimator a bit more like scikit-learn.

Add n_classes_ to fitted XGBClassifier

---

R-package/R/xgb.plot.importance.R

Suppress a Note in Cran check

---

R-package/R/utils.R

Needed if someone uses custom objective functions through obj parameter in xgb.cv. 
Also added a safeguard against someone attempting automatic CV folds creation with ranking.

Improved logic in stratified CV

---

doc/build.md

The complete ways to install XGBoost in OS X.

---

doc/param_tuning.md

Fixed some typos and sentence structure. Please review.

Fixed typos and sentence structure

---

wrapper/xgboost.py

This could probably use some tests for Python 2.x and Windows specifically. Seems to work ok on OSX with Python 3.4.

ENH: Make XGBModel pickleable.

---

wrapper/xgboost.py

Fix typo for undefined exception.

BUG: XGBError -> XGBoostError

---

wrapper/xgboost.py

Don't merge yet. I need to make sure they clone with the new keyword.

ENH: Allow settable missing value in sklearn api.

---

wrapper/xgboost.py

Overlooked that this is a potential use case.

ENH: Allow missing = 0

---

doc/parameter.md

only updated for tree booster parameters

Update parameter.md to include parameter ranges

---

R-package/README.md

I was facing this issue and this workaround worked for me. Maybe this should be moved to know issues section.

Adding workaround for install the R-package

---

wrapper/xgboost.py

Fixes type check for evals_result, described in issue #392

fix wrapper dict issue #392

---

R-package/R/xgb.model.dt.tree.R

That's a very annoying bug which should be fixed. Data.table v1.9.5 has fixes for "fread" function and a lot more, which make my life easier. Also i've checked that this fix works for data.table v 1.9.4 nicely.
I haven't observed any degradation in time.
Thank you for the great library.

issue #368, data.table problems

---

demo/guide-python/sklearn_examples.py
wrapper/xgboost.py

Don't merge yet but feel free to review. I want to get a little more experience using it. 
Things I'm not sure about. 
Should `sample_weights` also be passed through to the `evals` DMatrices? I also didn't change either of the `predict` functions to use the `best_iteration_` number from early-stopping mainly because this is not usually want I'd want to do, but I'm open to being convinced that it would be helpful/desirable.

ENH: Allow early stopping through scikit-learn API

---

demo/guide-python/README.md
demo/guide-python/runall.sh

Made a few minor corrections/updates:
- fixed a dead link in the README
- added a missing link to the README
- added several missing scripts to runall.sh

Cleaned up guide-python directory.

---

doc/parameter.md

alpha & lambda descriptions to "Parameters for Tree Booster" added (issue #466)

alpha & lambda for gbtree

---

CONTRIBUTORS.md
R-package/tests/testthat/test_custom_objective.R
R-package/tests/testthat/test_helpers.R
R-package/tests/testthat/test_poisson_regression.R

Let's see if this passes Travis...

More thorough unit testing for R package

---

python-package/xgboost/core.py
tests/python/test_basic.py

Follow-up for the @tqchen 's comment on #488.
Also, moved tests to use ``unittest`` to check some error handlings.

Cleanup str roundtrip using ctypes

---

CHANGES.md
R-package/R/predict.xgb.Booster.R
R-package/R/utils.R
R-package/R/xgb.DMatrix.R
R-package/R/xgb.cv.R
R-package/R/xgboost.R

For R users, I think that missing values are typically expressed as NAs, not 0s.

Switch missing values from 0 to NA in R package

---

python-package/xgboost/sklearn.py

added params:
alpha, lambda, colsample_bylevel and scale_pos_weight

added missing params to sklearn python wrapper

---

R-package/tests/testthat/test_lint.R

Just wanna upload this to repo first and we'll deal with all the lint issues later. @hetong007  Thanks.

Added test_lint.R to test code quality

---

doc/python/python_intro.md

Simply cleaning up the wording a little bit to make it clearer.

Clarifies wording on Data Interface intro list

---

doc/parameter.md

just clarifying some of the language describing the parameters

minor wording update

---

python-package/xgboost/training.py

Yields learning rate decay via list of learning rates per boosting round or function of current boosting round and num_boost_round.

learning_rates per boosting round

---

python-package/xgboost/sklearn.py

added output_margin & ntree_limit to predict and predict_proba

sklearn_wrapper additions

---

python-package/xgboost/training.py
tests/python/test_training_continuation.py

+ training continuation of existing model
+ maximize parameter just like in R package (whether to maximize feval)

python training continuation & maximize parameter

---

python-package/xgboost/training.py

- implements early_stopping_rounds parameter for cv
issue https://github.com/dmlc/xgboost/issues/529#issuecomment-154198031
- unittest

early stopping for CV (python)

---

demo/README.md

Fixed broken link for R 'First N Trees' sample.

Fixing broken link for R sample.

---

tests/python/test_early_stopping.py

added lost unittest of PR https://github.com/dmlc/xgboost/pull/602

python: unittest for early stopping of cv

---

python-package/xgboost/training.py

avoid dict comprehension for python 2.6 compatibility

python 2.6 compatibility

---

python-package/xgboost/training.py

Printing the evaluation metric every boosting stage is very handy, but if you have a lot of boosting rounds it will become a long cluttered list and can for example slow down Chrome when using iPython.
The verbose_eval extension will make it possible to print the evaluation metric **not every boosting round**, but every **x** boosting rounds by assigning it an ```integer``` instead of ```True```. It will always print the last boosting round and when given ```early_stopping_rounds``` it will print the best iteration.
The old functionality stays the same, this will only give you extra functionality. There is one exception. In current master the best iteration was printed, even if you explicitly use ```verbose_eval=False```. After this update, it will not anymore. If you say you don't want …

Python verbose_eval extension

---

CONTRIBUTORS.md
doc/model.md

I tried to make the minimal changes necessary to fix pluralization, tense agreement, spelling, sentence fragments, etc.

grammar/style fixes for "Introduction to Boosted Trees" docs

---

R-package/demo/basic_walkthrough.R

To close #431 
Easier to make a new PR
Drop switching to cat function for the display because cat doesn't include a new line at the end of the text printed.

Implement #431 PR

---

python-package/xgboost/training.py

ensures same behavior for verbose_eval=0 and verbose_eval=False

small verbose_eval fixes

---

R-package/R/predict.xgb.Booster.R
R-package/R/xgb.importance.R
R-package/demo/basic_walkthrough.R
R-package/demo/boost_from_prediction.R
R-package/demo/create_sparse_matrix.R
R-package/demo/cross_validation.R
R-package/demo/predict_leaf_indices.R
R-package/man/predict-xgb.Booster-method.Rd
R-package/man/xgb.importance.Rd
R-package/vignettes/discoverYourData.Rmd
R-package/vignettes/xgboostPresentation.Rmd

Close https://github.com/dmlc/xgboost/issues/383

Code cleaning + doc improvement #Rstat

---

.travis.yml
python-package/.pylintrc
python-package/setup_pip.py
python-package/xgboost/compat.py
python-package/xgboost/core.py
python-package/xgboost/plotting.py
python-package/xgboost/sklearn.py

@pommedeterresautee FYI, this should fix pylint test.

Pylint Fixes

---

.gitignore
src/data.h
src/gbm/gbm.h
src/gbm/gbtree-inl.hpp
src/io/io.h
src/io/libsvm_parser.h
src/io/page_fmatrix-inl.hpp
src/io/simple_dmatrix-inl.hpp
src/io/simple_fmatrix-inl.hpp
src/io/sparse_batch_page.h
src/learner/dmatrix.h
src/learner/evaluation-inl.hpp
src/learner/helper_utils.h
src/learner/learner-inl.hpp
src/learner/objective-inl.hpp
src/learner/objective.h
src/tree/model.h
src/tree/param.h
src/tree/updater.h
src/tree/updater_colmaker-inl.hpp
src/tree/updater_prune-inl.hpp
src/utils/base64-inl.h
src/utils/fmap.h
src/utils/iterator.h
src/utils/quantile.h
src/utils/random.h
src/utils/thread_buffer.h
src/utils/utils.h

I was reading through the code and fixing some things in the comments. Only a few trivial actual code changes were made to make it a bit more readable.
And it wouldn't hurt to have Eclipse project artifacts in .gitignore

Spelling, wording, and doc fixes in c++ code

---

Makefile
java/create_wrap.sh
src/io/dmlc_simple.cpp
src/utils/io.h

also make java/create_wrap.sh a bit more convenient to use

small fixes for make and gcc warnings

---

subtree/rabit/windows/rabit/rabit.vcxproj
windows/xgboost/xgboost.vcxproj

change the project file to fix windows compile problem

fix windows compile problem

---

python-package/xgboost/training.py
tests/python/test_basic.py

- fixed bug if both eval_metrics xgb-param and metrics param of cv function have been set
- cv early stopping output looks now like the one of xgb.train

python cv bugfixing (eval metrics)

---

R-package/R/xgb.cv.R
R-package/R/xgb.train.R

Hey guys,
Great work on the R package!
This is a simple pull request that adds newline characters to the early.stop.round output messages within R.
Let me know if you have any questions about the request!

Add newline chars to early.stop.round message

---

demo/regression/README.md

Hi guys,
I think "reg:linear" corresponds to linear regression.

Fix typo in demo/regression/README.md

---

doc/model.md

Hello,
I've removed a redundant "the" in the doc.

Remove redundant word

---

Makefile
java/xgboost4j_wrapper.cpp

#736 modified java wrapper building settings for refactor of xgboost core library

modify java wrapper settings for new refactor

---

NEWS.md

[docs] Fix typo in release notes

---

R-package/vignettes/xgboost.Rnw
R-package/vignettes/xgboostPresentation.Rmd
doc/R-package/Makefile
doc/R-package/xgboostPresentation.md
doc/build.md

(1) fixed the Rmarkdown error (close #760 )
(2) add drat repo in the doc (close #773 )
(3) Since we are using submodule, which is not supported well by `devtools`. So do not let user install from `devtools`.

[R] update doc (close #760, close #773)

---

R-package/R/xgb.cv.R

https://github.com/dmlc/xgboost/issues/807

Fix CV which was monitoring train-metric

---

python-package/xgboost/compat.py
python-package/xgboost/training.py
tests/python/test_cv.py

- two new parameters for python xgb.cv: *stratified* and *folds*
- stratified = False per default to keep current behavior
- user can pass sklearn KFolds or StratifiedKFolds via *folds* parameter 
- unit test added
- stratified = True depends on sklearn (install check implemented)

stratified cv for python wrapper

---

python-package/xgboost/training.py

Request for solving the problem in the tests of my contribution

---

R-package/README.md
doc/R-package/discoverYourData.md
doc/R-package/xgboostPresentation.md
doc/build.md

(1) install_github is not support due to the usage of submodule
(2) remove part of the markdown which is not displayed correctly, see
https://xgboost.readthedocs.org/en/latest/R-package/discoverYourData.html

[Doc] documents update. close #821

---

demo/README.md

Awesome XGboost page as @tqchen has suggested. It is the first version which contains the recent winning solutions using xgboost, interviews, tutorials, as well as list of tools, awards, and predictive services powered by xgboost.

Awesome-XGBoost page

---

doc/parameter.md
src/metric/elementwise_metric.cc

Retry to add "mean absolute error" to metrics

Add "mean absolute error" to metrics 

---

python-package/setup.py

the description field was set to what should be the long_description field -- making a bit of a mess on PyPi

fix PyPi Description issue

---

doc/parameter.md

Just add Hyperlink for Multiclass logloss

add url for mlogloss

---

python-package/xgboost/sklearn.py

The property feature_importances_ was wrongly implemented. It should return a float array as RandomForestClassifier and others.

Improve compatibility with sklearn

---

jvm-packages/pom.xml
jvm-packages/scalastyle-config.xml
jvm-packages/xgboost4j/pom.xml
jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/DMatrix.scala
jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/EvalTrait.scala
jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/ObjectiveTrait.scala
jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/XGBoost.scala
jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/BoosterImplTest.java
jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/DMatrixTest.java
jvm-packages/xgboost4j/src/test/scala/ml/dmlc/xgboost4j/scala/DMatrixSuite.scala
jvm-packages/xgboost4j/src/test/scala/ml/dmlc/xgboost4j/scala/ScalaBoosterImplSuite.scala

add test cases for Scala API

---

jvm-packages/checkstyle.xml
jvm-packages/xgboost4j-demo/src/main/java/ml/dmlc/xgboost4j/demo/CustomObjective.java
jvm-packages/xgboost4j-demo/src/main/java/ml/dmlc/xgboost4j/demo/DistTrain.java
jvm-packages/xgboost4j-demo/src/main/java/ml/dmlc/xgboost4j/demo/GeneralizedLinearModel.java
jvm-packages/xgboost4j-demo/src/main/java/ml/dmlc/xgboost4j/demo/util/CustomEval.java
jvm-packages/xgboost4j-demo/src/main/java/ml/dmlc/xgboost4j/demo/util/DataLoader.java
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/DMatrix.java
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/JNIErrorHandle.java
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/JavaBoosterImpl.java
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/NativeLibLoader.java
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/Rabit.java
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/XGBoost.java
jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/ScalaBoosterImpl.scala
jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/XGBoost.scala
jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/BoosterImplTest.java
jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/DMatrixTest.java

The PR imposes google-java-style indentation and impose the import order in source files 
cc: @tqchen , Please merge https://github.com/dmlc/xgboost/pull/905 first,

apply google-java-style indentation and impose import orders

---

jvm-packages/pom.xml
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/LabeledPoint.java
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/DMatrix.java
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/DataBatch.java
jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/DMatrix.scala
jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/DMatrixTest.java

[JVM] Add LabeledPoint read support

---

jvm-packages/test_distributed.sh
jvm-packages/xgboost4j-flink/pom.xml
jvm-packages/xgboost4j-flink/src/main/scala/ml/dmlc/xgboost4j/flink/Test.scala
jvm-packages/xgboost4j-flink/src/main/scala/ml/dmlc/xgboost4j/flink/XGBoost.scala
jvm-packages/xgboost4j-flink/src/main/scala/ml/dmlc/xgboost4j/flink/XGBoostModel.scala

@CodingCat we can use this as a cross ref on implementations. The flink now works.

[FLINK] Make runnable flink

---

jvm-packages/README.md
jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/spark/example/DistTrainWithSpark.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/DataUtils.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala

[Spark] Refactor train, predict, add save

---

jvm-packages/xgboost4j-example/README.md
jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/BasicWalkThrough.scala
jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/BoostFromPrediction.scala
jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/CrossValidation.scala
jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/CustomObjective.scala
jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/ExternalMemory.scala
jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/GeneralizedLinearModel.scala
jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/PredictFirstNTree.scala
jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/PredictLeafIndices.scala
jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/flink/DistTrainWithFlink.scala
jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/spark/DistTrainWithSpark.scala
jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/util/CustomEval.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala

https://github.com/dmlc/xgboost/pull/942 first

Scala examples

---

jvm-packages/xgboost4j-example/README.md

@tqchen sorry, just didn't check after updating README

fix typo in README

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostSuite.scala

we do not need to shuffle and repartition everytime...@tqchen

[jvm-packages] allow the user to specify the worker number and avoid unnecessary shuffle

---

demo/README.md

Uses the xgboost python package: https://rhiever.github.io/tpot/installing/
tpot's [setup.py](https://github.com/rhiever/tpot/blob/master/setup.py)

Add tpot to Tools using XGBoost

---

doc/jvm/index.md
jvm-packages/pom.xml

[jvm-packages] jvm doc index

---

doc/jvm/index.md
jvm-packages/README.md
jvm-packages/pom.xml
jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/spark/DistTrainWithSpark.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostSuite.scala
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java
jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/Booster.scala

patch to solve https://github.com/dmlc/xgboost/issues/974 and https://github.com/dmlc/xgboost/issues/972
https://github.com/dmlc/xgboost/pull/978 first

[jvm-packages] support kryo serialization 

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala

allow the user to access the low-level APIs in Booster.....

[jvm-packages] getter of XGBoostModel

---

LICENSE
README.md
doc/conf.py

I found that year in files is not up-to-date. So i changed it: 2015 -> 2016

update year in LICENSE, conf.py and README.md files

---

demo/README.md

I have edited the "Machine Learning Challenge Winning Solutions" of demo/README.md. Please see Airbnb New User Bookings, Winner’s Interview: 2nd place, Keiichi Kuroyanagi (@Keiku) | no free hunch http://blog.kaggle.com/2016/03/17/airbnb-new-user-bookings-winners-interview-2nd-place-keiichi-kuroyanagi-keiku/

Add a new winning solution to demo/README.md

---

demo/README.md

Winning solution added: "Homesite Quote Conversion" (Kaggle)

winning solution

---

doc/jvm/index.md

adding “-DskipTests” to Docs for JVM. without this flag building takes
forever

updating JVM docs

---

doc/jvm/index.md

Reverts dmlc/xgboost#1100
I would like to revert this PR, as test takes forever is an indicator of the error in local environment (or potential bug in XGBoost4J)....@tqchen

Revert "updating JVM docs"

---

python-package/xgboost/core.py
tests/python/test_with_sklearn.py

get split value histogram of a feature:
`gbdt.get_split_value_histogram('f29', bins=5)`
```
f29  SplitValue  Count
0           7.2     39
1          13.9      9
2          20.6      3
3          27.3      1
4          34.0      2
```

[py] split value histograms

---

R-package/vignettes/discoverYourData.Rmd

fixed typo

---

python-package/xgboost/core.py
python-package/xgboost/sklearn.py
tests/python/test_basic.py
tests/python/test_basic_models.py

Bug mixing DMatrix's with and without feature names

---

python-package/xgboost/training.py
tests/python/test_basic_models.py

- bugfix like in PR https://github.com/dmlc/xgboost/pull/1160
- better unit tests

[py] eta decay bugfix

---

python-package/xgboost/sklearn.py

Added a function in sklearn API to return the predicted leaves, this function is called apply to comply with sklearn's similar functions for trees and random forests.

[py] added apply function in sklearn API to return the predicted leaves

---

python-package/xgboost/sklearn.py

reg_lambda and reg_alpha should be swapped

XGBModel doctstring

---

doc/parameter.md
src/gbm/gbtree.cc

I found my mistakes.
https://github.com/marugari/Notebooks/blob/master/test_dart.ipynb

fix Dart::NormalizeTrees

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala

Fix for https://github.com/dmlc/xgboost/issues/1277
After thinking about several solutions, I found that the minimum intrusive way to handle the situation is to explicitly throw the exception

[jvm-packages] explicitly throw exception when detecting empty partition in training dataset

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostSuite.scala
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/DMatrix.java
jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/DMatrix.scala
jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/DMatrixTest.java
jvm-packages/xgboost4j/src/test/scala/ml/dmlc/xgboost4j/scala/DMatrixSuite.scala

[jvm-packages] create dmatrix with specified missing value

---

jvm-packages/README.md

Corrected some typos and formatting - sorry for the inconvenience :)

Typos in README

---

doc/_static/xgboost-theme/index.html

Hi there,
I hope this documentation fix is helpful.
Thanks,
Ryan

Fix spelling error.

---

doc/parameter.md
doc/tutorials/dart.md
doc/tutorials/index.md

https://github.com/dmlc/xgboost/issues/809

add Dart tutorial

---

python-package/xgboost/sklearn.py

Label encoding in `XGBClassifier` is done after putting the eval sets into DMatrix format, thus the labels of these sets aren't encoded which can trigger an error (most of the cases, it happens not to be useful to encode the labels).

[py] fix label encoding of eval sets in sklearn API

---

doc/parameter.md
src/metric/elementwise_metric.cc

1) Add a new metric for gamma regression (gamma-deviance);
2) Simplify the computation of nloglik for gamma regression.

Metrics for gamma regression

---

jvm-packages/xgboost4j-example/pom.xml
jvm-packages/xgboost4j-spark/pom.xml

https://github.com/dmlc/xgboost/issues/1377

fix #1377 spark-mllib scope: default => provided

---

CONTRIBUTORS.md

https://github.com/dmlc/xgboost/pull/1417

Updated - fix merged

---

ISSUE_TEMPLATE.md

@phunterlau @hetong007 @CodingCat @terrytangyuan 
Please add more you think necessary to reproduce an issue.
For issue template on github, see https://help.github.com/articles/creating-an-issue-template-for-your-repository/
A good example can be found from https://github.com/tensorflow/tensorflow/blob/master/ISSUE_TEMPLATE.md

[Doc] issue template (close #1469)

---

doc/build.md

Fixed syntax error in https://xgboost.readthedocs.io/en/latest/build.html

Fixed markdown syntax error 

---

demo/distributed-training/README.md

resolved dead link in demo/distributed-training/README.md

---

R-package/tests/testthat/test_gc_safety.R

This is a change following https://github.com/dmlc/xgboost/pull/1489.

Add unittest for garbage collection's safety in R

---

python-package/build_trouble_shooting.md

I found this typo in another location as well.

Fixes another typo "candicate"

---

python-package/xgboost/callback.py

A simple fix for an issue explained in #1450

Fix how maximize_metric value is determined in early_stop

---

Makefile
python-package/xgboost/__init__.py

open the "VERSION" file using the ''with'' statement

[python-package] modify __init__.py

---

demo/README.md

Added ouselves to your showcase for xgboost winning major ML competitions.

Added KDD Cup 2016 competition

---

doc/build.md

Apologies for 2 PRs, was easier using githubs interface rather than doing it through git

Update build.md - added link to nightly windows binaries

---

demo/README.md

Added a link to the nightly windows binaries hosted on Guido Tapia's (my) blog

Update README.md - added windows binaries

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/DMatrix.java
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoostJNI.java
jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/DMatrix.scala
jvm-packages/xgboost4j/src/native/xgboost4j.cpp
jvm-packages/xgboost4j/src/native/xgboost4j.h
jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/DMatrixTest.java
jvm-packages/xgboost4j/src/test/scala/ml/dmlc/xgboost4j/scala/DMatrixSuite.scala

To adapt to https://github.com/dmlc/xgboost/pull/1606

[jvm-packages] Robust dmatrix creation

---

src/c_api/c_api.cc
src/learner.cc

A fix to the issue 1474 (https://github.com/dmlc/xgboost/issues/1474)

Fix the issue 1474

---

.travis.yml
jvm-packages/create_jni.sh
jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/spark/SparkWithRDD.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/DataUtils.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassificationModel.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostEstimator.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressionModel.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/EvalError.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/SharedSparkContext.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/Utils.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostConfigureSuite.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostDFSuite.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala
jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/EvalTrait.scala
src/c_api/c_api.cc

This PR proposes to separate the regression and classification model of XGBoost into two files, which is to be consistent with the design of other machine learning libraries, e.g. Spark ML package, XGBoost Python package, etc. The most significant benefit brought by this design is to provide the clear organization of parameters and facilitate the pipeline building. 
Additionally, this PR contains the integration with Spark ML package to be compatible with the latest version of Spark
`XGBoostEstimator` implements the algorithm of XGBoost. Depending on the user-specified training task type, XGBoostEstimator.fit() produces either  `XGBoostClassificationModel` or `XGBoostRegressionModel`. 
`XGBoostClassificationModel` implements the RDD-based prediction and IO functionalities of a trained …

[jvm-packages] separate classification and regression model and integrate with ML package

---

python-package/xgboost/compat.py

import KFold & StratifiedKFold from sklearn.model_selection instead of sklearn.cross_validation
see http://scikit-learn.org/dev/whats_new.html#version-0-18

add scikit-learn v0.18 compatibility

---

CMakeLists.txt
plugin/updater_gpu/README.md
plugin/updater_gpu/speed_test.py
plugin/updater_gpu/src/cuda_helpers.cuh
plugin/updater_gpu/src/find_split.cuh
plugin/updater_gpu/src/find_split_multiscan.cuh
plugin/updater_gpu/src/find_split_sorting.cuh
plugin/updater_gpu/src/gpu_builder.cu
plugin/updater_gpu/src/gpu_builder.cuh
plugin/updater_gpu/src/loss_functions.cuh
plugin/updater_gpu/src/types.cuh
plugin/updater_gpu/src/types_functions.cuh
plugin/updater_gpu/src/updater_gpu.cc
plugin/updater_gpu/test.py
src/tree/param.h
src/tree/updater_skmaker.cc

Newer version of the algorithm supporting trees of arbitrary depth while keeping speed advantages.
All .cuh files should pass the linter now also.

Add GPU accelerated tree construction plugin

---

doc/parameter.md

scale_pos_weight default value

---

doc/jvm/java_intro.md
doc/parameter.md

Closes https://github.com/dmlc/xgboost/issues/1732

Add docs fro update_seq

---

R-package/demo/tweedie_regression.R
doc/parameter.md
src/metric/elementwise_metric.cc
src/objective/regression_obj.cc

re-submitting after rebase... originally in reference to issues #1392 and #681

Tweedie Regression Post-Rebase

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala

Fix a small typo in GeneralParams class

---

CMakeLists.txt
appveyor.yml
plugin/updater_gpu/src/cuda_helpers.cuh
plugin/updater_gpu/src/gpu_builder.cu
plugin/updater_gpu/src/types.cuh

Added an AppVeyor script. Should prevent issues related to #1751 #1744

GPU plug-in improvements + basic Windows continuous integration

---

R-package/R/xgb.cv.R

Typo Problem

---

python-package/setup.py

Added license information to the setup.py

Added license information

---

plugin/updater_gpu/README.md
plugin/updater_gpu/speed_test.py
plugin/updater_gpu/src/device_helpers.cuh
plugin/updater_gpu/src/find_split.cuh
plugin/updater_gpu/src/find_split_multiscan.cuh
plugin/updater_gpu/src/find_split_sorting.cuh
plugin/updater_gpu/src/gpu_builder.cu
plugin/updater_gpu/src/gpu_builder.cuh
plugin/updater_gpu/src/types.cuh
src/tree/param.h

GPU algorithm:
Improved build instructions with feedback from users. Memory usage decreased dramatically. 
Algorithm now automatically detects if there is not enough device memory and performs row subsampling.

Update build instructions,  improve memory usage

---

README.md

Change contribution link to open issues.

change contribution link to open issues

---

src/objective/rank_obj.cc

https://github.com/dmlc/xgboost/pull/1642

Fix issue introduced from correction to log2

---

src/c_api/c_api.cc
src/data/simple_dmatrix.cc
src/data/sparse_page_dmatrix.cc
src/gbm/gbtree.cc
src/tree/updater_basemaker-inl.h
src/tree/updater_colmaker.cc
src/tree/updater_histmaker.cc
src/tree/updater_refresh.cc
src/tree/updater_skmaker.cc

See also: http://stackoverflow.com/questions/8969748/omp-set-num-threads-not-working

Changing omp_get_num_threads to omp_get_max_threads

---

CMakeLists.txt
plugin/updater_gpu/README.md
plugin/updater_gpu/src/device_helpers.cuh
plugin/updater_gpu/src/gpu_builder.cu
plugin/updater_gpu/src/gpu_builder.cuh

Added some speed benchmarks to the readme. Fixed a couple of issues with Linux build.

GPU Plugin: Add benchmarks, fix GCC build

---

include/xgboost/learner.h

fix typo in comment.

---

python-package/xgboost/plotting.py

this support may useful to the one who care about the interpretion of model

python package tree plotting support fmap

---

doc/tutorials/index.md
doc/tutorials/monotonic.md

Synched with more current version of the code.
TODO's removed.

Add monotonic tutorial.

---

demo/gpu_acceleration/README.md
demo/gpu_acceleration/bosch.py
plugin/updater_gpu/README.md
plugin/updater_gpu/src/device_helpers.cuh
plugin/updater_gpu/src/find_split.cuh
plugin/updater_gpu/src/find_split_multiscan.cuh
plugin/updater_gpu/src/find_split_sorting.cuh
plugin/updater_gpu/src/gpu_builder.cu
plugin/updater_gpu/src/gpu_builder.cuh
plugin/updater_gpu/src/gpu_data.cuh

Implement parameters consistently with xgboost.

GPU Plugin: Add subsample, colsample_bytree, colsample_bylevel

---

doc/model.md
doc/tutorials/aws_yarn.md
doc/tutorials/dart.md
doc/tutorials/index.md
doc/tutorials/monotonic.md

Almost no changes in content or word choice; just small punctuation/spelling bits that make the documentation a little more readable.

Correcting small typos in documentation.

---

R-package/R/xgb.cv.R

change valudation to validation

Validation Typo

---

doc/python/python_intro.md

Fix for [#2016](https://github.com/dmlc/xgboost/issues/2016)

Fix typo in Python Package Introduction

---

NEWS.md
src/c_api/c_api.cc
src/tree/updater_colmaker.cc
src/tree/updater_histmaker.cc

Solves https://github.com/dmlc/xgboost/issues/2053

Automatically remove nan from input data when it is sparse.

---

.gitignore
jvm-packages/pom.xml
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/BoosterParams.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostDFSuite.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoost.java
jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/XGBoost.scala
jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/BoosterImplTest.java
jvm-packages/xgboost4j/src/test/scala/ml/dmlc/xgboost4j/scala/ScalaBoosterImplSuite.scala

too busy, will complete it in my spare time in the following days

[jvm-packages] Scala/Java interface for Fast Histogram Algorithm

---

python-package/setup_pip.py

that needs platform-tags in wheel names.
This fixes issue #1995

Inform setuptools that this is a binary package

---

R-package/R/xgb.DMatrix.R

Typo Issue

---

doc/parameter.md

Fixed list of parameters format for CLI mode

Formatting fixed for CLI parameters

---

plugin/updater_gpu/src/gpu_builder.cuh
plugin/updater_gpu/src/updater_gpu.cc

Learning rate was not being adjusted for multiple trees.

GPU Plugin: Bug fix #2048

---

doc/how_to/index.md

erratum in index.md

---

src/learner.cc

Storing and then loading a model loses any eval_metric that was
provided. This causes implementations that always store/load, like
xgboost4j-spark, to be unable to eval with the desired metric.

Store metrics with learner (#2240)

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala

* Support model evaluation for ranking tasks by accepting
groupData in XGBoostModel.eval

[jvm-packages] Accept groupData in spark model eval

---

jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/Booster.scala

* Add parameter passthru of format on Booster.getModelDump

[jvm-packages] Expose json dumps to scala

---

python-package/xgboost/sklearn.py
tests/python/test_with_sklearn.py

@terrytangyuan, as per #2321, I added n_jobs and random_state parameters along with DeprecationWarnings for seed and nthread.  This brings those two elements of the API up to date with Sklearn standards.  I also have tests showing the functionality and DeprecationWarnings.  I updated the docstring for XGBModel as well.  
I hope this helps!

Sklearn convention update

---

.travis.yml
CMakeLists.txt
jvm-packages/create_jni.sh
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/NativeLibLoader.java
jvm-packages/xgboost4j/src/native/xgboost4j.cpp

This is part of the ongoing effort to build jvm-packages on Windows. 
The `jvm` target in Makefile seems to be UNIX-focused.  Have anyone tested it MingGW/Windows?

libxgboost4j is now part of the CMake build

---

CMakeLists.txt
jvm-packages/xgboost4j/src/native/xgboost4j.cpp

See individual commit messages for details.

[jvm-packages] Minor improvements to the CMake build

---

R-package/R/callbacks.R
R-package/R/utils.R
R-package/R/xgb.Booster.R
R-package/R/xgb.DMatrix.R
R-package/R/xgb.cv.R
R-package/R/xgb.importance.R
R-package/R/xgb.model.dt.tree.R
R-package/R/xgb.train.R

I've included many very minor updates to make the R package more robust.

many minor changes to increase the robustness of the R code

---

.travis.yml
CMakeLists.txt
appveyor.yml
jvm-packages/create_jni.py
jvm-packages/xgboost4j/src/native/xgboost4j.cpp
tests/travis/run_test.sh

This fixes compilation issues on Windows and enables JVM build for OS X and Windows. The latter only builds the JNI bindings and doesn't run any tests.

[jvm-packages] Another pack of build/CI improvements

---

doc/how_to/contribute.md

Noticed when I was going to start contributing.

doc: Fix broken links in contribute.md

---

build.sh

build script shown 'Successfully build' message when it actually failed.

Add build failure message

---

CMakeLists.txt
plugin/updater_gpu/plugin.mk
plugin/updater_gpu/src/common.cuh
plugin/updater_gpu/src/device_helpers.cuh
plugin/updater_gpu/src/exact/argmax_by_key.cuh
plugin/updater_gpu/src/exact/fused_scan_reduce_by_key.cuh
plugin/updater_gpu/src/exact/gpu_builder.cuh
plugin/updater_gpu/src/gpu_hist_builder.cu
plugin/updater_gpu/src/register_updater_gpu.cc
plugin/updater_gpu/src/updater_gpu.cu
plugin/updater_gpu/src/updater_gpu.cuh

Prevent Cuda objects from being compiled twice for the executable and shared library.

[GPU-Plugin] Resolve double compilation issue

---

CMakeLists.txt
appveyor.yml
cmake/Utils.cmake
jvm-packages/create_jni.py
plugin/updater_gpu/test/cpp/argmax_by_key.cu
plugin/updater_gpu/test/cpp/fused_reduce_scan_by_key.cu
plugin/updater_gpu/test/cpp/gpu_builder.cu
plugin/updater_gpu/test/cpp/utils.cuh
tests/cpp/metric/test_elementwise_metric.cc
tests/cpp/metric/test_metric.cc
tests/cpp/metric/test_rank_metric.cc
tests/cpp/objective/test_multiclass_metric.cc
tests/cpp/objective/test_regression_obj.cc

-Use cmake provided functions instead of directly modifying flags, where possible
-Group sources for visual studio
-Default to release build
-Refactor to improve readability
Google test to be added soon

Cmake improvements

---

demo/gpu_acceleration/bosch.py

- fix deprecated expression on sklearn.StratifiedKFold
- use `range` instead of `xrange`

FIx GPU acceleration demo

---

make/config.mk

This follows the Makefile from MXNet:  https://github.com/dmlc/mxnet/blob/master/make/config.mk#L119-L124

Not use -msse2 on power or arm arch. close #2446

---

doc/model.md

Fixed spacing under "Model Complexity" section in the introduction document

Fixed spacing on introduction document

---

Makefile

Test on a raspberry pi 3.
@khotilov

To compile xgboost on ARM cpu

---

doc/jvm/index.md

[jvm-packages] Mentioned CMake in the docs

---

doc/conf.py

Use jQuery 2.2.4 for doc

---

doc/parameter.md

* fix indentation - otherwise list items are rendered incorrectly
* consistency: no spaces inside square brackets

Fix parameter documentation inconsistencies

---

.gitmodules

revert shallow submodule for cub

---

Makefile

Fixed error with build failure in case of path with spaces to make as described in issue #2618

fix build in case of spaces in path to make

---

doc/R-package/index.md
doc/jvm/index.md

I was reading the documentation and couldn't help but to contribute a small grammar tweak.

Fix past participle tense in docs

---

python-package/xgboost/sklearn.py

@RAMitchell Quick review?
Fixes #2657

Update sklearn API to pass along n_jobs to DMatrix creation

---

doc/gpu/index.md
tests/python-gpu/test_gpu_prediction.py
tests/python-gpu/test_gpu_updaters.py
tests/python-gpu/test_large_sizes.py

Add missing GPU documentation page after refactor.
Fix import error with GPU Python tests.

Add GPU documentation

---

jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/LabeledPoint.scala

in referece to the discussion in : https://github.com/dmlc/xgboost/pull/2532#discussion_r137172759

Returning back LabeledPoint into public

---

python-package/xgboost/core.py
tests/python/test_with_pandas.py

This PR will fix https://github.com/dmlc/xgboost/issues/2670

Fix issue 2670

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostDFSuite.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala

[jvm-packages] (xgboost-spark) preserving num_class across save & load

---

demo/multiclass_classification/train.py

"pred" is belong to the previous train test.

fix bug for multiclass classification train.py

---

python-package/xgboost/sklearn.py
tests/python/test_with_sklearn.py

https://docs.python.org/3/library/warnings.html#default-warning-filters

python: follow the default warning filters of Python

---

python-package/xgboost/core.py

Make __del__ method idempotent

---

CMakeLists.txt
NEWS.md
R-package/DESCRIPTION
R-package/demo/00Index
R-package/demo/README.md
R-package/demo/gpu_accelerated.R
R-package/demo/runall.R
R-package/src/init.c
R-package/src/xgboost_R.cc
cmake/Utils.cmake
cmake/modules/FindLibR.cmake
doc/build.md
doc/faq.md
src/tree/updater_gpu_common.cuh

Using a separate single shared library build, as I've described in https://github.com/dmlc/xgboost/issues/2625#issuecomment-327202613
It seems to work reasonably well - tested on several linux and windows machines. Note, I had to fix the BernoulliRng interface to accept the 64 bit seed from R's random generator - subsampling wouldn't work otherwise.
Here's an example with 200K x 200 data :
```r
library('xgboost')
N <- 200000
p <- 200
pp <- 50
set.seed(11)
X <- matrix(runif(N*p), ncol=p)
betas <- 2*runif(pp) - 1
sel <- sort(sample(p, pp))
m <- X[, sel] %*% betas - 1 + rnorm(N)
y <- rbinom(N, 1, plogis(m))
pt <- proc.time()
bst <- xgboost(X, y, nrounds=50, eta=0.3, max_depth=5, subsample=0.5, eval_metric='auc',
objective='reg:logistic', nthread=4, tree_method="gpu_hist")
proc.time() - pt
pt …
```

[R package] GPU support

---

include/xgboost/base.h
src/common/device_helpers.cuh
src/learner.cc
src/predictor/gpu_predictor.cu
src/tree/param.h
src/tree/tree_updater.cc
src/tree/updater_gpu.cu
src/tree/updater_gpu_common.cuh
src/tree/updater_gpu_hist.cu
src/tree/updater_gpu_hist_experimental.cu
tests/benchmark/benchmark.py
tests/cpp/common/test_device_helpers.cu
tests/cpp/tree/test_gpu_hist_experimental.cu
tests/python-gpu/test_gpu_updaters.py

-Add experimental GPU algorithm for lossguided mode
-Improved GPU algorithm unit tests
-Removed some thrust code to improve compile times

Improvements to benchmarking/testing and new experimental algorithm

---

doc/python/python_intro.md

Current coding style varies(for example: the mixed use of single quote and double quote), and it will be confusing, especially for new users.
This PR will try to follow proposal of PEP8, make the documents more readable.

coding style update

---

src/cli_main.cc

fix bug in loading config for pred task

---

python-package/xgboost/callback.py

Fixed typo in doc

---

demo/guide-python/boost_from_prediction.py

Some minor changes to code style in file 'boost_from_prediction.py'.

Minor changes to code style

---

include/xgboost/base.h
include/xgboost/data.h
include/xgboost/tree_model.h
src/common/compressed_iterator.h
src/common/device_helpers.cuh
src/common/hist_util.cc
src/common/hist_util.h
src/common/quantile.h
src/common/row_set.h
src/data/sparse_page_source.cc
src/learner.cc
src/predictor/gpu_predictor.cu
src/tree/param.h
src/tree/updater_gpu.cu
src/tree/updater_gpu_hist.cu
src/tree/updater_gpu_hist_experimental.cu
tests/cpp/common/test_compressed_iterator.cc
tests/cpp/common/test_device_helpers.cu
tests/cpp/predictor/test_gpu_predictor.cu
tests/cpp/tree/test_gpu_hist_experimental.cu
tests/travis/run_test.sh

Address several small bugs.
In particular resolve a number of type conversion warnings. These types demotions have the possibility to cause integer overflow errors and create very unexpected results.
Future PRs will work on removing these warnings altogether from XGBoost.

Various bug fixes

---

python-package/xgboost/compat.py
python-package/xgboost/core.py

Fix MultiIndex detection (breaks for latest pandas==0.21.0).

---

CMakeLists.txt
src/common/device_helpers.cuh
src/common/timer.h
src/gbm/gbtree.cc
src/learner.cc
src/objective/multiclass_obj.cc
src/objective/regression_obj.cc
src/tree/updater_gpu_common.cuh
src/tree/updater_gpu_hist.cu
src/tree/updater_gpu_hist_experimental.cu
tests/benchmark/benchmark.py
tests/cpp/common/test_device_helpers.cu
tests/cpp/tree/test_gpu_hist_experimental.cu
tests/python-gpu/test_gpu_updaters.py

- Implement colsampling, subsampling for gpu_hist_experimental
- Optimised multi-GPU implementation for gpu_hist_experimental
- Make nccl optional
- Add Volta architecture flag
- Optimise RegLossObj

Improved gpu_hist_experimental algorithm

---

doc/build.md

FIX typo in doc

---

python-package/xgboost/core.py

[python-package] Fix performance of c_array function

---

python-package/xgboost/plotting.py

updated comments for grid param

update doc string for grid parameter

---

src/common/timer.h
src/predictor/gpu_predictor.cu
src/tree/updater_gpu_hist.cu

Avoid repeated cuda API call in GPU predictor and only synchronize used GPUs

---

R-package/R/xgb.plot.shap.R
R-package/man/xgb.plot.shap.Rd
appveyor.yml
cmake/Utils.cmake
cmake/modules/FindLibR.cmake

Two additional appveyor jobs that build the R package:
- cmake + VC2015 x64 build + unit tests
- make + Rtools/mingw x64 build + R check
I've disabled the multiarch build for mingw since xgboost is crashing 32 bit R at exit on windows #2319

[R] AppVeyor CI for R package

---

include/xgboost/base.h
tests/cpp/predictor/test_gpu_predictor.cu
tests/cpp/tree/test_gpu_hist.cu

Fix Google test warnings and error

---

python-package/xgboost/core.py

Minor typo fix

---

src/objective/regression_obj_gpu.cu
src/tree/updater_gpu_hist.cu

Fix for Windows build as well is some minor bugs in tree construction

Fix GPU bugs

---

demo/guide-python/README.md

Just fixing a typo in the README.

Fix typo: cutomize -> customize

---

jvm-packages/pom.xml
jvm-packages/xgboost4j-spark/pom.xml

[jvm-packages] Declared Spark as provided in the POM

---

doc/parameter.md
doc/tutorials/dart.md

Fix minor typos, as pointed by issues #2212 and #3090

Fix typos, addressing issues #2212 and #3090

---

doc/build.md

#1442 
add how to edit config.mk for build from source on macOS cuz too many issue has been opened by this problem.

modify build guide from source on macOS

---

doc/_static/xgboost.css

Minor: fixed dropdown <li> width in xgboost.css

---

src/predictor/gpu_predictor.cu

I think this was meant to be this way.
The fix will result in very minor performance improvements

Fixed supposed performance bug

---

R-package/R/xgb.cv.R
R-package/R/xgb.train.R
R-package/man/xgb.cv.Rd
R-package/man/xgb.train.Rd
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/LearningTaskParams.scala
src/metric/rank_metric.cc
tests/cpp/metric/test_rank_metric.cc

Implementation of the AUC-PR calculation for weighted data, proposed by Keilwagen, Grosse and Grau (https://doi.org/10.1371/journal.pone.0092209)

rank_metric: add AUC-PR

---

src/predictor/gpu_predictor.cu
tests/python-gpu/test_gpu_prediction.py

Attempt #2 at fixing the phantom bug in #3162.
@dangoldner can you please try this fix and check it works before I merge this time.

Fix logic in GPU predictor cache lookup

---

CMakeLists.txt
cmake/Utils.cmake
tests/cpp/common/test_device_helpers.cu

Generate PTX code for most recent architecture. This will allow binaries to run on future architectures by JIT compiling. @teju85 can you please review this.

Add cuda forwards compatibility

---

src/common/device_helpers.cuh
src/objective/regression_obj.cc
src/objective/regression_obj_gpu.cu

Submitting PR for fixing issue #3306 on behalf of @canonizer .
@RAMitchell @pseudotensor can you guys review?

Fix for issue 3306.

---

jvm-packages/pom.xml
jvm-packages/xgboost4j-example/pom.xml
jvm-packages/xgboost4j-flink/pom.xml
jvm-packages/xgboost4j-spark/pom.xml
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
jvm-packages/xgboost4j/pom.xml

@hcho3 I think in future, if you want, you can just go to jvm-packages/ and run `dev/change_version.sh 0.72-SNAPSHOT 0.80-SNAPSHOT` when you prepare the release so that we can merge the commit with the formal release one

Update 0.8 version num

---

Jenkinsfile

Fixes failing builds on Jenkins due to version number change

Cleanup old artefacts in Jenkins

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/BoosterParams.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostSparkPipelinePersistence.scala

Hi:
This PR is based on issue #3385 and #3383. With such modification, we can make the project more accurate and clear.

[jvm-packages] xgboost4j-spark params confusion fixed

---

doc/jvm/index.md
jvm-packages/README.md

@CodingCat 
Added latest version number example to make it easier to follow the instruction to add xgboost jvm packages.

[jvm-packages] Added latest version number example

---

CONTRIBUTORS.md
R-package/src/Makevars.in
R-package/src/Makevars.win
amalgamation/xgboost-all0.cc
src/tree/param.h
src/tree/split_evaluator.cc
src/tree/split_evaluator.h
src/tree/updater_colmaker.cc
src/tree/updater_fast_hist.cc

Currently only FastHistMaker has been modified to use this new regularisation framework. I figured I should get some feedback before I put in the effort of refactoring the other updaters.
Future PRs will focus on novel regularisation methods.
**Things that need to be checked:**

Refactor of FastHistMaker to allow for custom regularisation methods

---

python-package/xgboost/core.py
tests/python/test_basic.py

Fix get_uint_info()

---

python-package/xgboost/sklearn.py

As per #3053. Pretty straightforward, so no tests written ... and not sure if it's enough to warrant adding to CONTRIBUTORS.md?
cc @aldanor

python sklearn api: defaulting to best_ntree_limit if defined, otherwise current behaviour

---

NEWS.md

Document 0.72.1 version

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifierSuite.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressorSuite.scala

Support single instance prediction for ```XGBoostClassificationModel``` and ```XGBoostRegressionModel```.

[JVM-packages] Support single instance prediction.

---

src/linear/updater_gpu_coordinate.cu
src/predictor/gpu_predictor.cu
src/tree/updater_gpu_hist.cu

Remove calls to thrust copy and fix indexing bug

Resolve GPU bug on large files

---

src/tree/updater_histmaker.cc

Issue: #3402
I believe I found and fixed the mistake with this PR but am unable to reproduce. @qwemicheal Are you able to build from this commit and see if the error persists?

Correct mistake from dmatrix refactor

---

python-package/xgboost/core.py

list('abcdcba') = ['a', 'b', 'c', 'd', 'c', 'b', 'a'] ---> resulting in duplicate values

Fix bug of using list(x) function when x is string

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala

this PR is to fix it
@yanboliang @superbobry would you please help to review?

[jvm-packages] the current version of xgboost does not consider missing value in prediction

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/LearningTaskParams.scala

[jvm-package]Add reg:tweedie to supported objectives in XGBoost4J-Spark

---

demo/rank/README.md
demo/rank/wgetdata.sh
doc/parameter.rst

Update broken links

---

doc/jvm/java_intro.rst

Updating `java_intro.rst` to work with latest XGBoost4J.
@CodingCat

[jvm-packages] Bring XGBoost4J Intro up-to-date

---

src/common/span.h

Fix ptrdiff_t namespace in Span.

---

python-package/xgboost/core.py

Fix accessing DMatrix.handle before set.

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/CheckpointManager.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala

closes https://github.com/dmlc/xgboost/issues/3613
@weitian @yanboliang please help to review

[jvm-packages] fix checkpoint save/load 

---

doc/conf.py
doc/jvm/xgboost4j_spark_tutorial.rst
doc/python/python_api.rst
python-package/xgboost/__init__.py
python-package/xgboost/core.py
python-package/xgboost/plotting.py
python-package/xgboost/sklearn.py
python-package/xgboost/training.py

XGBRanker was added by #3560 and needs to be added to the Python API documentation.
@Shiki-H

Update Python API doc

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
jvm-packages/xgboost4j-spark/src/main/scala/org/apache/spark/SparkParallelismTracker.scala

InterruptedException is not rethrown

[jvm-packages] throw ControlThrowable instead of InterruptedException

---

doc/parameter.rst

Link to Parameter Tuning was broken, fixed.

Link fixed in parameters.rst

---

python-package/xgboost/sklearn.py
tests/python/test_with_sklearn.py

Fix #3648: XGBClassifier.predict() should return margin scores when output_margin=True

---

doc/requirements.txt

The tutorial for feature interaction constraints requires numpy, matplotlib, and graphviz to build successfully.

Update requirements for doc build

---

doc/conf.py
doc/requirements.txt

#3674 broke the doc build. Fixing it by adding scikit-learn as requirement for doc build.

Fix Python doc build

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/CustomParams.scala

[jvm-packages] Remove println in jsonDecode

---

jvm-packages/pom.xml
jvm-packages/xgboost4j-flink/pom.xml

0.10 was years ago, bump version number

[jvm-packages] bump flink version number

---

src/common/common.cu
src/common/device_helpers.cuh
src/common/hist_util.cc
src/common/hist_util.cu
src/common/hist_util.h
src/common/host_device_vector.cu
src/common/host_device_vector.h
src/tree/updater_gpu_hist.cu
tests/cpp/common/test_device_helpers.cu
tests/cpp/common/test_gpu_hist_util.cu
tests/cpp/common/test_host_device_vector.cu

This PR attempts to fix some multi gpu issues.
* Do full data copy when reshard device memory.
* Remove calculating row_segments for gpu_hist and gpu_sketch.

Implement devices to devices reshard.

---

python-package/xgboost/core.py

Document behavior of get_fscore() for zero-importance features

---

Jenkinsfile-restricted

Still new to DevOps thing, so made a syntax error (`retry` block can't be outside of `stages` block)

Retry Jenkins CI tests up to 3 times to improve reliability (redux)

---

doc/parameter.rst
src/linear/coordinate_common.h

Closes #3773.
@RAMitchell Description has been copy-and-pasted from comments.

Document gblinear parameters: feature_selector and top_k

---

src/tree/param.h

The class is no longer being used.  It doesn't seem to be a very useful class anyway. :)  If it's indeed useful in some future cases, feel free to let me know and I will add a brief note to the code.

Remove NoConstraint.

---

CONTRIBUTORS.md

Update the committer list in `CONTRIBUTORS.md` to include everyone who has write access to this repository.

Update committer list

---

R-package/R/xgb.ggplot.R

Changed width parameter of var important ggplot from 0.05 to 0.5 to make it more visible when displaying more variables.

Update R-package/R/xgb.ggplot.R (visual)

---

doc/parameter.rst

Fix typo in docs

---

NEWS.md

@hcho3 The PR based on `release_0.81` branch, should I base it on `master`?

 Document GPU objectives in NEWS.

---

src/learner.cc

See discussion at #3884. The `num_feature` variable uses 32-bit integer, which causes XGBoost to fail for datasets with more than 2147483647 features. For now, print a better error message.

Document current limitation in number of features

---

src/linear/updater_gpu_coordinate.cu
tests/cpp/linear/test_linear.cu

Add `cudaSetDevice`.
Add tests.

Fix gpu coordinate running on multi-gpu.

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala

* avoid long parameter list in functions
* avoid too long functions
it's for the upcoming functionalities like multiple validation set

[jvm-packages][refactor] refactor XGBoost.scala (spark)

---

python-package/xgboost/core.py

Address deprecation of Python ABC.

---

jvm-packages/pom.xml
jvm-packages/xgboost4j-example/pom.xml
jvm-packages/xgboost4j-flink/pom.xml
jvm-packages/xgboost4j-spark/pom.xml
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
jvm-packages/xgboost4j/pom.xml

will update again if we decide jump to 0.9x

[jvm-packages] update version to 0.82-SNAPSHOT

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifierSuite.scala

Fix https://github.com/dmlc/xgboost/issues/3931

[jvm-packages] Fix vector size of 'rawPredictionCol' in XGBoostClassificationModel

---

src/common/device_helpers.cuh
src/common/hist_util.cu
src/common/host_device_vector.cu
src/common/timer.h
src/linear/updater_gpu_coordinate.cu
src/predictor/gpu_predictor.cu
src/tree/updater_gpu_hist.cu
tests/cpp/tree/test_gpu_hist.cu

- Improved GPU performance logging
- Reintroduces the subtraction trick in the multi-GPU case
- Adds better performance logging
- Use only one "ExecuteShards" function.
- Use threads to launch NCCL AllReduce

GPU performance logging/improvements

---

Makefile
R-package/R/xgb.plot.deepness.R
R-package/configure
R-package/configure.ac
R-package/man/xgb.plot.deepness.Rd
R-package/src/Makevars.in
R-package/src/Makevars.win
src/common/transform.h

Issue: https://github.com/dmlc/xgboost/issues/3963

Fix CRAN check warnings/notes

---

include/xgboost/logging.h
src/common/device_helpers.cuh
src/common/timer.h
src/logging.cc
src/tree/updater_gpu_hist.cu
src/tree/updater_quantile_hist.cc
tests/cpp/common/test_monitor.cc
tests/cpp/test_logging.cc

Re-opening, due to hanged Travis.
- Fixed incorrect switch statement.
- Use macro to prevent constructing stream when not needed, should have minor performance improvement.
- Add more tests.

Fix and optimize logger

---

doc/parameter.rst
src/gbm/gbtree.cc

Document num_parallel_tree.

---

src/common/span.h
src/linear/updater_gpu_coordinate.cu
tests/cpp/linear/test_linear.cc

* Use Span in device code.
* Fix shard size calculation.
- Use lower_bound instead of upper_bound.
* Check empty devices.

Use Span in gpu coordinate.

---

include/xgboost/data.h
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/TrainTestData.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifierSuite.scala

closes #4016
it's possible that some partitions didn't get any instance for a feature in distributed training 
as a result, it will lead to error when creating Span 
this PR is to address it by setting size as 0 when the index has beyond the length of offset vector
@RAMitchell @hcho3 @trivialfis

[BLOCKING] fix the issue with infrequent feature

---

python-package/xgboost/core.py

Check booster for dart in feature importance.

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
jvm-packages/xgboost4j-spark/src/main/scala/org/apache/spark/SparkParallelismTracker.scala

closes https://github.com/dmlc/xgboost/issues/4080

[jvm-packages] better fix for shutdown applications 

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala

[jvm-packages] fix simple logic error :)

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala

[jvm-packages] add `verbosity` param to make it easier to debug problems

---

src/common/device_helpers.cuh

omp index variable must be a signed integral type.

Fix for windows compilation

---

src/tree/updater_gpu_hist.cu

@trivialfis here is a challenge for you :) Find a way for us to eliminate bugs completely due to incorrect device selection.
I feel we will keep encountering these mistakes unless we come up with a better way.

Fix incorrect device in multi-GPU algorithm

---

appveyor.yml
tests/python-gpu/test_gpu_linear.py
tests/python/test_linear.py
tests/travis/run_test.sh

* Use `gpu_coord_descent` in test.
* Reduce number of running rounds.
closes #3961 .

Fix test_gpu_coordinate.

---

jvm-packages/pom.xml
jvm-packages/xgboost4j-example/pom.xml
jvm-packages/xgboost4j-flink/pom.xml
jvm-packages/xgboost4j-spark/pom.xml
jvm-packages/xgboost4j/pom.xml

make 0.83-SNAPSHOT for now
let's discuss what's the next version later @hcho3 @trivialfis @RAMitchell

[jvm-packages] bump version for master

---

src/tree/updater_gpu_hist.cu

Very minor fix. :)
@RAMitchell

minor fix: log InitDataOnce() only when it is actually called

---

R-package/README.md

Update R contribute link.

---

doc/tutorials/model.rst

Document limitation of one-split-at-a-time Greedy tree learning heuristic

---

src/common/column_matrix.h

Address #4042: Prevent out-of-range access in column matrix

---

README.md

* Remove contributors avatars, to reduce clutter
* Replace broken link for NVIDIA logo

Simplify README page

---

python-package/xgboost/sklearn.py
tests/python/test_with_sklearn.py

- added deprecation notice and warning
- removed silent from the tests for the SKLearn-like API

Brought the silent parameter for the SKLearn-like API back, marked it deprecated.

---

doc/build.rst
src/common/device_helpers.cuh

Mark CUDA 10.1 as unsupported.

---

jvm-packages/pom.xml
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/package.scala
jvm-packages/xgboost4j/src/main/resources/xgboost4j-version.properties

in a shared cluster environment, it's nice to have explicit version information to track which version the user is using

[jvm-packages] logging version number

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala
jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala

closes https://github.com/dmlc/xgboost/issues/4296 https://github.com/dmlc/xgboost/issues/4294

[jvm-packages] handle NaN as missing value explicitly

---

python-package/xgboost/core.py

* Use a temporary variable to store the handle.
* Decode c++ error message.
* Simple note about saved binary.
This prevents message like:
```
Exception ignored in: <bound method DMatrix.__del__ of <xgboost.core.DMatrix object at 0x7f24004a57f0>>
```

Don't store DMatrix handle until it's initialized.

---

doc/parameter.rst

Correct the calculation mistake in colsample_by* example.

Fix document about colsample_by* parameter

---

include/xgboost/data.h
src/data/data.cc
src/data/sparse_page_dmatrix.h
src/data/sparse_page_source.cc
src/data/sparse_page_source.h
tests/cpp/data/test_sparse_page_dmatrix.cc
tests/cpp/predictor/test_cpu_predictor.cc

add a test for cpu predictor using external memory

---

CMakeLists.txt

add USE_OPENMP option in CMakeLists.txt

add USE_OPENMP option in CMakeLists.txt

---

tests/python/test_with_pandas.py

fix broken python test

---

appveyor.yml

* Windows R tests try to compile igraph package from source and fails. Try to install binary igraph instead.
* Include Graphviz in PATH
@CodingCat

[CI] Fix Windows tests

---

include/xgboost/tree_model.h
tests/cpp/tree/test_tree_model.cc

* Initialize `sindex_` when reusing deleted node.

Fix node reuse.

---

jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala

looks like the jenkins is failing on jvm build
trying to give a fixed seed

[jvm-packages] fix the split of input

---

R-package/vignettes/xgboostfromJSON.Rmd

A vignette that describes aspects to consider when working with a JSON-dumped xgboost model.

Dev/xgboost from json vignette #3980

---

doc/jvm/xgboost4j_spark_tutorial.rst

@hcho3 fix a format problem in spark tutorial

Update xgboost4j_spark_tutorial.rst for formatting

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/LearningTaskParams.scala

Add back reg:linear for scala.

---

doc/python/python_api.rst

Add documentation for Python random forests API @canonizer.

Add python RF documentation

---

include/xgboost/learner.h
src/learner.cc
tests/python-gpu/test_pickling.py

Fix https://github.com/dmlc/xgboost/issues/4513 .
@pseudotensor @sh1ng

Fix prediction from loaded pickle.

---

python-package/xgboost/sklearn.py

Fix #4497: Enable feature importance property for DART booster

---

src/tree/updater_gpu_hist.cu
tests/cpp/tree/test_gpu_hist.cu

This PR removes an abstract base class for histogram building and two separate code paths for building histograms with and without shared memory. Instead it fuses the two code paths at the cost of a couple of if statements.

Refactor histogram building code for gpu_hist

---

python-package/README.rst
python-package/xgboost/compat.py

@RAMitchell Could you help verifying the Window pip issue in this file?  If it still persist I will move the note to doc/build.rst, otherwise I just remove all notes.

Fix doc and demo for Python package.

---

include/xgboost/objective.h
python-package/xgboost/sklearn.py
tests/cli/machine.conf.in

This time it should be thorough. :(

Remove remaining reg:linear.

---

include/xgboost/gbm.h
include/xgboost/generic_parameters.h
src/common/common.cc
src/common/host_device_vector.cu
src/gbm/gblinear.cc
src/gbm/gbtree.cc
src/gbm/gbtree.h
src/learner.cc
src/tree/updater_colmaker.cc
tests/cpp/gbm/test_gbtree.cc
tests/cpp/predictor/test_gpu_predictor.cu
tests/cpp/test_learner.cc
tests/cpp/test_main.cc

* Move tree heuristic configurations into GBTree.
* Split up declarations and definitions of GBTree for testing.
* Implement UseGPU in gbm to detect whether we are using GPU algorithm.
See  #4542 for more comments and plan.  This is part one of it, one or two more PRs are coming.

Offload some configurations into GBM.

---

src/data/sparse_page_dmatrix.h

Mark SparsePageDmatrix destructor default.

---

jvm-packages/pom.xml

Fixes https://github.com/dmlc/xgboost/issues/4548

updated kryo dependency to 2.22

---

doc/build.rst

@RAMitchell @trivialfis @hcho3

remove doc about not supporting cuda 10.1

---

tests/cpp/tree/test_gpu_hist.cu

Complaining about unused variable.
@RAMitchell

fix compiler warning

---

tests/benchmark/benchmark_tree.py

Looks like the exception type changed.
@RAMitchell @sriramch

fix benchmark_tree.py

---

demo/guide-python/README.md
demo/guide-python/custom_objective.py
demo/guide-python/custom_rmsle.py
doc/gpu/index.rst
doc/jvm/java_intro.rst
doc/tutorials/custom_metric_obj.rst
doc/tutorials/index.rst

Doc for customized objective/metric.

---

doc/contribute.rst
tests/ci_build/test_python.sh

A documentation change.
I added a chapter about how to build native unit tests and launch them to the Contributors docs
It was not at all obvious to me when I started on-boarding on this project so my guess someone else could benefit too
Tell me what do you think

Add to documentation how to run tests locally

---

python-package/xgboost/core.py

Should eliminate the Pandas series deprecation warning in issue #4300.
Closes #4300

Eliminate FutureWarning: Series.base is deprecated

---

doc/tutorials/index.rst
doc/tutorials/kubernetes.rst

The readme tutorial to train XGBoost job on Kubernetes cluster is added. 
Just readme, and related tutorial is linked.

Add tutorial for distributed training and batch prediction with Kubernetes

---

LICENSE
doc/conf.py
tests/cpp/helpers.h

* Updated LICENSE to 2019
* Updated year in `conf.py` and `helpers.h` to 2019

Updated year in few files

---

doc/R-package/xgboostPresentation.md

updated links to caret data splitting, xgb.dump(with_stats), and some grammar

[R] minor updates to links and grammar

---

src/objective/regression_obj.cu

Now that we are targeting 1.0, there's no reason for these to linger. :-)

Removed deprecated gpu objectives.

---

appveyor.yml

* Removing it as it is not fully c++11 compliance.

Remove VC-2013 support.

---

tests/ci_build/Dockerfile.gpu

Follow-up to #4704. I forgot to make the same change to the GPU container.
Should unblock #4686
cc @rongou @RAMitchell @trivialfis

[CI] Fix broken installation of Pandas

---

jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/CheckpointManagerSuite.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/PersistenceSuite.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/TmpFolderPerSuite.scala
jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala
jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/BoosterImplTest.java

I noticed that some tests do not fully clean up their tmp files so I fixed that.
Nothing else

[jvm-package] jvm test should clean up after themselfs

---

.gitignore
python-package/setup.py
python-package/xgboost/__init__.py
python-package/xgboost/dask.py
python-package/xgboost/tracker.py
tests/python/test_tracker.py

This PR is a response to issue #4653 .
I made a specialized copy of `dmlc_tracker/tracker.py` in xgboost, because:
1.  symbolic link doesn't work well under  _Windows_
2.  original version of `dmlc_tracker/tracker.py` has a lot of linter problem
3.  Future modifications can be applied on this copy without considering compatibility.

[python package] include dmlc-tracker into xgb python pkg

---

include/xgboost/base.h
include/xgboost/json.h
include/xgboost/json_io.h
src/common/json.cc
tests/cpp/common/test_json.cc

Extracted from #4732, which in turns is extracted from #4683 to reduce PR size for quicker review.

Add Json integer, remove specialization.

---

doc/tutorials/external_memory.rst

- to state that it is supported now on gpu algorithms
@RAMitchell @trivialfis @rongou - minor fix for external memory documentation.

- fix external memory documentation [skip ci]

---

include/xgboost/data.h
src/data/simple_dmatrix.cc
src/data/sparse_page_dmatrix.cc

- the synthesized copy constructor should do the appropriate job
@RAMitchell @trivialfis @rongou - please review

- enable natural copies of the batch iterators without the need of the clone method

---

src/tree/constraints.cuh
src/tree/param.h
src/tree/updater_gpu_common.cuh

* Removed unused functions.
* Removed unused parameters.
* Move `ValueConstraints` into constraints.cuh since it's now only used in GPU_Hist.

Clean up after removing `gpu_updater`.

---

src/tree/tree_model.cc

Remove initializing stringstream reference in generator.

---

src/gbm/gbtree.cc
src/learner.cc

Prevent copying data to host.

---

src/common/device_helpers.cuh
src/common/host_device_vector.cc
src/common/host_device_vector.cu
src/common/host_device_vector.h
src/metric/elementwise_metric.cu
src/metric/multiclass_metric.cu
src/predictor/gpu_predictor.cu
src/tree/updater_gpu_hist.cu
tests/cpp/common/test_device_helpers.cu
tests/cpp/common/test_host_device_vector.cu
tests/cpp/predictor/test_gpu_predictor.cu
tests/cpp/tree/test_gpu_hist.cu

Address review feedback in #4773 
@RAMitchell @trivialfis @sriramch

further cleanup of single process multi-GPU code

---

src/metric/rank_metric.cc

There was a dataset for ranking task, and most samples are negative. I tried to use train it in distributed mode and found that all workers contains at least one group which had only pos or neg samples. As the result, I got the exception: AUC: the dataset only contains pos or neg samples.Besides, I found that "auc_error" would be changed into "1" if there was a group full of negative or positive samples in each worker.
This PR modified the response of auc_error. In distribute mode, auc_error is regarded as the number of invalid groups in each worker. Workers will reserve the number of valid groups and calculate average auc among all valid groups from all workers.

Fix auc error in rank task

---

amalgamation/xgboost-all0.cc
include/xgboost/json.h
src/common/timer.cc
src/common/timer.h
src/learner.cc

Does all printings in rank 0 worker.
No unittest for this one ... Not sure about how to do it.  Sample output:
```
[13:19:57] ======== Monitor: Learner ========
From rank: 0: 
Configure: 4e-06s, 1 calls @ 4us
GetGradient: 3.26812s, 3 calls @ 3268121us
PredictRaw: 1.88846s, 3 calls @ 1888456us
UpdateOneIter: 39.4518s, 3 calls @ 39451772us
From rank: 1: 
Configure: 5e-06s, 1 calls @ 5us
GetGradient: 3.7504s, 3 calls @ 3750402us
PredictRaw: 1.87721s, 3 calls @ 1877214us
UpdateOneIter: 39.7579s, 3 calls @ 39757925us
```

monitor for distributed envorinment.

---

src/data/simple_dmatrix.cc
src/gbm/gbtree.h
src/predictor/cpu_predictor.cc
src/predictor/gpu_predictor.cu
tests/cpp/gbm/test_gbtree.cc
tests/cpp/test_learner.cc

Fix calling GPU predictor

---

include/xgboost/generic_parameters.h

Add `n_jobs` as an alias of `nthread`.

---

R-package/src/xgboost_R.cc
include/xgboost/c_api.h
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/DMatrix.java
jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoostJNI.java
jvm-packages/xgboost4j/src/native/xgboost4j.cpp
jvm-packages/xgboost4j/src/native/xgboost4j.h
python-package/xgboost/core.py
src/c_api/c_api.cc

closes #4761 .
Use `XGDMatrixSetUIntInfo` instead.  Tracked in #3986

Deprecate set group

---

include/xgboost/data.h
python-package/xgboost/compat.py
python-package/xgboost/core.py
src/data/data.cu
tests/cpp/data/test_metainfo.cu
tests/python-gpu/test_from_columnar.py

@VibhuJawa I added a test, could you please review? Closes  #4901

Support feature names/types for cudf.

---

demo/dask/README.md
demo/dask/cpu_training.py
demo/dask/gpu_training.py
demo/dask/sklearn_cpu_training.py
demo/dask/sklearn_gpu_training.py

* Add a readme with link to doc.
* Add more comments in the demonstrations code.
* Workaround https://github.com/dask/distributed/issues/3081 .

Improve doc and demo for dask.

---

Jenkinsfile
tests/ci_build/Dockerfile.cudf
tests/ci_build/test_python.sh
tests/python-gpu/test_gpu_with_dask.py
tests/python/testing.py

Closes #4792
@trivialfis @RAMitchell Feel free to tag more people who can help

[CI] Run cuDF tests in Jenkins CI server

---

README.md

Since now we support running XGBoost on Kubernetes.

Mention Kubernetes on README

---

CMakeLists.txt
doc/build.rst
doc/jvm/index.rst
doc/jvm/xgboost4j_spark_tutorial.rst

closes #4887 .
One issue at a day. ;-)

Copy CMake parameter from dmlc-core.

---

src/common/transform.h
tests/cpp/common/test_transform_range.cc

Catch exception in transform function omp context.

---

doc/contrib/docs.rst
doc/python/python_intro.rst
doc/tutorials/input_format.rst
src/common/config.h
src/data/data.cc
tests/cli/machine.conf.in
tests/cpp/data/test_data.cc

* Fix config regex.
* Try to explain the error better in exception. (not really useful since dmlc csv parser can parse libsvm file without generating any error.)
* Update doc.

Fix data loading

---

Jenkinsfile
Jenkinsfile-win64
doc/build.rst
tests/ci_build/rename_whl.py

Closes #4813.
Expected usage: pip3 install https:\/\/s3-us-west-2.amazonaws.com/xgboost-nightly-builds/xgboost-1.0.0+[commit hash]-py2.py3-none-manylinux1_x86_64.whl
Listing is available at https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/list.html
cc @randerzander @JohnZed

[CI] Upload nightly builds to S3

---

src/gbm/gbtree.cc
src/predictor/cpu_predictor.cc

Improve operation efficiency for single predict

Improve operation efficiency for single predict

---

python-package/xgboost/dask.py

I mistakenly pushed data as the first parameter and spent some time to figure it out as error message is telling me X having wrong shape ( y is placed as X).  This might be able to save others some time.

Assert dask client at early stage.

---

python-package/setup.py
python-package/setup_pip.py

Require Python 3.5+ in setup.py

---

python-package/xgboost/sklearn.py
tests/python/test_with_sklearn.py

Closes  #5030 #5032 .  @david-cortes I can't push to your master branch so created a separated PR with a modified patch.

Allow using RandomState object from Numpy in sklearn interface.

---

doc/python/python_intro.rst
doc/tutorials/external_memory.rst
doc/tutorials/input_format.rst

[DOC] Some notes for external memory.

---

doc/build.rst

A small update for compiling XGBoost in MacOS.

Fix issue #4933

---

python-package/xgboost/dask.py
tests/python/test_with_dask.py

Support dask dataframe as y for classifier.

---

include/xgboost/json.h
src/common/json.cc
tests/cpp/common/test_json.cc

* Fix parsing empty object.
Small part of #4732.

Convenient methods for JSON integer.

---

include/xgboost/tree_model.h
src/tree/updater_colmaker.cc

Closes https://github.com/dmlc/xgboost/issues/4314

Don't use 0 for "fresh leaf".

---

include/xgboost/data.h
include/xgboost/gbm.h
include/xgboost/predictor.h
include/xgboost/tree_model.h
src/c_api/c_api.cc
src/data/data.cc
src/gbm/gblinear.cc
src/gbm/gbtree.cc
src/gbm/gbtree.h
src/gbm/gbtree_model.h
src/predictor/cpu_predictor.cc
src/predictor/gpu_predictor.cu
src/tree/tree_model.cc
src/tree/updater_basemaker-inl.h
src/tree/updater_colmaker.cc
src/tree/updater_histmaker.cc
src/tree/updater_prune.cc
src/tree/updater_quantile_hist.cc
src/tree/updater_refresh.cc
tests/cpp/data/test_metainfo.cc
tests/python/test_basic.py
tests/python/test_dmatrix.py
tests/python/test_ranking.py

Closes #4133 .  Splitting small parts of JSON IO PR.

[Breaking] Remove num roots.

---

src/gbm/gbtree_model.cc
src/learner.cc
tests/cpp/gbm/test_gblinear.cc
tests/cpp/gbm/test_gbtree.cc
tests/cpp/test_learner.cc
tests/cpp/tree/test_gpu_hist.cu
tests/python/test_basic_models.py

* Addresses comments from @hcho3 in https://github.com/dmlc/xgboost/pull/5110 .
* Making the naming scheme more consistent across XGBoost.

Small refinements for JSON model.

---

R-package/R/xgb.train.R
R-package/src/xgboost_R.cc
doc/parameter.rst

Check against R seed.

---

R-package/R/xgb.cv.R

Continue https://github.com/dmlc/xgboost/pull/5064 .

Added new train_folds parameter

---

demo/guide-python/boost_from_prediction.py
src/objective/hinge.cu
src/objective/multiclass_obj.cu
src/objective/regression_obj.cu
tests/cpp/objective/test_multiclass_obj.cc

Add check for length of weights.

---

demo/guide-python/boost_from_prediction.py
python-package/xgboost/core.py
python-package/xgboost/sklearn.py
tests/python/test_basic_models.py
tests/python/test_with_sklearn.py

Closes https://github.com/dmlc/xgboost/issues/4190 .

Add base margin to sklearn interface.

---

demo/rank/README.md
demo/rank/rank.py
demo/rank/rank_sklearn.py

Update demo for ranking.

---

tests/python-gpu/test_gpu_with_dask.py
tests/python/test_with_dask.py

Closes https://github.com/dmlc/xgboost/issues/4120

Tests for empty dmatrix.

---

include/xgboost/tree_model.h
src/gbm/gbtree_model.h
src/tree/tree_model.cc

Closes https://github.com/dmlc/xgboost/issues/5164 .
~Need to verify.~

Fix num_roots to be 1.

---

doc/sphinx_util.py

Fix simple typo: utilty -> utility

---

python-package/xgboost/core.py

Fix minor bug when cupy is installed but cudf is not

Fix cupy without cudf import

---

python-package/xgboost/core.py
src/objective/rank_obj.cu
tests/python/test_dt.py
tests/python/test_with_pandas.py
tests/python/test_with_sklearn.py

* Unify helper functions for data and meta.
Fix issue found by @RAMitchell , weight is silently dropped when initialized with `pandas.DataFrame`.

Fix metainfo from DataFrame.

---

doc/parameter.rst
python-package/xgboost/sklearn.py
tests/python/test_with_sklearn.py

* Fix formatting for objective function's document.
* Add mono/interact constraint parameters to sklearn interface.
* Add document to parameters.rst and sklearn.py
Closes #5099 .

Add constraint parameters to Scikit-Learn interface.

---

src/c_api/c_api.cc
src/learner.cc

Fix compilation error due to 64-bit integer narrowing to size_t

---

tests/python/test_with_dask.py

Testing for Travis.  Please ignore until WIP label is removed.

Try avoiding test fixtures.

---

python-package/xgboost/sklearn.py
src/learner.cc
tests/python/test_with_sklearn.py

Related https://github.com/onnx/onnxmltools/issues/368 .

Export JSON config in `get_params`.

---

python-package/.pylintrc
python-package/xgboost/sklearn.py

Improved sklearn compatibility

---

python-package/setup.py
python-package/setup_pip.py

Declare Python 3.8 support in setup.py

---

doc/build.rst

Adds instructions for Visual Studio 15 and 16 and  the `cmake --build` command.

Updated Windows build docs

---

CONTRIBUTORS.md

I am switching my place of employment. Updating CONTRIBUTORS.md to reflect my new position.

Update affiliation of @hcho3

---

python-package/xgboost/core.py
tests/python/test_basic_models.py

Patching into 1.0 branch.  PR for running test as it's not trivial.

Restore loading model from buffer. (#5360)

---

python-package/xgboost/compat.py
python-package/xgboost/core.py
tests/python/test_basic.py
tests/python/testing.py

* Avoid importing datatable.
* Fix #5363.

Define lazy isinstance for Python compat. (#5364)

---

doc/tutorials/dask.rst

Change `signle-node` to `single-node`

Update dask.rst to correct a spelling mistake

---

Jenkinsfile

reenable rabit failure recovery test

enable rabit test

---

Jenkinsfile

Reverts dmlc/xgboost#5358
The test got stuck on master branch: https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/master/133/pipeline/

Revert "enable rabit test"

---

python-package/xgboost/sklearn.py

Fix simple typo: information.c -> information

---

include/xgboost/tree_model.h
include/xgboost/tree_updater.h
src/gbm/gbtree.cc
src/tree/tree_model.cc
src/tree/updater_prune.cc
src/tree/updater_refresh.cc
tests/cpp/gbm/test_gbtree.cc
tests/cpp/tree/test_tree_model.cc

Close https://github.com/dmlc/xgboost/issues/5376 .

Check whether current updater can modify a tree.

---

R-package/R/xgb.train.R
R-package/tests/testthat/test_basic.R
doc/parameter.rst
include/xgboost/logging.h
src/logging.cc

Cleaning up old deprecated parameter.

Remove silent parameter.

---

Jenkinsfile
Jenkinsfile-win64
src/cli_main.cc
tests/python/test_cli.py

Fix cli model IO.

---

python-package/xgboost/core.py

Documentation states that if value is set to `-1`, then XGBoost should use maximum number of threads.   So the input type should always be signed integer.
* Update doc.

Don't use uint for threads.

---

python-package/xgboost/training.py
src/cli_main.cc
tests/python/test_cli.py

Closes https://github.com/dmlc/xgboost/issues/5536 .

Don't set seed on CLI interface.

---

src/learner.cc

Fix configuration not run.

---

python-package/xgboost/core.py

Instruct Mac users to install libomp

---

include/xgboost/generic_parameters.h
tests/cpp/test_learner.cc

Closes https://github.com/dmlc/xgboost/issues/5637
Closes https://github.com/dmlc/xgboost/pull/5638

Support 64bit seed.

---

src/common/column_matrix.h

See https://github.com/dmlc/xgboost/pull/5631#issuecomment-624520843

Resolve vector<bool>::iterator crash

---

Jenkinsfile
tests/python-gpu/test_gpu_basic_models.py

Upgrade to CUDA 10.0

---

Jenkinsfile
tests/python-gpu/test_gpu_basic_models.py

Upgrade to CUDA 10.0 (#5649)

---

src/data/device_dmatrix.cu
tests/cpp/data/test_device_dmatrix.cu

Fix `IsDense`.

---

CMakeLists.txt
cmake/xgboost.pc.in

Add pkgconfig to cmake (#5744)
Co-authored-by: Peter Jung <peter.jung@heureka.cz>
Co-authored-by: Hyunsu Cho <chohyu01@cs.washington.edu>

Backport #5744 to 1.1.1

---

doc/R-package/xgboostPresentation.md

Remove `max.depth` in R gblinear example.

---

NEWS.md

Add release note for 1.1.0 in NEWS.md

---

include/xgboost/host_device_vector.h
src/common/host_device_vector.cu
tests/cpp/common/test_host_device_vector.cu

Implement `Empty` method for host device vector.

---

tests/python/test_linear.py

Relax test for shotgun.

---

src/c_api/c_api.cc

* Explicit cast for slice.
Closes #5828 .

Fix NDK Build.

---

python-package/xgboost/dask.py
python-package/xgboost/data.py
src/common/quantile.cuh
src/data/array_interface.h
src/data/data.cc
src/data/data.cu
src/data/device_adapter.cuh
src/data/iterative_device_dmatrix.cu
src/metric/multiclass_metric.cu
src/objective/multiclass_obj.cu
tests/python-gpu/test_gpu_with_dask.py
tests/python/test_with_dask.py

* Drive by fix for softprob with empty DMatrix.

Dask device dmatrix

---

R-package/R/xgb.DMatrix.R
R-package/tests/testthat/test_ranking.R

Closes #5942. Also add a unit test for the R package that runs ranking with weighted data.

[R] Enable weighted learning to rank

---

Jenkinsfile
src/tree/gpu_hist/evaluate_splits.cu

Run cuda-memcheck on CI.  Might take some time to complete.

[BLOCKING] Fix evaluate root split.

---

python-package/xgboost/sklearn.py

Fix https://github.com/dmlc/xgboost/issues/5976

Fix sklearn doc.

---

demo/guide-python/custom_objective.py
tests/python/test_basic_models.py

Fix https://github.com/dmlc/xgboost/issues/5621 .

Update Python custom objective demo.

---

doc/model.schema
tests/python/test_basic_models.py

* Add missing objectives
* Add tests for missing objectives.

Update JSON schema.

---

include/xgboost/data.h
include/xgboost/learner.h
tests/cpp/common/test_span.cc

Extracted from #6001 to get a clean merge.

Remove rabit dependency on public headers.

---

demo/README.md

https://github.com/parrt/dtreeviz

[Doc] Add dtreeviz as a showcase example of integration with 3rd-party software

---

src/common/hist_util.cc

This reverts commit 12e3fb6a6cb601c58d39ed54253e6e50f1513ccc.

Revert "Remove warning about memset. (#6003)"

---

tests/python-gpu/conftest.py

[CI] Fix Dask Pytest fixture

---

python-package/xgboost/sklearn.py

Fix https://github.com/dmlc/xgboost/issues/6012 .

Fix scikit learn cls doc.

---

include/xgboost/base.h
src/common/device_helpers.cuh
src/common/hist_util.h
src/data/ellpack_page.cuh
src/predictor/gpu_predictor.cu
src/tree/gpu_hist/histogram.cu
src/tree/gpu_hist/histogram.cuh
src/tree/updater_gpu_common.cuh

* Move binary search row to hist util.
* Remove dead code.

Make binary bin search reusable.

---

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/DataUtils.scala

We propose to only use the rowHashCode to compute the partitionKey, adding the FeatureValue hashCode might not bring a better load balancing and is makingthe computation slower. MurmurHash3 is known as being quite uniformly distributed and should suffice here.

[jvm-packages] Clean the way deterministic partitioning is computed

---

R-package/DESCRIPTION
R-package/R/utils.R
R-package/R/xgb.cv.R
R-package/R/xgb.train.R
R-package/man/a-compatibility-note-for-saveRDS-save.Rd
R-package/man/xgb.cv.Rd
R-package/man/xgb.train.Rd
R-package/vignettes/discoverYourData.Rmd
R-package/vignettes/xgboost.bib
R-package/vignettes/xgboostPresentation.Rmd

The future R check will enforce a more strict check on URLs. 
Will have a separate PR for the master branch.
Related: https://github.com/dmlc/xgboost/pull/6077

CRAN submission fix for 1.2.0

---

NEWS.md
dev/query_contributors.py

Add release note for 1.2.0 in NEWS.md

---

doc/tutorials/custom_metric_obj.rst

Close https://github.com/dmlc/xgboost/issues/6098 .

Fix custom obj link. [skip ci]

---

src/common/hist_util.cu
src/common/hist_util.cuh
src/common/quantile.cu
src/common/quantile.cuh
tests/cpp/common/test_device_helpers.cu
tests/cpp/common/test_quantile.cu

* Reuse pruning for initial construction of summary.

Merge extract weights into QuantileContainer.

---

doc/contrib/unit_tests.rst
include/xgboost/intrusive_ptr.h
include/xgboost/json.h
tests/cpp/common/test_intrusive_ptr.cc

Previously the PR is hosted on dmlc-core.  Let's merge it here for XGBoost first so we can get better perf for next release with JSON now being the default serialization format.
@hcho3

Implement intrusive ptr

---

plugin/CMakeLists.txt

Remove linking RMM library.

---

demo/dask/gpu_training.py
python-package/xgboost/dask.py
tests/python-gpu/test_gpu_demos.py

Add DaskDeviceQuantileDMatrix demo.

---

.gitignore

Generated by https://github.com/universal-ctags/ctags:
``` sh
ctags -e -R --languages=CMake
```

Add TAGS to gitignore. [skip ci]

---

demo/README.md

Related: #6173 
Could you please have a moment to take a look at it?

[Doc] Add list of winning solutions in data science competitions using XGBoost

---

demo/guide-python/custom_objective.py

Small update to the comment referencing the train implementation for further details.

updated reference to xgboost's train implementation to training.py

---

doc/build.rst

Add note about the required compiler version for CUDA. Also added a link that gives a short explanation on compute capability version

[Doc] Add info on GPU compiler

---

.travis.yml
tests/travis/run_test.sh
tests/travis/setup.sh

Added Arm64 job in Travis-CI, modified run_test.sh and setup.sh to add checks for arm64 platform.

Added arm64 job in Travis-CI

---

doc/model.schema

Add JSON schema for categorical splits.

---

src/c_api/c_api_error.h
tests/cpp/c_api/test_c_api.cc

Related: https://github.com/dmlc/xgboost/issues/6217

Catch all standard exceptions in C API.

---

python-package/xgboost/compat.py
python-package/xgboost/core.py
python-package/xgboost/dask.py
python-package/xgboost/data.py
tests/python/test_basic.py

* Remove pathlike as XGBoost 1.2 requires Python 3.6.
* Move conditional import of dask/distributed into dask module.

Cleanup Python code.

---

demo/README.md

Scanned through 10 competitions and added two winners in readme.md file as instructed
If you find this useful kindly merge and approve.

Update the list of winning solutions

---

python-package/xgboost/sklearn.py

Close https://github.com/dmlc/xgboost/issues/6246 .

Fix cls typo.

---

demo/README.md

Added one winner. See https://github.com/dmlc/xgboost/issues/6173

Updating list of winning solutions
