dmlc/xgboost

wrapper/xgboost.py
- DLL import now works when `__file__` is a relative path
- Various PEP8 and whitespace fixes + whitespace cleanup
- Docstring fixes (conform to numpydoc)
- Added `__all__` to the module
- Fixed mutable default values
- Removed print statements
- py2/py3-compatible string-type checks
- Replace asserts with proper exceptions
- Make classes new-style (derive from `object`)
=> [python] Fixed the dll import for relative paths + various cleanup.

wrapper/xgboost.py
Hey guys,
I have implemented early stopping in Python interface. To activate it, you set the number of boosting rounds to a negative number, for example -1 means that validation score must improve every round, -2: at least every second round, and so on. Obviously to compute validation score you need at least one set in _evals_; if there's more than one, early stopping will look at the last. It works with both losses (minimizing) and AUC/MAP/NDCG (maximizing).
Feel free to edit or let me know what to change.
=> Early stopping for Python wrapper

wrapper/xgboost.py
I'm not quite sure how you'd handle non-ascii encoded strings in the models, so I punted on this in favor of ascii only. Right now on Python 3 though, the byte objects coerce to strings like so if you don't explicitly decode them. I.e., the b"" gets written to the model object.
```
In [3]: b"asdasa"
Out[3]: b'asdasa'
In [4]: str(b"asdasa")
Out[4]: "b'asdasa'"
```
=> COMPAT: Decode bytes object for Python 3.

doc/build.md
`bash xgboost/build.sh` does not work as expected, so `cd` then `build.sh`. And remove the outdated information.
=> update build instruction in OS X

demo/guide-python/sklearn_examples.py, demo/guide-python/sklearn_parallel.py, wrapper/README.md, wrapper/xgboost.py
I added an example of the pickling and some notes about using OpenMP after fork. I also refactored your bytearray changes to avoid the copy in memmove. The example will only run on Python 3.4 now. Can you try it out on python 2.x? I don't have a 2.x dev environment handy on this machine. I think you may just need to do a 
```python
try:
select_start_method("forkserver")
except:
select_start_method("spawn")
```
Forkserver is only available on 3.4 and spawn has a lot more overhead.
=> ENH: Pickle xgbooster enhancments.

R-package/R/xgb.train.R, R-package/R/xgboost.R, R-package/man/xgb.train.Rd, R-package/man/xgboost.Rd
For example: xgboost(... , printEveryN=100) will print only 0th, 100th, 200th, 300th ... information/progress messages.
=> new parameter in xgboost() and xgb.train() to print every N-th progress message

wrapper/xgboost.py
As for now, python early stopping counts every metric as being miximized.
The problem is filter object is always `True` so we have to convert it to list before `if`'ing:
In [1]: list(filter(lambda x: True, [1, 2, 3]))
Out[1]: [1, 2, 3]
In [2]: list(filter(lambda x: False, [1, 2, 3]))
Out[2]: []
In [3]: if filter(lambda x: True, [1, 2, 3]):
....:     print("yes")
....:     
yes
In [4]: if filter(lambda x: False, [1, 2, 3]):
....:     print("yes")
....:     
yes
=> Fix early stopping in python wrapper

wrapper/xgboost.py
Scikit-learn's ensemble methods (bagging in particular) require that the base estimators implement a classes_ attribute in addition to n_classes_.  This information is already being captured in the "fit" method of xgboost's scikit-learn wrapper class as a local variable.  I simply modified it to save the list of classes in an instance attribute.  This change allows xgboost models to be used in a bagging ensemble.
=> Add classes_ attribute to scikit-learn wrapper

demo/binary_classification/README.md
I got this information about nthread='real cpu count' from https://github.com/dmlc/xgboost/blob/7cb449c4a75c2a16f6dfea5244ce959d998344b1/java/xgboost4j-demo/src/main/java/org/dmlc/xgboost4j/demo/ExternalMemory.java#L50
Please confirm if this note is still valid before merging this change!
=> Adding some details on nthread parameter

R-package/demo/custom_objective.R
Issue in "demo(package="xgboost", custom_objective)"
> bst <- xgb.train(param, dtrain, num_round, watchlist, 
+                  objective=logregobj, eval_metric=evalerror)
Error in xgb.train(param, dtrain, num_round, watchlist, objective = logregobj,  : 
Duplicated term in parameters. Please check your list of params.
=> Fixing duplicate params in demo

CHANGES.md, CONTRIBUTORS.md, doc/python/python_api.rst, doc/python/python_intro.md, python-package/xgboost/__init__.py, python-package/xgboost/plotting.py, scripts/travis_osx_install.sh, scripts/travis_script.sh, tests/python/test_basic.py
Closes #380. Added 3 functions:
- ``plot_importance``:  importance plot using ``matplotlib``
- ``to_graphiz``:  convert a specified tree to ``graphviz`` instance. ``graphviz`` instance can be plotted in ``IPython`` by itself.
- ``plot_tree``:  plot tree using ``matplotlib``  ~~I'm not sure if there is a way to render graphviz instance on matplotlib.~~
Output example:
- https://gist.github.com/sinhrks/cc9a88f74074fc296e12
I'm willing to change the behavior / specs based on feedbacks:)
=> Add visualization to python package

CHANGES.md, CONTRIBUTORS.md, Makefile, python-package/MANIFEST.in, python-package/README.md, python-package/setup.cfg, python-package/setup.py, python-package/xgboost/build-python.sh, python-package/xgboost/core.py
updated Makefile for packing necessary files for pip installation
updated setup.py for finding packages and data for pip installation
added MANIFEST.in and other necessary configration files for shipping and building xgboost on-the-fly while installation
updated xgboost/core.py for finding the compiled .so lib files with pip installation
Now it is uploaded to PyPI, and the python package can be installed with 'pip install xgboost', no more worry if a new user forgot to build.sh firstly.
P.S. the current version number on PyPI is "0.4a12" because I accidentally committed the first 0.4 official version to PyPI but it didn't pack all files. sorry my bad.
=> add necessary configrations for pip installation

python-package/setup.py
Hello,
I try to install xgboost on Anaconda 3 with the command pip install xgboost.
I have the following error: SyntaxError: Missing parentheses in call to 'print'
It occurs on line 13 in setup.py, when 'print output' is called.
Thanks!
=> Missing parentheses in call to 'print' 

.travis.yml, python-package/xgboost/plotting.py, scripts/travis_osx_install.sh, scripts/travis_script.sh, tests/python/test_basic.py
This is a follow-up for #439. I found current python visualization impl has a problem in python3.
I've fixed the problem and added travis test for python 3. Also, fixed ``setup.py`` which prevents the installation on python 3. Not sure python 3 is going to be supported officially, current test looks passed.
=> Python Visualization Fix for python 3

doc/parameter.md
Hi
I fixed a typo "filenam" to "filename" in parameter.md .
=> Fix a typo in parameter.md

python-package/xgboost/sklearn.py
Now it fails:
File "./biologicalResponse.py", line 76, in <module>
main()
File "./biologicalResponse.py", line 22, in main
score = rf.score(testFeatures, testTarget)
File "/home/denplusplus/.local/lib/python3.4/site-packages/sklearn/base.py", line 295, in score
return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
File "/usr/local/lib/python3.4/dist-packages/xgboost-0.4-py3.4.egg/xgboost/sklearn.py", line 322, in predict
column_indexes = np.repeat(0, data.shape[0])
AttributeError: 'list' object has no attribute 'shape'
It seems to be just a typo fix.
=> make XGBClassifier.score compatible with arrays

python-package/xgboost/training.py
The evals_results currently remains empty if early stopping is used and if the eval metric provides positive values.
=> bugfix evals_result regex

python-package/xgboost/core.py, scripts/travis_osx_install.sh, scripts/travis_script.sh, tests/python/test_basic.py, wrapper/xgboost_wrapper.cpp, wrapper/xgboost_wrapper.h
Python package can now handle feature names.
- Feature names can be set to ``DMatrix`` via ``feature_names`` kw as below(optional).
- ``feature_names`` must be a list only consistes form alphanumerics. Because symbols may corrupt ``get_dump`` function.
```
dm = xgb.DMatrix(iris.data, label=iris.target,
feature_names=['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth'])
```
- When ``DMatrix`` with ``feature_names`` is passed to ``Booster``, ``Booster`` stores it. Once ``Booster`` has ``feature_names``, it will not accept ``DMatrix`` with different ``feature_names``. Because these are regarded as different data.
- ``get_fscore`` and ``get_dump`` will attach ``Booster``'s feature names if exists.
- Thus, plotting functions can use it as below.
```
xgb.plot_importance(bst)
```
See my …
=> Support feature names in Python package 

python-package/xgboost/core.py, tests/python/test_basic.py
Closes #487.
I found #487 description is based on misunderstanding.  Current logic always regard input ``str`` as filename.
This should be after #496.
=> BUG: incorrect model_file results in segfault

python-package/xgboost/core.py, tests/python/test_basic.py
Following inputs are accepted by ``DMatrix`` unintendedly.
```
import numpy as np
xgb.DMatrix(np.array(1))
xgb.DMatrix(np.array([1, 2]))
```
I'll move the test cases once #496 is merged.
=> Bug: Fix numpy array check logic

python-package/setup.py
`execfile` was dropped from Python 3, but this is the [standard alternative](https://stackoverflow.com/a/6357418). The current `master` breaks py3, but I've confirmed that this patch works with Python 3.4.
=> Restore Python3 compatibility

Makefile
OS X Homebrew currently installs a bin called `gcc-5` rather than `gcc`. This should help with issues https://github.com/dmlc/xgboost/issues/465 and https://github.com/dmlc/xgboost/issues/276.
=> Use homebrew gcc if available

Makefile
Sorry about this. I've now tested that it works on OS X and Ubuntu.
=> Fix makefile typo

python-package/xgboost/core.py, python-package/xgboost/plotting.py, tests/python/test_basic.py
Follow-up for #488. This PR makes control output without using ``featmap.txt``. Also, made following changes.
~~I'm going to make ``feature_types`` works as below.~~
- ~~If user passes ``feature_types``, validate then use it as it is.~~
- ~~Check ``i`` columns only have 0/1 values.~~
- ~~Check ``int`` columns only have int-like values (``dtype`` may be float though)~~
- ~~Not check ``q``, ``float`` columns~~
- ~~If user doesn't pass ``feature_types``, use ``i`` for columns only has 0/1 values. Use ``q`` for other columns.~~
=> Python: Add feature_types to DMatrix

python-package/xgboost/training.py, scripts/travis_script.sh, tests/python/test_basic.py
Closes #294.
``xgb.cv`` behaves as below.
- If ``pandas`` is installed, return ``pd.DataFrame`` by default. No progress messages are output in this case, because ``pd.DataFrame`` should contain all information.
- Progress message can be enabled by specifying ``show_progres=True``.
- If ``pandas`` is not installed, or explicitly specified ``as_pandas=False``, return ``np.ndarray``. Progress messages are output because ``np.ndarray`` can't contain metadata.
- Progress message can be disabled by specifying ``show_progres=False``.
Pls see my gist for full example: https://gist.github.com/sinhrks/cc9a88f74074fc296e12#file-pandas-cv-ipynb
CC: @fyears
=> Python CV returns pd.DataFrame or np.ndarray

python-package/xgboost/core.py, scripts/travis_script.sh, tests/python/test_basic.py
Related to #294. It is nice if we can create ``DMatrix`` from ``pandas.DataFrame``. Feature names and types are automatically retrieved by ``DataFrame`` definitions otherwise specified.
Non-supported data types (other than ``int``, ``float``, ``bool`` ) result in ``ValueError``.
=> python DMatrix now accepts pandas DataFrame

python-package/xgboost/core.py, tests/python/test_basic.py
Follow-up for #522. When DataFrame columns are non-numeric, convert it to str.
=> Python supports pd.DataFrame with non-str columns

CONTRIBUTORS.md, demo/guide-python/README.md, demo/guide-python/evals_result.py, demo/guide-python/sklearn_evals_result.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py
Made changes to training.py to make sure all eval_metric information get passed to evals_result. Previous version lost and mislabeled data in evals_result when using more than one eval_metric.
Structure of eval_metric is now:
```
eval_metric[evals][eval_metric] = list of metrics
```
Example for XGBoost train:
```python
dtrain = xgb.DMatrix('../data/agaricus.txt.train', silent=True)
dtest = xgb.DMatrix('../data/agaricus.txt.test', silent=True)
param = [('max_depth', 2), ('objective', 'binary:logistic'), ('bst:eta', 0.01), ('eval_metric', 'logloss'), ('eval_metric', 'error')]
watchlist  = [(dtest,'eval'), (dtrain,'train')]
num_round = 2
evals_result = {}
bst = xgb.train(param, dtrain, num_round, watchlist, evals_result=evals_result)
print('Access logloss metric …
```
=> Update training.py and sklearn.py for evals_result

python-package/xgboost/plotting.py, scripts/travis_script.sh, tests/python/test_basic.py
Allow python plotting functions to handle ``XGBModel`` (sklearn API).
```
from sklearn import datasets
iris = datasets.load_iris()
classifier = xgb.XGBClassifier()
classifier.fit(iris.data, iris.target)
xgb.plot_importance(classifier)
xgb.plot_tree(classifier)
```
=> Allow plot function to handle XGBModel

python-package/xgboost/sklearn.py, python-package/xgboost/training.py
I've fixed a few lines to run evals_result in Python Version 3.
- training.py
TypeError: 'float' object cannot be interpreted as an integer
In Python3, / operator has been changed as follows:
```
>>> 100/3
33
>>> 100//3
33
>>>
>>> 100/3
33.333333333333336
>>> 100//3
33
>>>
```
- sklearn.py
TypeError: 'dict_keys' object does not support indexing
In Python3, keys() function return 'dict_keys' object.
```
>>> x = {"key": "value"}
>>> x.keys()
['key']
>>> x = {"key": "value"}
>>> x.keys()
dict_keys(['key'])
```
=> fix training.py and sklearn.py for evals_result in python3

python-package/xgboost/plotting.py, tests/python/test_basic.py
Fixed the importance plot y margin and typo.
```
import numpy as np
np.random.seed(1)
dm = xgb.DMatrix(np.random.randn(100, 100), label=[0, 1]*50)
bst = xgb.train({}, dm)
len(bst.get_fscore())
xgb.plot_importance(bst)
```
Before (current master):
After (this PR):
=> Python: adjusts plot_importance ylim

Makefile, python-package/MANIFEST.in, python-package/setup.py, python-package/xgboost/build-python.sh
Fix data file shipping confusions on pip install for #463 by:
1. removing data_files in setup.py and giving MANIFEST.in the full control of file shipping
2. leaving a pre-compiled .so file in the `xgboost/wrapper/` and deleting it during pip installation, so it can force system compiling
Add error message for windows users for less confusion.
Current pip installation should give errors when there is no gcc installed on the system, which is the right thing.
=> Fix data file shipping confusions on pip install for #463

python-package/xgboost/core.py
Changes "intialize" to "initialize" with an "i" between "in" and "t"
=> fixes typo in error message

python-package/setup.py
**After installing xgboost on a docker container (Dockerfile below) importing xgboost into python does not work.**
To reproduce:
python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import xgboost
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python2.7/dist-packages/xgboost-0.4-py2.7.egg/xgboost/__init__.py", line 11, in <module>
from .core import DMatrix, Booster
File "/usr/local/lib/python2.7/dist-packages/xgboost-0.4-py2.7.egg/xgboost/core.py", line 92, in <module>
_LIB = _load_lib()
File "/usr/local/lib/python2.7/dist-packages/xgboost-0.4-py2.7.egg/xgboost/core.py", line 83, in _load_lib
lib_path = find_lib_path()
File …
=> install xgboost so it can be imported

doc/python/python_intro.md, python-package/xgboost/core.py, python-package/xgboost/training.py, tests/python/test_eval_metrics.py
- Allows feval to return a list of tuples (name, error/score value)
- Changed behavior for multiple eval_metrics in conjunction with
early_stopping: Instead of raising an error, the last passed evel_metric
(or last entry in return value of feval) is used for early stopping
- Allows *eval_metric* to be a list in dict-typed xgb-params, 
e.g. params = { "eval_metric": ['error' , 'rmse']  }
=>  python: multiple eval_metrics changes

python-package/xgboost/training.py
Multiple eval metrics *has* been passed -> Multiple eval metrics *have* been passed
=> grammar correction

python-package/xgboost/core.py
replacing set literal {} with set() for python 2.6 compatibility (plus reformatting the line)
=> python 2.6 compatibility tweak

Makefile, python-package/MANIFEST.in, python-package/README.rst, python-package/build_trouble_shooting.md, python-package/conv_rst.py, python-package/setup.cfg, python-package/setup_pip.py, python-package/xgboost/build-python.sh
Fixed `pushd` problem in `build_python.sh`: on some machines not using bash or compatible shells, the old build script may fail secretly on `pushd` command which causes some pip installation issue.
Added `conv_rst.py` for converting README.md to README.rst: PyPI doesn't accept markdown so the PyPI `xgboost` page was so messed up. The pip maintainer should use makefile for triggering `conv_rst.py` in `pythonpack` section for generating `README.rst` on the fly. It needs pypandoc on pip maintainer's machine (`pip install pypandoc`, also commented in Makefile)
=> fix pushd problem of pip building, convert README to rst for PyPI

doc/python/python_intro.md, python-package/xgboost/training.py, tests/python/test_training_continuation.py
- new 'Booster' attribute *best_ntree_limit* (see https://github.com/dmlc/xgboost/issues/599)
- unittest for *best_ntree_limit*
- bugfix for wrong *best_iteration* returned after training continuation when using *num_parallel_tree* and/or *num_class* as parameter(s)
=> best_ntree_limit attribute & training continuation bugfix

python-package/conv_rst.py, python-package/xgboost/compat.py, python-package/xgboost/core.py, python-package/xgboost/sklearn.py, tests/python/test_basic.py
Follow-up for #597. We should handle ``data`` and ``label`` separately, because ``data`` can be other than ``DataFrame`` but ``label`` is.
=> Cleanup pandas support

doc/build.md
To support OS X El Capitan:
- Clang method doesn't seem to work anymore.
- GCC has been updated to 5.2.0.
Ref: https://github.com/dmlc/xgboost/issues/596, https://github.com/dmlc/xgboost/issues/626
=> Updated build instructions for OS X.

R-package/R/xgb.train.R, R-package/tests/testthat/test_parameter_exposure.R
Hey guys. 
Working on some projects. We need to be able to access model metadata from within R, in particular `objective` and `base_score`. 
It seems like this info is locked up in the `xgb.Booster.handle` class's bytes and off-limits to the R environment. Rather than write a bunch of c++ to parse the code in `xgb.Booster.handle`, it's neater to just record some model metadata in the R `xgb.Booster` object similar to R's `gbm` package.
Thoughts?
=> Expose model parameters to R

python-package/xgboost/training.py
This change allows you to set `cv()`'s `show_progress` to an integer n to print progress every n trees instead of for each tree, similar to the behavior of `train()`'s `verbose_eval` behavior.
=> modifying cv show_progress to allow print-every-n behavior

python-package/xgboost/training.py
The iteration counter when using training continuation starts with *nboost* of trained model instead of 0 now.
=> fixed wrong iter when using training continuation

python-package/xgboost/training.py
- show_progress=False or show_progress=0 led to devision by zero exception
- added mean and std output to early stopped CV ("Stopping. Best iteration: {} (mean: {}, std: {})\n")
=> python cv: fixed devision by zero exception

doc/model.md
Fixes a latex typo in the derivation of the objective function
=> minor latex typo fix in "Introduction to Boosted Tree's" documentation

R-package/R/xgb.cv.R
early.stop.rounds had an off by 1 bug in xgb.cv. This was causing one of two undesirable behaviors:
1) If only one metric is specified, the test metric is not accessible and runs off the end of the vector
2) If multiple metrics are specified, the wrong metric is used for stopping early
=> Fixed off by 1 bug in early.stop.rounds in xgb.cv

python-package/xgboost/core.py
fix issue#751 https://github.com/dmlc/xgboost/issues/751.
the memo argument seems not to be used in the following code, i suggest it renamed to a single '_'
=> fix signature of __deepcopy__ method

doc/build.md
I just install xgboost on my Debian machine and found a small bug in the documentation.
=> Python Package Installation Documentation Bug

python-package/xgboost/core.py
sklearn wrapper defaults to `missing=None` which means `np.nan`, make this default in the DMatrix constructor as well
=> Make missing handling consistent with sklearn's portion of the Python package

src/tree/updater_colmaker.cc
is the fsplit value should be half way between previous tree's last_value and current node's first_value?
=> fsplit value

R-package/DESCRIPTION, R-package/src/xgboost_R.h
The package on CRAN is just updated to 0.4-3 due to a minor bug. This PR brings the fix to the github version.
=> fix cran, update R-package version to 0.4-3

python-package/xgboost/sklearn.py
I added feature_importances_ property for scikit-learn compatibility.
=> Add feature_importances_ property for XGBClassifier

python-package/training.py, tests/python/test_basic.py
I was using the library and I found that when doing a cross validation, even when I chose the parameter show_progress to False, it showed some messages:
"Will train until cv error hasn't decreased in X rounds", in case of having early_stopping
"Stopping. Best iteration:\n[X] cv-mean:[...]\n"
I wrote some conditions for muting it when show_progress=Fase because if you run a bunch of models with a grid of parameters, the high number of messages can bother :D.
=> Muting the remaining messages when show_progress=False

python-package/xgboost/sklearn.py
The *best_ntree_limit* is not available directly through the sklearn interface. It is available indirectly via: *XGBModel.booster().best_ntree_limit*
=> minor fix: in sklearn.py return attribute best_ntree_limit if early stopped

demo/README.md
In-database parallel gridsearch for XGBoost on Greenplum (open-source MPP database based on Postgres) using PL/Python.
=> Plugging in gp_xgboost_gridsearch

Makefile
To build xgboost depend on dmlc-core and rabit.
But if codes included in those repositories is changed,  those codes would not be re-compiled.
So added dependencies into Makefile.
I think this modify is better for developers.
Would be happy for any feedback.
=> modify Makefile

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostSuite.scala
if the user specifies nthread parameter, we shall make it no larger than spark's cores per task configuration
=> [jvm-packages] if the user specifies nthread parameter, we shall make it meaningful

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala
As noted here: http://stackoverflow.com/a/16278054/3455159, we need to change the code a little bit to support different filesystems such as S3FileSystem.
=> Support different types of filesystems

jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/flink/DistTrainWithFlink.scala, jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/spark/DistTrainWithSpark.scala, jvm-packages/xgboost4j-flink/src/main/scala/ml/dmlc/xgboost4j/scala/flink/XGBoost.scala, jvm-packages/xgboost4j-flink/src/main/scala/ml/dmlc/xgboost4j/scala/flink/XGBoostModel.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostSuite.scala
Due to the changes in https://github.com/dmlc/xgboost/pull/965
I feel that we need to change the API name to reflect that we are supporting hadoop-compatible files instead of just HDFS/local file system, 
I prefer to keep consistent with spark's api http://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.rdd.PairRDDFunctions
i.e. saveAs....
=> [jvm-packages] change the API name 

python-package/xgboost/sklearn.py
Field classes_ in xgbclassifier has to have numpy array type for some sklearn procedures. For example I got error while using sklearn.ensemble.AdaBoostClassifier because classes_ had list type rather then numpy array.
=> change type of xgbclassifier.classes_ from list to numpy array

python-package/xgboost/core.py
This error message can be hard to understand when there are several fields, as shown in the example below. This addition improves the error message, letting the user know which fields were unexpected or missing.
import pandas as pd
train = pd.DataFrame({'a':[1], 'b':[2], 'c':[3], 'd':[4], 'f':[2], 'g':2, 'etc etc etc':[11]})
dtrain = xgb.DMatrix(train.drop('d', axis=1), train.d)
test = pd.DataFrame({'a':[1], 'b':[2], 'c':[1], 'd':[4], 'e':[2], 'f':[2], 'g':2, 'etc etc etc':[11]})
dtest = xgb.DMatrix(test)
modl = xgb.train({}, dtrain)
modl.predict(dtest)
=> a more verbose field mismatch error message

python-package/xgboost/core.py
A more verbose error message letting the user know which fields have impropper data types
=> More verbose error message: which fields have impropper data types

include/xgboost/c_api.h, src/c_api/c_api.cc
first, there's a mismatch between declaration and definition (`void *` in the header), secondly, `DMatrixHandle` array can be `const`.
=> XGBoosterCreate api unified to use const DMatrixHandle[] argument

Makefile
Makefile: change the hardcoded make command to MAKE valiable
http://www.gnu.org/software/make/manual/make.html#MAKE-Variable
That allows, e.g., to simply run `mingw32-make.exe -j` without any renaming or aliasing.
=> fix Makefile to use MAKE variable

src/metric/elementwise_metric.cc
The change allows to specify a prediction score threshold at which to calculate the error. Useful for imbalanced data and scores that are not probability. E.g., `"error@0"` with `"binary:logitraw"` would be the same as `"error"` with `"binary:logistic"`. The `"error"` defaults to `"error@0.5"`.
Had to drop `static` from `EvalRow`. I didn't check whether it actually inlines now, but I don't think saving a few CPU cycles matters here.
=> ability to specify threshold for the error metric

python-package/setup.py, python-package/setup_pip.py, python-package/xgboost/__init__.py, python-package/xgboost/compat.py, python-package/xgboost/core.py, python-package/xgboost/libpath.py, python-package/xgboost/plotting.py, python-package/xgboost/rabit.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py, tests/python/test_basic.py, tests/python/test_basic_models.py, tests/python/test_early_stopping.py, tests/python/test_eval_metrics.py, tests/python/test_plotting.py, tests/python/test_training_continuation.py, tests/python/test_with_pandas.py, tests/python/test_with_sklearn.py, tests/travis/run_test.sh
Enable ``flake8`` in addition to ``lint``, which performs static analysis of Python code. 
I could find missing import of ``pickle`` and ``XGBoostError``, and fixed in this PR.
=> Enable flake8 for Python

R-package/README.md, doc/build.md, python-package/README.rst
Fixed local compilation, and installation for R package and Python package. Modified the according documents.
Used JeanFrancoisPuget's instructions (https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_For_Anaconda_on_Windows?lang=en) and my own local try at compiling xgboost and installing the R package using devtools.
=> Updated obsolete installation instructions

src/c_api/c_api.cc, src/learner.cc
- Make random seed resetting in Configure happen only before a model is initialized. That should help with #1054.
- Prevent accumulation of parameter "history" within `Booster::cfg_` during repeated Configure calls, by resetting the value if a name already exists. It shouldn't really change any results, except it would make the propagation of parameters more efficient while doing parameter resets at each iteration for models with thousands of rounds.
=> Fixes for repeated Configure calls

python-package/xgboost/compat.py, python-package/xgboost/sklearn.py, python-package/xgboost/testing.py, tests/python/test_early_stopping.py, tests/python/test_eval_metrics.py, tests/python/test_plotting.py, tests/python/test_training_continuation.py, tests/python/test_with_pandas.py, tests/python/test_with_sklearn.py, tests/travis/run_test.sh
Found Python API doc is broken (sklearn and plotting).
- http://xgboost.readthedocs.io/en/latest/python/python_api.html
The reason is ``xgboost.sklearn`` imports ``LabelEncoder`` which requires ``scikit-learn``. Remove the ``scikit-learn`` dependencies, and fixed ``"python_lightweight_test"`` to run tests as much as possible without non-core packages (sklearn, pandas and matplotlib).
=> DOC/TST: Fix Python sklearn dep

python-package/xgboost/core.py, python-package/xgboost/plotting.py, python-package/xgboost/sklearn.py, tests/python/test_basic.py
From what I could tell the python package only implemented feature importances using `get_fscore()` which returned the number of times a feature was used to split data (I called this "weight", it was called "weight" in the R package). I added a function to calculate the average gain/coverage called `get_score()` with input importance_type. I also added it to plotting.py so the user can plot gain/coverage with `plot_importance` and a unit test to make sure I didn't botch anything.
=> Added other feature importances in python package

doc/R-package/discoverYourData.md
panda -> Pandas
Note: I had a similar fix a few days ago (https://github.com/dmlc/xgboost/commit/a6909e389f4d64916678b4f7a91acda7f40a35ad) but at that time I missed this similar file.
=> Fixed a typo

python-package/xgboost/sklearn.py
In the fit function for XGBModel, if eval_set is specified with missing data there is an error related to 'missing' not being given. This is because the call to DMatrix is missing 'missing=self.missing'. I have fixed that.
=> call to DMatrix was missing 'missing=self.missing' 

python-package/xgboost/core.py, python-package/xgboost/training.py
XGBoost raises VisibleDeprecationWarning when the numpy version is over 0.9.
```
(xgboost-3.5.1) SUNGHEEui-MacBook:xgboost shaynekang$ nosetests tests/python/
...
/Users/shaynekang/.pyenv/versions/3.5.1/envs/xgboost-3.5.1/lib/python3.5/site-packages/xgboost-0.4-py3.5.egg/xgboost/training.py:273: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
idset = [randidx[(i * kstep): min(len(randidx), (i + 1) * kstep)] for i in range(nfold)]
...
/Users/shaynekang/.pyenv/versions/3.5.1/envs/xgboost-3.5.1/lib/python3.5/site-packages/xgboost-0.4-py3.5.egg/xgboost/core.py:907: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
preds = preds.reshape(nrow, preds.size / nrow)
... …
```
=> Fix VisibleDeprecationWarning

src/data/data.cc
Hi Maintainers,
I recently updated xgboost, I found ".weight" file support is broken. It seems the check-condition was removed for some reason, I don't know whether there is a official guide describe the reason although I was trying to find it.
I am not alone.
#1023
=> [DATA] fix instance weights loading

src/cli_main.cc
When doing count:poisson regression, it trains smoothly. But when doing prediction, it complains max_delta_step missing. 
For example, in the mushroom demo, using this config, the prediction crashes. 
~~~~
booster = gbtree
objective = count:poisson
eta = 1.0
gamma = 1.0
min_child_weight = 1
max_depth = 3
max_delta_step = 0.7
num_round = 2
save_period = 0
data = "agaricus.txt.train"
eval[test] = "agaricus.txt.test"
eval_train = 1
test:data = "agaricus.txt.test"
~~~~
=> fix cli_main crashes when using count:poisson regression

python-package/xgboost/sklearn.py
Save the actual objective used on xgboost.train.
Not saving it was giving problem in predict_proba, as issue  #1215
=> [py]Preserve the actual objective used on the booster

src/c_api/c_api.cc, src/learner.cc, tests/python/test_basic_models.py
My PR #1153 had essentially disabled the multiple eval metrics functionality by allowing only the last metric. This one should fix it by providing a special duplication detection for `eval_metric`.
Also, when setting the DefaultEvalMetric right after loading, it can sometimes create unwanted default metric. So I've moved the lazy DefaultEvalMetric creation into EvalOneIter where it is invoked when really necessary.
=> Fixes for multiple and default metric

src/cli_main.cc
Fix a bug which crashes the program when dumping a count:poisson model
=> Fix issue #1236: cli_main crashes when dumping count:poisson model

doc/parameter.md, src/gbm/gbtree.cc, tests/python/test_basic_models.py
https://github.com/dmlc/xgboost/pull/1199
=> Add Dart booster.

python-package/xgboost/callback.py
related to 
https://github.com/dmlc/xgboost/issues/1251
=> Fixed Setting verbose_eval to False causes DivisionByZero 

R-package/R/xgb.cv.R, R-package/R/xgb.train.R
Added *best_ntreelimit* attribute to *xgb.Booster* if early stopped.
Currently, *xgb.Booster$bestInd* returns the next value of the index of the best iteration specified in the eval message created by booster. This is inconsistent with the implementation in python package.
=> R: fix "bestInd" and add "best_ntreelimit" to xgb.Booster

src/tree/param.h
```
In file included from src/tree/tree_model.cc:8:0:
src/tree/./param.h: In member function 'double xgboost::tree::TrainParam::CalcGain(double, double) const':
src/tree/./param.h:127:61: error: call of overloaded 'abs(double&)' is ambiguous
return - 2.0 * (ret + (double)reg_alpha * std::abs(w));
```
=> Fix OSX compile error: ambiguous call to function abs which both exists in c and c++.

.travis.yml, CMakeLists.txt, include/xgboost/c_api.h, include/xgboost/tree_updater.h, src/c_api/c_api.cc, src/data/sparse_batch_page.h, tests/travis/run_test.sh
-Basic cmake build system added
-Test added to travis build script
-Minor changes to compile for MSVC
=> cmake build system

jvm-packages/README.md
I found out that when I trained a model using the distributed version of the JVM package - the libsvm format for the indexes has to be **one-based** ascending order. Whereas, when I used the saved model in the Python package it expected the libsvm format to be **zero-based** - which resulted in different predictions in the Python package. To work around this you have to modify your libsvm format accordingly.
=> Inconsistency in libsvm formats

CMakeLists.txt
On MSVC its enough to check for new enough compiler versions to get c…++11 support; 
For non-msvc, actually enforce c++11 support, it was allowing c++09 support to pass - the alternative is that the message in the cmake config is wrong and c++09 support is really all thats needed.
=> c++11 cmake check fixes

CONTRIBUTORS.md, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala
At LinkedIn we are prototyping the use of distributed XGBoost with Apache Spark on large datasets for the generation of new categorical machine learning features.
We first learn a distributed XGBoost tree model. Then for each instance, we look at the leaf node to which the instance is assigned by the model and we extract the leaf index as a new kind of "non-linear" tree-based categorical feature.
In this Pull Request, we expose the ability to predict the leaf indices in the Scala XGBoostModel class by calling the predictLeaf method on the underlying Booster.
=> Expose predictLeaf functionality in Scala XGBoostModel

src/data/sparse_page_source.cc, src/gbm/gblinear.cc
when predict in gblinear, loop over output_group is duplicated
=> fix duplicate loop over output_group when predict

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala
fix Issue:
[jvm-packages] Executors fail during prediction (Doing rabit call after Finalize) #1284
=> fix bug: doing rabit call after finalize in spark prediction phase

R-package/R/xgb.DMatrix.R
Fix to a bug when the class function returns more than one value. In that case, the code will fail.
The fixed code simply checks if the "matrix" value is in the set of classes the object can have.
=> Class function returns more than one value

src/gbm/gbtree.cc, src/learner.cc, src/metric/rank_metric.cc, src/tree/param.h
* Removed exception-throwing macros out of some `omp parallel` regions, so that those exceptions could be caught. That should address #1386 
* Since setting the number of OpenMP threads is a global operation, moved the setting of `omp_set_num_threads` with the `nthread` parameter from gbtree into Learner. This way, setting the `nthread` would have effect not only when or after a gbtree model is created. That should fix #1345
=> A couple of openmp fixes

doc/build.md
In Mac, even after gcc is installed from homebrew, gcc and g++ still point to clang's version. 
Need to update the make/config.mk file to point the gcc and g++ compliers to the version installed by homebrew. 
More details can be found in this blog: https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_on_Mac_OSX?lang=en
=> updating Mac installation instructions

Makefile, python-package/MANIFEST.in, python-package/README.rst, python-package/prep_pip.sh, python-package/setup.py, python-package/setup_pip.py, python-package/xgboost/build-python.sh
changed `Makefile` and forced Mac OS X using either `gcc-5` or `clang-omp`, since the `-lopenmp` flag fails the default `Xcode` compiler and causes confusions when linking.
added `pippack` subroutine in `Makefile` for packaging for `pip` installation
changed `MANIFEST.in`, the most important part, by adding refactored code plus exclusion to `.a` files which can fail Linux build-on-the-fly
changed `setup.py` and `setup_pip.py`, added `prep_pip.sh` for supporting updated `pip` install
and, submitted `0.6a2` tag to `PyPI`, tested with Mac OS X 10.10, ubuntu 14/16 and CentOS 7 with no problem
=> PyPI (pip installation) setup for 0.6 code

R-package/src/xgboost_R.cc
@hetong007 gave an example [here](https://gist.github.com/hetong007/d8a27389e95f6f0eed5fd6278e435e7c) in which `xgboost` would cause segfault when `gctorture(TRUE)` is enabled.
This is because in file `xgboost_R.cc`, `UNPROTECT(1)` is called after `R_API_END()`, however `R_API_END()` contains the R API function call `PutRNGstate()`. So in fact, the allocated vector loses protection when `PutRNGstate()` is invoked.
Most of the time this does not cause big problems, but `gctorture()` forces garbage collection on every memory allocation, so the issue comes out when `gctorture(TRUE)` is enabled.
=> Fix a segfault in R package

python-package/xgboost/libpath.py
Currently xgboost can only be installed by running:
python setup.py install
Now it can be packaged (in binary form) as a wheel and installed like:
pip install xgboost-0.6-py2-none-any.whl
distutils and wheel install `data_files` differently than setuptools.
setuptools will install the `data_files` in the package directory whereas the
others install it in `sys.prefix`. By adding `sys.prefix` to the list of
directories to check for the shared library, xgboost can now be distributed as
a wheel.
=> Make python package wheelable

jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/spark/DistTrainWithSpark.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostSuite.scala
since XGBoostModel in xgboost-spark package has exposed booster through a public interface, 
we shall not maintain API working with DMatrix any more 
by removing these APIs, we can remove the redundancy and facilitate various parameter combinations
=> [jvm-packages] remove APIs with DMatrix from xgboost-spark 

CMakeLists.txt
Fixed to work with future versions of visual studio i.e., 2015
MSVC has it's own section for setting compile parameters, it shouldn't need to fall into section below i.e., checking for c++11 as this is definitely already supported, though this isn't an issue for Visual Studio 2012, it breaks for later versions
of visual studio i.e., 2015 when the default c++ is version 14.  Though still backward compatible with c++11
=> MS Visual Studio 2015 fix

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
The original comparison `nThread.toString <= coresPerTask` compares two strings lexically, which leads to failures of assertion, *e.g.*
```
the nthread configuration (4) must be no larger than spark.task.cpus (12)
```
An detailed exception with stack trace:
```
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: the nthread configuration (4) must be no larger than spark.task.cpus (12)
at scala.Predef$.require(Predef.scala:219)
at ml.dmlc.xgboost4j.scala.spark.XGBoost$.train(XGBoost.scala:142)
at ml.dmlc.xgboost4j.scala.example.spark.PlAlgoModelTrainSpark$.main(PlAlgoModelTrainSpark.scala:96)
at ml.dmlc.xgboost4j.scala.example.spark.PlAlgoModelTrainSpark.main(PlAlgoModelTrainSpark.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at …
```
=> [jvm-packages] Fixed the sanity check for parameter 'nthread' against 'spark.task.cpus'.

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
ml.dmlc.xgboost4j.scala.spark.XGBoost.scala:51
values is empty when we meet it at first time, so values(0) throw an IndexOutOfBoundsException.
It should be  dVector.values(i) instead of values(i).
=> [Bug Found] IndexOutOfBoundsException

R-package/R/xgb.DMatrix.R, R-package/src/xgboost_R.cc, R-package/src/xgboost_R.h, R-package/tests/testthat/test_dmatrix.R, include/xgboost/c_api.h, python-package/xgboost/core.py, src/c_api/c_api.cc, tests/python/test_sparse_dmatrix.py
Addresses #1583 
The new "explicit" XGDMatrixCreateFromCS*Ex functions are pretty much duplicates of the old ones with an extra argument, slight code change, and slightly safer types. The old ones are marked as `\deprecated` in their doc. 
I've updated the Python interface, but need to think a bit more about R (would like to make it handle the 64 bit indexing properly). And I didn't touch jvm.
=> More robust DMatrix creation from a sparse matrix

R-package/R/xgb.Booster.R, R-package/tests/testthat/test_helpers.R
R's `as.character` does not guarantee a round-trip numeric -> character -> numeric of storing and retrieving an xgb-attribute to result in an identical double number. Formatting with 17 digits should allow a safe round-trip.
=> [R-package] store numeric attributes with higher precision

python-package/xgboost/compat.py, python-package/xgboost/training.py, tests/python/test_with_sklearn.py
Fixed #1654 @tqchen @CodingCat
=> Fixed #1654: Fix mknfold using new StratifiedKFold API

CMakeLists.txt
add_library(libxgboost SHARED ${SOURCES}) builds a library named
liblibxgboost.so; However, simply changing it to add_library(xgboost ...)
won't work, as add_executable(xgboost ...) and add_library(xgbboost ...)
will then have the same target name. This patch correctly handles the
same-name situation through SET_TARGET_PROPERTIES.
=> Fix a bug to handle Executable and Library with same name (xgboost) correctly

Makefile
Problem and fix of this PR were described in Issue #1667.
Basically it adds the following to the Makefile in order to allow macports users on OS X to use gcc-6 for installation.
```
export CC = $(if $(shell which gcc-6),gcc-6,$(if $(shell which gcc-mp-6), gcc-mp-6, clang))
export CXX = $(if $(shell which g++-6),g++-6,$(if $(shell which g++-mp-6),g++-mp-6, clang++))
```
Please note that the documentation should be updated accordingly (let me know if I can help).
=> Add option on OSX to use macports (Issue #1667)

CMakeLists.txt
fix the problem that there is no libxgboost.dll built with Visual Studio.
=> fix the problem that there is no libxgboost.dll

python-package/xgboost/callback.py
*Fix 1439
*Fix python_wrapper when eval set name contain '-' will cause early_stop maximize variable con't set to True propely
Change-Id: Ib0595afd4ae7b445a84c00a3a8faeccc506c6d13
=> [python-package] Fix the issue #1439

src/metric/rank_metric.cc, src/objective/rank_obj.cc
DCG use log base-2, however `std::log` returns log base-e.
=> correct CalcDCG in rank_metric.cc and rank_obj.cc

R-package/README.md
While I'm big fan of drat, it isn't really needed here. Below code to reproduce installation from base R. `xgboost` is taken from your drat, while all `xgboost` dependencies are taken from repo defined in `repos` option (default user cran mirror(s)).
```
docker pull r-base
docker run -it r-base
install.packages("xgboost", repos=c("http://dmlc.ml/drat/", getOption("repos")), type="source")
packageVersion("xgboost")
#[1] ‘0.6.0’
```
=> simplify installation of R pkg devel version

doc/build.md
The `cd ..;` in the one liner takes you up a directory instead of into the xgboost directory. This will cause that step of the installation to fail. It seems like you are meant to enter the xgboost directory as you did in the instructions for installing xgboost without openmp.
=> Fix `cd ..` typo is OSX installation instructions

include/xgboost/c_api.h, include/xgboost/data.h, include/xgboost/gbm.h, include/xgboost/learner.h, include/xgboost/tree_model.h, plugin/README.md, plugin/example/README.md, python-package/xgboost/core.py, src/c_api/c_api.cc, src/cli_main.cc, src/data/sparse_page_source.h, src/gbm/gblinear.cc, src/gbm/gbtree.cc, src/learner.cc, src/tree/tree_model.cc, tests/python/test_basic.py
This adds the option to dump as JSON.
The bindings for python, R, and java have hardcoded the format as "text" to retain the earlier usage.
Related issue is at https://github.com/dmlc/xgboost/issues/1722
=> Add dump_format=json option

src/logging.cc
On Unix systems, it's common for programs to read their input from stdin, and
write their output to stdout.  Messages should be written to stderr, where they
won't corrupt a program's output, and where they can be seen by the user even
if the output is being redirected.
This is mostly a problem when XGBoost is being used from Python or from another
program.
=> Have ConsoleLogger log to stderr instead of stdout

python-package/xgboost/core.py
For python packages, some times I just want to add one or few customized evaluation functions besides the builtin evaluation functions. We can support both.
=> keep builtin evaluations while using customized evaluation function

src/objective/regression_obj.cc
unable to load, save, or dump model that was created in a different R session unless setting a default for max_delta_step.  this is related to issues #1236 and #1253.
=> add default max_delta_step to for count:poisson

jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/spark/SparkWithDataFrame.scala
Currently the way ```SparkWithDataFrame.scala``` reads data in LibSBM format is still calling the old API ```MLUtils.loadLibSVMFile``` from mllib pakcage, which is causing the following errors with Spark 2.0:
``` 
User class threw exception: java.lang.IllegalArgumentException: requirement failed: Column features must be of type org.apache.spark.ml.linalg.VectorUDT@3bfc3ba7 but was actually ArrayType(FloatType,true). 
```
A cleaner way of reading ```DataFrame``` from files in LibSVM format is to leverage the Spark ml API, as proposed in this PR, which is also more intuitive for folks who are interested to learn XGBoost with Spark 2.0.
The change proposed in this PR has been successfully tested on Spark 2.0.0 hosted on a cluster managed by Hadoop 2.6 (Yarn).
=> [jvm-packages] Leverage the Spark ml API to read DataFrame from files in LibSVM format.

src/c_api/c_api.cc
In ecb3a271bed151252fb048528ce5a90ad75bb68f the silent argument
in XGDMatrixCreateFromFile of c_api.cc was always overridden to
be false. This disabled the functionality to hide log messages.
This commit reverts that part to enable the hiding of log messages.
Fixes https://github.com/dmlc/xgboost/issues/1216
Fixes https://github.com/dmlc/xgboost/issues/1742
=> c_api.cc: Bring back silent argument

doc/jvm/index.md, jvm-packages/pom.xml
This code snippet publishes the sources to the maven local repo along with the binaries. 
With this change it is possible to use Java IDEs functions like "jump to function" and see the actual source code - as they automatically get the sources from the maven repo.
=> [jvm-packages] xgboost4j: publishing sources along with bins

python-package/xgboost/sklearn.py
I noticed the `XGBRegressor` is missing `feature_importances_` that `XGBClassifier` has. I think it's very useful for visualizations or potentially feature selection for downstream models.
It's easy to move this method into the base `XGBModel` to provide access to `XGBRegressor` as well. 
See below:
``` python
from xgboost.sklearn import XGBRegressor, XGBClassifier
import numpy as np
def feature_importances_(self):
"""
Returns
-------
feature_importances_ : array of shape = [n_features]
"""
b = self.booster()
fs = b.get_fscore()
all_features = [fs.get(f, 0.) for f in b.feature_names]
all_features = np.array(all_features, dtype=np.float32)
return all_features / all_features.sum()
random_state = np.random.RandomState(1)
X = random_state.uniform(0, 1, (100, 3))
y = X[:, 0]
reg = …
```
=> Move feature_importances_ to base XGBModel for XGBRegressor access

doc/_static/xgboost-theme/index.html
This pull request replaces "Lanuages" -> "Languages" in the documentation landing page.
=> fix typo on documentation page

R-package/R/xgb.train.R, R-package/tests/testthat/test_update.R, doc/parameter.md, src/gbm/gbtree.cc, src/tree/param.h, src/tree/updater_refresh.cc
The main part of this PR is about adding the infrastructure to "update" an existing tree model. It is a simple mod of the GBTree booster, introducing a `prosess_type` parameter which allows to switch between the default full boosting process (which grows new trees and updates them) and the update process for an existing model (which works by passing a model through a desired set of updater modules using some specific data). I've made this parameter as enum instead of bool, so it would keep a possibility for other process types open. Overall, it is still the same booster that basically allows for a different starting point, so I don't think it would make sense to use inheritance to create a separate booster. And the process switch should work seamlessly for DART as well.
There could be …
=> [CORE] The update process for a tree model, and its application to feature importance

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala
I refactor the eval method in XGBoostModel. There are some redundant code of two approaches, I use match pattern to do the same thing in less code.
=> [jvm-package] refactor evaluation of xgboost4j-spark

make/config.mk
Set the TEST_COVER to 0 by default so it uses optimization
-O3 when compiling.
=> config.mk: Set TEST_COVER to 0 by default

R-package/R/callbacks.R, R-package/R/xgb.Booster.R, R-package/R/xgb.cv.R, R-package/R/xgb.dump.R, R-package/man/xgb.cv.Rd, R-package/man/xgb.dump.Rd, R-package/src/xgboost_R.cc, R-package/src/xgboost_R.h, R-package/tests/testthat/test_callbacks.R, R-package/tests/testthat/test_helpers.R
- R-API for JSON dump format that was contributed in #1726 
- bugfix for #1845 
- bugfix for #1628 
JSON dump example:
```R
data(agaricus.train, package='xgboost')
bst <- xgboost(data = agaricus.train$data, label = agaricus.train$label, max_depth = 2, 
eta = 1, nthread = 2, nrounds = 2, objective = "binary:logistic")
jdump <- xgb.dump(bst, with_stats = TRUE, dump_format='json')
cat(jdump)
```
produces:
```json
[
{ "nodeid": 0, "depth": 0, "split": 28, "split_condition": -9.53674e-007, "yes": 1, "no": 2, "missing": 1, "gain": 4000.53, "cover": 1628.25, "children": [
{ "nodeid": 1, "depth": 1, "split": 55, "split_condition": -9.53674e-007, "yes": 3, "no": 4, "missing": 3, "gain": 1158.21, "cover": 924.5, "children": [
{ "nodeid": 3, "leaf": 1.71218, "cover": 812 },
{ "nodeid": 4, "leaf": …
```
=> [R-package] JSON dump format and a couple of bugfixes

src/gbm/gbtree.cc
Is this a bug? Should normalization factors multiply to trees with drop_idx?
=> fix dart bug

python-package/xgboost/training.py, tests/python/test_basic.py
Add possibility to not shuffle the data when creating k folds.
=> option to shuffle data in mknfolds

demo/gpu_acceleration/bosch.py
Since release of scikit-learn 0.18 (stable) in Sep. 28, `cross_validation` module is included in `model_selection` module.
=> Importing StratifiedKFold

demo/guide-python/cross_validation.py
`cv()` doesn't output `std_value` because `show_stdv` is set to False.
=> Fix comment in cross_validation.py

R-package/DESCRIPTION, R-package/R/xgb.plot.multi.trees.R, R-package/R/xgb.plot.tree.R, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_helpers.R
This PR fix https://github.com/dmlc/xgboost/issues/1934 and https://github.com/dmlc/xgboost/issues/1812.
Adding flags to two tests. The windows one (comparing raw) cannot be resolved for now. The solaris one (comparing precision) should be done in a more careful way later.
=> 0.6-4 submission

R-package/R/xgb.Booster.R
Enforce ntreelimit=0 in predict for gblinear.
=> [R] fix #1903

python-package/setup.py
fixing error on `python setup.py install`:
```
setup() arguments must *always* be /-separated paths relative to the
setup.py directory, *never* absolute paths.
```
see #1932
=> Make lib path relatrive to fix setup error #1932

amalgamation/xgboost-all0.cc, include/xgboost/base.h, include/xgboost/data.h, src/common/hist_util.cc, src/common/hist_util.h, src/common/quantile.h, src/common/row_set.h, src/gbm/gbtree.cc, src/learner.cc, src/tree/param.h, src/tree/updater_fast_hist.cc, tests/python/test_fast_hist.py, tests/travis/run_test.sh
* Add a brand new updater to support histogram-based algorithm, which buckets continuous features into discrete bins to speed up training. To use it, set `tree_method=hist` to configuration.
* Support multiple tree growing strategies. For now, two policies are supported:
* `grow_policy=depthwise` (default):  favor splitting at nodes closest to the root, i.e. grow depth-wise.
* `grow_policy=lossguide`: favor splitting at nodes with highest loss change
* Improve single-threaded performance
* Unroll critical loops
* Introduce specialized code for dense data (i.e. no missing values)
* Additional training parameters: `max_leaves`, `max_bin`, `grow_policy`, `verbose`
=> Histogram Optimized Tree Grower

python-package/xgboost/plotting.py
Following issues #1245 and #1862, added the parameter `max_features` to the `plot_importance` function in order to limit the number of top features to be displayed on plot.
=> added the max_features parameter to the plot_importance function.

python-package/xgboost/plotting.py
follow #1963 
1. not overwrite ylim if ylim is not None
2. use num_of_features as ylim instead of max_num_features if max_num_features > num_of_features
=> fix ylim with max_num_features in python plot_importance

src/tree/tree_updater.cc, src/tree/updater_fast_hist.cc
As discussed in issue #1978, `tree_method=hist` ignores the parameter
`param.num_roots`; it simply assumes that the tree has only one root. In
particular, when `InitData()` method initializes `row_set_collection_`, it simply
assigns all rows to node `0`, the value that's hard-coded.
For now, the updater will simply fail when `num_roots` exceeds 1. I will revise
the updater soon to support multiple roots.
=> Disallow multiple roots for tree_method=hist

src/metric/elementwise_metric.cc
Fixes a small typo in the Poisson metric.
BTW I couldn't find an easy way to run the tests for the package.
Looking at `dmlc-core/scripts/packages.mk` it includes a call to `wget http://googletest.googlecode.com/files/gtest-1.7.0.zip` which currently leads to a 404. Let me know if I should open an issue for that, and if there's an easy way to run tests locally, I'm a newbie with C++ testing.
=> [trivial] Fix typo in Poisson metric name.

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/BoosterParams.scala
Actually, one friend of mine find out the default scalePosWeight is set to 0, which triggered issue #1941
=> [jvm-packages] fix MLlib CrossValidator issues #1941

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostEstimator.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/BoosterParams.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostDFSuite.scala
this is a further fix of https://github.com/dmlc/xgboost/issues/1941 based on https://github.com/dmlc/xgboost/pull/2042
the cross validation issue is caused by a misconfiguration of default value of scale_pos_weight, and this misconfiguration only takes effect when we create an estimator with copy() 
the reason is that when doing copy, we use the ML's parameters to build a Map and pass this Map to trainingWithRDD(), however, when creating estimator from the user's code, we directly use the user-defined Map to pass to trainingWithRDD()
in this patch, I unify these two paths and always uses ML's parameters to build a Map right before we call trainingWithRDD()
=> [jvm-packages] use ML's para system to build the passed-in params to XGBoost

python-package/xgboost/callback.py
verbose_eval docs claim it will log the last iteration (http://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.train). this is also consistent w/the behavior from 0.4. not a huge deal but I found it handy to see the last iter's result b/c my period is usually large.
this doesn't address logging the last stage found by early_stopping (as noted in docs) as I'm not sure how to do that.
=> print_evaluation callback output on last iteration

R-package/demo/caret_wrapper.R
in `caret` settings, if you want do 10*10 cross validation, you need to set repeats=10, number=10 and method=repeatedcv, if you set method=cv, actually just one 10-fold cross validation will be run; fixes #2055
=> fixes #2055

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala
fix bug: doing rabit call after finalize in spark prediction phase #1420 
The above has fixed the fucntion of predict(testSet: RDD[MLVector], useExternalCache: Boolean = false),but predictLeaves() and predict(testSet: RDD[MLDenseVector], missingValue: Float)
have the same problem.so I fixed them.
=> [jvm-packages]fix bug doing rabit call after finalize

jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/rabit/handler/RabitWorkerHandler.scala, jvm-packages/xgboost4j/src/test/scala/ml/dmlc/xgboost4j/scala/rabit/RabitTrackerConnectionHandlerTest.scala
This is a PR attempting to fix the issue reported in #2069. The same issue was originally reported in #1925. 
Previously, a PR (#1993) was submitted to address the buffer underflow exception. However, the pattern matching at https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/rabit/handler/RabitWorkerHandler.scala#L132 was incorrect. It was supposed to catch `BufferUnderflowException`; instead, I wrote `BufferOverflowException`. 
The unit test which was supposed to test the exception handling was also incorrectly constructed due to an ill-formed ByteBuffer. The unit test was updated to fix the error, with more checks added to make sure that the tracker command was constructed properly. 
@CodingCat Please verify that this PR resolves …
=> [jvm-packages] Fixed Exception handling for fragmented Rabit 'print' tracker command.

include/xgboost/learner.h
I use the online prediction function(`inline void Predict(const SparseBatch::Inst &inst, ... ) const;`), the results obtained are different from the results of the batch prediction function(`  virtual void Predict(DMatrix* data, ...) const = 0`). After the investigation found that the online prediction function using the `base_score_` parameters, and the batch prediction function is not used in this parameter. It is found that the `base_score_` values are different when the same model file is loaded many times.
```
1st times：base_score_: 6.69023e-21
2nd times：base_score_: -3.7668e+19
3rd times：base_score_: 5.40507e+07
```
Online prediction results are affected by `base_score_` parameters. After deleting the if condition(`if (out_preds->size() == 1)`) , the online prediction is consistent …
=> fix online prediction function in learner.h

python-package/xgboost/callback.py
When metric's name contains `-`, Python will complain about insufficient arguments to unpack.
=> bugfix: when metric's name contains `-`

src/c_api/c_api.cc
This resolves #2006. I have locally recompiled the new version and can verify that this fix indeed fixes the issue (base_margin is now copied and sliced accordingly during CV). 
Thanks.
=> base_margin was not copied by XGDMatrixSliceDMatrix

demo/guide-python/sklearn_examples.py, tests/python/test_early_stopping.py, tests/python/test_eval_metrics.py, tests/python/test_fast_hist.py, tests/python/test_with_sklearn.py
`sklearn.cross_validation` module is [deprecated](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/cross_validation.py#L40) in scikit-learn 0.18, this PR will resolve this problem.
=> fix DeprecationWarning on sklearn.cross_validation

Makefile
`gcc/g++` defaults to `clang/clang++` anyways and this will support real `gcc/g++` installs too.
=> ENH add gcc/g++ before clang for macs

Makefile
This commit proposes a simpler single compiler specification for OSX and *nix. It also lets people override the setting on both systems, not just *nix.
I am very sorry for the series of seemingly conflicting PRs on this topic from me. I think this one makes the most sense given the discussion [here](https://github.com/conda-forge/staged-recipes/pull/2573#discussion_r107425585).
Happy to chat more of course!
=> ENH more makefile updates

tests/python/test_basic_models.py
Fixes PR #2121 error which is due to bad luck (non deterministic outcome of multithreaded gblinear).
I managed to get >0.20 error after trying 100,000 random xgboost gblinear, which means a false positive issue is possible.
You can compare on the following which are based on #2121 commit e32d759:
* Not failing (and will not fail oddly): https://travis-ci.org/Laurae2/xgboost/jobs/214635300
* Reported weird failure (pure luck): https://travis-ci.org/dmlc/xgboost/jobs/213328891
=> GLM test unit: make run deterministic

include/xgboost/base.h, include/xgboost/tree_updater.h, src/cli_main.cc, src/common/column_matrix.h, src/common/hist_util.cc, src/common/hist_util.h, src/common/row_set.h, src/gbm/gbtree.cc, src/learner.cc, src/metric/rank_metric.cc, src/tree/param.h, src/tree/updater_colmaker.cc, src/tree/updater_fast_hist.cc, tests/python/test_fast_hist.py
* Use columnwise accessor to accelerate `ApplySplit()` step, with support for a compressed representation
* Parallel sort for evaluation step
* Cache gradient pairs when building histograms in `BuildHist()`
TODO: write a blog post
=> Improve multi-threaded performance

demo/binary_classification/README.md
As `num_round=2` there is no `0003.model` file after training.
=> Nonreproducible sequence of evaluations fixed

src/c_api/c_api.cc
This log appears to fire every time I ask the python package to make a prediction. It's the only log that fires from XGBoost. When we're getting predictions on millions of items a day in production, this log seems out of place.
=> Removes extraneous log

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostEstimator.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/BoosterParams.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostDFSuite.scala
Making XGBoostModel hold BoosterParams is beneficial in the case that the XGBoostEstimartor is inaccessible, e.g. when a PipelineModel is taken as the parent of the produced XGBoostModel 
and it also makes the access of the params more convenient, previously, we need to access XGBoost.parent.xxxx
=> [jvm-packages] make XGBoostModel hold BoosterParams as well

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoostJNI.java, jvm-packages/xgboost4j/src/native/xgboost4j.cpp, jvm-packages/xgboost4j/src/native/xgboost4j.h, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/BoosterImplTest.java
* Change Booster dump from XGBoosterDumpModel to XGBoosterDumpModelEx
Allows exposing multiple formatting options of model dumping.
=> [jvm-packages] Expose json formatted booster dumps (#2233)

src/common/hist_util.cc
Reported in issue #2165. Dynamic scheduling of OpenMP loops involve
implicit synchronization. To implement synchronization, libgomp uses futex
(fast userspace mutex), whereas MinGW uses kernel-space mutex, which is more
costly. With chunk size of 1, synchronization overhead may become prohibitive
on Windows machines.
Solution: use 'guided' schedule to minimize the number of syncs
=> Fix performance degradation of BuildHist on Windows

NEWS.md, R-package/DESCRIPTION, R-package/R/callbacks.R, R-package/R/utils.R, R-package/R/xgb.Booster.R, R-package/R/xgb.DMatrix.R, R-package/R/xgb.DMatrix.save.R, R-package/R/xgb.cv.R, R-package/R/xgb.dump.R, R-package/R/xgb.importance.R, R-package/R/xgb.model.dt.tree.R, R-package/R/xgb.plot.deepness.R, R-package/R/xgb.plot.importance.R, R-package/R/xgb.plot.tree.R, R-package/R/xgb.save.R, R-package/R/xgb.train.R, R-package/R/xgboost.R, R-package/README.md, R-package/man/xgb.Booster.complete.Rd, R-package/man/xgb.DMatrix.Rd, R-package/man/xgb.dump.Rd, R-package/man/xgb.model.dt.tree.Rd, R-package/man/xgb.plot.tree.Rd, R-package/man/xgb.train.Rd, R-package/src/xgboost_R.cc, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_dmatrix.R, R-package/tests/testthat/test_helpers.R, doc/how_to/contribute.md
Some fixes, doc changes, and some minor new features:
- Bumped up the R-package version in the development. Users can easily get confused when CRAN-released and development version numbers are the same.
- In some situations, it's more efficient to have tree nodes encoded as integers (as opposed to strings like "2-8"), and the `use_int_id` parameter to `xgb.model.dt.tree()` now provides a direct way to have that.
- The `save_period` parameter must have the same default value in `xgboost()` and `xgb.train()`.
- It's [not unheard of](https://stackoverflow.com/questions/43359154) to have data with all integer columns. xgb.DMatrix should not fail when given a matrix of integers, and should process it the same way as a numeric matrix. The fix allows this without creating an extra copy of data. …
=> [R] maintenance Apr 2017

jvm-packages/pom.xml, jvm-packages/xgboost4j-flink/pom.xml
The former was just Scala binary tag, and the latter was hardcoded in the 'xgboost4j-flink' POM.
=> Removed 'flink.suffix' and added 'flink.version'

include/xgboost/c_api.h, include/xgboost/gbm.h, include/xgboost/learner.h, include/xgboost/tree_model.h, python-package/xgboost/core.py, src/c_api/c_api.cc, src/gbm/gblinear.cc, src/gbm/gbtree.cc, src/learner.cc, tests/python/test_basic.py
This implements the idea described at http://blog.datadive.net/interpreting-random-forests/
which tries to give insight in how a prediction is composed of its feature contributions
and a bias.
The calculation of the node values is based on the findings of @SauceCat at https://github.com/dmlc/xgboost/issues/1986.
Open issues:
1. I added this functionality to `XGBoosterPredict()` as another value to `option_mask`. However it is mutually exclusive with the `PredictLeaf()` and `PredictRaw()` options, so it feels wrong to being able to pass `0x07` to this function (which is no different from `0x04`)
1. to calculate the values at each node, I multiply the learning rate with the `base_weight` property. However, the `learning_rate` value seems to be unavailable in `GBTree` (or `RegTree` for that …
=> Add prediction of feature contributions

include/xgboost/tree_updater.h, src/data/sparse_batch_page.h
Compilation failed with
```
In file included from src/tree/tree_updater.cc:6:0:
include/xgboost/tree_updater.h:75:46: error: 'function' is not a member of 'std'
std::function<TreeUpdater* ()> > {
```
caused by a missing `<functional>` include.
=> Fix compilation on OS X with GCC 7

NEWS.md, R-package/DESCRIPTION, R-package/R/xgb.Booster.R, R-package/man/predict.xgb.Booster.Rd, R-package/tests/testthat/test_helpers.R, include/xgboost/c_api.h, include/xgboost/gbm.h, include/xgboost/learner.h, src/gbm/gblinear.cc, src/gbm/gbtree.cc
This is a follow-up to #2003 .
It also fixes a bug in GBLinear::DumpModel where group and feature indices were swapped.
=> adding feature contributions to R and gblinear

CONTRIBUTORS.md, NEWS.md, python-package/xgboost/core.py, python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
This allows users of the Sklearn API to provide all Booster params via a **kwargs dict.
=> Sklearn kwargs

R-package/demo/predict_leaf_indices.R
for loop in create.new.tree.features was referencing length(trees) as the upper bound of the loop. trees is a base R dataset and not the model that the code is generating. Changed loop boundary to model$niter which should be the number of trees.
=> Fixed loop bound in create.new.tree.features

jvm-packages/create_jni.sh, jvm-packages/xgboost4j/pom.xml
- Fixed one of the Maven warnings, complaining about missing version for `exec-maven-plugin`.
- Changed `create_jni.sh` to be easier to debug.
=> Minor improvements to xgboost/jvm-packages build 

jvm-packages/checkstyle-suppressions.xml
XGBoostJNI.java was not excluded on Windows, probably because the path
specified in 'checkstyle-suppressions.xml' used UNIX file separators.
Closes #2347, #2017.
=> [jvm-packages] Fixed checkstyle excludes on Windows

include/xgboost/c_api.h
Makes `c_api.h` compatible with C compilers - fixes `c_api.h:10:10: fatal error: 'cstdint' file not found`and `error: unknown type name 'uint64_t` errors. This fix was tested on MacOS + Clang and Linux + GCC.
See also https://github.com/dmlc/rabit/pull/44.
=> Fix C API header compatibility with C compilers

python-package/xgboost/core.py
Don't use implicit conversions to c_int, which incidentally happen to work
on (some) 64-bit platforms, but:
* may lead to truncation of the input value to a 32-bit signed int,
* cause segfaults on some 32-bit architectures (tested on Ubuntu ARM,
but is also the likely cause of issue #1707).
Also, when passing references use explicit 64-bit integers, where needed,
instead of c_ulong, which is not guaranteed to be this large.
For consistency and to avoid confusion I also made conversions to c_int explicit.
=> [Python] Use appropriate integer types when calling native code.

src/data/data.cc
Use int32_t explicitly when serializing version field of dmatrix meta in binary format. On ILP64 architectures, although very little, size of int is 64 bits.
=> Use int32_t explicitly when serializing version

R-package/DESCRIPTION, R-package/R/xgb.importance.R, R-package/man/xgb.importance.Rd, R-package/tests/testthat/test_helpers.R
- fixed multiclass importance for gblinear, as raised in #2331
- new `trees` parameter allows, e.g., to inspect feature importances for each class separately
=> [R] xgb.importance: fix for multiclass gblinear, new 'trees' parameter

.gitmodules, CMakeLists.txt, cmake/Cuda.cmake, cmake/Utils.cmake, jvm-packages/xgboost4j/src/native/xgboost4j.cpp, plugin/updater_gpu/README.md, plugin/updater_gpu/src/common.cuh, plugin/updater_gpu/src/device_helpers.cuh, plugin/updater_gpu/src/exact/argmax_by_key.cuh, plugin/updater_gpu/src/exact/gpu_builder.cuh, plugin/updater_gpu/src/functions.cuh, plugin/updater_gpu/src/gpu_data.cuh, plugin/updater_gpu/src/gpu_hist_builder.cu, plugin/updater_gpu/src/gpu_hist_builder.cuh, plugin/updater_gpu/src/types.cuh, plugin/updater_gpu/src/updater_gpu.cu, plugin/updater_gpu/test/python/test.py, src/tree/param.h
* Added multi-GPU capability using NVIDIA NCCL into grow_gpu_hist plugin
1) Multi-GPU shards rows across multiple GPUs, so problem sizes can be as large as the cumulative GPU memory size.  This allows much larger data to be processed by a single model.
2) Multi-GPU shards nodes across multiple GPUs, for faster node splitting at high depth
3) As with GPU vs. CPU, multi-GPU will not always be faster than a single GPU due to PCI bus bandwidth that can limit performance and due to CPU overhead between GPU calls
* Cleaned-up CMakeLists.txt to compile cub and nccl automatically as submodules
* Added cmake helper files (copied from dmlc/mshadow/cmake) to automatically handle cuda compute compatibility
* Ensured nccl and xgboost compile and run properly in visual studio in windows
=> [GPU-Plugin] Multi-GPU for grow_gpu_hist histogram method using NCCL

python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
discuss in https://github.com/dmlc/xgboost/commit/6cea1e3fb7bdc435aeba5ea6fc5567e29249486e#commitcomment-22391065
if n_jobs/nthreads or seed/random_state is changed in other place except `__init__`, it will cause clone error.
=> [python-package] fix sklearn n_jobs/nthreads and seed/random_state bug 

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/IRabitTracker.java, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/RabitTracker.java, jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/rabit/RabitTracker.scala
Previously the code relied on the tracker process being terminated
by the OS, which was not the case on Windows.
Closes #2394
=> [jvm-packages] Deterministically XGBoost training on exception

doc/parameter.md
The objective section was missing a space and thus all the bullet were are the same level.
=> Fix Typo in documentation

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala
When using xgboost4j-spark I had executors getting killed much more
often than i would expect by yarn for overrunning their memory limits,
based on the memoryOverhead provided. It looks like a significant
amount of this is because dmatrix's were being created but not release
as they were only released when the GC decided it was time to
cleanup the references.
Rather than waiting for the GC, release the DMatrix's when we know
they are no longer necessary.
=> [jvm-packages] Release dmatrix when no longer needed

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java, jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/Booster.scala
Added a method similar to the predictLeaf one, called predictContrib, and followed that pattern.
=> [jvm-packages] Expose prediction feature contribution on the Java side 

Makefile, python-package/xgboost/libpath.py
As discussed in 2cb51f7097df44f7f2993d47865b0090194e2dc4.
I haven't implemented the symlink, because 
* it was previously broken for OS X as well (the shared library had an .so extension) and 
* I'd rather prefer pushing the users to do the right thing. 
If you think I should do otherwise, please comment.
=> Fixed shared library loading in the Python package

doc/parameter.md
The original URL (https://www.kaggle.com/wiki/MultiClassLogLoss) shows 404 Error. Changes it to https://www.kaggle.com/wiki/LogLoss
=> Update URL for "Multiclass logloss".

.gitignore, CMakeLists.txt, Makefile, plugin/updater_gpu/README.md, plugin/updater_gpu/benchmark/benchmark.py, plugin/updater_gpu/gitshallow_submodules.sh, plugin/updater_gpu/src/common.cuh, plugin/updater_gpu/src/device_helpers.cuh, plugin/updater_gpu/src/exact/argmax_by_key.cuh, plugin/updater_gpu/src/exact/fused_scan_reduce_by_key.cuh, plugin/updater_gpu/src/exact/gpu_builder.cuh, plugin/updater_gpu/src/exact/gradients.cuh, plugin/updater_gpu/src/exact/loss_functions.cuh, plugin/updater_gpu/src/exact/node.cuh, plugin/updater_gpu/src/exact/split2node.cuh, plugin/updater_gpu/src/gpu_data.cuh, plugin/updater_gpu/src/gpu_hist_builder.cu, src/tree/updater_colmaker.cc, src/tree/updater_fast_hist.cc
* Fixed ability to use gpu_id to access other GPUs for both grow_gpu and grow_gpu_hist methods.
* Default to no sharding of nodes as on typical systems and depths this is expensive due to communication overhead.  Added new param.h option findsplit_shardongpus that defaults to 0.
* Additional documentation for the gpu plugin.
* Updated cub submodule to latest 1.7.0 version that has various bug fixes.
* Allow user to avoid cloning recursive and call plugin/updater_gpu/gitshallow_submodules.sh because cub has very large history that is not needed.  Leads to much faster clone of xgboost.
* Bug fix to use of colsample so doesn't lead to 0 columns selected (both cpu and gpu code)
=> [GPU-Plugin] Multi-GPU gpu_id bug fixes and additional documentation

jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/spark/SparkWithRDD.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala, jvm-packages/xgboost4j-spark/src/test/resources/log4j.properties, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/SharedSparkContext.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/DMatrix.java, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/DataBatch.java, jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/DMatrix.scala
The users can now initialize boosting with predictions from an external model. This feature is implemented via RDD API and therefore does not require the user to know the partitioning of the training set.
=> [jvm-packages] Exposed baseMargin

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala
Prior to this commit XGBoostModel.predict produced an RDD with
an array of predictions for each partition, effectively changing
the shape wrt the input RDD. A more natural contract for prediction
API is that given an RDD it returns a new RDD with the same number
of elements. This allows the users to easily match inputs with
predictions.
This commit removes one layer of nesting in XGBoostModel.predict output.
Even though the change is clearly non-backward compatible, I still
think it is well justified. See discussion in 06bd5dca for motivation.
=> [jvm-packages] Fixed a signature of XGBoostModel.predict

src/common/column_matrix.h, src/common/hist_util.cc, src/common/hist_util.h, src/tree/fast_hist_param.h, src/tree/param.h, src/tree/updater_fast_hist.cc
Change parallel strategy for histogram construction.
Instead of partitioning data rows among multiple threads, partition feature columns instead. Useful heuristics for assigning partitions have been adopted from [LightGBM project](https://github.com/Microsoft/LightGBM/blob/master/src/io/dataset.cpp). In particular, features that do not have overlapping nonzeros are grouped together.
How to use: by default, the new parallel strategy will be used. To revert to old behavior, simply set `enable_feature_grouping=0`.
Background: poor performance scaling with respect to number of worker threads has been reported by [a user benchmark](https://github.com/Laurae2/gbt_benchmarks). OpenMP inserts an implicit synchronization barrier at end of each parallel loop; with high work imbalance, most threads …
=> Patch to improve multithreaded performance scaling

Makefile, include/xgboost/tree_model.h, src/tree/updater_fast_hist.cc
fixes the following error
```
Makefile:73: Extraneous text after `else' directive
Makefile:76: *** only one `else' per conditional.  Stop.
```
=> Fix broken make on windows

src/tree/fast_hist_param.h
It has been reported that new parallel algorithm (#2493) results in excessive
message usage and random crashes. Until issues are resolved, XGBoost should use
the old parallel algorithm by default. The user would have to specify
`enable_feature_grouping=1` manually to enable the new algorithm.
=> Use old parallel algorithm for histogram construction by default

jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/TrainTestData.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/Utils.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostConfigureSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostDFSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala
This is preparatory PR for a proper implementation of baseMargin, which sadly doesn't work for RDDs with >1 partition.
=> [jvm-packages] Deduplicated train/test data access in tests

plugin/updater_gpu/src/device_helpers.cuh, plugin/updater_gpu/src/gpu_hist_builder.cu, plugin/updater_gpu/src/gpu_hist_builder.cuh, plugin/updater_gpu/test/python/test_large.py, src/common/column_matrix.h, src/common/compressed_iterator.h, src/common/hist_util.cc, src/common/hist_util.h, src/common/row_set.h, src/tree/updater_fast_hist.cc, tests/cpp/common/test_compressed_iterator.cc
[GPU-Plugin] Fix gpu_hist to allow matrices with more than just 2^{32} elements limited by int (32-bit) and instead use bst_ulong or size_t for element-related quantities.  Also fixed CPU hist algorithm for same reason (uses common code, so had to propagate down through cpu hist algorithm as well). Tested with test_large.py .
=> [GPU-Plugin] Fix hist and gpu_hist to allow matrices with more than just 2^{32} elements

CMakeLists.txt, Makefile, appveyor.yml, include/xgboost/base.h, src/c_api/c_api.cc
- As discussed in #2461 , dropped the 'lib' prefix from shared library name in MinGW as well. Python package works with mingw again.
- Added Apveyor CI for MinGW and python
- I don't think it is necessary to run two appveyor jobs for jvm; and, perhaps, can live without a Debug job for MSVC2013
- some 'g++ 4.8 or higher' defines seemed to (unintentionally?) miss versions above 4
=> MinGW: shared library prefix and appveyor CI

CMakeLists.txt, amalgamation/xgboost-all0.cc, include/xgboost/gbm.h, include/xgboost/learner.h, include/xgboost/predictor.h, src/gbm/gblinear.cc, src/gbm/gbtree.cc, src/gbm/gbtree_model.h, src/learner.cc, src/predictor/cpu_predictor.cc, src/predictor/predictor.cc
Remove prediction logic from gbtree class and extract into new prediction interface.
This will allow us to perform prediction on GPUs in future. 
This pr should contain no changes to the execution of XGBoost.
=> [WIP] Extract prediction into separate interface

doc/parameter.md, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/BoosterImplTest.java
The parameter `max_bin` was misspelled as `max_bins`. Reported in issue #2567.
=> Fix documentation for a misspelled parameter

.gitmodules, Makefile, python-package/xgboost/training.py, src/gbm/gbtree_model.h
- Fixed the serialization bug after the update process #2545
- The CV folds splitting process in python could omit some data instances. E.g.
```python
nrow = 9
nfold = 5
idx = np.arange(nrow)
kstep = int(len(idx) / nfold)
[idx[(i * kstep): min(len(idx), (i + 1) * kstep)] for i in range(nfold)]
```
produces `[array([0]), array([1]), array([2]), array([3]), array([4])]` which omits indices from 5 to 8
- Some make versions in windows (coming with Rtools or some MSYS2 distributions) get wrong locations for $CURDIR and $MAKE. I've added some attempts to auto-fix them. That should, hopefully, cure many make-in-windows related issues.
- `make clean` should clean up the R-package as well
- The recently added `cub` git submodule adds 146M to a cloned xgboost repository, making it 168M total. Most …
=> Several fixes

include/xgboost/base.h
Improves sorting performance by around 5x on 8 core fx8350 vs std::sort().
In particular this speeds up the AUC metric calculation.
=> Add parallel sort for MSVC

jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostDFSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala
Apparently, there is a bug in 2.10 which allows passing positional arguments after a named one.
=> [jvm-packages] Fixed compilation on Scala 2.10

python-package/xgboost/plotting.py
I often prefer hiding the values from the feature importances plot, mainly for esthetic reasons. This PR retains the default setting of showing the values, and allows their removal with a boolean.
=> Option to remove values in feature importances plot

.travis.yml, jvm-packages/pom.xml, tests/travis/run_test.sh
The current codecov only reports the coverage of cpp code. To better integrate with codecov plugin, we should enable coverage report for Java and Python as well.
=> Add Coverage Report for Java and Python

.travis.yml
So the travis jobs are killed by linux OOM killer rather than maven. Because the travis container only has 4GB memory, the OOM killer seems very aggressive. If we switch to Sudo-enabled VM, we will be much safer.
https://docs.travis-ci.com/user/reference/overview/
=> Use Sudo-enabled VM which has 7.5GB memory

include/xgboost/base.h, src/common/hist_util.h, src/gbm/gblinear.cc, src/objective/rank_obj.cc, src/tree/param.h, src/tree/updater_basemaker-inl.h, src/tree/updater_colmaker.cc, src/tree/updater_fast_hist.cc, src/tree/updater_gpu_common.cuh, src/tree/updater_gpu_hist.cu, src/tree/updater_histmaker.cc, src/tree/updater_skmaker.cc, tests/cpp/helpers.cc, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/xgboost_test.mk
Use integer backed gradient pair storage. This provides deterministic summation with atomic operations performed in nondeterministic order. 
Gradient pair type changed to use getter and setter methods to abstract the underlying storage.
=> Integer gradient summation for GPU histogram algorithm.

doc/faq.md
`doc/faq.md` has invalid links to `param_tuning.md` and `external_memory.md`
=> Fixed links in faq.md

doc/_static/xgboost-theme/static/searchtools.js
Current version of [xgboost.readthedocs.io](https://xgboost.readthedocs.io) has a broken search box.
Enabling themes on ReadTheDocs is known to break the search function, as reported in [this document](https://github.com/rtfd/readthedocs.org/issues/1487). To get around the bug, we replace the `searchtools.js` file with our custom version.
How to test the custom script before merging this PR:
* Download `searchtools.js` to your home folder.
* Run `python -m SimpleHTTPServer`.
* Open the web browser and browse to http://localhost:8000/searchtools.js
Make sure that you can access the script using this address.
* Download the Google Chrome extension [Resource Override](https://chrome.google.com/webstore/detail/resource-override/pkoacgokdfckfpndoffpifphamojphii).
This will let you subtitute …
=> A hack to fix broken search bar in doc

CONTRIBUTORS.md, python-package/xgboost/sklearn.py
Currently, `XGBClassifier.get_xgb_params()` throws an error if `seed` or `nthread` are missing from the `__init__` method of a child class of `XGBClassifier`.  Since `nthread` and `seed` are deprecated, we should not force child classes of `XGBClassifier` to include `nthread` and `seed` in the `__init__` method.  This PR fixes the issue in `XGBClassifier.get_xgb_params()` by checking for the existence of the `nthread` and `seed` keys in the `xgb_params` dict before checking the values associated with the keys.
=> Check existance of seed/nthread keys before checking their value.

jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/BasicWalkThrough.scala, jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/CrossValidation.scala, jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/CustomObjective.scala, jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/ExternalMemory.scala, jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/GeneralizedLinearModel.scala, jvm-packages/xgboost4j-flink/src/main/scala/ml/dmlc/xgboost4j/scala/flink/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/LearningTaskParams.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostDFSuite.scala, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoost.java, jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/XGBoost.scala, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/BoosterImplTest.java, jvm-packages/xgboost4j/src/test/scala/ml/dmlc/xgboost4j/scala/ScalaBoosterImplSuite.scala
This PR allows configuring the number of consecutive increases in the eval metrics which lead to early stopping. The parameter is exposed both in standalone versions in Java/Scala and in the distributed ones.
=> [jvm-packages] Implemented early stopping

python-package/xgboost/sklearn.py
Adding xgb_model paramter allows the continuation of model training.
Model has to be saved by calling `model.get_booster().save_model(path)`
=> Add xgb_model parameter to sklearn fit

src/common/row_set.h
Problem:
Fast histogram updater crashes whenever subsampling picks zero rows
Diagnosis:
Row set data structure uses "nullptr" internally to indicate a non-existent
row set. Since you cannot take the address of the first element of an empty
vector, a valid row set ends up getting "nullptr" as well.
Fix:
Use an arbitrary value (not equal to "nullptr") to bypass nullptr check.
=> Fix issue #2800

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala
Training a model with the experimental rank:ndcg objective incorrectly
returns a Classification model. Adjust the classification check to
not recognize rank:* objectives as classification.
=> [jvm-packages] Rank is not a classification task

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala
In the refactor to add base margins, #2532, all of the labels were lost
when creating the dmatrix. This became obvious as metrics like ndcg
always returned 1.0 regardless of the results.
=> [jvm-packages] Repair spark model eval

doc/build.md
Keeping things simpler for OS X users:
- tested on macOS Sierra 10.12.6
- `brew install gcc` is now at v 0.7.2,
- `--without-multilib` isn't an option anymore:
```
$ brew info gcc
gcc: stable 7.2.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org/
/usr/local/Cellar/gcc/7.2.0 (1,487 files, 284MB) *
Poured from bottle on 2017-10-11 at 23:04:26
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb
==> Dependencies
Required: gmp ✔, libmpc ✔, mpfr ✔, isl ✔
==> Options
--with-jit
Build just-in-time compiler
--with-nls
Build with native language support (localization)
--HEAD
Install HEAD version
```
(it's actually not needed in our case as `there is no incompatibility between OpenMP and multilib support` https://github.com/Homebrew/homebrew-core/pull/16751)
=> Update OSX build instructions

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassificationModel.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressionModel.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostTrainingSummary.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostDFSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModelSuite.scala, jvm-packages/xgboost4j/src/native/xgboost4j.cpp
They are accessible via `XGBoostModel.summary`. The summary is not serialized with the model and is only available after the training.
=> [jvm-packages] Exposed train-time evaluation metrics

include/xgboost/c_api.h
`XGDMatrixFree()` argument type was different between `include/xgboost/c_api.h` and `src/c_api/c_api.cc`. This fix adjusts argument type to `src/c_api/c_api.cc`.
=> Fix XGDMatrixFree argument type

doc/model.md
Here are some small fixes to the notation in the formulas in the "Introduction to Boosted Trees" document.  They seem to have been missed in https://github.com/dmlc/xgboost/pull/1461.
=> Small fixes to notation in documentation

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/RabitTracker.java, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/TrackerProperties.java
In some scenarios, the host IP determined by tracker.py may not be suitable. For instance, while connecting to a spark cluster through a VPN network.
I included the ability to parameterize the host-ip (retrieving the resource xgboost-tracker.properties), to then pass it as a parameter to tracker.py.
=> Parameterize host-ip to pass to tracker.py

build.sh
Provide hints on how to build if a new user just clones the repository without --recursive and is looking for help with this error
```
xgboost/python-package$ python setup.py develop
File "setup.py", line 19, in <module>
LIB_PATH = [os.path.relpath(libfile, CURRENT_DIR) for libfile in libpath['find_lib_path']()]
File "xgboost/libpath.py", line 46, in find_lib_path
'List of candidates:\n' + ('\n'.join(dll_path)))
__builtin__.XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
```
=> build.sh hints for errors related to: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?

src/data/data.cc
When xgboost ran in distributed mode, different workers load different part of train file and val file.
It might happen that the partition of the val file didn't get the real number of the features. (Say, the maximum index in this partition is 99, while the truth is 100) In this case, the train partition and the val partition will fail the validation check. 
I add an allreduce call to sync up the number of features after workers loaded different partitions, so that each partition knows the real number of features and the validation check will note fail.
=> Sync number of features after loaded matrix in different workers.

doc/gpu/index.md, src/tree/param.h, src/tree/updater_colmaker.cc, src/tree/updater_gpu.cu, src/tree/updater_gpu_common.cuh, src/tree/updater_gpu_hist.cu, tests/python-gpu/test_gpu_updaters.py, tests/python-gpu/test_monotonic_constraints.py
Implements monotone constraints for the GPU histogram algorithm.
Contains unit tests for the univariate case.
Also passes visual tests here for multivariate case: https://github.com/XiaoxiaoWang87/xgboost_mono_test
Implementing this feature required some small changes to the existing constraints code. In particular it was not possible to access the vector containing the constraints information (param.monotone_constraints) in device code. For this reason the CalcSplitGain function now directly accepts an integer constraint instead of requiring params as an argument.
=> Monotone constraints for gpu_hist

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostDFSuite.scala
Prior to this PR both data sets were persisted in the same directory, i.e. the test data replaced the training one which led to
* training on less data (since usually test < train) and
* test loss being exactly equal to the training loss.
Closes #2945.
=> [jvm-packages] Fixed test/train persistence

python-package/xgboost/sklearn.py
delete duplicated code in python-package.
The line 142 and line 158 in the python-package/xgboost/sklearn.py are the same code, delete line 142.
=> delete duplicated code in python-package

appveyor.yml
This patch changes appveyor config.
Added new msvc target for win32 platform.
Wheel artifacts are created after build stage for msvc release targets.
```
python-package\wheel\xgboost-0.6-py2.py3-none-win32.whl
python-package\wheel\xgboost-0.6-py2.py3-none-win_amd64.whl
```
Slightly related to [#1551](https://github.com/dmlc/xgboost/issues/1551)
=> [Python] AppVeyor CI for Python wheel package

NEWS.md
This is a modification of #2975, to document major changes made in year 2017. After this PR is merged, I'll go ahead and create the tag `v0.7`.  
Note: The release log is extraordinarily long because so many things happened since the last release (v0.6), which was one year and half ago. From now on, let's stick with bi-monthly schedule of minor releases.
=> Tag version 0.7

python-package/setup.py, python-package/setup_pip.py
This patch is essential so that the Python wheels get correct version number.
=> Update PyPI maintainer; use VERSION for binary wheels

python-package/README.rst
After installing gcc@5, CMAKE_C_COMPILER will not be set to gcc-5 automatically in some macOS environment  and the installation of xgboost will still fail. Manually setting the compiler will solve the problem.
=> update macOS gcc@5 installation guide

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala
the current implementation will cause java.util.NoSuchElementException in predict() since we call .head API even numRows is 0
this PR contains a tiny fix for it
=> [jvm-packages] tiny fix for empty partition in predict

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/CheckpointManager.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/CheckpointManagerSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala
There are multiple terminology such as `checkpointXXX` `savingXXX` and `model` for the CheckpointManager feature which makes it confusing. Also, it's more accurate to change `frequency` to `interval` since freq = 1 / interval. This PR makes adjustment to the docs and terminology.
=> [jvm-packages] Update docs and unify the terminology

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
As these are cache files, we can apply these changes to avoid naming conflicts and leftovers after Spark jobs finish.
=> [jvm-packages] Move cache files to TempDirectory and delete this directory after XGBoost job finishes

jvm-packages/xgboost4j-spark/src/main/scala/org/apache/spark/SparkParallelismTracker.scala
This PR changes how xgboost registers and removes Listeners to SparkContext so that it works on Spark2.3 while it continues to work on versions of Spark >= 2.0.
Spark 2.3 includes changes in LiveListenerBus which are incompatible with xgboost's SparkParallelTracker - the SparkContext::listenerBus member variable changed type and it is no longer possible to register or deregister listeners by directly accessing list of listeners in it. I've changed  it so that listener is registered via public method on SparkContext. The public method for removing listener has been added only in Spark2.3 and in order to run on older versions of Spark I still call the method on the listenerBus instance.
This change means xgboost will not compile against/ run on spark version < 2.0.
=> (Minor) Fix in SparkParallelTracker to work with Spark2.3

R-package/DESCRIPTION, R-package/R/xgb.train.R, R-package/man/xgb.train.Rd, R-package/src/init.c, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_helpers.R
This PR fix the current Error/Warning from `R CMD check --as-cran`, in order to have a new CRAN submission.
- The R-package version number increases to `0.7-0`, following the change of the main repository.
- Resolving https://github.com/dmlc/xgboost/issues/2960 and  https://github.com/dmlc/xgboost/issues/2948 .
The check logs from https://win-builder.r-project.org can be viewed at:
- R 3.3.3: https://win-builder.r-project.org/8xI5cw7al9UR/00check.log
- R 3.4.3: https://win-builder.r-project.org/Af73bVzp8BDq/00check.log
- R devel: https://win-builder.r-project.org/CC2L5vstoeP1/00check.log
=> A fix for CRAN submission of version 0.7-0

src/common/device_helpers.cuh
- thrust::copy() called from dvec::copy() for gpairs invoked a GPU kernel instead of
cudaMemcpy()
- this resulted in illegal memory access if the GPU running the kernel could not access
the data being copied
- new version of dvec::copy() for thrust::device_ptr iterators calls cudaMemcpy(),
avoiding the problem.
=> Fixed the bug with illegal memory access in test_large_sizes.py with 4 GPUs.

src/common/quantile.h, src/common/timer.h
Submission of the R package to CRAN forbids the use of std::cout #2960, #3061. All the console output needs to go through the LOG facilities which are then captured in https://github.com/dmlc/xgboost/blob/master/R-package/src/xgboost_custom.cc
I did the change in a couple of files that are currently included in the R package submission to CRAN. @RAMitchell There's still some cout use in device_helpers.cuh and updater_gpu_hist.cu that should be preferably also changed to LOG. If there is interest, I can define, e.g., LOG_VERBATIM in https://github.com/dmlc/xgboost/blob/master/include/xgboost/logging.h that would allow using LOG(VERBATIM) very much as cout (it would not prefix its output with timestamp even when XGBOOST_LOG_WITH_TIME is defined, and would not have automatic newline).
=> Replacing cout with LOG

src/c_api/c_api.cc
In line 461, the "size_t offset = 0;" should be declared before any calculation, otherwise will cause compilation error. 
When using CMake for mvn package under jvm-package, will cause error below:
```
I:\Libraries\xgboost\src\c_api\c_api.cc(416): error C2146: Missing ";" before "offset" [I:\Libraries\xgboost\build\objxgboost.vcxproj]
```
and with the modification in the PR the problem solved.
Not sure with higher CMaker will fix the problem, but in C standard, the variable maybe better to be declared on the top in the function.
=> c_api.cc variable declared inapproiate

doc/build.md
=> added mingw64 installation instruction, and library file copy.

python-package/xgboost/callback.py
This pull request addresses an issue when verbose_eval parameter set to zero leads to ZeroDivisionError: integer division or modulo by zero.
=> Fix for ZeroDivisionError when verbose_eval equals to 0.

cmake/modules/FindLibR.cmake, src/gbm/gbtree.cc, src/objective/regression_obj.cc, src/predictor/cpu_predictor.cc
Addresses the issue of the O(num_class^2) prediction cache behavior #1689, #2926 where cache updates within CommitModel may start dominating with many classes. The reason was that the cache was updated for each single class group commit in a boosting round. E.g., with
```R
set.seed(1)
n <- 1e4
num_feat <- 200
num_class <- 150
y <- apply(rmultinom(n, 1, rep(1, num_class)), 2, function(yy) which(yy != 0)) - 1
dtr <- xgb.DMatrix(matrix(rnorm(n*num_feat), n, num_feat), label = y)
param <- list(objective='multi:softprob', num_class=num_class, debug_verbose=1,
tree_method='hist', subsample=0.6)
bst <- xgb.train(param, data=dtr, nrounds=1)
rm(bst)
gc()
```
the timing result before (note that no watchlist was used, and using it would make caching even slower):
```
[16:21:50] ======== Monitor: …
```
=> [core] fix slow predict-caching with many classes

doc/tutorials/monotonic.md, src/tree/param.h, src/tree/updater_fast_hist.cc, tests/python/test_monotone_constraints.py
I have extended the monotonic constraints functionality so that they are now compatible with the 'hist' tree method. I have also added tests based on the repo by @madrury (https://github.com/madrury/xgboost-monotonic-testing).
=> 'hist': Montonic Constraints

src/common/hist_util.cc
There was a bug for both hist and gpu_hist where the lowest quantile could have an upper bound of zero and lower bound of zero. This fixes it so that the minimum value is strictly less than all other cut values.
=> Fix incorrect minimum value in quantile generation

src/predictor/gpu_predictor.cu, tests/python/test_with_sklearn.py
Restrict the gpu_predictor to only caching matrices also stored in the host DMatrix cache. This guarantees a matrix cached on the device will always have a valid pointer to a DMatrix on the host.
This fixes #3162, which was caused by the DMatrix being deleted on the host but the gpu_predictor was still dereferencing its pointer.
=> Fix bug with gpu_predictor caching behaviour

include/xgboost/c_api.h
Without this, with gcc 7.2.0, we see:
/xgboost/include/xgboost/c_api.h:98:1: error: function
declaration isn't a prototype [-Werror=strict-prototypes]
XGB_DLL const char *XGBGetLastError();
^~~~~~~
=> Allow compilation with -Werror=strict-prototypes

src/c_api/c_api.cc
This replaces the array allocated by new with a std::vector.
Fixes #3161
=> Fix memory leak in XGDMatrixCreateFromMat_omp()

R-package/DESCRIPTION
Note that a lot more stuff can be added in comment field, such as an [ORCID](orcid.org/).
"cre" on Tong He simply means the maintainer of the package.
=> Change DESCRIPTION to more modern look

Makefile, python-package/setup_pip.py, python-package/xgboost/build-python.sh
* Now `make pippack` works without any manual action: it will produce `xgboost-[version].tar.gz`, which one can use by typing `pip3 install xgboost-[version].tar.gz`. I tested it on MacOS and Linux.
* Detect OpenMP-capable compilers (clang, gcc-5, gcc-7) on MacOS
This PR will fix recent reports of failed installation on MacOS, such as #3118, #3194, #2426, provided that a new release is issued using `make pippack`. I plan to make release 0.71 once this is merged.
=> Fix up `make pippack` command for building source package for PyPI

appveyor.yml
The R package dependency 'data.table' is apparently unavailable in Windows binary format, resulting into the following build errors:
* https://ci.appveyor.com/project/tqchen/xgboost/build/1.0.1810/job/hhanvg0c2cqpn7bc
* https://ci.appveyor.com/project/tqchen/xgboost/build/1.0.1811/job/hg65t9wb3rt1f5k8
Fix: use type='both' to fall back to source when binary is unavailable
=> Fix RMinGW build error: dependency 'data.table' not available

jvm-packages/xgboost4j-example/README.md
The link is broken. As DataFrame is the first class API for Spark, so I point the the link to DataFrame based example.
cc @CodingCat
=> [jvm-packages] Fix broken link for xgboost-spark example.

src/tree/updater_gpu_hist.cu
Performing cub reduction inside a loop, using temporary shared memory location, without a barrier between successive calls was causing race conditions on K80/K40 cards. Not sure why this hasn't been a problem on Maxwell/Pascal/Volta! See the Issue #3264 for the root-cause and the final output after this fix.
=> Fix for the issue #3264.

src/common/device_helpers.cuh, src/common/host_device_vector.cc, src/common/host_device_vector.cu, src/common/host_device_vector.h, src/gbm/gbtree.cc, src/objective/regression_obj_gpu.cu, src/predictor/gpu_predictor.cu, src/tree/updater_gpu.cu, src/tree/updater_gpu_hist.cu
- HostDeviceVector instances can now span multiple devices, defined by GPUSet struct
- the interface of HostDeviceVector has been modified accordingly
- GPU objective functions are now multi-GPU
- GPU predicting from cache is now multi-GPU
- avoiding omp_set_num_threads() calls
- other minor changes
=> Multi-GPU HostDeviceVector.

src/linear/updater_coordinate.cc, src/objective/multiclass_obj.cc, tests/cpp/linear/test_linear.cc
Solves #3261
Default learning rate for coordinate descent updater also changed to 0.5 to match shotgun updater.
=> Prevent multiclass Hessian approaching 0

src/tree/tree_model.cc
`DumpRegTree` writes floats with default 6-digits precision which causes precision loss. 
This PR aims at setting the precision to a level where the conversion back to float is lossless.
=> Increase precision of bst_float values in tree dumps

.gitignore
In particular, the patterns involving 'xgboost' seemed overly broad. We shouldn't ignore /include/xgboost, I think.
=> Improve .gitignore patterns

CMakeLists.txt, amalgamation/dmlc-minimum0.cc, plugin/dense_parser/dense_libsvm.cc, tests/travis/run_test.sh
This is a follow-up of #3215. Updating the dmlc-core submodule lets XGBoost take advantage of fixes applied to the CSV parser.
Ideally, I'd like to see https://github.com/dmlc/dmlc-core/pull/385 to be merged before this PR gets approved.
=> Update dmlc-core submodule

jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/CheckpointManagerSuite.scala
As before, the compilation error is caused by mixing positional and labelled arguments.
=> [jvm-packages] Fixed CheckpointManagerSuite for Scala 2.10

Makefile, R-package/remove_warning_suppression_pragma.sh
A few headers in dmlc-core contain #pragma's that disable compiler warnings, which is against the CRAN submission policy. Fix the problem by removing the offending #pragma's as part of the command `make Rbuild`.
This addresses issue #3322.
=> For CRAN submission, remove all #pragma's that suppress compiler warnings

jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/spark/SparkModelTuningTool.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/BoosterParams.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/LearningTaskParams.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/CheckpointManagerSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/PersistenceSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifierSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostConfigureSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressorSuite.scala
Refactor and reorganize XGBoost-Spark params, now it follows both XGBoost(snake_case for param names) and Spark MLlib(camelCase) convention. For example, if you would like to train a ```XGBoostClassificationModel```, you can use either of the following ways:
* Set params with XGBoost way
```
val paramMap = Map(
"eta" -> "1",
"max_depth" -> "6",
"silent" -> "1",
"objective" -> "binary:logistic",
"num_round" -> 5,
"num_workers" -> 4)
val model1 = new XGBoostClassifier(paramMap).fit(trainingDF)
```
* Set params with Spark MLlib way
```
val model2 = new XGBoostClassifier()
.setEta(1)
.setMaxDepth(6)
.setSilent(1)
.setObjective("binary:logistic")
.setNumRound(5)
.setNumWorkers(4)
.fit(trainingDF)
```
=> [jvm-packages] Refactor XGBoost-Spark params to make it compatible with both XGBoost and Spark MLLib

python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
In Sklearn wrapper, the option to train using using instance weights works OK. However, when evaluating performance metrics on validation sets, there was no option to use instance weights.
=> Sklearn: validation set weights

tests/cpp/tree/test_param.cc
Fix include path of tests/cpp/test_param.cc
Currently the build process can pass is because cmake adds -I<path-to>/dmlc-core/include compiler flag, which let "../../" accidentally becomes the root path of xgboost.
=> Fix test_param.cc header path

python-package/xgboost/sklearn.py
```XGBClassifier.predict_proba``` is to predict class probabilities, so it doesn't make sense to support ```output_margin```. If users want to output margin, they can just use ```predict(data, output_margin=True)```.
Some users report misuse of this argument when calling ```XGBClassifier.predict_proba``` at #3308. If users set ```output_margin=True``` when calling ```predict_proba``` by mistake, it will produce confused and meaningless result.
For example, this is the correct result:
(This is binary classification, each column is the probability of the sample being of a given class)
```
>>> model.predict_proba(X_test, output_margin=False)[0:10]
array([[0.9545844 , 0.04541559],
[0.05245447, 0.9475455 ],
[0.41897488, 0.5810251 ],
[0.9831998 , 0.0168002 ],
[0.4119159 , 0.5880841 ], …
```
=> [python-package] Remove output_margin from XGBClassifier.predict_proba argument list.

R-package/R/xgb.Booster.R
I always get "Handle is invalid!" message with the R package xgboost 0.71.1. I found that `valid_handle` is `TRUE` when `x$handle` is (a kind of ) `NULL`, but it seems to be the opposite.
=> Fix print.xgb.Booster for R

src/cli_main.cc
Currently, `CLIPredict()` saves prediction results in default 6-digit precision which causes precision loss. This PR sets precision to a level so that the conversion back to `bst_float` is lossless.
Related: #3298.
=> Save outputs in high precision in CLI prediction

R-package/DESCRIPTION, appveyor.yml
This PR includes fix following https://github.com/dmlc/xgboost/issues/3365 , for a `0.71.2` submission to CRAN.
Please hold until https://github.com/dmlc/rabit/pull/59 and https://github.com/dmlc/dmlc-core/pull/408 are merged, and submodules are updated.
=> Fix CRAN check for lintr

src/tree/updater_gpu_common.cuh, src/tree/updater_gpu_hist.cu, tests/python-gpu/test_gpu_updaters.py
Use shared memory atomics (wherever possible) for building histograms. Currently, I tested this on 2M rows of airline dataset, Tesla V100, cuda v9.0, depthwise tree grow, max-depth=5, numTrees=100. Here are the training numbers with and without shared mem atomics.
```
w/o smem: train_time (s): 44.84
w/ smem: train_time (s): 16.98
```
Current change, at runtime, decides to use shared memory for building histogram, if there's enough shared mem available, else, falls back to global mem atomics.
=> Shared memory atomics while building histogram

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
Fixes https://github.com/dmlc/xgboost/issues/3412
Regarding the concern with memory usage in https://github.com/dmlc/xgboost/pull/3387, since Seq is lazy I don't think there's much overhead (and it definitely isn't loading the whole thing in memory, otherwise the indexing wouldn't be an issue) compared to using the iterator directly.
Manually ran and checked that it 1) had the same output and 2) completed for a large input
=> [jvm-packages] Avoid use of Seq.apply in buildGroups

tests/ci_build/build_via_cmake.sh, tests/travis/run_test.sh
CI tests were failing because wget prompts "the user" for a response whenever the google test archive is already on the disk.
Fix: Use `-nc` option to skip download when the archive already exists
=> Fix wget for google tests in CI

tests/ci_build/build_via_cmake.sh, tests/travis/run_test.sh
This is a follow-up of #3414. The google test archive should not be un-zipped when the extracted directory already exists.
=>  Fix wget for google tests in CI (follow-up)

CONTRIBUTORS.md, src/objective/regression_obj.cc, tests/cpp/objective/test_regression_obj.cc
Unlike `reg:poisson`, the `ProbToMargin` function for `TweedieRegression` was not defined so the `base_score` was not passed through a `std::log`.
=> Fix tweedie handling of base_score

jvm-packages/xgboost4j/src/native/xgboost4j.cpp, src/c_api/c_api.cc, src/c_api/c_api_error.h
SegFault or SIGSEGV in JVM is usually very hard to debug. This PR convert such failure to user friendly messages. Take the following Java code for example,
```
Booster booster = ...;
booster.dispose();
booster.toByteArray();
```
Before this PR,
```
#
#
#
#
#
#
#
```
After this PR,
```
[22:45:29] /home/yunn/xgboost/dmlc-core/include/dmlc/logging.h:300: [22:45:29] /home/yunn/xgboost/src/c_api/c_api.cc:809: Booster has not been intialized or has alrady been disposed.
Stack trace returned 4 entries:
[bt] (0) /home/yunn/xgboost/lib/libxgboost4j.so(_ZN4dmlc15LogMessageFatalD1Ev+0x41) [0x7f6ef8260f81]
[bt] (1) /home/yunn/xgboost/lib/libxgboost4j.so(XGBoosterGetModelRaw+0x265) [0x7f6ef8264a05]
[bt] (2) /home/yunn/xgboost/lib/libxgboost4j.so(Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterGetModelR …
```
=> Convert handle == nullptr from SegFault to user-friendly error.

Jenkinsfile
@hcho3 where did we get to with uploading GPU enabled wheels to pypi? I will be releasing a blog post soon it would be nice to have this ready if possible.
=> Build universal wheels using GPU CI

CMakeLists.txt
Fixed #977. Very old issue, but is still presented while xgboost installation via MinGW.
=> fixed MinGW missed dll

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala
This is used to call low-level APIs on native booster, such as "getFeatureScore".
=> [jvm-package] Expose nativeBooster for XGBoostClassificationModel and XGBoostRegressionModel

CMakeLists.txt, Makefile, include/xgboost/c_api.h, include/xgboost/logging.h, python-package/xgboost/core.py, src/c_api/c_api.cc, src/logging.cc
Addresses #3020. Any language wrapper can call `XGBRegisterLogCallback()` to intercept the output of `LOG(INFO)` and `LOG(CONSOLE)`.
=> Add callback interface to re-direct console output

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/BoosterParams.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala
as gbtree is the only booster type having distributed updater (hist_maker,prune) we should disable the configuration of these two parameters to avoid confusing users
=> [jvm-packages] disable booster setup for xgboost4j-spark

Jenkinsfile
- Needed by the issue #3404
- as v9.1 doesn't have a nccl2 release
JFYI, please refer to @hcho3's comment regarding possible caching behavior of Jenkinsfile here: https://github.com/dmlc/xgboost/pull/3404.
=> Upgrade cuda version to 9.2 for CI workflows

python-package/xgboost/core.py, tests/python/test_shap.py
Add `'total_gain'` and `'total_cover'` as possible `importance_type`
arguments to `Booster.get_score` in the Python package.
`get_score` already accepts a `'gain'` argument, which returns each
feature's average gain over all of its splits.  `'total_gain'` does the
same, but returns a total rather than an average.  This seems more
intuitively meaningful, and also matches the behavior of the R package's
`xgb.importance` function.
I also added an analogous `'total_cover'` command for consistency.
This resolves #3484.
=> Add total_gain and total_cover importance measures

.clang-tidy, src/learner.cc
Fixes #3509 and #3026, where `max_delta_step` parameter gets lost during serialization / pickling.
Fix: save `max_delta_step` as a Booster attribute, which is guaranteed to be saved correctly.
=> Fix model saving for 'count:possion': max_delta_step as Booster attribute

CMakeLists.txt
Move building dmlc-core before adding DMLC_LOG_CUSTOMIZE.
Fix #3520.
=> Fix building dmlc-core from xgboost.

jvm-packages/README.md
looks like some users still confused about the explanation here
=> [jvm-packages] a better explanation about the inconsistent issue

src/tree/split_evaluator.cc
I think the `ThresholdL1` function in `split_evaluator.cc` has a typo: for small values of `g`, it makes more sense to return `0` rather than `g`.  This is what the version of `ThresholdL1` in `param.h` does.  (In fact, maybe it would be simplest to just call that one directly?)
But I could be missing something -- @henrygouk is the original author so maybe he can correct me.
=> Fix typo in ElasticNet threshold function

include/xgboost/base.h
* \_\_CUDA\_\_ is defined in clang. Making the change won't make clang
compile xgboost, but syntax checking for *.cu from clang is at least partially
working.
=> Use __CUDA__ macro with __NVCC__.

src/predictor/cpu_predictor.cc
The base margin will need to have length `[num_class] * [number of data points]`. Otherwise, the array holding prediction results will be only partially initialized, causing undefined behavior.
Fix: check the length of the base margin. If the length is not correct, use the global bias (`base_score`) instead. Warn the user about the substitution.
This PR fixes #3505 by clarifying the use of `set_base_margin()`.
=> Fix #3505: Prevent undefined behavior due to incorrectly sized base_margin

R-package/tests/testthat/test_dmatrix.R, src/c_api/c_api.cc
Description: The bug is triggered when
1. The data matrix has empty rows at the bottom. More precisely, the rows `n-k+1`, `n-k+2`, ..., `n` of the matrix have missing values in all dimensions (`n` number of instances, `k` number of trailing rows)
2. The data matrix is given as Compressed Sparse Column (CSC) format.
Diagnosis: When the CSC matrix is converted to Compressed Sparse Row (CSR) format (this is common format used for DMatrix), the trailing empty rows are silently ignored. More specifically, the row pointer (`offset`) of the newly created CSR matrix does not take account of these rows.
Fix: Modify the row pointer.
This PR fixes #3545.
=> Fix #3545: XGDMatrixCreateFromCSCEx silently discards empty trailing rows

include/xgboost/gbm.h, src/gbm/gblinear.cc, src/gbm/gbtree.cc, src/learner.cc, tests/python/test_basic_models.py
Dropout (for DART) should only be used at training time.
Fixes #3485.
Fixes #3540.
=> Fix #3485, #3540: Don't use dropout for predicting test sets

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/BoosterParams.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifierSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressorSuite.scala, jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/Booster.scala
=> [jvm-packages] enable predictLeaf/predictContrib/treeLimit in 0.8 

doc/parameter.rst, doc/tutorials/dart.rst, include/xgboost/gbm.h, python-package/xgboost/core.py, python-package/xgboost/sklearn.py, src/gbm/gblinear.cc, src/gbm/gbtree.cc, src/learner.cc, tests/python/test_basic_models.py
Reverts dmlc/xgboost#3556, as it breaks the logic for custom evaluation and custom objective. I've documented the use of `ntree_limit` when predicting with test sets.
=> Revert "Fix #3485, #3540: Don't use dropout for predicting test sets"

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java
Related to https://github.com/dmlc/xgboost/issues/3570#
=> Eliminate use of System.out + proper error logging

doc/conf.py
ReadTheDocs detaches git HEAD so you need extra logic to locate current branch.
=> Refined logic for locating git branch inside ReadTheDocs

src/common/hist_util.cc, src/data/simple_dmatrix.cc, src/data/sparse_page_dmatrix.cc, src/gbm/gblinear.cc, src/gbm/gbtree.cc, src/linear/coordinate_common.h, src/linear/updater_gpu_coordinate.cu, src/linear/updater_shotgun.cc, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, src/tree/updater_basemaker-inl.h, src/tree/updater_colmaker.cc, src/tree/updater_gpu.cu, src/tree/updater_histmaker.cc, src/tree/updater_refresh.cc, src/tree/updater_skmaker.cc
@hcho3 this heavily impacts performance of the linear models so it should go in 0.8 if possible.
=> Remove accidental SparsePage copies

jvm-packages/xgboost4j-spark/src/main/scala/org/apache/spark/SparkParallelismTracker.scala
This pull request amends the broken #3062 allow Spark 2.2 to work.
Please note this won't work in Spark <=2.1 as sc.removeSparkListener was implemented in Spark 2.2. (So perhaps a more general method is better, although that is what was attempted in #3062)
This PR fixes: #3208, #3151 and the discussion in #1927.
I do find it strange that #3062 dose not work in Spark 2.2, it's probably due to some sort of public/private issue in the org.apache.spark.scheduler.LiveListenerBus class inheritance (In Spark itself). The error is: `java.lang.NoSuchMethodError: org.apache.spark.scheduler.LiveListenerBus.removeListener(Ljava/lang/Object;)V`
=> [jvm-packages] Fix Spark 2.2 Support (Amending #3062)

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala
Suggestion: I would recommend implementing `predictRaw` and `raw2probabilityInPlace` correctly as well, so it would comply with all regular spark stages.
=> [jvm-packages] Make sure 'thresholds' are considered when executing predict method

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala
Current computation of `Array(1 - probability(0), probability(0))` is done with `Float` which looses precision. This fix converts to `Double` first, then computes the probabilities.
=> [jvm-packages] Avoid loosing precision when computing probabilities by converting to Double early

include/xgboost/data.h, include/xgboost/tree_model.h, src/c_api/c_api.cc, src/common/hist_util.cc, src/common/host_device_vector.cc, src/common/host_device_vector.cu, src/common/host_device_vector.h, src/common/span.h, src/data/simple_dmatrix.cc, src/data/simple_dmatrix.h, src/gbm/gblinear.cc, src/linear/coordinate_common.h, src/linear/updater_gpu_coordinate.cu, src/linear/updater_shotgun.cc, src/objective/regression_obj_gpu.cu, src/tree/updater_basemaker-inl.h, src/tree/updater_colmaker.cc, src/tree/updater_gpu.cu, src/tree/updater_histmaker.cc, src/tree/updater_skmaker.cc, tests/cpp/c_api/test_c_api.cc, tests/cpp/common/test_host_device_vector.cu, tests/cpp/common/test_span.cc, tests/cpp/common/test_span.cu, tests/cpp/common/test_span.h, tests/cpp/data/test_simple_csr_source.cc, tests/cpp/data/test_simple_dmatrix.cc, tests/cpp/data/test_sparse_page_dmatrix.cc
Implement span class from ISO++20 for safer pointer indexing.
TODOs:
=> Span class.

jvm-packages/pom.xml
for some reason this part was missing in master branch????
=> [jvm-packages] add the missing scm urls

demo/binary_classification/README.md, doc/parameter.rst
I wrote a native XGBoost to Vespa converter that uses XGBoost's JSON model dump as input (https://github.com/vespa-engine/vespa/pull/6577), so I added some missing documentation for the existing `dump_format` parameter in the CLI version.
=> Add JSON model dump functionality documentation

demo/guide-python/custom_objective.py
Custom objective whose name contains a colon (:) will cause crash:
```
...../xgboost/training.py in _train_internal(params, dtrain, num_boost_round, evals, obj, feval, xgb_model, callbacks)
88                 msg = bst_eval_set.decode()
89             res = [x.split(':') for x in msg.split()]
---> 90             evaluation_result_list = [(k, float(v)) for k, v in res[1:]]
91         try:
92             for cb in callbacks_after_iter:
too many values to unpack (expected 2)
```
Fixes #3598.
=> Fix #3598: document that custom objective can't contain colon (:)

demo/guide-python/custom_objective.py, doc/parameter.rst, src/learner.cc
Currently, if the user don't specify the parameter `eval_metric`, XGBoost will print RMSE by default. (The default metric depends on the task. For classification, the default metric is error.) This is the case even when the custom loss function is supplied. This pull request adds an option to suppress the default metric.
=> Add option to disable default metric

.travis.yml, CMakeLists.txt, cmake/modules/FindASan.cmake, cmake/modules/FindLSan.cmake, cmake/modules/FindTSan.cmake, doc/contribute.rst, tests/cpp/c_api/test_c_api.cc, tests/cpp/common/test_column_matrix.cc, tests/cpp/common/test_gpu_hist_util.cu, tests/cpp/data/test_metainfo.cc, tests/cpp/data/test_simple_csr_source.cc, tests/cpp/data/test_simple_dmatrix.cc, tests/cpp/data/test_sparse_page_dmatrix.cc, tests/cpp/helpers.cc, tests/cpp/helpers.h, tests/cpp/linear/test_linear.cc, tests/cpp/metric/test_elementwise_metric.cc, tests/cpp/metric/test_metric.cc, tests/cpp/metric/test_multiclass_metric.cc, tests/cpp/metric/test_rank_metric.cc, tests/cpp/objective/test_hinge.cc, tests/cpp/objective/test_objective.cc, tests/cpp/objective/test_ranking_obj.cc, tests/cpp/objective/test_regression_obj.cc, tests/cpp/objective/test_regression_obj_gpu.cu, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/test_learner.cc, tests/cpp/tree/test_gpu_hist.cu, tests/travis/run_test.sh
Early PR. I need to see how's travis reacting.
=> Add travis sanitizers tests.

demo/binary_classification/README.md, doc/parameter.rst
The CLI parameter `use_buffer` is no longer recognized by the latest codebase.
=> Fix #3609: Removed unused parameter 'use_buffer'

demo/rank/README.md, demo/rank/rank.py, demo/rank/rank_sklearn.py, python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
This PR resolves #2859. My implementation is slightly different from OP's implementation as group information has to be separately fed to `fit` method, instead of combining it together with features. I believe that ranking is quite a different task compare to classification or regression, so this difference in interface is probably justified. By the way, this is currently how LightGBM implements its sklearn ranker interface. 
Regarding testing, I am not very sure what is the best way to test this interface. What I have done so far is to compare it with the results obtained from the `train` method, but this relies on the dataset used in `demo/rank`. If you believe there are better ways of testing, please let me know.
=> sklearn api for ranking

doc/tutorials/model.rst
There seems to be an extra dollar sign in the "Introduction to Boosted Trees" doc.
=> Remove errant $

doc/gpu/index.rst, doc/tutorials/external_memory.rst
=> Document CUDA requirement, lack of external memory on GPU

src/common/common.h, src/common/device_helpers.cuh, src/common/gpu_set.h, src/common/hist_util.cu, src/common/host_device_vector.h, src/common/timer.h, src/linear/updater_gpu_coordinate.cu, src/objective/regression_obj_gpu.cu, src/predictor/gpu_predictor.cu, src/tree/updater_gpu.cu, src/tree/updater_gpu_hist.cu, tests/cpp/common/test_gpuset.cc
* Remove the use of old NDevices* functions.
@RAMitchell Some planed changes from #3608 extracted here to let that PR less messy.  To complete that PR, some functions need to be generalized for both CPU and GPU.  Since I can't test it on multi-gpu environment, I think it's best to split this as an independent PR to ease reviewing.
=> Merge generic device helper functions into gpu set.

src/common/host_device_vector.cu, tests/cpp/common/test_random.cc, tests/cpp/data/test_metainfo.cc
Some meta infotests were accidentally removed in a previous commit due to failures with some Windows compilers.
=> Add google test for a column sampling, restore metainfo tests

demo/binary_classification/mapfeat.py
Fixes #3638 by ensuring that feature indices start with 0, not 1.
=> Fix #3638: Binary classification demo should produce LIBSVM with 0-based indexing

src/common/host_device_vector.cu, tests/cpp/common/test_host_device_vector.cu
- previously, vec_ in DeviceShard wasn't updated on copy; as a result,
the shards continued to refer to the old HostDeviceVectorImpl object,
which resulted in a dangling pointer once that object was deallocated
=> Fixed copy constructor for HostDeviceVectorImpl.

demo/rank/runexp.sh, demo/rank/wgetdata.sh
This is a very trivial issue. I noticed that with the original script, data processing is bundled with `run_exp.sh`, which now serves as a demo on how to use CLI. If one wants to play with python interface, he needs to execute `run_exp.sh` first. I figured that it might be better to process the data right after it is downloaded so one can run the python demos independently from CLI demo.
=> Fix `demo/rank` data processing order

R-package/src/Makevars.in, R-package/src/Makevars.win, R-package/tests/testthat/test_helpers.R, include/xgboost/logging.h
Reference to std::cerr causes CRAN check to fail. The solution is to remove the reference when compiled with R.
=> Fix CRAN check by removing reference to std::cerr

doc/parameter.rst
The parameter doc only listed `rank:pairwise`, while omitting listwise objectives `rank:ndcg` and `rank:map`.
=> Document LambdaMART objectives: pairwise, listwise

python-package/xgboost/core.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py
Goal is to pass scikit-learn's check_estimator() for XGBClassifier, XGBRegressor, and XGBRanker.
It is actually not possible to do so entirely, since check_estimator() assumes that NaN is disallowed, but XGBoost allows for NaN as missing values. However, it is always good idea to add some checks inspired by check_estimator().
Related: #3580
=> Add scikit-learn tests

doc/conf.py, doc/requirements.txt, python-package/xgboost/core.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py
#3674 adds a few tests in an attempt to pass `check_estimator()` test of scikit-learn, but it has broken the doc build. Given that it is actually not possible to pass `check_estimator()` entirely (see #3674 for reason why), I think the tests cause a lot of headaches without much tangible benefits. Instead of spending more time to fix it, I think it is more fruitful to revert #3674.
From now on, I will be more careful when submitting pull requests.
=> Revert #3677 and #3674

doc/python/python_api.rst, python-package/xgboost/callback.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py
Following issue #3663
Closes #3663
=> Fix #3663: Allow sklearn API to use callbacks

src/tree/updater_gpu_hist.cu
- it turns out creating an std::vector on every call is faster
than cudaMallocHost()/cudaFreeHost()
=> Fixed the performance regression within EvaluateSplits().

python-package/xgboost/callback.py
Early stopping callback makes splits with '-' letter, which interferes with metrics of form NDCG@n-. As a result, XGBoost tries to minimize NDCG@n-, where it should be maximized instead.
Fix. Specify maxsplit=1.
=> Fix #3397: early_stop callback does not maximize metric of form NDCG@n-

R-package/tests/testthat/test_basic.R, src/tree/split_evaluator.cc
The `max_delta_step` parameter fell through the cracks during the recent change to `SplitEvaluator` for the `grow_colmaker` and `grow_fast_histmaker` updaters. It can be very useful for noisy datasets. I didn't see any noticeable timing performance change for the default `max_delta_step=0` case.
Also I've removed the unused reg_gamma parameter from ElasticNet, since it's only to be used during pruning.
=> Add the missing max_delta_step

LICENSE
Including full text of Apache 2.0 allows GitHub to automatically detect license for the XGBoost repository.
Example:
=> Include full text of Apache 2.0 license

python-package/xgboost/core.py
Addresses #3616.
On some systems, the XGBoost library (`libxgboost.so`, `xgboost.dll`, or `libxgboost.dylib`) may fail to load because of missing dependencies. Previously, it would result in a uninformative error
```
UnboundLocalError: local variable 'lib' referenced before assignment
```
This pull request is aimed at producing a better error message for this scenario.
=> Better error message for failed library loading

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/LearningTaskParams.scala
According to the [Learning Task Parameters documentation](https://xgboost.readthedocs.io/en/latest/parameter.html#learning-task-parameters), `rank:ndcg` and `rank:map` learning objectives should be available.
There is a little discussion about if there was any specific reason why these objectives were previously omitted [here](https://github.com/dmlc/xgboost/issues/901) and [here](https://discuss.xgboost.ai/t/jvm-packge-does-xgboost-spark-support-rank-ndcg/229).
=> [jvm-packages] Add rank:ndcg and rank:map to Spark supported objectives

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/LearningTaskParams.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifierSuite.scala
This is to address xgboost4j-spark 0.8: customized objective function "obj_type" error when one tries to use custom objectives. If a custom objective is specified without defining obj_type, one will hit a "requirement failed: parameter "obj_type" is not defined" error when XGBoost.trainDistributed checks that it is defined in LearningTaskParams. obj_type is currently missing in LearningTaskParams.
closes https://github.com/dmlc/xgboost/issues/3620
=> [jvm-packages] Fix "obj_type" error to enable custom objectives and evaluations

src/tree/tree_model.cc
Fixes #3702 by not rounding up integer threshold for integer features  in JSON dump
=> Fix #3702: do not round up integer thresholds for integer features in JSON dump

python-package/xgboost/core.py
I deleted a word that seems to be extra.
=> [python-package] remove extra "of" in class docstring

tests/ci_build/test_gpu.sh, tests/python-gpu/test_gpu_prediction.py, tests/python/test_with_sklearn.py, tests/travis/run_test.sh
sklearn.cross_validation has been removed from scikit-learn 0.20, so replace it with sklearn.model_selection
Fixes #3730.
=> Fix #3730: scikit-learn 0.20 compatibility fix

R-package/demo/00Index
Add the new demo on interaction constraints to `00Index`.
=> fix R check warning

Jenkinsfile-restricted, tests/ci_build/jenkins_tools.Groovy
Right now, the Jenkins CI server (https://xgboost-ci.net) creates artifacts (binary Python wheels and documentation) for every branch and pull request. This is a security risk, since an adversary is able to create a pull request and inject malicious code.
Fix: Build artifacts only for branches `master`, `release_0.72`, and `release_0.80`. The danger of malicious code is lessened because every pull request is vetted before getting merged to a branch.
=> [Jenkins CI] Do not build artifacts for pull requests

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala
The updater used in distributed training is grow_histmaker and not grow_colmaker as the error message stated prior to this commit.
=> [jvm-packages] Fixed the distributed updater check

src/common/common.cu, src/common/device_helpers.cuh
=> Catch dmlc::Error.

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoostJNI.java, jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/Booster.scala, jvm-packages/xgboost4j/src/native/xgboost4j.cpp, jvm-packages/xgboost4j/src/native/xgboost4j.h, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/BoosterImplTest.java
I've add a jni stub `XGBoosterDumpModelExWithFeatures` to support setting feature names when getting model dump and feature scores. And some new tests are added.
Could you help to take a look? @CodingCat 
close #3725
=> [jvm-packages] support specified feature names when getModelDump and getFeatureScore

Jenkinsfile, Jenkinsfile-restricted
Related: #3746
It is important that the binary wheel (`xgboost-*-none-any.whl`) can run on machines without GPUs, so the CI server should test its compatibility for every incoming pull request.
=> Test wheel compatibility on CPU containers, for all pull requests

doc/conf.py
`matplotlib.sphinxext.only_directives` extension has been removed from Matplotlib 3.0.
=> Fix broken doc build due to Matplotlib 3.0 release

python-package/xgboost/core.py, python-package/xgboost/sklearn.py
Feature importance is defined only when the base learner is decision tree.
Fixes #3747.
=> Fix #3747: disable feature importance for non-tree learners

CMakeLists.txt, doc/build.rst
Now installing R package with multi-threading on OSX is much easier: invoke CMake with `R_LIB=ON` option and run `make` and `make install`.
=> Produce xgboost.so for XGBoost-R on Mac OSX, so that `make install` works

python-package/xgboost/core.py, tests/python/test_basic.py
Feature names were being silently ignored when `data` is empty, as is the case for `slice()`.
=> Fix #3714: preserve feature names when slicing DMatrix

Jenkinsfile, Jenkinsfile-restricted
Sometimes Jenkins CI tests fail because spot instance workers are shut down in the middle. For now, retry the failed tests up to 3 times. I want to find a better method, since retries can mask flaky tests. Ideally, we want to distinguish between communication failures (due to instance shutting down) and test failure (due to exception thrown).
=> Retry Jenkins CI tests up to 3 times to improve reliability

Jenkinsfile, Jenkinsfile-restricted
#3769 does not really work, since failed tests are restarted on workers that already went down. Rearrange `retry` blocks to choose a new worker to re-run failed tests.
=> Retry Jenkins CI tests up to 3 times to improve reliability (redux)

Jenkinsfile-restricted
Commit ID and branch info should be accessed from Scripted Pipeline, not Declarative Pipeline.
=> Fix Jenkins syntax

CONTRIBUTORS.md, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala
private var isNewGroup = true
override def hasNext: Boolean = {
return base.hasNext || isNewGroup
}
The initial value for isNewGroup should be false otherwise the hasNext is wrong with empty partition.
=> [Blocking][jvm-packages] For training data with group, empty RDD partition threw exception (#3749)

include/xgboost/data.h, src/common/device_helpers.cuh, src/common/hist_util.h, src/tree/updater_gpu_common.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/helpers.cc, tests/cpp/helpers.h, tests/cpp/linear/test_linear.cc, tests/cpp/tree/test_gpu_hist.cu
* Split building histogram into separated class.
* Extract `InitCompressedRow` definition.
* Basic tests for gpu-hist.
* Document the code more verbosely.
* Removed HistCutUnit.
* Removed some duplicated copies in GPUHistMaker.
This PR is to add some basic unittests for gpu-hist method, for later refactor (using span, reducing memory requirement, etc.) needs.
Trying to create the unit tests somehow shows that each step in the algorithm depends on different and large amount of data pieces.  I hope we can come up with a better solution to handle these data (and parameters) dependencies before adding more extensive tests.
=> Add basic unittests for gpu-hist method.

src/objective/multiclass_obj.cu, src/tree/param.h, tests/python-gpu/test_gpu_updaters.py
With min_child_weight and lambda set to 0 it is possible to have a divide by zero in the weight calculation leading to incorrect results.
This PR prevents the divide by zero, adds tests for this case and fixes a minor compilation issue with Windows.
=> Address #2754, accuracy issues with gpu_hist

R-package/tests/testthat/test_basic.R, src/common/random.h
**Diagnosis** Apple Clang's implementation of `std::shuffle` doesn't work correctly when it is run with the random bit generator for R package:
```cpp
CustomGlobalRandomEngine::result_type
CustomGlobalRandomEngine::operator()() {
return static_cast<result_type>(
std::floor(unif_rand() * CustomGlobalRandomEngine::max()));
}
```
Minimial reproduction of failure (compile using Apple Clang 10.0):
```cpp
std::vector<int> feature_set(100);
std::iota(feature_set.begin(), feature_set.end(), 0);
// initialize with 0, 1, 2, 3, ..., 99
std::shuffle(feature_set.begin(), feature_set.end(), common::GlobalRandom());
// This returns 0, 1, 2, ..., 99, so content didn't get shuffled at all!!!
```
Note that this bug is platform-dependent; it does not appear when GCC or upstream LLVM Clang is used.
**Fix** …
=> Fix #3523: Fix CustomGlobalRandomEngine for R

tests/distributed/runtests.sh, tests/travis/run_test.sh, tests/travis/setup.sh
Currently, dmlc tracker is failing for `distributed_test` unit tests, due to Python 2.x incompatibility. As a workaround, use Miniconda + Python 3.
=> Fix Python environment for distributed unit tests

tests/ci_build/Dockerfile.gpu, tests/ci_build/Dockerfile.release, tests/cpp/data/test_metainfo.cc, tests/cpp/data/test_simple_csr_source.cc, tests/cpp/data/test_simple_dmatrix.cc, tests/cpp/data/test_sparse_page_dmatrix.cc, tests/cpp/helpers.cc, tests/cpp/helpers.h
Depends on dmlc/dmlc-core#464.
Use `dmlc::TemporaryDirectory` to handle all temporary files. This method has several advantages:
* Does not use deprecated function `std::tmpnam()`.
* Does not assume how many drives (C:, D:, etc) are used on a Windows machine
* User doesn't have to worry about calling `std::remove` manually, in most cases
Closes #3708.
=> Fix #3708: Use dmlc::TemporaryDirectory to handle temporaries in cross-platform way

jvm-packages/pom.xml
A privilege escalation vulnerability (CVE-2017-15288) has been identified in the Scala compilation daemon. See https://nvd.nist.gov/vuln/detail/CVE-2017-15288.
Fix: Upgrade Scala to 2.11.12.
=> [Blocking] [jvm-packages] Upgrade Scala to 2.11.12 to address CVE-2017-15288

doc/jvm/xgboost4j_spark_tutorial.rst, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/LearningTaskParams.scala, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoost.java, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/BoosterImplTest.java
added direction parameter and also fix the judge criterion 
closes https://github.com/dmlc/xgboost/issues/3631 
closes https://github.com/dmlc/xgboost/issues/3140
=> [Blocking][jvm-packages] fix the early stopping feature

python-package/xgboost/sklearn.py
The `save_model()` and `load_model()` method only saves the part of the model that's common to all language interfaces and do not preserve Python-specific attributes, such as `feature_names`. More crucially, label encoder is not preserved either; this is needed for the scikit-learn wrapper, since you may have string labels.
Fix: Explicitly recommend pickling as the way to save scikit-learn model objects.
Related issue: #3828
=> Recommend pickling as the way to save XGBClassifier / XGBRegressor / XGBRanker

jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/rabit/RabitTracker.scala
Allow specifying host ip from the `xgboost-tracker.properties` file in RabitTracker for Scala
=> [jvm-packages] Allow specifying host ip from TrackerProperties

CONTRIBUTORS.md
cleanup and apply fix to address OSX test failure on
https://github.com/dmlc/xgboost/pull/3818
=> merge latest rabit module

python-package/xgboost/sklearn.py
```
clf = xgb.XGBRanker(objective="rank:map")
```
The above code returns "please use XGBRanker for ranking task", despite passing a valid ranking objective.
This PR allows any objective function with the substring "rank:" instead of just "rank:pairwise".
=> Allow XGBRanker sklearn interface to use other xgboost ranking objectives

Jenkinsfile, tests/ci_build/Dockerfile.gpu
CUDA 10.0 was released on September 19, 2018. To ensure that XGBoost works with the latest CUDA, add CUDA 10.0 to the Jenkins CI server (https://xgboost-ci.net).
=> Update Jenkins CI to accommodate CUDA 10.0

jvm-packages/pom.xml
To get around of the bug https://issues.apache.org/jira/browse/SUREFIRE-1588, set `useSystemClassLoader=false`.
=> [jvm-packages] Fix JVM doc build

doc/jvm/index.rst, doc/jvm/xgboost4j_spark_tutorial.rst
See discussion at https://discuss.xgboost.ai/t/xgboost0-72-when-tried-to-compile-with-spark2-3cloudera3-errors-out. We are not able to support third-party distributions of Spark, since they potentially contain breaking changes over the vanilla Apache Spark.
=> [jvm-packages] Require vanilla Apache Spark

Makefile, src/common/enum_class_param.h, src/learner.cc, tests/cpp/common/test_enum_class_param.cc, tests/cpp/test_learner.cc, tests/cpp/test_learner.h
Try to consolidate logic concerning `tree_method` and `updater` into one place. Also use C++11 enum class for `tree_method` for extra safety. (For instance, compilers will generate warning if a `switch` statement doesn't handle all possible values of an enum class. This makes our code future-proof, in case someone decides to add another tree method.)
Closes #3840.
=> [Blocking] Fix #3840: Clean up logic for parsing tree_method parameter

python-package/xgboost/sklearn.py
Scikit-learn expects linear learners to expose `coef_` and `intercept_` as properties.
Closes #3747.
=> Fix #3747: Add coef_ and intercept_ as properties of sklearn wrapper

doc/gpu/index.rst, src/common/common.h, src/common/device_helpers.cuh, src/common/hist_util.cu, src/common/host_device_vector.cu, src/common/host_device_vector.h, src/common/transform.h, src/linear/updater_gpu_coordinate.cu, src/objective/hinge.cu, src/objective/multiclass_obj.cu, src/objective/regression_obj.cu, src/predictor/gpu_predictor.cu, src/tree/updater_gpu.cu, src/tree/updater_gpu_hist.cu, tests/cpp/common/test_common.cc, tests/cpp/common/test_common.cu, tests/cpp/common/test_transform_range.cu, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/tree/test_gpu_hist.cu, tests/python-gpu/test_gpu_updaters.py
Address #3850 .
I don't have the multi-gpu machine for testing currently.
=> Fix specifying gpu_id, add tests.

tests/travis/run_test.sh
Make sure that any new pull request does not use `std::regex`. Although `std::regex` is part of C++11, GCC 4.8.x does not support it. (GCC 4.8.x is used to build Python wheels for the sake for maximum portability.)
=> In lint check, disallow std::regex since it's not supported by GCC 4.8.x

python-package/setup.py, python-package/xgboost/build-python.sh
Use `io.open` with `utf-8` to prevent the following error on machines with non-standard locale:
https://github.com/RGF-team/rgf/issues/65
https://github.com/henry0312/pytest-codestyle/pull/34
=> open README with utf-8 and add gcc-8

src/data/sparse_page_source.cc, tests/cpp/common/test_transform_range.cc, tests/cpp/helpers.cc, tests/cpp/helpers.h, tests/cpp/objective/test_multiclass_obj.cc, tests/cpp/tree/test_gpu_hist.cu
* Fix logic for external memory. The letter ':' is part of drive letter, so remove the drive letter before splitting on ':'.
* Cosmetic syntax changes to keep MSVC happy.
Fixes #3038.
=> Make C++ unit tests run and pass on Windows

python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
See discussion at #3747. Scikit-learn expects `coef_` and `intercept_` fields to be of `np.array` types of certain dimensions.
=> Fix coef_ and intercept_ signature to be compatible with sklearn.RFECV

src/learner.cc
Rectify my mistake in #3849, according to discussion in https://github.com/dmlc/xgboost/pull/3849#issuecomment-436866139.
=> Remove unnecessary warning when 'gblinear' is selected

doc/R-package/xgboostPresentation.md
Signed-off-by: Jiacheng Xu <xjcmaxwellcjx@gmail.com>
=> Fix a typo in the R-package documentation: max.deph -> max.depth

jvm-packages/xgboost4j-example/README.md
SparkWithDataFrame is not there anymore. So replace with SparkMLlibPipeline.scala to fix the link.
=> [jvm-packages] Minor update on xgboost4j README.md

src/common/device_helpers.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/tree/test_gpu_hist.cu
Move split evaluation logic into each device instead of having this logic "globally".  This is in preparation for a future PR where each device will propose splits based on its subset of the data, each device will vote and then the algorithm will globally calculate the optimal split for the selected feature.
Use span class in split evaluation for improved memory safety.
=> Minor refactor of split evaluation in gpu_hist

src/common/device_helpers.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/tree/test_gpu_hist.cu
I rewrote the radix sort function to optimise for the case of 1 bit keys (instances either go to the left node or right node). This is much faster, although impact on total program run-time is not very high. It also saves about 8 bytes per row of memory.
=> Improve update position function

python-package/.pylintrc
Automatically enforce naming conventions in the Python codebase. See the motivating discussion at https://github.com/dmlc/xgboost/pull/3859#discussion_r232226021.
@trivialfis
=> Enforce naming style in Python lint

Jenkinsfile, appveyor.yml, tests/ci_build/Dockerfile.gpu, tests/ci_build/Dockerfile.release, tests/ci_build/test_gpu.sh, tests/ci_build/test_mgpu.sh, tests/python-gpu/test_gpu_linear.py, tests/python-gpu/test_gpu_prediction.py, tests/python-gpu/test_gpu_updaters.py, tests/python-gpu/test_large_sizes.py, tests/python-gpu/test_monotonic_constraints.py, tests/python/test_basic.py, tests/python/test_dt.py, tests/python/test_early_stopping.py, tests/python/test_eval_metrics.py, tests/python/test_linear.py, tests/python/test_plotting.py, tests/python/test_training_continuation.py, tests/python/test_updaters.py, tests/python/test_with_pandas.py, tests/python/test_with_sklearn.py, tests/python/testing.py, tests/travis/run_test.sh
- Remove nose tests.  Now only pytest is required, with the benefit of reducing Travis test time.
- Format all python test code.  I don't know why flake8 on test farm doesn't report any error.  But it keeps bugging me on my editor.  If it's too much noise for review I will change it back.
- Display fulltrace when tests fail, should be helpful for #3720.
=> Refactor Python tests.

tests/travis/run_test.sh
I mistakenly removed the python2 tests in Travis python-lightweight-test.  Sorry for the noise.
@hcho3 Did I break something on Jenkins?  Commit on master branch failed to build on Jenkins.  Thanks for helping out in so many times.
=> Add back python2 tests for Travis light weight tests.

python-package/xgboost/plotting.py
add parameters `'conditionNodeParams'` and `'leafNodeParams'` to function  `to_graphviz` enable to configure node type
as mentioned in issue https://github.com/dmlc/xgboost/issues/3858
=> Add parameter to make node type configurable in plot tree

src/linear/updater_gpu_coordinate.cu
See discussion at https://discuss.xgboost.ai/t/xgboost-with-gpu-support-on-macos/446/7. When a user tried compiling XGBoost on Mac OSX with CUDA enabled, the following compiler error occurred:
```cpp
src/linear/updater_gpu_coordinate.cu(232):
error: no instance of overloaded function "std::min" matches the argument list
argument types are: (size_t, uint64_t)
```
To prevent this error, use consistent types in `src/linear/updater_gpu_coordinate.cu`.
=> Use consistent type for sharding GPU data in GPU coordinate updater

demo/binary_classification/README.md
Fixes #3918 
Pointed parameter doc link to `parameter.rst`
=> Fix link in binary classification demo README.md (#3918)

doc/python/python_intro.rst
Currently, the DMLC parser for CSV is limited and does not recognize the header. This limitation should be documented.
Closes #3933.
=> Address #3933: document limitation of DMLC CSV parser + recommend Pandas

jvm-packages/pom.xml
=> [jvm-packages] Fix #3898: use correct group ID for maven-site-plugin

python-package/xgboost/callback.py
See discussion at https://github.com/dmlc/xgboost/issues/3712#issuecomment-441216780.
=> Add AUC-PR to list of metrics to maximize for early stopping

python-package/xgboost/sklearn.py
The addition of self.booster attribute broke backward compatibility.
Closes #3894.
=> Fix #3894: Allow loading pickles without self.booster attributes

python-package/xgboost/core.py
#3938 was incomplete, so making additional change now
=> Fix #3894: Allow loading pickles without self.booster attributes (redux)

Jenkinsfile, Jenkinsfile-restricted
Spot instances are just too unreliable. They are interrupted too often, and thus tests have to be re-started, holding up pull requests. In addition, sometimes Spot requests are denied, leading to 2 hour timeouts for pull requests. We will be exclusively using on-demand instances from now on.
=> Disable retries in Jenkins CI, since we're now using On-Demand instances instead of Spot

doc/tutorials/feature_interaction_constraint.rst
Copy-and-Paste mistake: some phrases saying "monotonicity constraints" when they should have said "feature interaction constraints."
=> Fix typo in Feature Interaction Constraints tutorial

src/common/config.h
I was playing around with AWS's latest offering of ARM instances, and running the binary classification CLI example resulted into an infinite loop.
**Diagnosis.** `std::istream.get()` and `getchar()` have return type `int`, not `char`, because both may return EOF, which is commonly -1. Storing EOF in a `char` results in undefined behavior. The `char` type is usually signed on x86 systems but unsigned on ARM systems (see http://blog.cdleary.com/2012/11/arm-chars-are-unsigned-by-default/), so the undefined behavior will only be apparent when compiled on ARM.
EDIT. The [DMLC config parser](https://github.com/dmlc/dmlc-core/blob/649be18a8c55c48517861d67158a45dec54992ee/src/config.cc) suffers from the same issue. Fortunately, DMLC JSON parser and parameter packs are unaffected.
=> Use int instead of char in CLI config parser

doc/gpu/index.rst, src/common/device_helpers.cuh, src/common/hist_util.cu, src/common/hist_util.h, src/tree/param.h, src/tree/updater_gpu_common.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/common/test_gpu_hist_util.cu, tests/cpp/tree/test_gpu_hist.cu, tests/python-gpu/test_gpu_updaters.py
This PR adds the ability to perform histogram summation on the GPU in single precision floating point. To do this I templated most of the code in gpu_hist. A side-effect will be modestly increased compile times and slightly larger binaries (with gcc, 153mb->155mb).
Another side-effect of this PR currently is that the GPUHistMaker will be reset every time updater->Init() is called. I'm not sure yet if this is exactly the behaviour we want.
I also simplified the gpu_hist test slightly to avoid combinatorial explosion of test cases, significantly reducing runtime.
=> Single precision histograms on GPU

src/common/device_helpers.cuh
The counters were previously left uninitialized. This resulted in displaying incorrect values when those counters were printed.
=> Initialized AllReducer counters to 0.

include/xgboost/tree_model.h, src/gbm/gbtree.cc, src/tree/tree_model.cc, src/tree/updater_prune.cc, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/tree/test_gpu_hist.cu, tests/cpp/tree/test_prune.cc, tests/cpp/tree/test_quantile_hist.cc, tests/cpp/tree/test_refresh.cc
This PR contains a subset of less controversial changes from #3983 with more concrete reasoning for the changes. The high level goal is to reduce the complexity and size of the class and improve usability.
The changes are:
**Merge TreeModel and RegTree**
RegTree is a subclass of TreeModel, which has no other subclasses. It looks as if this was designed many years ago with the possibility of having other types of trees apart from regression trees. Todays xgboost only supports regression trees and it is difficult to see what other kind of tree we might support, whether this interface would even allow it and how this would fit into the current code base.
I believe this classifies as speculative generality (https://refactoring.guru/smells/speculative-generality). Removal will make the code …
=> Combine TreeModel and RegTree

include/xgboost/tree_model.h, src/tree/updater_colmaker.cc, src/tree/updater_gpu_common.cuh, src/tree/updater_gpu_hist.cu, src/tree/updater_histmaker.cc, src/tree/updater_quantile_hist.cc, src/tree/updater_skmaker.cc, tests/cpp/tree/test_prune.cc, tests/cpp/tree/test_refresh.cc
This PR reduces the below code, used in various updater algorithms into a single line. This reduces boilerplate code and increases safety. Before you could add child nodes without any split in the parent node.
```
p_tree->AddChilds(nid);
(*p_tree)[nid].SetSplit(e.best.SplitIndex(), e.best.split_value, e.best.DefaultLeft());
// mark right child as 0, to indicate fresh leaf
(*p_tree)[(*p_tree)[nid].LeftChild()].SetLeaf(0.0f, 0);
(*p_tree)[(*p_tree)[nid].RightChild()].SetLeaf(0.0f, 0);
```
New code:
```
p_tree->ExpandNode(nid, e.best.SplitIndex(), e.best.split_value, e.best.DefaultLeft());
```
=> Reduce tree expand boilerplate code

jvm-packages/pom.xml, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala
as we fixed in training part, iterator.duplicate() keeps the gap of two iterators in memory and it leads to the memory pressure to the system 
this part eliminate this duplicate() and convert it to a RDD zipPartitions
=> [jvm-packages] fix the scalability issue of prediction

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java, jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/Booster.scala, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/BoosterImplTest.java
The [Python API](https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.Booster.get_score) currently supports obtaining feature importances for the following types:
- Weights
- Cover (Total and Average)
- Gain (Total and Average)
The Java Booster API only supports the first (weights-based), which finds the feature importances based on the number of nodes that the feature was used to split on.
This PR adds in the other two feature importance measures (gain and cover) mimicking the Python API and making it consistent across the board
=> [jvm-packages] Updates to Java Booster to support other feature importance measures

src/data/sparse_page_source.cc
* Remove usage of raw pointers in SparsePageSource.
Address #4037.
=> Fix sparse page segfault.

R-package/tests/testthat/test_interactions.R, src/tree/tree_model.cc
This is my attempt to fix the bug creating NaN SHAP values (#3333). I have an example R script (below) which produces NaN SHAPs without this patch and doesn't produce any with it, but I don't know whether my change is statistically correct.
The script is:
```R
library(xgboost)
d = data.frame(
x1 = c(-2.3, 1.4, 5.9, 2, 2.5, 0.3, -3.6, -0.2, 0.5, -2.8, -4.6, 3.3, -1.2, -1.1, -2.3, 0.4, -1.5, -0.2, -1, 3.7),
x2 = c(291.179171, 269.198331, 289.942097, 283.191669, 269.673332, 294.158346, 287.255835, 291.530838, 285.899586, 269.290833, 268.649586, 291.530841, 280.074593, 269.484168, 293.94042, 294.327506, 296.20709, 295.441669, 283.16792, 270.227085),
y = c(9, 15, 5.7, 9.2, 22.4, 5, 9, 3.2, 7.2, 13.1, 7.8, 16.9, 6.5, 22.1, 5.3, 10.4, 11.1, 13.9, 11, 20.5),
fold = c(2, 2, 2, 1, 2, 2, 1, 2, 1, 1, …
```
=> Avoid generating NaNs in UnwoundPathSum

jvm-packages/xgboost4j-spark/src/main/scala/org/apache/spark/SparkParallelismTracker.scala
looks like we are capturing the wrong events in SparkParallelismTracker
fix it @Yunni
=> [jvm-packages] fix safe execution

tests/cpp/common/test_gpu_compressed_iterator.cu, tests/cpp/common/test_span.cu
- ./testxgboost (without filters) failed if run on a multi-GPU machine because
the memory was allocated on the current device, but device 0
was always passed into LaunchN
=> Fixed single-GPU tests.

include/xgboost/tree_model.h, src/tree/param.h, src/tree/updater_colmaker.cc, src/tree/updater_gpu_common.cuh, src/tree/updater_gpu_hist.cu, src/tree/updater_histmaker.cc, src/tree/updater_quantile_hist.cc, src/tree/updater_skmaker.cc, tests/cpp/tree/test_param.cc, tests/cpp/tree/test_prune.cc, tests/cpp/tree/test_refresh.cc
This PR extends the RegTree::ExpandNode() function to require summary statistics for the node being expanded as well as leaf weights for the left and right child. Calculating the leaf weights in advance for the child nodes required cacheing the left and right gradient sums from split calculation, so I have extended the SplitEntry class with this information.
There are several impacts to this change:
- Expanding a tree node is now a safe operation. After you call ExpandNode() the tree is complete and may be used immediately with all the required statistics and leaf nodes configured.
- As a consequence of the above, all code in tree updater algorithms that manually accesses RegTree internals such as tree nodes, statistics or leaf nodes becomes unnecessary (e.g. …
=>  Require leaf statistics when expanding tree

.travis.yml, tests/travis/run_test.sh, tests/travis/setup.sh
Mac builds on Travis CI are timing out, e.g. https://travis-ci.org/dmlc/xgboost/jobs/485689143#L2365
Solution:
1. Use the latest Mac image with XCode 10.1, so that we don't have to upgrade XCode and Command Line tools manually
2. Use Homebrew Addon integration of Travis CI, instead of manually invoking `brew install`. Should result in faster CI runtime.
=> Fix failing Travis CI on Mac

tests/ci_build/Dockerfile.gpu
Conserve CI resources by downloading pre-compiled CMake binaries, instead of compiling it from scratch every time. This also speeds up CI turn-around time.
=> Speed up Jenkins CI by not compiling CMake

doc/python/python_intro.rst, python-package/xgboost/core.py, src/learner.cc
* Add warning for internal functions.
* Check number of features.
close #4056 .
=> Prevent training without setting up caches.

.clang-tidy, CMakeLists.txt, Jenkinsfile, doc/contribute.rst, tests/ci_build/Dockerfile.clang_tidy, tests/ci_build/clang_tidy.sh, tests/ci_build/setup_cuda_path.sh, tests/ci_build/tidy.py
* Add `GENERATE_COMPILATION_DATABASE' to CMake.
* Rearrange CMakeLists.txt.
* Add basic Python clang-tidy script.
Proposed in #4032 .
@hcho3 Could you please help automating this on Jenkins after sorting out other priorities?  I added a simple documentation and a Python script for the new linting,  but I don't know what's happening with Jenkins or Docker.  Thanks! :)
- clang-tidy >= 7
- cmake >= 3.8
=> Perform clang-tidy on both cpp and cuda source.

src/common/device_helpers.cuh, src/common/hist_util.cc, src/common/hist_util.h, src/common/host_device_vector.h, src/common/span.h, src/common/transform.h, src/tree/param.h, src/tree/split_evaluator.cc, src/tree/updater_basemaker-inl.h, src/tree/updater_colmaker.cc, src/tree/updater_gpu.cu, src/tree/updater_gpu_common.cuh, src/tree/updater_gpu_hist.cu, src/tree/updater_histmaker.cc, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, src/tree/updater_refresh.cc, src/tree/updater_skmaker.cc, tests/cpp/tree/test_quantile_hist.cc
Remove:
- GHistRow
- GHistEntry
- GHistIndexRow
- kSimpleStats
- CheckInfo
- SetLeafVec
Moved LossChangeMissing output common since they are not common..
Addressed some compiler warnings, the build message will be cleaner.
There are suggestions from @hcho3 and @RAMitchell we reduce the stored data in algorithm class #3803, and I also want to structure these algorithms in a nicer way, so this would be a multi-stage refactor.
At first I will try to use Span class, if the bound check in it hurts performance too much I will switch to a similar class without bound check.  Along the way I also want to create unittests, which might be a little time consuming.
=> Simplify tree building code.

src/common/device_helpers.cuh, src/common/host_device_vector.cu, src/tree/updater_gpu_hist.cu, tests/cpp/tree/test_gpu_exact.cu
* launch all reduce sequentially.
* Fix gpu_exact test memory leak.
close #4107
=> Use nccl group calls to prevent from dead lock.

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala
closes https://github.com/dmlc/xgboost/issues/4117
@trivialfis
=> [jvm-packages] force use per-group weights in spark layer 

python-package/xgboost/core.py, python-package/xgboost/sklearn.py
Fixes #4039.
Also clarifies that data weights are per-group for ranking task, per #4115.
@trivialfis
=> Update Python docstring for ranking functions

python-package/.pylintrc, tests/benchmark/benchmark_tree.py
Making the code a bit easier to read in IDEs like PyCharm. For now this is pure refactoring, but hoping to make this run faster to generate larger datasets.
@RAMitchell
=> reformat benchmark_tree.py to get rid of lint errors

.travis.yml, tests/travis/run_test.sh, tests/travis/setup.sh
Missing GCC Fortran causes installation failure of a dependency package (igraph).
@trivialfis @CodingCat @RAMitchell This should fix the R test.
=> Fix broken R test: Install Homebrew GCC

doc/python/python_intro.rst, src/common/hist_util.cc, src/common/hist_util.h, src/learner.cc, tests/cpp/common/test_hist_util.cc, tests/cpp/test_learner.cc
* Add checks for group size.
Address segfault in  #4098,  error in quantile is not resolved.
=> Make `HistCutMatrix::Init' be aware of groups.

python-package/xgboost/compat.py, python-package/xgboost/core.py
This PR ensures that xgboost continues to work correctly with the upcoming changes to the `datatable` package.
- Prefer name `dt.Frame` instead of `dt.DataTable` (which was deprecated a year ago);
- `dt.Frame.internal` namespace will be removed; instead the underlying data pointers can be accessed using `datatable.internal.frame_column_data_r()` (which returns a `ctypes.c_void_p` object).
=> Update datatable usage

src/common/span.h, tests/cpp/common/test_span.cc, tests/cpp/common/test_span.cu
* Silent the death tests.
Related to #4144 . But this doesn't make XGBoost ready for empty dataset.  Death tests are silent, there's no need to see those messages from unit tests.
=> Fix empty subspan.

src/common/hist_util.cc, tests/cpp/tree/test_quantile_hist.cc, tests/python/test_updaters.py
In fast histogram algorithm, empty columns (or nearly empty columns) may prevent the quantile sketcher 
from producing any quantile point. Failure cases: #4085 and #2943.
Whenever the quantile sketcher produces no quantile point, insert `2 * [minimum feature value]` into the quantile sketch, so that every feature gets at least one quantile point.
Closes #4085 
Closes #2943
@trivialfis @pseudotensor 
Ps. This PR probably does not address #4083.
=> Prevent empty quantiles in fast hist

demo/kaggle-otto/README.MD
I noticed "Benckmark" was used at the demo/kaggle-higgs/README.MD instead of "Benchmark".
If that was intentional then ignore this change.
=> demo's doc: Update README.MD to fix typo

include/xgboost/c_api.h, include/xgboost/data.h, python-package/xgboost/core.py, src/c_api/c_api.cc, src/data/data.cc, tests/python/test_basic.py
=> Accept numpy array view.

include/xgboost/c_api.h, include/xgboost/data.h, python-package/xgboost/core.py, src/c_api/c_api.cc, src/data/data.cc, tests/python/test_basic.py
#4147 attempted to read sliced NumPy array directly into the C++ backend, but it relied on a NumPy internal variable (`data.base`) whose meaning we are not able to determine precisely. In particular, `len(data.base)` can sometimes mean the number of bytes in the NumPy array and other times mean the number of elements in the array.
Rather than dealing with undocumented NumPy internals, we'll take the approach of Microsoft/LightGBM#1210, i.e. always copy sliced data. This approach increases memory consumption slightly but the effect is not too bad. After all, the data matrix gets always copied when the input is a slice:
https://github.com/dmlc/xgboost/blob/c8c472f39aa08d5b8f180076a429f09317451cc7/python-package/xgboost/core.py#L487-L490
Closes #4163
=> Fix #4163: always copy sliced data

python-package/.pylintrc, python-package/xgboost/core.py, tests/python/test_parse_tree.py
Worked alongside @hshujuan for this PR to add nearly equivalent methodology to python package as R for parsing a dumped text model to a pandas DataFrame. Testing on model built on agaricus dataset included...
* Parse 10,000 trees of `max_depth` 5 in  about 3 seconds
* Parse `gbtree` and `dart` boosters
* Output equivalent to R's `xgb.model.dt.tree()` function
* Can handle trees that have no splits (i.e. leaf only trees)
If any thing about this PR is not adequate, please let me know.
Thanks,
Patrick
=> Added trees_to_df() method for Booster class

include/xgboost/data.h, src/common/group_data.h, src/common/timer.h, src/data/data.cc, src/data/sparse_page_source.cc, src/tree/updater_basemaker-inl.h, tests/cpp/data/test_data.cc, tests/cpp/test_learner.cc
* Move Push* definitions into cc file.
* Add `std::` prefix to `size_t` to make clang++ happy.
* Address monitor count == 0.
close #4037.
close #4130.
=> Add PushCSC for SparsePage.

doc/jvm/xgboost4j_spark_tutorial.rst, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoost.java, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/BoosterImplTest.java
Two major take aways:
* Fix the early stop condition: training stops if the current iteration is ```earlyStoppingSteps``` away from the _best iteration_. 
* If there are multiple ```watches```, only the last one is used to determinate early stop.
=> [jvm-packages] Fix early stop with xgboost4j-spark

NEWS.md
This release is packed with many new features and bug fixes.
* Poor performance scaling of the `hist` algorithm for multi-core CPUs has been under investigation (#3810). #3957 marks an important step toward better performance scaling, by using software pre-fetching and replacing STL vectors with C-style arrays. Special thanks to @Laurae2 and @SmirnovEgorRu.
* See #3810 for latest progress on this roadmap.
* It is now possible to run the `hist` algorithm in distributed setting. Special thanks to @CodingCat. The benefits include:
1. Faster local computation via feature binning
2. Support for monotonic constraints and feature interaction constraints
3. Simpler codebase than `approx`, allowing for future improvement
* Depth-wise tree growing is now performed in a separate code path, so that …
=> [RFC] Version 0.82 release candidate

doc/build.rst
* Multi-GPU training will work right away after running `pip install xgboost`.
* Use GCC 8 in Homebrew.
* Recommend use of CMake over Makefile.
=> Update build doc: PyPI wheel now support multi-GPU

doc/parameter.rst
Minor formatting correction for `num_parallel_tree`
=> Fix docs for num_parallel_tree

jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/rabit/handler/RabitTrackerHandler.scala
This PR addresses the following issues:
- https://github.com/dmlc/xgboost/issues/4054
- https://github.com/salesforce/TransmogrifAI/issues/181
- https://github.com/dmlc/xgboost/issues/3418
closes #4054 #3418
It looks like there is a race condition between actors and sometimes the Tracker actor might get shut down before its supervisor is notified about completing the job.
There is no need to kill the actor explicitly after all workers are done as RabitTracker will shutdown the system anyways after hearing back from the actor: https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/rabit/RabitTracker.scala#L159
=> [jvm-packages] Fix "Rabit returns with exit code 3" problem

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala
When tree_method="hist" and grow_policy="lossguide", max_leaves is needed.
=> [xgboost4j-spark] Allow set the parameter "maxLeaves".

Jenkinsfile
See https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-4231/2/pipeline/51.
The current scripts downloads NCCL2 from URL `https://developer.download.nvidia.com/compute/redist/nccl/v2.2/nccl_2.2.13-1%2Bcuda${CUDA_VERSION}_x86_64.txz`. This URL works fine when `CUDA_VERSION` is 8.x or 9.x but fails for 10.1.
~~TODO. Either find a link that's not behind a login wall, OR upload installers to a private S3 bucket.~~
EDIT. I think it would be best if we place NCCL2 installers inside the worker image. This way, we don't generate unnecessary HTTP traffic.
=> Downgrade Jenkins agent to CUDA 9.2, to fix broken NCCL2 installation

doc/rf.rst, python-package/xgboost/__init__.py, python-package/xgboost/sklearn.py, tests/python-gpu/test_gpu_prediction.py, tests/python/test_with_sklearn.py
- added XGBRFClassifier and XGBRFRegressor classes to Scikit-Learn-like xgboost API
- added documentation describing how to use xgboost for random forests,
as well as existing caveats
=> Added SKL-like random forest Python API.

R-package/DESCRIPTION, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_callbacks.R, src/common/transform.h
R-devel recently changed the RNG behavior, and that breaks R unittests. 
This PR
- Bumps up the version number of the R-package
- Fix the unittest for both the latest R release and R-devel
- Fix a `-Wreorder` warning.
I have already submitted the R-package 0.82 to CRAN with these fixes.
=> Fix errors on R-devel

src/linear/updater_gpu_coordinate.cu
I believe the issue was that calls to ->ConstHostVector() can modify the underlying vector, allocating or de allocating memory. Multiple threads were calling this in parallel resulting in strange memory errors.
@trivialfis I used ordinary gdb to find this as cuda-gdb seems to just crash.
=> Fix multi-GPU test failures

doc/rf.rst, python-package/xgboost/sklearn.py
* Mark Scikit-Learn RF interface as experimental.
* Copy a small example in doc from test.
close #4253.
=> Mark Scikit-Learn RF interface as experimental in doc.

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/LearningTaskParams.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala
the current behavior of xgboost-spark is to avoid caching training data for the user. However, with the checkpoint feature, user has to repartition data for every checkpoint construction which potentially prolongs the overall execution time (depends on the cost of repartition and memory usage)
this PR adds a flag to grant the user with the permission to control whether to cache repartitioned data
=> [jvm-packages] add configuration flag to control whether to cache transformed training set

src/common/device_helpers.cuh, src/common/random.h, src/tree/updater_colmaker.cc, src/tree/updater_gpu_common.cuh, src/tree/updater_gpu_hist.cu, src/tree/updater_quantile_hist.cc, tests/cpp/common/test_random.cc, tests/cpp/tree/test_gpu_hist.cu
* Use streams to overlap operations.
* Reduce redundant calls to cudaSetDevice().
* ColumnSampler now uses HostDeviceVector to prevent repeatedly copying feature vectors to the device.
=> Optimisations for gpu_hist.

src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h
Now that we published r0.82, old performance monitor can be safely removed.  Small example of output:
```
[23:37:34] ======== Monitor: Learner ========
[23:37:34] EvalOneIter: 0.000541892s, 16 calls @ 33us
[23:37:34] GetGradient: 0.00054553s, 16 calls @ 34us
[23:37:34] PredictRaw: 0.00403017s, 16 calls @ 251us
[23:37:34] UpdateOneIter: 11.6501s, 16 calls @ 728131us
[23:37:34] ======== Monitor: GBTree ========
[23:37:34] BoostNewTrees: 11.6216s, 16 calls @ 726351us
[23:37:34] CommitModel: 0.0238338s, 16 calls @ 1489us
[23:37:34] ======== Monitor: Quantile::Builder ========
[23:37:34] ApplySplit: 0.0314834s, 1704 calls @ 18us
[23:37:34] BuildHist: 2.7814s, 1736 calls @ 1602us
[23:37:34] BuildLocalHistograms: 4.62041s, 224 calls @ 20626us
[23:37:34] BuildNodeStats: 0.00127785s, 224 calls @ …
```
=> Use Monitor in quantile hist.

src/learner.cc
When training with multiple matrices, such as a test and train matrix, the preds_ member variable is resized at least twice per boosting iteration.
When the GPU is being used this resize is particularly costly, as copies between the host and device must be performed.
This PR uses std::map to provide a unique predictions vector for each dmatrix so the predictions vectors never need to be resized.
This PR results in around 10% improvement in runtime for tests/benchmark/benchmark_tree.py.
=> Allow unique prediction vector for each input matrix

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoost.java, jvm-packages/xgboost4j/src/test/scala/ml/dmlc/xgboost4j/scala/ScalaBoosterImplSuite.scala
There is currently no option to suppress the output from Rabit in xgboost4j. Redirecting `System.out` temporarilly does not help either (since the print happens in native code). This can result in a large amount of printing to the screen, resulting in other important messages being lost.
This PR changes the behavior to the following:
* Setting "silent" in this map to "true", "True", a non-zero integer, or a string that can be parsed to such an int will prevent printing.
* Setting "verbose_eval" to "False" or "false" will prevent printing.
* Setting "verbose_eval" to an int (or a String parseable to an int) `n` will result in printing every n steps, or no printing is `n` is zero.
This is to match the python behaviour described here: …
=> [jvm-packages] Allow supression of Rabit output in Booster::train in xgboost4j

Jenkinsfile, Jenkinsfile-restricted, src/common/host_device_vector.cu, tests/ci_build/Dockerfile.gpu
Also removed the hack to work around the cuda 10.1 compiler bug. We can try 10.1 again once update 1 is out and the bug is fixed.
@RAMitchell @trivialfis
=> jenkins build for cuda 10.0

include/xgboost/tree_model.h, src/learner.cc, src/predictor/gpu_predictor.cu, src/tree/updater_gpu_hist.cu, tests/cpp/helpers.h, tests/cpp/tree/test_gpu_hist.cu
- Fuse final update position functions into a single more efficient kernel
- Refactor gpu_hist with a more explicit ellpack matrix representation
=> Further optimisations for gpu_hist.

src/common/device_helpers.cuh, src/linear/updater_gpu_coordinate.cu, src/tree/updater_gpu.cu, src/tree/updater_gpu_common.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/common/test_device_helpers.cu, tests/cpp/tree/test_gpu_hist.cu
Both classes serve the same purpose - a non-owning memory container. Span is more generic and better designed.
=> Retire DVec class in favour of c++20 style span for device memory.

jvm-packages/create_jni.py
I was doing a lot of builds trying to figure out the corrupted .so issue, it was pretty slow. This speeds it up quite a bit. :)
@CodingCat @hcho3
=> [jvm-packages] use all cores to build on linux

tests/ci_build/Dockerfile.gpu, tests/travis/run_test.sh
Upgrade the Jenkins CI container to use GCC 5.3.1, in order to obtain complete C++11 support (along with `std::regex`),
=> [CI] Upgrade to GCC 5.3.1, CMake 3.6.0

jvm-packages/xgboost4j/pom.xml
The recent change #4271 causes resources to be filtered, including shared library files that are copied there (see https://github.com/dmlc/xgboost/blob/master/jvm-packages/create_jni.py#L102), corrupting them in the process:
```sh
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/libxgboost4j7996472599554222538.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
```
@CodingCat
=> [jvm-packages] do not filter shared library files

src/c_api/c_api.cc, src/data/sparse_page_dmatrix.cc, src/tree/updater_basemaker-inl.h, src/tree/updater_colmaker.cc, src/tree/updater_skmaker.cc
=> Get rid of a few trivial compiler warnings.

CMakeLists.txt, doc/contribute.rst, src/common/host_device_vector.cc, src/common/host_device_vector.cu, src/common/host_device_vector.h, tests/ci_build/test_gpu.sh, tests/ci_build/test_mgpu.sh, tests/travis/run_test.sh
on which cmake is run. this appends the build directory to the test binary
- make the assignments of HostDeviceVector exception safe
- rm storing a dummy GPUDistribution instance for CPU based code
=> - make test fails to find testxgboost, if a build directory is created

Jenkinsfile, tests/ci_build/Dockerfile.gpu, tests/ci_build/ci_build.sh
* ~Upgrade CMake to 3.8, as needed by #4323~ CMake upgrade has been postponed.
* Add external Docker build cache, so that we can automatically cache builds from the latest Dockerfile. Docker caches are super important for speeding up CI builds. (Right now, I have to manually update the cache every time Dockerfile is updated.)
=> [CI] Add external Docker build cache

tests/ci_build/ci_build.sh
This is a follow-up to #4331.
Docker build caches are per-branch, so new pull requests will initially have no build cache, causing the Docker containers to be built from scratch. New pull requests should use the cache associated with the
master branch. This makes sense, since most pull requests do not modify the Dockerfile.
=> [CI] Optimize external Docker build cache

R-package/demo/predict_leaf_indices.R
Fix the bug report of https://github.com/dmlc/xgboost/issues/4328.
I am the beginner of the Git so just try my best to follows the guide, https://xgboost.readthedocs.io/en/latest/contribute.html#r-package.
I find there is no `dev`  branch, so I pull this fix from my master branch to the original master branch.
=> Make the train and test input with same colnames.

demo/c-api/Makefile, demo/c-api/c-api-demo.c
=> C API example

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoostJNI.java, jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/Booster.scala, jvm-packages/xgboost4j/src/native/xgboost4j.cpp, jvm-packages/xgboost4j/src/native/xgboost4j.h, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/BoosterImplTest.java
Add wrappers to support operating attributes of booster in jvm-packages, which follow API design in python-package.
=> [jvm-packages] support operating attributes of booster

README.md
While reading through your docs tonight, I noticed that the first two badges in the main README are indistinguishable visually:
Would you consider this small PR to add the Travis logo to the Travis badge?
=> Add travis logo to README badge

src/tree/updater_gpu_hist.cu, tests/cpp/tree/test_gpu_hist.cu
nidx_map is cleared after `Reset`, but histogram data size isn't changed hence
histogram recycling is used in later iterations.  After a reset(building new
tree), newly allocated node will start from 0, while recycling always choose
the node with smallest index, which happens to be our newly allocated node 0.
close #4330.
=> Fix Histogram allocation.

R-package/R/xgb.DMatrix.R
In the R package, the user can provide additional information for the custom objective function by adding attributes to the `DMatrix` . `xgb.cv` relies on `slice.xgb.DMatrix` for slicing the folds. 
However, those attributes are sliced only if they are vectors of same length as the `DMatrix`. In a multiclass problem, it makes sense to use a matrix instead of a vector for additional information about the classes. 
MWE:
```r
library(xgboost)
data(agaricus.train, package = "xgboost")
dtrain <- xgb.DMatrix(agaricus.train$data, label = agaricus.train$label)
attr(dtrain, "vec") <- getinfo(dtrain, "label")
nrow(dtrain)
#> [1] 6513
train_len <- length(attr(dtrain, "vec"))
attr(dtrain, "mat") <- matrix(runif(train_len * 2), nrow = train_len, ncol = 2)
length(attr(dtrain, "mat")) # != nrow(dtrain), …
```
=> Fix matrix attributes not sliced

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/NativeLibLoader.java
Fix for issue #4342.
The old NativeLibLoader had a short-circuit load path which modified java.library.path and attempted to load the xgboost library from outside the jar first, falling back to loading the library from inside the jar. This path is a no-op every time when using XGBoost outside of it's source tree. Additionally it triggers an illegal reflective access warning in the module system in 9, 10, and 11.
On Java 12 the ClassLoader fields are not accessible via reflection (separately from the illegal reflective acces warning), and so it fails in a way that isn't caught by the code which falls back to loading the library from inside the jar.
This commit removes that code path and always loads the xgboost library from inside the jar file as it's a valid technique across multiple JVM …
=> [jvm-packages] Fixing the NativeLibLoader on Java 9+

tests/cpp/data/test_sparse_page_dmatrix.cc, tests/cpp/helpers.cc, tests/cpp/helpers.h, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu
=> refactor tests to get rid of duplication

.travis.yml, tests/travis/run_test.sh
Currently, this project's R stage on Travis depends on `craigcitro/r-travis`, a project that was officially [deprecated in July 2016](https://github.com/craigcitro/r-travis/commit/dd538f85b2d3ca42e6587beb363f2ea54de5bb55). In this PR, I propose a way to factor it out.
See #4348 and other linked issues there for more details.
Thanks for considering it!
=> [r-package] cut CI-time dependency on craigcitro/r-travis (fixes #4348)

.gitignore
When running the [instructions for installing the development version of the R-package](https://xgboost.readthedocs.io/en/latest/build.html#installing-the-development-version), I found that two new files were cerated which are not currently ignored by this project's `.gitignore`:
I hope you'll consider this PR to ignore these files in `.gitignore` to make it clear to future contributors that those files should not be committed and to prevent people from inadvertently committing them if they use `git add .`.
=> added files from local R build to gitignore

src/common/column_matrix.h, src/common/hist_util.cc, src/common/hist_util.h, src/common/row_set.h, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h
This commit is a part of this [pull-request](https://github.com/dmlc/xgboost/pull/4278).
Performance before this commit:
Data Set | First iteration | 50 iterations
-- | -- | --
Higgs1m, ms | 900 | 3889
Higgs10m, ms | 8923 | 33638
9m x 45, ms | 6093 | 19389
Performance results for these changes:
Data Set | First iteration | 50 iterations
-- | -- | --
Higgs1m, ms | 672 | 3502
Higgs10m, ms | 7834 | 30121
9m x 45, ms | 4369 | 15960
HW: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, 2 sockets, 14 cores per socket.
=> Optimizations of pre-processing for 'hist' tree method

R-package/R/callbacks.R, R-package/R/xgb.Booster.R, R-package/R/xgb.DMatrix.R, R-package/R/xgb.cv.R, R-package/R/xgb.plot.importance.R, R-package/R/xgb.plot.shap.R, R-package/R/xgb.train.R, R-package/man/callbacks.Rd, R-package/man/cb.cv.predict.Rd, R-package/man/cb.early.stop.Rd, R-package/man/cb.evaluation.log.Rd, R-package/man/cb.reset.parameters.Rd, R-package/man/cb.save.model.Rd, R-package/man/dim.xgb.DMatrix.Rd, R-package/man/dimnames.xgb.DMatrix.Rd, R-package/man/getinfo.Rd, R-package/man/predict.xgb.Booster.Rd, R-package/man/print.xgb.DMatrix.Rd, R-package/man/print.xgb.cv.Rd, R-package/man/slice.xgb.DMatrix.Rd, R-package/man/xgb.Booster.complete.Rd, R-package/man/xgb.DMatrix.Rd, R-package/man/xgb.cv.Rd, R-package/man/xgb.gblinear.history.Rd, R-package/man/xgb.plot.importance.Rd, R-package/man/xgb.plot.shap.Rd, R-package/man/xgb.train.Rd, R-package/man/xgboost-deprecated.Rd, R-package/vignettes/discoverYourData.Rmd, R-package/vignettes/xgboostPresentation.Rmd
Thank you for this great project. I hope you'll consider this pull request to fix minor typos in the R-package documentation (found with `devtools::spell_check()`).
I apologize about the extra lines touched for trailing whitespace, that is a setting I have in my IDE. Please let me know if you would like me to revert those whitespace-only edits.
I also regenerated the documentation with `devtools:;document()` so the `.Rd` files in `man/` would be consistent with the roxygen changes I made.
=> fixed typos in R package docs

.travis.yml, Makefile, python-package/.pylintrc, python-package/xgboost/callback.py, python-package/xgboost/compat.py, python-package/xgboost/core.py, python-package/xgboost/libpath.py, python-package/xgboost/plotting.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py, tests/travis/run_test.sh, tests/travis/setup.sh
As we are about to deprecate Python 2 (#4379), we need to migrate pylint (Python coding style check) to Python 3. There are some minor changes to meet the new requirements.
=> Migrate pylint check to Python 3

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/InferenceParams.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/PerTest.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifierSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressorSuite.scala, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java
fix issue #4387 by replacing zip RDDs with caching original data in closure.
Corresponding unit tests have been added.
closes #4387 
closes https://github.com/dmlc/xgboost/issues/4307
=> [BLOCKING][jvm-packages] fix non-deterministic order within a partition  (in the case of an upstream shuffle) on prediction 

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/MissingValueHandlingSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifierSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/DataBatch.java
it's a successive PR for https://github.com/dmlc/xgboost/commit/ad4de0d718e33b98d9ae32bb3858a57a989ef5f8
Spark's vector assembler transformer only accepts 0 as the missing value, which creates problems when the user takes 0 as the meaningful value and there are enough number of 0-valued features leading vector assembler to use SparseVector to represent the feature vector. The reason is that those 0-valued features has been filtered out by Spark. 
It's fine if the user's DataFrame only contains DenseVector, as the 0 is kept.
This PR  changes the behavior of XGBoost-Spark as:
when the user sets a non-zero missing value and we detect there is sparse vector, we stop the application to prevent error
=> [BREAKING][jvm-packages] fix the non-zero missing value handling

CMakeLists.txt, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/RabitRobustnessSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Rabit.java, tests/ci_build/build_jvm_packages.sh, tests/ci_build/test_jvm_cross.sh
closes https://github.com/dmlc/xgboost/issues/4406
@sperlingxx FYI, because we call rabit.shutdown only when the partition is exhausted https://github.com/dmlc/xgboost/pull/4388/files#diff-a435450e9c28607f848ccf3246944a44R330, if we partially evaluate a DataFrame with APIs like show(), it will leave some rabit in initialized but not shutdown state
as a result, when we run a new task in the same thread, rabit will crash since we cannot call init() for twice, 
I have fixed rabit in https://github.com/dmlc/rabit/pull/92 and added a test in xgboost guarding it
@hcho3, I am resuming the disabled spark test in this PR, hopefully everything fine
=> [jvm-packages] allow partial evaluation of dataframe before prediction

demo/README.md
Hi guys,
I am one of the authors of [BentoML](https://github.com/bentoml/bentoml).  BentoML is a python library for packaging and deploying ML models.  It provides high-level APIs for defining an ML service and packaging its artifacts, source code, dependencies, and configurations into a production-system-friendly format that is ready for deployment.
We create this example notebook to showcase the power of XGBoost and how to use it in production setting.  We create a simple Titanic survival prediction model with XGBoost, and we are able to use BentoML quickly create a model archive bundle from the Jupyter notebook with all of the dependencies included.  Afterward, we start REST API server from generated model archive without writing any web service code.   
You can also distribute the …
=> [Docs]Update demo readme's use case section with BentoML

include/xgboost/tree_model.h, src/CMakeLists.txt, src/common/device_helpers.cuh, src/common/random.h, src/predictor/gpu_predictor.cu, src/tree/updater_gpu_hist.cu, tests/cpp/common/test_random.cc, tests/cpp/tree/test_gpu_hist.cu, tests/distributed/distributed_gpu.py, tests/python-gpu/test_gpu_updaters.py
This PR contains major changes in the design of the gpu_hist algorithm. Previously we repeatedly launched groups of omp threads with one thread per GPU to execute some unit of work on the GPU. During a single tree construction there would be hundreds of thread launches. This can cause stalls as shown here:
This PR now launches one thread per GPU and this thread is used to construct the entire tree, only exiting when tree construction is finished. Each device shard still needs to communicate with other shards, but this is achieved via NCCL.
So we now no longer need to create and destroy many threads per iteration (or rely on the omp implementation to manage the thread pool efficiently) and we now avoid any unnecessary CPU thread synchronisation.
This PR also fixes #4332
Potential issues to …
=>  Combine thread launches into single launch per tree for gpu_hist

jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/MissingValueHandlingSuite.scala
I found that `VectorAssembler. setHandleInvalid`,  which used in `MissingValueHandlingSuite.scala`, 
is newly added in spark_2.4.
So, I tried to replace`VectorAssembler` by creating `DenseVector` directly.
=> [jvm-packages] fix compatibility problem of spark version

src/common/host_device_vector.cc, src/common/host_device_vector.cu, src/common/host_device_vector.h, src/common/transform.h, src/metric/elementwise_metric.cu, src/metric/multiclass_metric.cu, src/objective/multiclass_obj.cu, src/predictor/gpu_predictor.cu, src/tree/updater_gpu.cu, src/tree/updater_gpu_hist.cu, tests/cpp/common/test_host_device_vector.cu, tests/cpp/common/test_transform_range.cu
* Rename the `Reshard` method to `Shard`
* Add a new `Reshard` method for sharding a vector that's already sharded
@canonizer @RAMitchell @sriramch
=> more explict sharding methods

src/tree/split_evaluator.cc, tests/python/test_interaction_constraints.py, tests/python/test_monotone_constraints.py
Port some tests from JVM packages to beef up the Python test suite. This will be useful in debugging #4341.
Also add an assertion in `CheckInteractionConstraint()` so that out-of-range access to `int_cont_` produces a legible error (instead of SIGSEGV)
=> Add additional Python tests for training under constraints

src/tree/split_evaluator.cc, src/tree/split_evaluator.h, src/tree/updater_quantile_hist.cc
Fixes #4217 
Use feature interaction constraints to narrow search space for split candidates.
=> Use feature interaction constraints to narrow search space for split candidates

src/tree/split_evaluator.cc
A follow-up of #4426 and #4341. Simplify the bound checking in `CheckInteractionConstraint()` by using the bound checking interface [`std::vector::at()`](https://en.cppreference.com/w/cpp/container/vector/at).
=> Simplify bound checking in feature interaction constraints

src/cli_main.cc
2 additional digits are not needed to guarantee that casting the decimal representation will result in the same float, see https://github.com/dmlc/xgboost/issues/3980#issuecomment-458702440
=> max_digits10 guarantees float decimal roundtrip

src/metric/rank_metric.cc, tests/python/test_ranking.py
Fixes #4431.
I read [the paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3961324/) referenced by the AUCPR implementation, and as far as I can tell, the `EvalAucPR` seems to be consistent with the paper.
The issue was that `EvalAucPR` was assuming the existence of only a single query group. More precisely, it throws an exception when `sum_auc >= 1.0`, where it should have checked `sum_auc >= ngroup` instead. Since all tests for AUCPR was performing binary classification (where there is only one group), the bug went undetected.
Fix. Have a proper check on the AUC value, in presence of multiple query groups. Also add a test with learning-to-rank example.
=> Make AUCPR work with multiple query groups

src/metric/rank_metric.cc, tests/python/test_ranking.py
This is a proposed bugfix based on PR https://github.com/dmlc/xgboost/pull/3379 originally submitted by @ngoyal2707, which intends to change how the instance weight vector is defined.
For a training dataset of K groups and N total training examples/instances, @ngoyal2707's original PR requires a weight vector of length K. That is, each group has its own weight, and the same weight is shared by all instances in the same group. While this scheme of specifying group weights works without issues in isolation, it however does conflicts with the computation of certain ranking metrics (e.g. `auc` and `aucpr`) in https://github.com/dmlc/xgboost/blob/master/src/metric/rank_metric.cc, which expects the weights to be populated for **every training example**. 
To demonstrate the bug, we can use the …
=> In AUC and AUCPR metrics, detect whether weights are per-instance or per-group

doc/jvm/xgboost4j_spark_tutorial.rst
add tutorial on missing values and how to handle those within XGBoost.
=> [jvm-packages] Tutorial on handling missing values

CMakeLists.txt, cmake/modules/FindNccl.cmake
=> Enable building with shared NCCL.

doc/jvm/xgboost4j_spark_tutorial.rst, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/LearningTaskParams.scala
This pull request is aimed at resolving "[jvm-packages] false should be the default value of maximize_evaluation_metrics"(#4422).
The metric names to maximize are aligned with [xgboost.callback.early_stop](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/callback.py#L189) in the Python package.
To avoid duplicating codes in both `XGBoostClassifier` and `XGBoostRegressor`, parameter `maximize_evaluation_metrics` is set in [XGBoost.scala](https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala) when not provided by user.
closes https://github.com/dmlc/xgboost/issues/4422
=> [jvm-packages] Automatically set maximize_evaluation_metrics if not explicitly given in XGBoost4J-Spark

cmake/Utils.cmake
The move to native cuda cmake support meant that the flag CUDA_VERSION_MAJOR was no longer defined. As a result we have not been correctly generating SASS for more recent cuda versions.
=> Correctly determine cuda version

src/common/host_device_vector.h, src/predictor/gpu_predictor.cu, tests/cpp/predictor/test_gpu_predictor.cu
Alternative approach to #4437. Uses explicit offsets of slide over the out prediction vector. I feel this is slightly cleaner, but I'm ok with either approach.
@canonizer @RAMitchell @sriramch
=> mgpu predictor using explicit offsets

tests/ci_build/ci_build.sh
There are two R test suites currently running, one for R 3.4.4 and another for R 3.5.3. They require two separate Docker containers, but currently only one of them is being cached; the other container is being built from scratch.
After this small fix, both R containers will be cached.
=> [CI] Properly cache Docker containers for R tests

Jenkinsfile
Per suggestion of @RAMitchell, we should build XGBoost with CUDA 9.0, so that the compiled code won't need to be JIT compiled for the newer Volta architectures.
=> [CI] Build XGBoost wheels with CUDA 9.0

CMakeLists.txt, Jenkinsfile, Jenkinsfile-win64, cmake/Utils.cmake, src/CMakeLists.txt
1\. Add Windows GPU to Jenkins CI pipeline (see #4234). All pull requests will now be tested to ensure compatibility with Windows platform.
2\. Fix #4462: Use `/MT` flag consistently so that MSVC builds don't fail
Background: Microsoft Visual C++ (MSVC) offers [multiple options for the C++ runtime](https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2019): `/MT` (static runtime) and `/MD` (shared DLL runtime).  XGBoost has traditionally used `/MT` to compile all sources. The utility function `msvc_use_static_runtime()` is defined in `cmake/Utils.cmake` to replace all occurrences of `/MD` with `/MT`.
Diagnosis of #4462: Recently, #4323 revised CMakeLists.txt extensively so as to incorporate [CUDA as a first-class …
=> [CI] Add Windows GPU to Jenkins CI pipeline

Jenkinsfile, src/common/device_helpers.cuh, tests/ci_build/Dockerfile.gpu_build
Still waiting for the docker image to land, but all the tests passed locally.
This requires CUDA V10.1.168.
@hcho3 @RAMitchell
=> Add cuda 10.1 support

src/predictor/gpu_predictor.cu
@canonizer @RAMitchell @sriramch
=> only copy the model once when predicting multiple batches

CMakeLists.txt, Jenkinsfile-win64, tests/ci_build/insert_vcomp140.py, tests/cpp/CMakeLists.txt
Follow-up to #4463. At minimum, we want to run Python and C++ tests. In particular, we want to ensure that the generated Python wheel is broadly compatible, e.g. on following platform combinations:
1. Windows Server 2008 R2 without GPU
2. Windows Server 2012 R2 with GPU + CUDA 9.0
3. Windows Server 2016 with GPU + CUDA 10.0
4. Windows Server 2019 with GPU + CUDA 10.1
=> [CI] Add Python and C++ tests for Windows GPU target

python-package/xgboost/core.py
Closes https://github.com/dmlc/xgboost/issues/4480
If the DataFrame column names aren't strings, constructing the error message here will yield an error:
```
File "/databricks/python/lib/python3.6/site-packages/shap/explainers/tree.py", line 172, in shap_values
X = xgboost.DMatrix(X)
File "/databricks/python/lib/python3.6/site-packages/xgboost/core.py", line 384, in __init__
feature_types)
File "/databricks/python/lib/python3.6/site-packages/xgboost/core.py", line 241, in _maybe_pandas_data
raise ValueError(msg + ', '.join(bad_fields))
TypeError: sequence item 0: expected str instance, int found
```
This simply ensures it's a string.
=> Ensure pandas DataFrame column names are treated as strings in type error message

src/common/hist_util.cc
@SmirnovEgorRu @hcho3 @RAMitchell
See https://github.com/dmlc/xgboost/pull/4433#issuecomment-495951502 for detail.
=> Revert hist init optimization.

.gitignore, demo/dask/README.md, demo/dask/dask_demo.py, demo/dask/dask_gpu_demo.py, demo/dask/dask_simple_demo.py, doc/python/python_api.rst, python-package/setup.py, python-package/xgboost/__init__.py, python-package/xgboost/compat.py, python-package/xgboost/dask.py, tests/ci_build/Dockerfile.cpu, tests/ci_build/Dockerfile.gpu, tests/python/test_with_dask.py, tests/python/testing.py
There has been some discussion about integrating dask-xgboost into the main xgboost repository (dask/dask-xgboost#39). This will make maintenance/packaging easier and ensure the documentation lives in the same place.
I have taken a different approach to the integration than the original dask-xgboost, which completely wraps everything into a new API. I have instead provided helper functions for launching dask workers. Workers launched in this way are automatically connected via rabit and may perform distributed training.
I believe this approach is very flexible as we do not need to modify the existing xgboost python API in any way, we just call these functions using the dask launcher. This approach was also extremely lightweight in terms of code.
See the demo for a worked example.
TODO: …
=> Add native support for Dask

python-package/xgboost/libpath.py
When built under cygwin, the Makefile produces 'cygxgboost.dll', which dll_path.py did not cover.
=> Add dll_path for cygwin users

src/common/hist_util.cc, tests/cpp/common/test_column_matrix.cc, tests/cpp/helpers.cc
- use the batch size to determine the correct number of rows in a batch
- use the right number of threads in omp parallalization if the batch size
is less than the default omp max threads (applicable for the last batch)
@canonizer @RAMitchell @rongou please review.
=> - fix issues with training with external memory on cpu

src/data/data.cc, tests/cpp/data/test_data.cc
fix crash with approx tree method on cpu when training is enabled with external memory
@trivialfis  - please review
=> - fix crash with approx tree method on cpu

src/common/device_helpers.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/common/test_device_helpers.cu
This PR addresses a performance regression that was introduced to the distributed GPU algorithms in #4343, after which we no longer intelligently selected whether to build the histogram on the left or right node based on how much data was in each partition. The performance regression only applies to the distributed or multi-GPU version.
To solve this I needed to construct a simple max AllReduce operation that works over multiple threads as rabit is not thread safe.
=>  Smarter choice of histogram construction for distributed gpu_hist

src/learner.cc
This piece of code is subtly broken:
https://github.com/dmlc/xgboost/blob/fbbae3386a9b6ff3ed31fe4ef5106a3c4665c6e5/src/learner.cc#L548-L569
The problem here is that `multiple_predictions` has an incorrect type (`bool`), so the sum
```cpp
bool multiple_predictions = static_cast<int>(pred_leaf) + 
static_cast<int>(pred_interactions) + 
static_cast<int>(pred_contribs); 
```
gets truncated down to 1. So it is not able to detect whether the user enabled both `pred_interactions` and `pred_contribs`.
Enabling both `pred_interactions` and `pred_contribs` causes an undefined behavior. Specifically, the snippet
```python
preds = model.predict(dtest, pred_contribs=True, pred_interactions=True)
```
will cause an error similar to #4276. Here's why:
1. In the C++ layer, we run `PredictContribution()`, …
=> Enforce exclusion between pred_interactions=True and pred_interactions=True

doc/gpu/index.rst, doc/parameter.rst, src/tree/updater_gpu.cu
Document deprecation of the exact GPU algorithm. I am no longer willing to support this algorithm, users should be encouraged to use 'gpu_hist' in all cases.
Reduction in old code will help reduce maintenance burden and refactoring overhead for those of us currently working on GPU algorithms.
=> Deprecate gpu_exact, bump required cuda version in docs

src/cli_main.cc, src/common/config.h, tests/cpp/common/test_config.cc
In https://github.com/dmlc/xgboost/pull/4486#issuecomment-497509172, we found out that #4478 broke the CLI parser when the training data path contained a `#` letter. That is, the new C++11 parser could not differentiate between
```
data = train.libsvm    # cache
```
and
```
data = "train.libsvm#cache"
```
I did an overhaul of parser logic (with `std::regex`!) to fix this issue and others. I also wrote bunch of tests.
**Why not just revert #4478?**  I like the idea of using C++11. Also, the old parser silently ignored backslashes (`\`), which breaks Windows paths.
cc @sriramch
TODO. Update the CLI doc to describe the grammar of configuration file. See some examples now in `tests/cpp/common/test_config.cc`.
=> Fix C++11 config parser

tests/ci_build/tidy.py
`load` without `Loader` is deprecated.
=> Use yaml.safe_load.

src/objective/regression_obj.cu, tests/cpp/objective/test_regression_obj.cc, tests/cpp/test_main.cc
Retuning a c_str from temporary string can result in segfault.
=> Fix tweedie metric string.

src/CMakeLists.txt, src/common/device_helpers.cuh, src/common/hist_util.cu, src/common/host_device_vector.cu, src/predictor/gpu_predictor.cu, src/tree/updater_gpu_hist.cu, tests/benchmark/benchmark_tree.py, tests/cpp/CMakeLists.txt, tests/cpp/tree/test_gpu_hist.cu
This PR creates a custom thrust device memory allocator. It serves as an entry point to use custom allocators in the future (such as cacheing pool allocators) and provides logging for memory usage statistics.
There should be no change in behaviour here.
The logging output looks like this:
```
[16:39:52] ======== Global Device Memory Allocations:  ========
[16:39:52] Peak memory usage: 1114mb
[16:39:52] Number of allocations: 198
```
TODO:
=> Overload device memory allocation

src/tree/updater_gpu_hist.cu, tests/cpp/helpers.cc, tests/cpp/helpers.h, tests/cpp/tree/test_gpu_hist.cu
- when external memory support is enabled, building of histogram indices are
done incrementally for every sparse page
- the entire set of input data is divided across multiple gpu's and the relative
row positions within each device is tracked when building the compressed histogram buffer
- the external memory is used for building the compressed buffer *only*. it is required for the compressed buffer to fit entirely into the gpu memory
- this was tested using a mortgage dataset containing ~ 670m rows before 4xt4's could be
saturated
@RAMitchell @canonizer @rongou - please review
=> - training with external memory - part 2 of 2

CMakeLists.txt, doc/build.rst, doc/gpu/index.rst, include/xgboost/generic_parameters.h, src/learner.cc
First step for #4531 
@canonizer @RAMitchell @trivialfis
=> deprecate single node multi-gpu mode

Jenkinsfile
See https://github.com/dmlc/xgboost/pull/4554#discussion_r295070473. Now that we are distributing XGBoost compiled with CUDA 9.0, we will cease testing XGBoost against CUDA 8.0 target. This should reduce the cost of the Jenkins CI pipeline.
=> [CI] Remove CUDA 8.0 from CI pipeline

include/xgboost/learner.h, src/common/span.h, src/learner.cc, src/tree/constraints.cu, src/tree/constraints.cuh, src/tree/param.h, src/tree/split_evaluator.cc, src/tree/updater_gpu_hist.cu, tests/cpp/tree/test_bitfield.cu, tests/cpp/tree/test_constraints.cu, tests/cpp/tree/test_gpu_hist.cu, tests/cpp/tree/test_split_evaluator.cc, tests/python-gpu/test_gpu_interaction_constraints.py, tests/python/test_interaction_constraints.py
Continuation of #4488.
This PR removed the previous attempt of reusing CPU `SplitEvaluator` to avoid device/host memory copying during tree update, as suggested by @RAMitchell .  The downside is now the memory usage on GPU side is of size `O(n_features^2) + O(n_features * n_nodes)`, let alone some other buffer allocations.  One possible improvement is to parse the input data during DMatrix construction to optimize sparse dataset memory usage, but that is beyond the scope of this PR.
TODOs:
=> Feature interaction for GPU Hist.

Jenkinsfile, tests/ci_build/ci_build.sh
Background: The Jenkins CI pipeline (https://xgboost-ci.net) uses AWS ECR (Elastic Container Registry) to cache Docker images, in order to speed up builds.
This pull request will explicitly specify the AWS account ID (492475357299) when connecting to ECR. This change is intended to allow worker instances from another AWS account to connect to the same ECR registry. Having multiple AWS accounts is necessary to divide the expenses between multiple billing accounts.
=> [CI] Specify account ID when logging into ECR Docker registry

src/common/device_helpers.cuh, src/tree/gpu_hist/row_partitioner.cu, src/tree/gpu_hist/row_partitioner.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/common/test_device_helpers.cu, tests/cpp/tree/gpu_hist/test_row_partitioner.cu, tests/cpp/tree/test_gpu_hist.cu
This PR extracts out data structures and logic for partitioning rows in gpu_hist. It uses automatic caching memory allocators in the new data structure so that it may be deleted and recreated every tree building iteration without incurring memory allocation costs. The reason for doing this is to not keep memory buffers between training iterations with unknown state, instead it is cleaner and less bug prone to create and destroy data structures after each use.
The new RowPartitioner class accepts device lambdas as inputs to define logic for splitting instances into left or right nodes. This means the class has no dependency on any particular tree structure or logic for partitioning the tree.
This is part of an effort to separate our monolithic gpu_hist code base into parts that are …
=> Refactor out row partitioning logic from gpu_hist, introduce caching device vectors

src/tree/constraints.cu
* Split up the kernel to sync write.
* QueryNode is no-longer used in Query, but kept for testing.
=> Fix race condition in interaction constraint.

python-package/xgboost/sklearn.py
Input to `XGBClassifier.predict()` / `XGBRegressor.predict()` / `XGBRanker.predict()` should be either NumPy or SciPy array, NOT DMatrix.
Closes #4582, #4549
=> Fix docstring for XGBModel.predict() [skip ci]

doc/gpu/index.rst, doc/tutorials/feature_interaction_constraint.rst, python-package/xgboost/dask.py, python-package/xgboost/plotting.py, python-package/xgboost/sklearn.py
I'm not confident about my writing, please help verifying.  Otherwise it might be very embarrassing ...
I am not sure about how to fix the following warnings yet:
```
/home/fis/Workspace/xgb/xgboost/doc/gpu/index.rst:89: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/home/fis/Workspace/xgb/xgboost/doc/jvm/index.rst:3: WARNING: Duplicate explicit target name: "here".
/home/fis/Workspace/xgb/xgboost/doc/jvm/xgboost4j_spark_tutorial.rst:3: WARNING: Duplicate explicit target name: "here".
/home/fis/Workspace/xgb/xgboost/doc/jvm/xgboost4j_spark_tutorial.rst:3: WARNING: Duplicate explicit target name: "here".
/home/fis/Workspace/xgb/xgboost/python-package/xgboost/plotting.py:docstring of xgboost.to_graphviz:19: WARNING: Unexpected indentation. …
```
=> Update doc for feature constraints.  Fix some warnings.

doc/contribute.rst
cc @sriramch
Aside: now it is possible to add [skip ci] in the commit message to skip Jenkins tests for a single pull request.
=> Add instruction to run formatting checks locally [skip ci]

include/xgboost/feature_map.h, python-package/xgboost/core.py, python-package/xgboost/plotting.py, src/c_api/c_api.cc, src/common/timer.h, src/tree/tree_model.cc, src/tree/updater_gpu.cu, tests/cpp/tree/test_tree_model.cc, tests/python/test_plotting.py, tests/python/test_shap.py, tests/python/test_with_sklearn.py
* Split up builders.
* Use pattern matching.
* Implement generator for Graphviz.
Closes #4228, Closes #4561
There are few benefits of this PR:
- After introducing proper code templates in generator, the semantic of generated text files become clearer.  Currently we don't have documentation around what exactly a dumped model should look like.
- Eliminates parsing the text dump again in language bindings.  One can generate very weird output by parsing the dumped text, as in above linked issues.  This PR implements a generator for Graphviz, which directly parses the tree model instead of text output.
- All bindings of Graphviz can accept dot file strings, so it should be easier for scala and jvm (and any other languages) to implement plotting.  @CodingCat. (I did a simple grep in the jvm …
=> Implement tree model dump with code generator.

doc/tutorials/custom_metric_obj.rst
Follow-up to #4598. The example training log was not being displayed because of a syntax issue.
=> Fix doc for customized objective/metric

doc/requirements.txt
ReadTheDocs service (it hosts https://xgboost.readthedocs.io/en/latest/) has been previously using Sphinx 1.8.1, which is quite an old version. Upgrade Sphinx to 2.1+.
cc @trivialfis
=> Use Sphinx 2.1+ to compile documentation

.gitmodules, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/LearningTaskParams.scala, jvm-packages/xgboost4j-spark/src/main/scala/org/apache/spark/SparkParallelismTracker.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/ParameterSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/PerTest.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/RabitRobustnessSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifierSuite.scala, jvm-packages/xgboost4j/src/native/xgboost4j.cpp
this PR deletes all constraints from spark layer about obj and eval
and simultaneously it ensures that the error caused by native layer (such as unsupported obj and eval) can be handled properly in jvm layer
=> [jvm-packages] delete all constraints from spark layer about obj and eval metrics and handle error in jvm layer

src/predictor/gpu_predictor.cu, tests/cpp/predictor/test_gpu_predictor.cu
This should fix the problem #4594 is trying to enforce.
@RAMitchell @CodingCat
=> fix gpu predictor when dmatrix is mismatched with model

python-package/xgboost/dask.py, tests/ci_build/Dockerfile.cpu, tests/ci_build/Dockerfile.gpu
The current Dask integration in XGBoost (`xgboost/dask.py`) does not work with Dask 2.0.0 (released Jun 25, 2019) because dask/distributed#2758 replaced all occurrences of `ncores` with `nthreads`.
This pull request will access `ncores` and `nthreads`, whichever is available, so that XGBoost can work with both 1.2.x and 2.0.0 versions of Dask.
Also, we specify the exact version of Dask in the Dockerfile, so that we know which version of Dask XGBoost is tested with.
@RAMitchell @mrocklin @mt-jones
=> Support Dask 2.0

include/xgboost/data.h, src/data/data.cc, src/data/simple_dmatrix.h, src/data/sparse_page_dmatrix.h, src/data/sparse_page_source.cc, src/data/sparse_page_writer.cc, tests/cpp/common/test_column_matrix.cc, tests/cpp/common/test_gpu_hist_util.cu, tests/cpp/data/test_data.cc, tests/cpp/data/test_sparse_page_dmatrix.cc, tests/cpp/helpers.cc, tests/cpp/helpers.h, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu
This fixes two bugs:
* Use PushCSC to get column batches.
* Don't remove the created temporary directory before finishing test.
Please note that this PR doesn't solve #4619 yet.  These are another two bugs I found while debugging the Python test.
=> Fix external memory for get column batches.

python-package/xgboost/core.py, tests/python/test_early_stopping.py, tests/python/test_with_sklearn.py
If PANDAS_INSTALLED is False then
DataFrame = object and that means that
instance("any file path", DataFrame) returns true
which is not what we want
I tried to run pytest without installing pandas and few tests failed because of this
=> pytest tests/python fails if no pandas installed

R-package/DESCRIPTION, R-package/R/xgb.cv.R, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_callbacks.R
When `xgb.cv()` takes in an `xgb.DMatrix` object as the `data` argument, the built-in label from the object should be extracted and used for building folds (`generate.cv.folds()`).
Closes #4509
@JaakobKind
=> [R] Use built-in label when xgb.DMatrix is given to xgb.cv()

src/metric/metric.cc, src/metric/rank_metric.cc, tests/cpp/metric/test_rank_metric.cc
Closes #4247
Now `ndcg-` and `map-` are accepted as valid metrics.
Note: XGBoost already has been accepting `ndcg@-` and `map@-`, but the doc refers to `ndcg-` and `map-` instead. With this PR, all of these four will be accepted.
=> Support ndcg- and map-

python-package/xgboost/sklearn.py
Many methods of `XGBClassifier` relies on the existence of certain fields, such as `self.objective`, `self.missing`, and `self.n_classes_` (these fields exist to ensure interoperability with scikit-learn) and these fields are **not** preserved by the call to `XGBClassifier.save_model()`, as the binary serialization format is not aware of these fields. See #4517, where `XGBClassifier.save_model()` breaks `predict_proba()` for multi-class classifiers.
Fix: Display prominent warning whenever `save_model()` is called from `XGBClassifier`. The recommendation is not to use it, unless the purpose is to export the model to a non-Python environment (e.g. Java).
EDIT. Maybe we should just deprecate `save_model()`, as its name is quite misleading, and call it `export_model_for_external_use()` or …
=> Add warning when save_model() is called from scikit-learn interface

python-package/xgboost/callback.py
Closes #4443, by ignoring iterations with empty evaluation result.
=> Empty evaluation list in early stopping should produce meaningful error message

python-package/xgboost/sklearn.py, python-package/xgboost/training.py, tests/python/test_early_stopping.py
* Consistently choose the last validation set + last metric combination as the early stopping criteria.
* The order between metrics should be preserved, so that the user will have certainty of which metric will be used for early stopping.
* Clarify the semantics of early stopping in the Python API doc. Preview: https://hcho3-xgboost.readthedocs.io/en/fix_early_stopping_python/python/python_api.html#xgboost.train
Closes #4630
Closes #4421
=> Fix early stopping in the Python package

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala
As discussed in https://discuss.xgboost.ai/t/jvm-packages-v0-90-sparse-vector-prediction-issue-on-missing-values/903/5, we should expose `setMissing()` method in XGBoostClassificationModel / XGBoostRegressionModel, so that `transform()` will behave correctly.
=> [jvm-packages] Expose setMissing method in trained Model

jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/PerTest.scala, jvm-packages/xgboost4j-spark/src/test/scala/org/apache/spark/SparkParallelismTrackerSuite.scala
This does seem to work better on my desktop which has 12 cores. Should fix #3955.
@hcho3 @CodingCat
=> [jvm-packages] fix spark tests on machines with many cores

src/metric/rank_metric.cc
Running xgboost distributedly with imbalanced datasets may trigger the exception: `AUC: the dataset only contains pos or neg samples` ,  especially when world_size is large.  Because sub datasets held by some workers only contains no pos or neg samples,  which will cause local exceptions.
This PR modified the response of `auc_error`.  In distribute mode, workers whose `auc_error > 0` will be ignored in AUC average rather than raising an error.
=> Fix auc error in distributed mode caused by imbalanced dataset

jvm-packages/pom.xml, jvm-packages/xgboost4j/pom.xml
* exec plugin was missing a version
* reportPlugins has been deprecated:
see https://maven.apache.org/plugins/maven-site-plugin/maven-3.html#Classic_configuration_Maven_2__3
=> Fix maven warnings

python-package/setup.py, python-package/setup_pip.py
I did some python code reading and I noticed that we have a lot of optional dependencies which are not fully exposed though setup.py.
So I added extra dependencies.
Now one can use
pip install -e .[dask]
to install all xgboost supporting dask
=> Improve setup.py by adding extra dependencies

appveyor.yml, jvm-packages/README.md, jvm-packages/pom.xml, jvm-packages/xgboost4j-example/pom.xml, jvm-packages/xgboost4j-flink/pom.xml, jvm-packages/xgboost4j-spark/pom.xml, jvm-packages/xgboost4j-tester/generate_pom.py, jvm-packages/xgboost4j/pom.xml, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/DMatrix.java, jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/rabit/RabitTracker.scala, tests/ci_build/Dockerfile.jvm_cross, tests/ci_build/test_jvm_cross.sh
hello!
spark 2.4 will be last spark release to support scala 2.11 and is also available for scala 2.12
flink 1.7 is available for scala 2.11 and scala 2.12. i am not familiar enough with flink or its community to say when they will drop scala 2.11
this pullrequest builds the jvm libs using scala 2.12. to make the switch i had to change java version to 1.8 (required for scala 2.12) and upgrade flink and akka.
to be able to publish artifacts for both scala 2.11 and 2.12 (scala is not compatible across minor versions) i modified the artifacts to have scala version in the name. its not pretty :( but it seems to be the convention.
to publish artifacts for scala 2.11 one just has to make a few small modifications to pom files. this can probably easily be automated with a bash script. e.g. …
=> upgrade to Scala 2.12

jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala
this PR is to include  https://github.com/dmlc/rabit/pull/99
the use case is like following 
```
val df1 = xgbmodel.transform(training)
val df2 = xgbmodel2.transform(df1)
```
because we shutdown rabit in both of df1 and df2 (the task will processing df1's partition first and then df2's ), the original code explicitly prohibit such usage pattern, 
I added a test to guard this usage pattern 
@sperlingxx would you mind helping to review ?
=> [jvm-packages] allowing chaining prediction

tests/ci_build/Dockerfile.cpu
Many pull requests (#4698, #4701, #4699, #4697) are currently failing with the following cryptic error:
```
>       return arith_flex, comp_flex, arith_special, comp_special, bool_special
E       UnboundLocalError: local variable 'arith_flex' referenced before assignment
/opt/python/lib/python3.7/site-packages/pandas/core/ops/__init__.py:719: UnboundLocalError
!!!!!!!!!!!!!!!!!!! Interrupted: 20 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 20 error in 5.70 seconds ===========================
```
I found out that the command `conda install dask=2.0.0` silently pulls in Pandas 0.24.2 from Anaconda, and that causes conflict with previously installed Pandas 0.25.0 (installed via Pip). The error disappears when I install only one copy of Pandas, whether it's 0.24.2 …
=> [CI] Fix broken installation of Pandas

include/xgboost/data.h
@hcho3 @RAMitchell @trivialfis
=> remove RowSet which is no longer being used

amalgamation/xgboost-all0.cc, include/xgboost/json.h, include/xgboost/json_io.h, src/common/io.cc, src/common/io.h, src/common/json.cc, tests/cpp/common/test_json.cc
This will enable #4702 and #4683 (extracted from there).  Other than serialization,  the JSon implementation will be used to consume [numpy array interface](https://docs.scipy.org/doc/numpy/reference/arrays.interface.html), and [cuda array interface](numba.pydata.org/numba-doc/latest/cuda/cuda_array_interface.html).  This will benefit XGBoost as creating the generic interface will enable introp with lots of existing libraries (~arrow and friends~, cupy, numba etc..) without creating specific C backend source code.
A json implementation will the first part of on going effort for above described features.  This PR doesn't touch any existing code base, can we consider merging it although it's not used by other code?
=> A simple Json implementation for future use.

src/common/bitfield.cuh, src/tree/constraints.cu, src/tree/constraints.cuh, tests/cpp/common/test_bitfield.cu
To be used by cudf support.
The validity mask from Apache arrow memory layout is passed in as `unsigned char`, but the specification also said that it must be of 8 byte aligned and the length should be padded to be a multiple of 8 byte.  So `uint64_t` used in BitField fits.
=> Move bitfield into common.

src/learner.cc, tests/cpp/test_learner.cc
Issue repro step:
1. load a model (naming A) from disk,
2. invoke A.setParam() to set a parameter
3. Learner.configured_ will be set to false
4. A.Predict()
5. learner.Configure()
then tparam_.objective will set to default (reg:squarederror)
6. learner.ConfigureObjective() will use incorrect objective
For example
in train phase, objective is multi:softprob
but after before 6 steps, in predict phase, objective will be multi:softmax
=> fix objective parameter issue

src/common/bitmap.h, src/learner.cc, src/objective/rank_obj.cc, src/tree/updater_colmaker.cc, src/tree/updater_histmaker.cc
After removing `gpu_hist`, I ran cppcheck to see if it can find more dead code, but it found a few random functions.
@RAMitchell @trivialfis @hcho3
=> remove some unused functions as reported by cppcheck

include/xgboost/data.h, src/data/data.cc, src/data/simple_csr_source.cc, src/data/sparse_page_source.h, tests/cpp/data/test_metainfo.cc
I'm not sure how much we care about saved `MetaInfo` binaries. If you want I can add the versioning back.
Part of the DMatrix refactoring #4354 
@trivialfis @RAMitchell
=> remove the qids_ field in MetaInfo

include/xgboost/generic_parameters.h, src/learner.cc, tests/cpp/common/test_gpu_hist_util.cu, tests/cpp/linear/test_linear.cu, tests/cpp/metric/test_elementwise_metric.cc, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/test_learner.cc, tests/cpp/tree/test_gpu_hist.cu, tests/distributed/distributed_gpu.py, tests/distributed/runtests-gpu.sh, tests/python-gpu/test_gpu_linear.py, tests/python-gpu/test_gpu_updaters.py, tests/python-gpu/test_large_sizes.py, tests/python-gpu/test_pickling.py
See RFC #4531
Part of 1.0.0. roadmap #4680 
@RAMitchell @trivialfis @sriramch
=> [BREAKING] prevent multi-gpu usage

src/common/span.h
`KERNEL_CHECK`:
```
Kernel error:
In: /home/fis/Workspace/cuDf/xgboost/tests/cpp/common/test_span.cu: 327
void xgboost::common::TestAssert2(xgboost::common::Span<unsigned long, -1L>)
Expecting: _span.size() > 3
Block: [0, 0, 0], Thread: [0, 0, 0]
```
Official cuda `assert`:
```
/home/fis/Workspace/cuDf/xgboost/tests/cpp/common/test_span.cu:324: void xgboost::common::TestAssert(xgboost::common::Span<unsigned long, -1L>): block: [0,0,0], thread: [0,0,0] Assertion `_span.size() > 3` failed.
```
=> Mimic cuda assert output in span check.

src/common/hist_util.cc, src/tree/updater_quantile_hist.cc, tests/cpp/tree/test_quantile_hist.cc, tests/python/test_openmp.py
Problem: 
- Distributed training with hist method will stop working when synchronizing histograms of different machines.
Debug Stack:
-   Size of `expand_nodes` in different workers are not equal, because one node may be a leaf node on one worker, but it is still splitable on other workers.
-  Results of `SplitEvaluation` are inconsistent on different workers (machines).
-  Inconsistent split results will be observed only when `nthread > 1`.
-  When I changed OPENMP schedule policy of `EvaluateSplitsBatch` from `schedule(guided)` to `schedule(dynamic) num_threads(nthread)`,  everything works.
=> [HOTFIX] distributed training with hist method 

tests/ci_build/Dockerfile.rproject
See https://rubuntu.netlify.com/post/changes-to-cran-ubuntu-webpage-regarding-apt-secure-key/ and https://cran.r-project.org/bin/linux/ubuntu/ .
This unblocks the current CI.
=> Use long key id.

CMakeLists.txt, Makefile, doc/build.rst, doc/parameter.rst, make/config.mk, make/travis.mk, plugin/CMakeLists.txt, plugin/README.md, plugin/dense_parser/plugin.mk, plugin/example/README.md, plugin/example/plugin.mk, plugin/lz4/plugin.mk, plugin/updater_gpu/README.md, src/CMakeLists.txt, tests/cpp/CMakeLists.txt, tests/cpp/plugin/test_example_objective.cc, tests/travis/run_test.sh
Closes #4627.
Default to CMake instead.
Breaking: Makefile will no longer work with plugins.
=> Remove plugin, cuda related code in automake & autoconf files

R-package/R/xgb.Booster.R
Previously `xgb.get.handle` was only checking the first class of the provided object.
Now it checks all its class to guess if it s a handler or if it s a model
fix #4764
=> [R] `xgb.get.handle` now checks all class listed of `object`

python-package/xgboost/callback.py
the eval metric print was irregular when there was more than one comparison set
=> eval_metrics print fixed

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/CheckpointManagerSuite.scala
several pattern matching needs to be changed when adding a new param now, e.g. https://github.com/dmlc/xgboost/pull/4805
this PR is to refactor XGBoost.scala to make code cleaner
=> [jvm-packages] Refactor XGBoost.scala to put all params processing in one place

include/xgboost/gbm.h, src/gbm/gblinear.cc, src/gbm/gbtree.cc, src/gbm/gbtree.h, src/tree/updater_gpu_hist.cu, src/tree/updater_histmaker.cc, tests/cpp/gbm/test_gbtree.cc
For parameter validation, I need to remove the copy of configuration.  Or at least copy only what's necessary.  After this PR, the copied configuration will only be used by initializing `updaters` and `TreeParam`.  I plan to deprecate `TreeParam` after introducing JSON.
=> Restrict access to `cfg_` in gbm.

src/tree/updater_quantile_hist.cc
In #4716,  we modified schedule policy of OPENMP from `guided` to `static`. But I caught same problem after this fix.  
After a lot of debug work, I found the `rabit::IsDistributed` method, which is in parallel body of OPENMP,  is not thread safe.  Because [rabit::GetEngine](https://github.com/dmlc/rabit/blob/dba32d54d1668033356a2ad505c239411d660821/src/engine.cc#L74) is thread local.
=> [blocking] fix parallel eval_split of hist updater

amalgamation/xgboost-all0.cc, include/xgboost/data.h, src/common/hist_util.cu, src/common/hist_util.h, src/data/ellpack_page.cc, src/data/ellpack_page.cu, src/data/ellpack_page.cuh, src/data/simple_batch_iterator.h, src/data/simple_dmatrix.cc, src/data/simple_dmatrix.h, src/data/sparse_page_dmatrix.cc, src/data/sparse_page_dmatrix.h, src/tree/updater_gpu_hist.cu, tests/cpp/common/test_gpu_hist_util.cu, tests/cpp/data/test_ellpack_page.cu, tests/cpp/helpers.h, tests/cpp/tree/test_gpu_hist.cu
@RAMitchell @trivialfis @sriramch this PR pulls out the quantile sketches and binning compression into a separate `EllpackPage`. For now the whole `ELLPackMatrix` is still kept in GPU memory. Next step is to break apart the matrix and persist to disk.
Please take a look.
Part of #4357.
=> add ellpack page

doc/index.rst
From https://discuss.xgboost.ai/t/ruby-library-for-xgboost/1133, I learned that there is now a Ruby binding for XGBoost. 
Announcement: https://ankane.org/xgboost-lightgbm-come-to-ruby
cc @ankane
=> Add link to Ruby XGBoost gem

.gitignore
Ignore files generated by IDEs (VSCode, IntelliJ, CLion, etc.).
@RAMitchell @trivialfis @CodingCat
=> ignore vscode and clion files

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala, jvm-packages/xgboost4j-spark/src/main/scala/org/apache/spark/SparkParallelismTracker.scala
This PR propose a more stable approach to query total number of alive cores; fetch executor information via spark API `sc.statusStore.executorList` directly rather than using restful API of spark WebUI.
In addition,  I found a bug about `waitForCondition`. Query thread wrapped by `Future` will never exit if condition is not satisfied.  Because `Await.ready` will throw an exception without stopping the`Future` thread when timeout is reached. 
@CodingCat can you help to look this?
=> [jvm-packages] refine numAliveCores method of SparkParallelismTracker 

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/DataUtils.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostEstimatorCommon.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/DeterministicPartitioningSuite.scala
part of https://github.com/dmlc/xgboost/issues/4786
=> [jvm-packages] enable deterministic repartitioning when checkpoint is enabled

src/common/math.h
Closes  #4882.  Haven't verify the fix yet.  Just trying to see general test results.
=> Workaround `isnan` across different environments.

src/tree/updater_gpu_hist.cu, tests/cpp/tree/test_gpu_hist.cu
@hcho3 @RAMitchell I just prevent the split when `loss_chg` < `gamma`.  Could you think of a case adding an explicit `pruner` is useful?  One additional thing I found in `pruner` is a syncing operation (broadcasting rank 0 tree), but I don't think it's necessary for `gpu_hist`.
=> Support gamma in GPU_Hist.

src/common/hist_util.cu, src/common/host_device_vector.h, src/data/ellpack_page.cu, src/linear/updater_gpu_coordinate.cu, src/objective/multiclass_obj.cu, src/predictor/gpu_predictor.cu, src/tree/updater_gpu_hist.cu, tests/cpp/tree/test_gpu_hist.cu
Remove `DeviceShard` classes since we no longer support single process multi-GPU.
In `updater_gpu_hist.cu`, I only renamed the `DeviceShard` to `GPUHistMakerDevice` since it's fairly self contained. Let me know if you have a better name for it.
Hopefully the last cleanup PR for #4531.
@RAMitchell @trivialfis @sriramch
=> remove device shards

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala
To support specifying long parameter as String, the same as other basic
type, such as Int, Double ...
=> [jvm-package] Add case for LongParam.

python-package/xgboost/compat.py, python-package/xgboost/core.py, tests/python-gpu/test_from_columnar.py
This PR allows  `cudf.Series` to go via `columnar` initalizlizer . 
This pr fixes the code-path to follow when the label is a `cudf.Series` . 
```python
X_train = cudf.DataFrame({'1':
cudf.Series( np.random.randint(low = -1000, high = 50_000 , size= 1_000_000, dtype=np.int32))})
Y_train = cudf.Series(np.random.randint(low = 0,high = 2 ,size = 1_000_000, dtype=np.int32))
```
Before this pr below took  `2min 18s`
```python
%time xgb.DMatrix(X_train,Y_train)
```
After this PR below takes  10.5 ms
```python
%time xgb.DMatrix(X_train,Y_train)
```
=> Add support for cudf.Series

python-package/xgboost/dask.py, src/common/device_helpers.cuh
Resolves performance bug where dask attempts to generate hashes from nested functions with large arguments in client.map.
On the YearPredictMSD dataset this reduces runtime from 90s to 45s when using dask.
=> Resolve dask performance issues

include/xgboost/generic_parameters.h, python-package/xgboost/sklearn.py, src/learner.cc, tests/python-gpu/test_gpu_with_sklearn.py, tests/python/test_with_sklearn.py
* Remove `nthread`, `seed`, `silent`. Add `tree_method`, `gpu_id`, `num_parallel_tree`. Fix #4909.
* Check data shape. Fix #4896.
* Check element of `eval_set` is tuple. Fix #4875
* Add doc for random_state with hogwild. Fixes #4919
=> [Breaking] Update sklearn interface.

Jenkinsfile
Raise timeout from 120 minutes to 240 minutes. I don't expect the actual tests to take this long, but sometimes, it takes a while for GPU workers to be allocated. I raised the limit for multi-GPU workers to ameliorate the bottleneck (*), but at the same time, we should raise the timeout just to be safe.
cc @trivialfis @RAMitchell 
(*) The limit is now 3. Thankfully, G4 instances are about 2x more affordable as P2 instances.
=> [CI] Raise timeout threshold in Jenkins

src/common/bitfield.h, src/data/columnar.h, src/data/simple_csr_source.cu, src/data/simple_csr_source.h, tests/cpp/common/test_bitfield.cu, tests/cpp/data/test_simple_csr_source.cu, tests/python-gpu/test_from_columnar.py
* Ignore the 8 bytes requirement.
* Fix stride size.
* tests.
=> Ignore columnar alignment requirement.

python-package/xgboost/sklearn.py
The second line was rendered out of the Note container in HTML.
=> Fix incorrectly displayed Note in the doc

include/xgboost/span.h, src/common/device_helpers.cuh, src/common/hist_util.h, src/common/host_device_vector.cu, src/data/columnar.h, tests/cpp/common/test_span.cc, tests/cpp/common/test_span.cu, tests/cpp/data/test_data.cc, tests/cpp/tree/test_quantile_hist.cc
* Remove a batch of `static_cast'.
Originally I implemented `Span` with some conventions from GSL, where uses `int64_t` as `index_type`.  But `span` in c++20 actually uses `size_t`, and during the development I found `size_t` should be much more consistent with the rest of the world.  So this PR changes `Span` to align with std.
* Added front and back from c++20 for completeness.
=> Span: use `size_t' for index_type,  add `front' and `back'.

demo/dask/gpu_training.py, python-package/xgboost/core.py, python-package/xgboost/dask.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_pickling.py, tests/python/test_with_dask.py
* Also fix another issue found in dask prediction.
=> Don't `set_params` at the end of `set_state`.

src/tree/updater_gpu_hist.cu, tests/cpp/common/test_device_helpers.cu
This PR considerably improves performance for the distributed GPU algorithm. We use the sum of Hessian in the left and right node to estimate which has fewer training instances instead of using rabit to sync and calculate this exactly. In particular it improves latency.
Performance numbers from training on a DGX-1 with https://github.com/NVIDIA/gbm-bench
| dataset | old     | new      | speedup  |   
|---------|----------|----------|------|
| airline | 68.4073  | 59.2706  | 1.15 |
| bosch   | 20.12437 | 16.1119  | 1.25 |
| covtype | 81.049   | 59.8792  | 1.35 |
| epsilon | 306.2088 | 311.6957 | 0.98 |
| fraud   | 8.3944   | 6.7949   | 1.24 |
| higgs   | 34.4294  | 24.0335  | 1.43 |
| year    | 25.8719  | 15.3342  | 1.69 |
I also removed the old HostAllReduce function, which is redundant …
=> Use heuristic to select histogram node, avoid rabit call

python-package/xgboost/core.py
I have noticed an inconsistent convention used throughout xgboost's core Python file. So I made some changes that will make the core file to respect docstring conventions according to [PEP 257](https://www.python.org/dev/peps/pep-0257/).
=> Follow Docstring Conventions

doc/build.rst, python-package/.pylintrc, python-package/xgboost/core.py, python-package/xgboost/tracker.py
As reported in https://github.com/dmlc/xgboost/pull/4873#issuecomment-544680495, the latest master branch is failing the lint check, probably because `pylint` package has been updated. This PR updates `.pylintrc` (with a few cosmetic code changes) to make the lint check pass again.
Also closes #4969, by using GCC 8 throughout the installation doc.
=> [CI] Update lint configuration to support latest pylint convention

tests/ci_build/Dockerfile.cpu, tests/ci_build/Dockerfile.cudf, tests/ci_build/Dockerfile.gpu
Dask tests are stuck and timing out due to dask/dask#5465: https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-4971/2/pipeline/40/#step-75-log-1677. The cause of the timeout is because one of dependencies of Dask, `distributed`, changed its semantics in recent versions in ways that are not compatible with Dask 2.0.0. Fix: Pin version of `distributed`.
=> [CI] Use latest dask

Jenkinsfile, Jenkinsfile-win64
This is a follow-up to #4976.
According to [this link](https://issues.jenkins-ci.org/browse/JENKINS-44835?focusedCommentId=302882&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-302882), path to root directory should be set as `""` (empty string), not `"/"`. The latter just creates a directory called `/`.
=> [CI] Upload master branch artifacts to S3 root

doc/contrib/unit_tests.rst
Addresses @sriramch's comment in https://github.com/dmlc/xgboost/pull/4862#issuecomment-548573232
=> Document minimum version required for gtest [skip ci]

src/tree/updater_colmaker.cc
This patch addresses the issue raised in https://github.com/dmlc/xgboost/issues/3826
I was able to determine that this situation arises when there is "spike" of data at a single floating point number having a slight increase in gain to split away.  The lack of numerical precision causes the split point calculation to fail to resolve between the observed values.  Then, the "<" logic of scoring the tree is different from the sort and split logic of the search.  
In this patch, I've simply tried to catch the loss of resolution and propose a different split in that situation.  Testing this on the example provided in the issue above, the split leading to the 0-cover nodes is shifted slightly (the tree structure below is similar to the previous tree), and the nodes on the other side of the tree …
=> attempt to fix repeated split and 0 cover nodes

python-package/xgboost/core.py
When feature_names contains something other than a string (e.g. integer), the previous error message (`feature_names may not contain [, ] or <`) made me confused. Therefore I propose adding more explanation.
=> Add more explanation for reason of ValueError

src/common/column_matrix.h, src/common/hist_util.cc, src/common/hist_util.h, src/common/row_set.h, src/tree/param.h, src/tree/split_evaluator.cc, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, tests/cpp/tree/test_quantile_hist.cc
After #4529, the 'hist' updater became quite unwieldy and currently few developers understand it. In particular, `CreateTasksForXXX` functions have created multiple layers of indirection, making it unclear which objects are being computed/modified.
This PR reverts #4529 in an attempt to simplify the 'hist' updater. I plan to incorporate parts of #4529 in a later date, under the following conditions: 
* Test suite to detect regression in performance is correctness must be set up.
* All new abstractions should be clearly documented, with unit tests.
Also closes #4679.
cc @chenqin @trams
=> Revert #4529

src/common/hist_util.cc
In `GHistIndexMatrix::Init` reset the temporary `hit_count_tloc_` for reuse in next loop iteration.
The bug is only triggered if there are multiple pages.
While there are no automated test case, this fix resulted in matching `hit_count` (and learning results) when comparing `SimpleDMatrix` and my custom multipage `DMatrix` implementation.
=> fix: reset hit counter for next batch

demo/gpu_acceleration/README.md, demo/gpu_acceleration/memory.py, doc/gpu/index.rst
Documents workarounds for #4668 and provides some additional info on GPU memory allocation.
=> Some guidelines on device memory usage

.travis.yml, doc/tutorials/external_memory.rst, tests/cpp/data/test_data.cc, tests/travis/run_test.sh, tests/travis/setup.sh
- Install wget explicitly to match openssl.
- Install CMake explicitly.
- Use newer miniconda link.
- Reenable CMake test.
- Disable
- gcc@9 + xcode@10 for osx due to missing <_stdio.h>.  Other versions of gcc should also work.  But as homebrew pour gcc@9 after update by default, so I just stick with latest version.
- Disabled one external memory test for OSX.  Not sure about the thread implementation in there and fixing external memory is beyond the scope of this PR.
- Use Python3 with conda in jvm package.
=> [CI] Fix Travis tests.

tests/ci_build/insert_vcomp140.py
After I re-built Jenkins testing pipeline from scratch, I found out that I cannot always expect the path `C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\14.0\\VC\\redist\\x64\\Microsoft.VC140.OpenMP\\vcomp140.dll` to exist. Since vcomp140.dll is a system lib, it's better to use `C:\\Windows\\System32\\vcomp140.dll`
=> [CI] Locate vcomp140.dll from System32 directory

R-package/tests/testthat/test_helpers.R, amalgamation/xgboost-all0.cc, include/xgboost/predictor.h, make/mingw64.mk, src/data/ellpack_page.cc, src/data/ellpack_page_source.cc, src/data/ellpack_page_source.cu, src/data/ellpack_page_source.h, src/gbm/gbtree.cc, src/gbm/gbtree.h, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu
Fixes #5036.
I edited `CPUPredictor::PredictContribution` to multiply each tree's contributions by the tree's DART weight before adding them. This makes SHAP sums equal predictions, as expected. ~~The bug likely still exists for the GPU predictor and for interaction SHAPs.~~ Both non-interaction SHAPs and interaction SHAPs are affected.
This PR contains a commit from #5058 in order to get it to compile. The commit can be rebased out once #5058 is merged.
=> Use DART tree weights when computing SHAPs

doc/build.rst, python-package/xgboost/build-python.sh
The build documentation and python installation script is updated to resolve the installation issue in MacOS versions higher than High Sierra. see #4933.
=> Update python install script to fix MacOS build error (#4933).

CMakeLists.txt, src/CMakeLists.txt, src/common/observer.h
Closes #4837  Small part of https://github.com/dmlc/xgboost/pull/4732 .
=> Implement training observer.

amalgamation/xgboost-all0.cc, src/tree/param.cc, src/tree/param.h, tests/cpp/tree/test_param.cc
Small part of https://github.com/dmlc/xgboost/pull/4732 .
=> Fix parsing empty vector in parameter.

src/common/io.cc, src/common/io.h, tests/cpp/common/test_io.cc
* Add fixed size stream for reading model stream.
* Add file extension.
Another fraction of https://github.com/dmlc/xgboost/pull/4732 .  Fixed size stream is used for reading `dmlc::Stream` coming from rabit checkpoint.  While `FileExtension` is used for distinguishing what model format we should use.
=> Add IO utilities.

include/xgboost/tree_updater.h, src/tree/param.h, src/tree/split_evaluator.cc, src/tree/split_evaluator.h, src/tree/updater_basemaker-inl.h, src/tree/updater_colmaker.cc, src/tree/updater_gpu_hist.cu, src/tree/updater_prune.cc, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, src/tree/updater_refresh.cc, src/tree/updater_sync.cc, tests/cpp/tree/test_gpu_hist.cu, tests/cpp/tree/test_quantile_hist.cc
* Remove parameters in split evaluator.
Another small fraction of #4732 .
=> Implement JSON IO for updaters

doc/parameter.rst, include/xgboost/gbm.h, include/xgboost/generic_parameters.h, include/xgboost/predictor.h, src/gbm/gblinear.cc, src/gbm/gbm.cc, src/gbm/gbtree.cc, src/gbm/gbtree.h, src/learner.cc, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, src/predictor/predictor.cc, tests/cpp/gbm/test_gbtree.cc, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu, tests/python-gpu/test_gpu_training_continuation.py, tests/python-gpu/test_gpu_with_dask.py
Continues https://github.com/dmlc/xgboost/pull/5072 .  The JSON PR works out everything, but being too huge.  So continue the band-aid for rapids' release.  @RAMitchell @JohnZed 
* Define prediction cache in GBTree.
* Initialise prediction cache on first iteration.
* Save gpu_id into binary model when CUDA is enabled.
=> Hack for GPU ID config

src/tree/updater_quantile_hist.cc
It is PR №1 from the issue https://github.com/dmlc/xgboost/issues/5104.
It is required to handle performance of all functions from QuantileHistMaker::Builder class.
=> CPU optimizations - part 1: extending timer to cover UpdatePredictionCache function

src/common/group_data.h, src/data/simple_dmatrix.h, tests/cpp/common/test_group_data.cc, tests/cpp/data/test_adapter.cc, tests/cpp/data/test_simple_dmatrix.cc
This is an alternative fix to #5097, it addresses the issue of slow performance when building large files due to the group builder repeatedly creating large temporary vectors.
It adds the optional parameter of base_row_offset_, so when building incrementally, temporary thread vectors are sized relative to this instead of 0.
I used the following test (not committed) to measure performance:
```c++
TEST(SimpleDMatrix, Performance) {
std::string filename = "test.libsvm";
CreateBigTestData(filename, 100000000);
std::unique_ptr<dmlc::Parser<uint32_t>> parser(
dmlc::Parser<uint32_t>::Create(filename.c_str(), 0, 1, "auto"));
data::FileAdapter adapter(parser.get());
common::Timer t;
data::SimpleDMatrix dmat(&adapter, std::numeric_limits<float>::quiet_NaN(),
1);
t.Stop(); …
```
=> Group builder modified for incremental building

include/xgboost/data.h, src/c_api/c_api.cc, src/common/hist_util.cc, src/data/adapter.h, src/data/data.cc, src/data/simple_dmatrix.h, src/data/sparse_page_dmatrix.h, src/data/sparse_page_source.h, src/data/sparse_page_writer.h, tests/cpp/data/test_adapter.cc, tests/cpp/data/test_simple_dmatrix.cc, tests/cpp/data/test_sparse_page_dmatrix.cc
#5044 added adapters for external data and used them to construct SimpleDMatrix. This PR uses these adapters to construct SparsePageDMatrix. 
A side-effect of this is that we can now use any data type to create a SparsePageDMatrix, where previously this had to be a file. This functionality is still not exposed to end users because the only interface to activate external memory is by adding a cache prefix to a file URI. Nonetheless, we have the capability to do this in internal code if we want.
It is also possible now to set missing values for SparsePageDMatrix internal code.
=> Use adapters for SparsePageDMatrix

amalgamation/xgboost-all0.cc, include/xgboost/c_api.h, include/xgboost/gbm.h, include/xgboost/json_io.h, include/xgboost/model.h, include/xgboost/tree_model.h, src/c_api/c_api.cc, src/common/io.cc, src/gbm/gblinear.cc, src/gbm/gblinear_model.cc, src/gbm/gblinear_model.h, src/gbm/gbtree.cc, src/gbm/gbtree.h, src/gbm/gbtree_model.cc, src/gbm/gbtree_model.h, src/learner.cc, src/tree/tree_model.cc, src/tree/updater_gpu_hist.cu, src/tree/updater_sync.cc, tests/cpp/c_api/test_c_api.cc, tests/cpp/gbm/test_gblinear.cc, tests/cpp/gbm/test_gbtree.cc, tests/cpp/test_learner.cc, tests/cpp/tree/test_tree_model.cc, tests/python/test_basic_models.py
The "model" part of https://github.com/dmlc/xgboost/pull/4732.  Follow up PRs will be for "Configuration".
=> Model IO in JSON.

src/learner.cc
Found during implementing a R test.  Sorry for the oversight.
=> Quick fix for loading metric name.

doc/jvm/xgboost4j_spark_tutorial.rst, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/MissingValueHandlingSuite.scala
This pull request adds a new parameter in Spark XGBoost that allows for bypassing assertion added as part of https://github.com/dmlc/xgboost/pull/4349/files (related comment https://github.com/dmlc/xgboost/pull/4349#issuecomment-517506892)
The reason for this change is that I have my own VectorAssembler implementation that allows for creating sparse vectors where any value can be encoded as missing. I had been using this assembler to create feature vectors with NaN encoded as missing which integrated well with XGBoost (both in Spark and saving the models in binary form for use on other platforms). This change would let me continue doing that by providing this special flag, essentially its a way of addressing the "Note" section at …
=> [jvm-packages] Allow for bypassing spark missing value check

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/MissingValueHandlingSuite.scala
Scala style check enforces that all lines be shorter than 100-letters. #4805 introduced a few lines longer than 100-letters and caused the master branch to fail JVM builds.
@sriramch @CodingCat
=> [jvm-packages] Comply with scala style convention

jvm-packages/dev/Dockerfile, tests/ci_build/Dockerfile.jvm, tests/ci_build/Dockerfile.jvm_cross
CI is currently broken because the download URL for Maven 3.6.1 is broken.
cc @trams
=> [CI] [jvm-packages] Repair download URL for Maven 3.6.1

src/data/columnar.h, src/data/data.cu, src/data/simple_csr_source.cu, tests/cpp/data/test_simple_csr_source.cu
This PR changes the way we process inputs from array interface, where each column in the input may have a different type.
The current implementation processes one column at a time and dispatches templated functions. This is limiting because we cannot access more than one column at a time inside a kernel.
This PR implements dynamic type dispatching. The idea is, in future we will wrap adapters around these columns and they will be processed in batches potentially containing many columns with generic matrix construction code.
=> Use dynamic types for array interface columns instead of templates

doc/python/python_api.rst, doc/tutorials/dask.rst, python-package/xgboost/dask.py, python-package/xgboost/plotting.py
I received many questions around why the `DaskDMatrix` is slow and buggy, while most of the time `DaskDMatrix` is not the one to be blamed.  Here's some short notes for what's happening inside `DaskDMatrix`.
=> Note for `DaskDMatrix`.

python-package/xgboost/callback.py, python-package/xgboost/training.py, tests/python-gpu/test_gpu_basic_models.py, tests/python-gpu/test_gpu_interaction_constraints.py, tests/python/test_basic_models.py
It's been deprecated since we have callback.
* Set `before_iteration` to False to preserve the initial learning rate, and
comply to the term "reset".
Closes #4709.
* Test for various `tree_method`.
=> [Breaking] Remove `learning_rates`.

src/gbm/gbtree.cc, src/learner.cc, src/tree/param.h, src/tree/updater_colmaker.cc, tests/cpp/test_learner.cc
Related issue: https://github.com/dmlc/xgboost/issues/4211
Using the first option described in: https://github.com/dmlc/xgboost/issues/4211#issuecomment-568661064 
Note the parameter validation is not strict, because we have a lots of parameters packed into `TrainParam` and each tree method uses only a selected subset.  But to me this is a good starting point for future development.  The difficult part of getting it work is refactoring `approx`.
I didn't split the parameters exclusive to CPU Hist, as I think some of them are useful to GPU in the future.
=> Parameter validation

.travis.yml, CMakeLists.txt, demo/c-api/CMakeLists.txt, src/CMakeLists.txt, tests/ci_build/Dockerfile.cpu, tests/cpp/CMakeLists.txt, tests/travis/run_test.sh, tests/travis/setup.sh
Simplify logic for importing OpenMP into the CMake build by treating OpenMP as a target. We no longer have to set compiler flags; all it takes is to import target `OpenMP::OpenMP_CXX` via `target_link_libraries()`. See https://cliutils.gitlab.io/modern-cmake/chapters/packages/OpenMP.html for more information.
This will be especially useful for Mac OSX users. The old way requires them to use Homebrew GCC, which is a heavy dependency (*). The new way allows them to use Apple Clang (default system compiler) instead, provided that they install OpenMP library via Homebrew (`brew install libomp`). Furthermore, we can release XGBoost 1.0.0 on Homebrew with OpenMP enabled.
CMake version is raised to ~3.9~ 3.12 to access `OpenMP::OpenMP_CXX` target. 3.12 is needed to use `target_link_libraries()` …
=> Enable OpenMP with Apple Clang (Mac default compiler)

src/data/simple_dmatrix.cc, src/data/sparse_page_source.h, src/learner.cc, tests/cpp/data/test_sparse_page_dmatrix.cc, tests/cpp/helpers.cc, tests/python-gpu/load_pickle.py, tests/python-gpu/test_gpu_pickling.py
* Removed some data copying.
* Make sure `gpu_id` is valid before any configuration is carried out.
Closes https://github.com/dmlc/xgboost/issues/4618 .
=> Fix wrapping GPU ID.

python-package/xgboost/compat.py, python-package/xgboost/core.py, tests/python/test_with_pandas.py
pd.Int64Index.format() does  not create numeric feature_names (spaces like `" 9", "10"` are inserted) while pd.RangeIndex.format() creates numeric one.
I have fixed xgb.DMatrix to create numerical feature_names when DataFrame with Int64 columns passed.
Following code reproduces the problem.
```
import pandas
import xgboost
import numpy
data = pandas.DataFrame(
numpy.arange(100).reshape((10, 10)),
columns=range(9, 19, 1)
)
Y = pandas.DataFrame([0] * 5 + [1] * 5)
test = pandas.DataFrame(
numpy.arange(100).reshape((10, 10)),
columns=range(9, 19, 1)
)
test.columns = list(test.columns)
classifier = xgboost.XGBClassifier()
classifier.fit(data, Y)
classifier.predict(test)
```
=> fix: feature_names differ between pd.Int64Index and pd.RangeIndex

src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, tests/cpp/tree/test_quantile_hist.cc
Closes https://github.com/dmlc/xgboost/issues/3579 .
The proper fix is putting quantiles in `DMatrix`, which we have already done for GPU Hist.  See https://github.com/dmlc/xgboost/issues/5143 for related future roadmap.  This PR is a band-aid for fixing the old issue as we want a fully working 1.0 release.
=> Quick fix for memory leak in CPU Hist.

src/common/threading_utils.h, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, tests/cpp/common/test_threading_utils.cc, tests/cpp/tree/test_quantile_hist.cc
EvaluateSplit was optimized by processing many tree nodes in the same time.
Foe details look at the issue https://github.com/dmlc/xgboost/issues/5104
To implement this ParallelFor2d was introduced to support nested parallelism. This function will be used for optimizations of other functions BuildHist and ApplySplit.
In previous implementation the main source of code complexity was blocking for nested parallelism. Now common code for this was aggregated and moved in common threading utils. So, further PRs should be more light-weight.
I will provide performance numbers a bit later.
CC: @hcho3, @RAMitchell, @trivialfis
=> Optimization of EvaluateSplit function 

src/common/device_helpers.cu
The error was removed at some point, bringing it back.
=> Throw error when not compiled with NCCL.

doc/parameter.rst, include/xgboost/generic_parameters.h, python-package/xgboost/core.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py, src/learner.cc, tests/cpp/common/test_monitor.cc, tests/cpp/test_learner.cc, tests/cpp/test_serialization.cc, tests/python-gpu/test_gpu_pickling.py
Scikit-Learn passes all parameters down to XGBoost, whether they are used or
not.  See #5152  .
=> Disable parameter validation for Scikit-Learn interface.

include/xgboost/span.h
* Make sure copy constructor is used.
* Constructor for container no-longer available for device code.
=> Fix span constructor.

include/xgboost/data.h, include/xgboost/host_device_vector.h, src/common/host_device_vector.cc, src/common/host_device_vector.cu, src/predictor/gpu_predictor.cu, tests/cpp/common/test_host_device_vector.cu, tests/cpp/common/test_random.cc
* Fix #5162.
* Disable copy constructor of HostDeviceVector.  Prevents implicit copying.
=> Lazy initialization of device vector.

doc/jvm/xgboost4j_spark_tutorial.rst
Realized from looking at https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html#dealing-with-missing-values that the options were kind of hard to look at as didn't provide new lines so added them in. Not sure if better way to format this/not really sure how to preview them beforehand.
Also, hadn't really known doc changes would go live immediately, I thought would only go live once new option was available in a version
=> Add new lines for spark tutorial missing values section

include/xgboost/data.h, src/c_api/c_api.cc, src/c_api/c_api.cu, src/common/device_helpers.cuh, src/data/adapter.h, src/data/columnar.h, src/data/data.cu, src/data/device_adapter.cuh, src/data/simple_dmatrix.cu, tests/cpp/data/test_adapter.cc, tests/cpp/data/test_columnar.h, tests/cpp/data/test_device_adapter.cu, tests/cpp/data/test_simple_csr_source.cu, tests/cpp/data/test_simple_dmatrix.cu
This PR updates DMatrix creation from device memory to use adapters.
I will remove old code in a separate PR for clarity.
=> Implement cudf construction with adapters.

doc/parameter.rst, doc/tutorials/param_tuning.rst, include/xgboost/generic_parameters.h, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java, jvm-packages/xgboost4j/src/native/xgboost4j.cpp, src/common/observer.h, src/data/data.cc, src/gbm/gbtree.cc, src/learner.cc, src/tree/updater_colmaker.cc, tests/cpp/test_learner.cc, tests/python-gpu/test_gpu_pickling.py, tests/python-gpu/test_gpu_prediction.py, tests/python-gpu/test_gpu_with_sklearn.py, tests/python/test_with_sklearn.py
Some related fixes ported from https://github.com/dmlc/xgboost/pull/5178 .
* Added a check call macro in jvm package, prevents executing other functions from jvm when error occurred in XGBoost.  For example, when prediction fails jvm should not try to allocate memory based on the output prediction size.
* Update doc to recommend `hist`/`gpu_hist` algorithm.
* Add a parameter `validate_features` and enable it for `R/Python/C` except for `jvm`.
* Sync maximum number of columns in DMatrix across workers.  This also fixes empty dask cudf dataframe.
=> Enforce correct data shape.

R-package/R/utils.R, R-package/R/xgb.Booster.R, R-package/src/init.c, R-package/src/xgboost_R.cc, R-package/src/xgboost_R.h, R-package/tests/testthat/test_helpers.R, doc/tutorials/dart.rst, include/xgboost/c_api.h, include/xgboost/gbm.h, include/xgboost/learner.h, jvm-packages/xgboost4j/src/native/xgboost4j.cpp, python-package/xgboost/core.py, src/c_api/c_api.cc, src/gbm/gblinear.cc, src/gbm/gbtree.cc, src/gbm/gbtree.h, src/learner.cc, src/predictor/cpu_predictor.cc, tests/cpp/gbm/test_gbtree.cc, tests/cpp/test_learner.cc, tests/cpp/test_logging.cc, tests/python/test_basic_models.py, tests/python/test_ranking.py
This is another attempt at #3556 to avoid the issue of people forgetting to set `ntreelimit` / `ntree_limit` (or not being aware that they have to) and getting incorrect predictions under DART.
I am aware that a change like this was previously reverted (#3563) because "it breaks the logic for custom evaluation and custom objective". However, no tests seem have been added or examples provided that demonstrate this breakage, so I have no idea whether this new PR recapitulates it. What I can say is that this PR passes the test suite for the R package, including with an assignment to `ntreelimit` removed.
=> [Breaking] Don't drop trees during DART prediction by default

src/c_api/c_api.cc, src/data/adapter.h, src/data/data.cc, src/data/simple_dmatrix.cc, src/data/sparse_page_source.h, tests/cpp/data/test_adapter.cc, tests/cpp/data/test_simple_dmatrix.cc
This PR allows us to consolidate further constructions of DMatrix into a single constructor path.
=> Implement slice via adapters

src/CMakeLists.txt, tests/cpp/CMakeLists.txt
One of C++ tests contain non-ASCII letters:
https://github.com/dmlc/xgboost/blob/8cbcc53ccbd3d2c4c74ef35fcec018be64d084cd/tests/cpp/common/test_config.cc#L154-L156
Microsoft Visual C++ (MSVC) uses the system codepage by default when compiling C++ sources. This resulted in error `Error C2001: Newline in constant` when I compiled XGBoost on my Windows laptop, which had Korean (CP949) locale.
This PR explicitly sets the compilation flag `/utf-8` so that MSVC always uses UTF-8 encoding. See related discussion at https://github.com/libusb/libusb/issues/207.
=> Explicitly use UTF-8 codepage when using MSVC

R-package/R/xgboost.R, R-package/src/xgboost_R.cc, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_helpers.R, src/gbm/gbtree.cc
Closes https://github.com/dmlc/xgboost/issues/5203 .
=> Fix R dart prediction and add test.

README.md
Hi!
[Optuna]( (optuna.org) ) is a new hyperparameter optimization library, and we've written an integration module for XGBoost to make it easy to use Optuna to search for good hyperparameter settings and prune unpromising trials. We're looking for ways to let users of XGboost know this is available and thought a badge to show Optuna integration is available would be helpful.
If there are other ways you would recommend reaching out to XGBoost users to let them know about Optuna, please let us know.
Thanks!
=> Add Optuna badge to README.md

Jenkinsfile, cmake/Sanitizer.cmake, cmake/modules/FindUBSan.cmake, src/common/compressed_iterator.h, src/common/hist_util.h
This PR adds an CMake option to run UBSan (Undefined Behavior Sanitizer). It is motivated by https://news.ycombinator.com/item?id=22063849.
Also:
* Add UBSan to CI
* Fix some undefined behavior in the C++ codebase.
* Update dmlc-core, to pick up dmlc/dmlc-core#591.
This PR depends on dmlc/dmlc-core#591.
Example output:
```
/workspace/tests/cpp/common/../../../src/common/hist_util.h:40:11: runtime error: null pointer passed as argument 2, which is dec$
ared to never be null
#0 0x5607d5de33c6 in xgboost::common::SimpleArray<unsigned int>::resize(unsigned long) /workspace/src/tree/./../common/hist_u$
il.h:40
#1 0x5607d5dde9fd in xgboost::common::ColumnMatrix::Init(xgboost::common::GHistIndexMatrix const&, double) (/workspace/build/$
estxgboost+0x26b19fd)
#2 0x5607d5dd89e5 in …
```
=> Add CMake option to run Undefined Behavior Sanitizer (UBSan)

python-package/xgboost/compat.py, python-package/xgboost/core.py, src/c_api/c_api.cc, src/c_api/c_api.cu, src/data/array_interface.h, src/data/data.cu, src/data/device_adapter.cuh, src/data/simple_csr_source.cc, src/data/simple_dmatrix.cu, tests/ci_build/Dockerfile.cudf, tests/ci_build/test_python.sh, tests/cpp/data/test_array_interface.h, tests/cpp/data/test_device_adapter.cu, tests/cpp/data/test_metainfo.cu, tests/cpp/data/test_simple_dmatrix.cu, tests/python-gpu/test_from_columnar.py, tests/python-gpu/test_from_cupy.py, tests/python/testing.py, tests/travis/run_test.sh
A few things left to do:
@trivialfis I removed the check for array interface version as I found I could get version 0 by installing cupy from conda or 2 by installing from pip, but not 1. Does this break anything for cudf?
=> Support dmatrix construction from cupy array

tests/python-gpu/test_from_columnar.py
These tests failed after upgrading cudf to 0.12. Turns out they were probably silently failing before as unsigned integers were never supported in cudf.
=> uint not supported in cudf

python-package/xgboost/core.py, python-package/xgboost/dask.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py, tests/python/test_early_stopping.py, tests/python/test_with_sklearn.py
PR started as: https://github.com/dmlc/xgboost/issues/5100
Summary (edited):
- main point is refactoring of `get_params` in `XGBModel` thats allow less repetition in `__init__` of children classes like XGBClassifier (MixIn was not required, it was based on https://stackoverflow.com/questions/59248211) and now is more clear which parameters defaults values are directly inherited
- I've deleted in `get_params` in `XGBModel` two lines that were giving me error in my issue:
` if params['missing'] is np.nan:`      
`     params['missing'] = None  # sklearn doesn't handle nan. see #4725)`
tests are passing, so either there is no specific test-case, or everything is correct ;-)
- in original default for `n_jobs` in `XGBRanker` is `-1` (accidental inconsistency?)
- `XGBRegressor` now has its own …
=> [Breaking] Remove Scikit-Learn default parameters

include/xgboost/data.h, include/xgboost/host_device_vector.h, src/c_api/c_api.cc, src/data/data.cc, tests/cpp/data/test_metainfo.cc
This PR implements a brand-new way to serialize DMatrix::MetaInfo into a binary stream. See discussion for new binary format in #4956. The idea is to add a header consisting of field names as well as byte offsets. The header makes it easy to add a new field over time.
The layout of the file is as follows:
* Header
- Name of field 0, Byte offset of field 0
- Name of field 1, Byte offset of field 1
- ...
* Data
- Byte representation of field 0
- Byte representation of field 1
- ...
**Assumptions**
* We assume that fields are added and never removed (unless we bump up the major version). The order of existing fields does not change. (So Field 0 will always correspond to `num_row`, Field 3 to `labels`, and so forth.) New fields are appended at the end of the list. Currently, we have 7 fields: …
=> Extensible binary serialization format for DMatrix::MetaInfo

tests/python-gpu/test_from_columnar.py, tests/python-gpu/test_from_cupy.py
We observed an intermittent test failure, with a small difference and accuracy between two subsequent training calls.
This PR makes random numbers consistent, prevents weights from getting close to 0 and enforces a single thread.
=> Make some GPU tests deterministic

Makefile, R-package/configure, R-package/configure.ac, R-package/src/Makevars.in
CMake doesn't appear to be a well accepted alternative in the R ecosystem, in particular CRAN. Without CMake, detecting endianness has been a hairy endeavor:
```cpp
#if defined(__APPLE__) || defined(_WIN32)
#define DMLC_LITTLE_ENDIAN 1
#elif defined(__GLIBC__) || defined(__GNU_LIBRARY__) \
|| defined(__ANDROID__) || defined(__RISCV__)
#include <endian.h>
#define DMLC_LITTLE_ENDIAN (__BYTE_ORDER == __LITTLE_ENDIAN)
#elif defined(__FreeBSD__) || defined(__OpenBSD__)
#include <sys/endian.h>
#define DMLC_LITTLE_ENDIAN (_BYTE_ORDER == _LITTLE_ENDIAN)
#elif defined(__EMSCRIPTEN__) || defined(__hexagon__)
#define DMLC_LITTLE_ENDIAN 1
#elif defined(__sun) || defined(sun)
#include <sys/isa_defs.h>
#if defined(_LITTLE_ENDIAN)
#define DMLC_LITTLE_ENDIAN 1
#else
#define DMLC_LITTLE_ENDIAN 0
#endif …
```
=> [R] Robust endian detection in CRAN xgboost build

src/common/json.cc, src/common/timer.cc
* `exp10` is a GNU extension and is missing on FreeBSD. Add `__FreeBSD__` guard to disable use of `exp10`. In the long run, we may want to add a feature testing for `exp10` to the build system.
* `std::chrono::duration_cast<...>.count()` implementation returns `long long` type, which `JsonInteger` does not accept. Explicitly cast the result into `int64_t`.
Depends on https://github.com/dmlc/rabit/pull/133.
Closes https://github.com/dmlc/xgboost/issues/5117.
=> Support FreeBSD

Makefile, R-package/configure, R-package/configure.ac, R-package/src/Makevars.in, doc/build.rst
Follow-up to #5232. This PR uses Autoconf to detect the availability of OpenMP library (`libomp`) on Mac OSX. This is done by compiling the following program with command `${CC} -o conftest conftest.c /usr/local/lib/libomp.dylib -Xclang -fopenmp`:
```c
/* conftest.c */
#include <omp.h>
int main(void) {
return (omp_get_max_threads() <= 1);
// returns 0 when there's only one thread
// returns 1 when there's more than one thread
}
```
**Implication: Now Mac users can simply run `install.packages('xgboost')` and enjoy the performance of multiple threads,** as long as they first install `libomp` package from Homebrew. 
I tested this change as follows:
* I ran `R CMD INSTALL .` on my Macbook Pro. A sample XGBoost training job runs with all 4 threads:
```r
library(xgboost)
data(agaricus.train, …
```
=> [R] Enable OpenMP with AppleClang in XGBoost R package

.travis.yml, Makefile, doc/build.rst, python-package/xgboost/build-python.sh, tests/travis/run_test.sh, tests/travis/setup.sh
This PR makes a few fixes so that users can install Python XGBoost from a source tarball `xgboost-1.0.0-SNAPSHOT.tar.gz`. This is important for users of Mac OSX, FreeBSD, and other platforms where we do not offer pre-built wheels.
Note that #5146 enabled the use of AppleClang (default compiler on OSX), so we no longer require Homebrew GCC. Thus, we can simplify the installation doc considerably.
How to test:
```bash
make pippack 
pip3 install xgboost-1.0.0-SNAPSHOT.tar.gz --user
```
=> Make `pip install xgboost*.tar.gz` work by fixing build-python.sh

src/common/hist_util.cc, src/common/hist_util.h, src/common/threading_utils.h, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, tests/cpp/common/test_hist_util.cc, tests/cpp/common/test_threading_utils.cc, tests/cpp/tree/test_quantile_hist.cc
Optimizations for Histogram building. A part of the issue #5104
The PR contains changes from #5138, it will be rebased after #5138 merging.
=> Optimized BuildHist function

include/xgboost/model.h, src/c_api/c_api.cc, src/data/adapter.h, tests/cpp/common/test_hist_util.cc, tests/cpp/common/test_threading_utils.cc, tests/cpp/data/test_adapter.cc, tests/cpp/data/test_simple_dmatrix.cc, tests/cpp/data/test_sparse_page_dmatrix.cc
From clang-tidy-9 and gcc-7: Invalid case style, narrowing definition, wrong
initialization order, unused variables.
=> Cleanup warnings.

src/common/observer.h, src/common/timer.cc
R packages cannot use `std::cout` for printing, per CRAN policy.
```
* checking compiled code ... NOTE
File ‘xgboost/libs/xgboost.so’:
Found ‘_ZSt4cout’, possibly from ‘std::cout’ (C++)
Object: ‘./amalgamation/xgboost-all0.o’
Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs.
See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
```
* `src/common/timer.cc`: Replace `std::cout` with `LOG(CONSOLE)`.
* `src/common/observer.h`: Replace `std::cout` with `LOG(INFO)` (only when `XGBOOST_STRICT_R_MODE` macro is active).
=> Remove use of std::cout from R package

python-package/setup.py
=> Fix CMake + MSVC build with setuptools.

include/xgboost/learner.h, src/c_api/c_api.cc, src/cli_main.cc, src/common/device_helpers.cuh, src/common/observer.h, src/gbm/gblinear.cc, src/learner.cc, tests/cpp/c_api/test_c_api.cc, tests/cpp/gbm/test_gbtree.cc, tests/cpp/test_learner.cc, tests/cpp/test_serialization.cc, tests/cpp/tree/test_gpu_hist.cu
Extracted from https://github.com/dmlc/xgboost/pull/5220 .
=> Pass shared pointer instead of raw pointer to Learner.

src/common/hist_util.cc, src/common/hist_util.cu, src/common/hist_util.h, tests/cpp/common/test_hist_util.cc, tests/cpp/common/test_hist_util.h, tests/cpp/helpers.cc, tests/cpp/tree/test_gpu_hist.cu, tests/python-gpu/test_gpu_updaters.py, tests/python/regression_test_utilities.py, tests/python/test_linear.py
This PR is for adding more tests for quantile generation in hist/gpu_hist. Part of the motivation is to create some absolute tests of accuracy for GPU sketching, instead of comparing against existing CPU algorithms.
So far I have tested the following expected behaviours with respect to a single feature:
- The histogram cut `min_value` should be less than all inputs
- The last histogram cut value should be greater than all inputs
- The rank of quantile cuts from the sketch should not exceed error ~0.01 as compared to rank from sorted values
- And input of k < num_bins unique values should output k unique bins. i.e. it should be possible to split over each unique value
I also expected that number of cuts (excluding the minimum value) should equal the number of bins requested if the unique …
=> Testing hist_util

include/xgboost/gbm.h, include/xgboost/predictor.h, include/xgboost/tree_model.h, src/c_api/c_api.cc, src/gbm/gblinear.cc, src/gbm/gblinear_model.h, src/gbm/gbm.cc, src/gbm/gbtree.cc, src/gbm/gbtree.h, src/learner.cc, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, src/predictor/predictor.cc, tests/cpp/gbm/test_gbtree.cc, tests/cpp/helpers.cc, tests/cpp/helpers.h, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/predictor/test_predictor.cc, tests/python/test_basic.py
* Remove duplicated cache in Learner and GBM.
* Remove ad-hoc fix of invalid cache.
* Remove `PredictFromCache` in predictors.
* Remove prediction cache for linear altogether, as it's only moving the prediction into training process but doesn't provide any actual overall speed gain.
* The cache is now unique to Learner, which means the ownership is no longer shared by any other components.
* Add version to prediction cache.
* Use weak ptr to check expired DMatrix.
* Pass shared pointer instead of raw pointer.
Before the DMatrix is tied to Booster with a shared pointer, which means the access to it is always safe as it can't expire before the booster.  Now we need to make sure the safety ourselves.
As now we don't store the shared pointer any more,  this should reduce the memory usage when …
=> Move prediction cache to Learner.

python-package/setup.py
Closes https://github.com/dmlc/xgboost/issues/5309
@victornoel Thanks for raising the issue.
=> Use `scikit-learn` in extra dependencies.

src/common/hist_util.cc, src/common/hist_util.cu, src/common/hist_util.h, src/common/quantile.h
This PR bounds the size of sketch data structures when the number of rows is small. Previously, training on even a single row requires allocating >4096 cut samples per feature. Benchmark performance results below, training on 10 rows
=> Wide dataset quantile performance improvement

include/xgboost/c_api.h, include/xgboost/gbm.h, include/xgboost/generic_parameters.h, include/xgboost/json.h, include/xgboost/learner.h, include/xgboost/metric.h, include/xgboost/parameter.h, include/xgboost/predictor.h, include/xgboost/tree_updater.h, src/common/hist_util.h, src/common/transform.h, src/gbm/gbtree.cc, src/gbm/gbtree.h, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, tests/cpp/common/test_hist_util.h
Move this function into gbtree, and uses only updater for doing so.  As now the predictor knows exactly how many trees to predict, there's no need for it to update the prediction cache.
- Remove update prediction cache from predictors and update the cache in gbtree.
- Move `GetPredictor` into a CC file.
This is part of on going work to enable prediction from `EllpackDMatrix`.
=> Remove update prediction cache from predictors.

jvm-packages/xgboost4j/src/native/xgboost4j.cpp
* Add a check call macro in jvm package, prevents executing other functions
from jvm when error occurred in XGBoost. For example, when prediction fails jvm
should not try to allocate memory based on the output prediction size.
=> [jvm-packages] Add JVM_CHECK_CALL.

src/data/ellpack_page_source.cu, src/data/sparse_page_dmatrix.cc, src/data/sparse_page_dmatrix.h, src/data/sparse_page_source.h, tests/cpp/data/test_sparse_page_dmatrix.cc
This refactoring separates out many of the components used in the external memory dmatrix. In particular the prefetching and management of pages is extracted into `ExternalMemoryPrefetcher<T>` and different external memory page types all have their own constructors now.
Part of the reason for doing this is to manage the lifetime of the cache files and remove them when the DMatrix gets destructed. Discussion about this in #4237. Leaving behind cache files leads to many unpredictable and unwanted behaviours, for example if I train the first time using 10% of my data, then train a second time using 100% but do not change the cache prefix, the 10% data will get loaded and used, completely ignoring the training input from the second run.
=> Refactor SparsePageSource, delete cache files after use

Jenkinsfile, python-package/xgboost/__init__.py, python-package/xgboost/sklearn.py, tests/ci_build/Dockerfile.cpu, tests/ci_build/test_python.sh
Closes #5328. Also add Python 3.5 to CI so that f-string does not get accidentally added to the codebase again.
I will need to make a patch and create 1.0.1 patch release.
Aside: Dask now requites Python 3.6+, so I do not run Dask integration tests with Python 3.5.
=> Remove f-string, since it's not supported by Python 3.5

doc/parameter.rst, doc/tutorials/external_memory.rst
Last bit for #4357 
@RAMitchell @trivialfis
=> update docs for gpu external memory

python-package/xgboost/training.py, tests/python/test_with_sklearn.py
Closes #5340. The typo was introduced in #5130 and causes crash only when the user supplies multiple evaluation metrics in `eval_metric`.
=> Fix a small typo in sklearn.py that broke multiple eval metrics

include/xgboost/data.h, include/xgboost/tree_model.h, src/data/ellpack_page.cu, src/data/ellpack_page.cuh, src/data/simple_dmatrix.cc, src/data/simple_dmatrix.h, src/data/sparse_page_dmatrix.cc, src/data/sparse_page_dmatrix.h, src/predictor/gpu_predictor.cu, src/tree/tree_model.cc, src/tree/updater_gpu_hist.cu, src/tree/updater_refresh.cc, tests/cpp/data/test_ellpack_page.cu, tests/cpp/data/test_sparse_page_dmatrix.cu, tests/cpp/helpers.h, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/predictor/test_predictor.cc, tests/cpp/predictor/test_predictor.h, tests/python/regression_test_utilities.py
* Unify GPU prediction node.
* Add `PageExists`.
* Dispatch prediction on input data.
Extracted from #5319 .  CPU version might not be coming very soon.  I'm having trouble in understanding the Column matrix.
Moving the conversation in https://github.com/dmlc/xgboost/pull/5319#issuecomment-588515939 to here.
=> Predict on Ellpack.

include/xgboost/data.h, src/data/simple_dmatrix.cc, src/data/simple_dmatrix.h, src/data/sparse_page_dmatrix.cc, src/data/sparse_page_dmatrix.h, src/gbm/gbtree.cc, src/linear/updater_gpu_coordinate.cu, src/tree/updater_colmaker.cc, tests/cpp/data/test_simple_dmatrix.cc, tests/cpp/data/test_sparse_page_dmatrix.cc, tests/cpp/test_learner.cc
Two methods are removed that do not provide broadly useful functionality:
DMatrix::GetColumnDensity
DMatrix::SingleColumnBlock
Column density is only needed by the exact algorithm, so I compute it in the updater itself. Single column block can be established by other means.
=> Remove unnecessary DMatrix methods

include/xgboost/tree_model.h, src/tree/param.h, src/tree/updater_prune.cc, tests/cpp/tree/test_prune.cc, tests/python/test_updaters.py
* Honor the tree depth.
* Prevent pruning pruned node.
Closes #5297
Note that `leaf_child_cnt` is no longer used in XGBoost.
=> Fix pruner.

include/xgboost/c_api.h, jvm-packages/xgboost4j/src/native/xgboost4j.cpp, src/c_api/c_api.cc, src/common/group_data.h, src/data/adapter.h, src/data/data.cc, src/data/simple_dmatrix.cc, src/objective/regression_obj.cu, tests/cpp/data/test_adapter.cc, tests/cpp/data/test_simple_dmatrix.cc, tests/cpp/data/test_sparse_page_dmatrix.cc
This helps mitigating imputing sparse dataset from JVM package, where some columns might be completely missing.  @wbo4958 will submit a follow up PR on JVM side.
For consistency and simplicity, `NativeDataIter` is turned into an adapter.
As a new data field is added, we break the ABI.
=> Add number of columns to native data iterator.

python-package/xgboost/core.py, tests/python/test_basic_models.py
Closes #5356.
Originally I removed it in the hope of having consistency and prevent confusion.  Buffer are only for memory snapshot.  This PR restores the ability of loading model from buffer so that we can have one less breaking change. For future plan, we should try to merge `save_raw` and `save_model`.
=> Restore loading model from buffer.
