python-package/xgboost/compat.py, python-package/xgboost/core.py, tests/python/test_basic.py, tests/python/testing.py
I replaced explicit import for datatable with simple string.  The trick should also work with other packages.  But I'm keeping this PR to be minimum so that others can raise concerns around the new compatibility check.
Should close https://github.com/dmlc/xgboost/issues/5363 .  @brydag Could you please try this patch?  I can't reproduce it as there are some specific libraries in your dependencies that are using `sys.__stdin__`.
@RAMitchell  Just tried importing dask + datatable, it seems they still don't play well with each others.  But I don't think XGBoost is a good place to workaround the limitation.
@hcho3
=> Use type name for data type check.

src/common/device_helpers.cuh, src/objective/rank_obj.cu, tests/cpp/objective/test_ranking_obj_gpu.cu, tests/cpp/tree/gpu_hist/test_gradient_based_sampler.cu
- this is the first of a handful of pr's that splits the larger pr #5326
- it moves this facility to common (from ranking objective class), so that it can be
used for metric computation
- it wraps all the bald device pointers into span
- it uses the device caching allocator where applicable
@RAMitchell @trivialfis @rongou - please review
there is no functionality change besides what has been explicitly called out.
i'll next create a pr for the cpu side metric changes
=> - move segment sorter to common

src/metric/metric_common.h, src/metric/rank_metric.cc, tests/cpp/helpers.cc, tests/cpp/helpers.h, tests/cpp/metric/test_rank_metric.cc
- auc/aucpr ranking metric accelerated on cpu
- fixes to the auc/aucpr metrics
it may help if you view the changes by ignoring the whitespace changes. 
next, i'll create a pr for a gpu metric registry to decouple the cpu and gpu implementations
@RAMitchell @trivialfis @rongou - please review
=> fixes and changes to the ranking metrics computed on cpu

doc/parameter.rst, include/xgboost/base.h, python-package/xgboost/core.py, python-package/xgboost/plotting.py, src/common/observer.h, src/data/ellpack_page_source.cc, src/learner.cc, src/tree/gpu_hist/gradient_based_sampler.cuh, src/tree/gpu_hist/histogram.cu, src/tree/gpu_hist/histogram.cuh, src/tree/updater_gpu_common.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/common/test_gpu_hist_util.cu, tests/cpp/helpers.h, tests/cpp/test_serialization.cc, tests/cpp/tree/gpu_hist/test_histogram.cu, tests/cpp/tree/test_gpu_hist.cu, tests/python-gpu/test_gpu_basic_models.py
* Use pre-rounding based method to obtain reproducible floating point
summation.
* This makes GPU Hist more stable but not yet fully reproducible.
=> POC implementation of deterministic GPU histogram.

src/metric/metric.cc, src/metric/metric_common.h, src/metric/rank_metric.cc
- if this approach is palatable, this can be rolled to other areas as well
- the objective is to separate the cpu and gpu implementations (where they digress significantly) such that they evolve independently. to that end, this approach will:
- preserve the same metrics configuration (from the end user perspective)
- internally delegate the responsibility to the gpu metrics builder when there is a
valid device present
- decouple the gpu metrics builder from the cpu ones to prevent misuse (thus not impacting other areas of the code). the locality of gpu reference is strictly within the metric builders registered with the metric registry 
- move away from including the cuda file from within the cc file and segregate the code
via ifdef's
next, i'll create a pr for the ranking metric …
=> - create a gpu metrics (internal) registry

src/common/compressed_iterator.h, src/common/hist_util.cc, src/common/hist_util.h, src/common/host_device_vector.cu, src/data/ellpack_page.cc, src/data/ellpack_page.cu, src/data/ellpack_page.cuh, src/data/ellpack_page_raw_format.cu, src/data/ellpack_page_source.cc, src/data/ellpack_page_source.cu, src/data/ellpack_page_source.h, src/data/sparse_page_dmatrix.cc, src/predictor/gpu_predictor.cu, src/tree/gpu_hist/gradient_based_sampler.cu, src/tree/gpu_hist/histogram.cu, src/tree/gpu_hist/histogram.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/data/test_ellpack_page.cu, tests/cpp/data/test_sparse_page_dmatrix.cu, tests/cpp/helpers.h, tests/cpp/tree/gpu_hist/test_gradient_based_sampler.cu, tests/cpp/tree/gpu_hist/test_histogram.cu, tests/cpp/tree/test_gpu_hist.cu
This PR tries to resolve a few issues with EllpackPage to allow some new features in future.
- Remove dependency between external objects (e.g. EllpackPageSource) and EllpackPage. Previously the memory for histogram cuts would be stored in some other object. This is dangerous and breaks encapsulation. Proposed design keeps a set of histogram cuts inside EllpackPage so the object is self-sufficient. This does require us to serialise and deserialise cuts for external memory, some performance testing is needed.
- HistogramCuts now uses HostDeviceVector for storage. This lets me use it in EllpackPage for storing the cuts.
- Remove the ability to half construct EllpackPage. Previously it was very easy to incorrectly construct this object, resulting in crashes. Now this mostly happens via safe …
=> Partial rewrite EllpackPage

src/learner.cc
This PR splits up `LearnerImpl` into 3 different components.  Starting from basic configuration to model IO and lastly the actual learner that performs training/prediction .  This is an attempt to modularize it so we can shrink it down in the future.
For instance, some configurations are no longer needed in current state of XGBoost, like the objective function configuration should be simplified.  Binary model IO is really difficult to work with and should be reduced to absolute minimum.  This PR splits the monolithic `LearnerImpl` so we can look into individual group of features more easily.
=> Split up `LearnerImpl`.

python-package/xgboost/dask.py
In this PR I am fixing #5412:
I added the `verbose` parameter in the same way that the non-dask sklearn wrapper fit-method has the same parameter and passing it through to `verbose_eval` of the `train`-function. 
I also set the default to `True` which mirrors the non-dask sklearn wrapper settings.
=> [dask] passed through verbose for dask fit

include/xgboost/data.h, src/common/device_helpers.cuh, src/common/hist_util.cu, src/common/hist_util.h, src/data/ellpack_page.cu, src/data/ellpack_page_source.cu, src/tree/updater_gpu_hist.cu, tests/cpp/common/test_hist_util.cu, tests/cpp/data/test_ellpack_page.cu, tests/cpp/data/test_sparse_page_dmatrix.cu, tests/cpp/tree/gpu_hist/test_gradient_based_sampler.cu, tests/cpp/tree/gpu_hist/test_histogram.cu, tests/cpp/tree/test_gpu_hist.cu
This PR resolves a bug where for large datasets it was possible to exceed device memory from sketching.
I added explicit tests for memory usage of sketching and smart batch size calculation able to use 80% of the available memory.
@sriramch can you please verify.
=> Fix memory usage of device sketching

src/gbm/gbtree.cc
Closes https://github.com/dmlc/xgboost/issues/4700, specifically https://github.com/dmlc/xgboost/issues/4700#issuecomment-599041332 by @kevinkvothe .
Early stopping could reduce the number of built trees in training.  So using the same `boost_rounds` for updating might result in error.
=> Better error message for updating.

python-package/xgboost/dask.py
Used to make better logging in rabit.  Without this parameter, it would be:
```
task NULL got new rank 0
```
=> [dask] Use `DMLC_TASK_ID`.

demo/dask/cpu_training.py, python-package/xgboost/dask.py, tests/python/test_with_dask.py
This PR tries to preserve the ordering of data parts in `DaskDMatrix`, which is necessary for prediction.
=> [dask] Order the prediction result.

demo/dask/cpu_training.py, demo/dask/gpu_training.py, doc/tutorials/dask.rst, python-package/xgboost/dask.py, tests/python/test_with_dask.py
Check `nthreads` from dask worker.  This parameter can be set by:
``` python
with LocalCluster(n_workers=7, threads_per_worker=1) as cluster:
```
or similar command line argument of `dask-worker`.
=> [dask] Honor `nthreads` from dask worker.

python-package/xgboost/dask.py
`nthread` can be restored from internal parameter in skl interface, which is mis-interpreted as
user defined parameter.
=> [dask] Check non-equal when setting threads.

python-package/xgboost/dask.py, tests/python/test_with_dask.py
* Returns a series when input is dataframe.
Related: https://github.com/dmlc/xgboost/issues/5425
=> [dask] Accept other inputs for prediction.

cmake/modules/FindLibR.cmake
I've been using this project's `FindLibR.cmake` as a reference, and noticed something that I think could be improved.
According to the [cmake docs](https://cmake.org/cmake/help/v3.12/command/find_program.html):
> This command is used to find a program. A cache entry named by <VAR> is created to store the result of this command. If the program is found the result is stored in the variable and the search will not be repeated unless the variable is cleared. If nothing is found, the result will be <VAR>-NOTFOUND, and the search will be attempted again the next time find_program is invoked with the same variable.
As far as I can tell right now, this script's uses of `find_program()` for `gendef` and `dlltool` isn't taking advantage of that caching, and is repeating the search for those …
=> [R-package] changed FindLibR to take advantage of CMake cache

python-package/xgboost/core.py, tests/python/test_with_pandas.py
Closes https://github.com/dmlc/xgboost/issues/4648 .
=> Support pandas SparseArray.

R-package/R/utils.R
In this PR, I'd like to propose a minor change in the R package. I found two passes where `typeof(x) == 'list` or `typeof(x) != 'list'` is being used to check that something is a list.
This check isn't totally safe, since `data.table` or `data.frame` objects will pass this check.
>  typeof(data.frame())
> > [1] "list"
>
> typeof(data.table::data.table())
> > [1] "list"
>
In this PR, I propose changing to a stricter check, `identical(class(x)) == 'list'`.
Thanks for your time and consideration!
=> [R-package] fixed uses of class()

plugin/updater_gpu/README.md
There is a broken URL to GPU algorithms in this paper:
Mitchell, R., & Frank, E. (2017). Accelerating the XGBoost algorithm using GPU computing. PeerJ Computer Science, 3, e127.
=> Add link to GPU documentation

src/common/compressed_iterator.h
This forces allocated buffer for compressed iterator to be 4 bytes aligned to meet the requirement of `atomicOr`, which operates  on `unsigned int` instead of bytes.  Normally this is a non-issue as `cudaMalloc` has larger alignment size, but it breaks `cuda-memcheck` as we are actually writing out of boundary.
Related: https://github.com/dmlc/xgboost/issues/4239
=> Force compressed buffer to be 4 bytes aligned.

tests/cpp/c_api/test_c_api.cc, tests/cpp/common/test_column_matrix.cc, tests/cpp/common/test_hist_util.cc, tests/cpp/common/test_hist_util.h, tests/cpp/data/test_adapter.cc, tests/cpp/data/test_ellpack_page.cu, tests/cpp/data/test_simple_dmatrix.cc, tests/cpp/gbm/test_gbtree.cc, tests/cpp/helpers.cc, tests/cpp/helpers.h, tests/cpp/linear/test_linear.cc, tests/cpp/linear/test_linear.cu, tests/cpp/objective/test_regression_obj.cc, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/predictor/test_predictor.cc, tests/cpp/predictor/test_predictor.h, tests/cpp/test_helpers.cc, tests/cpp/test_learner.cc, tests/cpp/test_serialization.cc, tests/cpp/tree/gpu_hist/test_histogram.cu, tests/cpp/tree/test_gpu_hist.cu, tests/cpp/tree/test_histmaker.cc, tests/cpp/tree/test_prune.cc, tests/cpp/tree/test_quantile_hist.cc, tests/cpp/tree/test_refresh.cc
Extracted from #5389 .
Currently the generator replaces only the `CreateDMatrix` function.  But for longer term, we need to generate more data types as we are adding inplace operations (like the quantile dmatrix).   As a bonus we don't need to handle pointer to shared pointer anymore.
=> Refactor tests with data generator.

python-package/xgboost/__init__.py, python-package/xgboost/core.py, src/c_api/c_api.cu, src/common/compressed_iterator.h, src/common/device_helpers.cuh, src/common/hist_util.cu, src/common/hist_util.h, src/data/data.cu, src/data/device_adapter.cuh, src/data/device_dmatrix.cu, src/data/device_dmatrix.h, src/data/ellpack_page.cc, src/data/ellpack_page.cu, src/data/ellpack_page.cuh, src/data/simple_dmatrix.cu, src/gbm/gbtree.cc, src/tree/gpu_hist/gradient_based_sampler.cu, tests/ci_build/test_python.sh, tests/cpp/common/test_hist_util.cu, tests/cpp/data/test_device_dmatrix.cu, tests/python-gpu/test_from_columnar.py, tests/python-gpu/test_from_cudf.py, tests/python-gpu/test_from_cupy.py, tests/python-gpu/test_gpu_updaters.py, tests/python/regression_test_utilities.py
This is a proof of concept for a DMatrix class that only contains an EllPack page and may be created efficiently from cupy/cudf inputs. See #5143 for roadmap.
Issues to be resolved:
- The DeviceDMatrix currently has no way to get the parameter `max_bin` so is fixed on 256 bins. 
- I directly exposed the DMatrix class in python. Not sure if this is necessary or the best way to do things.
- 2 new C API functions are added. Again not sure if this is the best approach or we should pass parameters into existing functions to select DMatrix type.
=> Device dmatrix

cmake/modules/FindLibR.cmake
In this PR, I want to propose cleaning up an inconsistency in `FindLibR.cmake` to make installation of the R package more reliable.
I think that the searches for `LIBR_INCLUDE_DIRS` and `LIBR_LIB_DIR` should use `--vanilla`  to ignore any `.Rprofile` files and the calling environment. This will reduce the chance that a user's particular R setup could cause failures in these calls.
Thanks for your consideration!
=> [R-package] fixed inconsistency in R -e calls in FindLibR.cmake

include/xgboost/gbm.h, include/xgboost/learner.h, include/xgboost/predictor.h, python-package/setup.py, python-package/xgboost/core.py, python-package/xgboost/dask.py, src/c_api/c_api.cc, src/c_api/c_api.cu, src/data/device_adapter.cuh, src/data/simple_dmatrix.cu, src/gbm/gbtree.h, src/learner.cc, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, src/predictor/predictor.cc, tests/cpp/helpers.cc, tests/cpp/helpers.h, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/predictor/test_predictor.cc, tests/cpp/predictor/test_predictor.h, tests/python-gpu/test_gpu_prediction.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_predict.py, tests/python/test_with_dask.py
* Implementation for numpy, csr, cudf and cupy.
* Tie thread local to Learner. (merged)
* A placeholder for cache id.
Related: https://github.com/dmlc/xgboost/issues/5339 https://github.com/dmlc/xgboost/issues/5207
~Currently `ntree_limit` is not supported, nor `tree_begin`.  I can add these additional parameters, but it feels more  interesting if we can have a  method to "slice" the model somehow.~
The prediction type is specified as a string, and only normal prediction is supported.  I can change it to using explicit parameter with bits like `predict` function.  I just thought maybe string is cleaner.
Lastly, the C API has a lots of parameters as it has to accept most of the parameters from DMatrix and prediction.
=> Thread safe, inplace prediction.

include/xgboost/span.h, tests/cpp/common/test_span.cc, tests/cpp/common/test_transform_range.cc
Related: #5461
From my bench having span check is about 10% slower with higgs dataset (a dense dataset is be good enough for this case)  running https://github.com/NVIDIA/gbm-bench .  This PR drops it to 5% while still keeping the possibility of printing out error message.
I still want to keep the check as there are always surprises in real world.
=> Reduce span check overhead.

src/common/common.h, src/common/compressed_iterator.h, src/common/hist_util.h, src/common/quantile.h, src/data/data.cc, src/data/simple_dmatrix.h, src/data/sparse_page_dmatrix.h, tests/cpp/common/test_hist_util.cc, tests/cpp/data/test_simple_dmatrix.cc
* Set default dtor for SimpleDMatrix to initialize default copy ctor, which is
deleted due to unique ptr.
* Remove commented code.
* Remove warning for calling host function (std::max).  Fix  #5462  .
* Remove warning for initialization order.
* Remove warning for unused variables.
=> Prevent copying SimpleDMatrix.

python-package/xgboost/core.py, python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
Closes: #5471
Note that the current form of validation is still not precise due to our monolithic `TrainParam` for tree updater.
=> Enable parameter validation for skl.

tests/cpp/data/test_ellpack_page.cu, tests/cpp/helpers.h, tests/cpp/histogram_helpers.h, tests/cpp/tree/test_gpu_hist.cu
Extracted from #5460 .
This PR splits ellpack page construction into a different header.  As including histogram related header in `helpers.h` includes a lots of file.  Any of them is changed all tests have to be recompiled.
=> Split up test helpers header.

include/xgboost/host_device_vector.h, tests/cpp/common/test_host_device_vector.cu
=> Implement host span.

src/tree/param.h
=> Accept other gradient types for split entry.

include/xgboost/learner.h, src/c_api/c_api.cc, src/learner.cc
The error shows up by running `demo/regression`, mentioned by a user contacting me via mail.
This forces `Configure` in `DumpModel`, as a result, this function is no-longer const.
=> Fix cli dump model.

doc/gpu/index.rst
@rongou @sriramch please review briefly. @rongou you might consider adding some documentation for your external memory features with some code examples in `xgboost/demo/gpu_acceleration` and a link on the main GPU documentation page. I will leave that up to you.
=> Small updates to GPU documentation

doc/tutorials/aft_survival_analysis.rst
Adding R example to the AFT tutorial, as survival analysis is well used in statistics field, and many statisticians like to use R.
=> Add R code to AFT tutorial

R-package/R/xgb.cv.R
Corrected spelling in `xgb.cv.R`. 
I'd be happy to rebuild the documentation... but I'm having issues.
Are `roxygen2::roxygenise()` or `devtools::document()` used? Both fail with the following:
```
xgboost_R.cc:2:10:fatal error: logging.h: No such file or directory
#include <dmlc/logging.h>
^~~~~~~~~~~~~~~~
compilation terminated.
/usr/lib/R/etc/Makeconf:175: recipe for target 'xgboost_R.o' failed
make: *** [xgboost_R.o] Error 1
ERROR: compilation failed for package `xgboost`
```
I tried the `make html` from the doc folder, but I get the perplexing:
```
sphinx-build -b html -d _build/doctrees   . _build/html
File "/usr/bin/sphinx-build", line 14, in <module>
from sphinx import main
ImportError: cannot import name 'main'
Makefile:55: recipe for target …
```
=> corrected spelling of 'list'

doc/tutorials/kubernetes.rst
* Various edits
* Removed "Work in progress" section as it will be tracked on xgboost-operator repo
* Added "Support" section to redirect issues to xgboost-operator repo
=> Edits on tutorial for XGBoost job on Kubernetes

doc/gpu/index.rst
@RAMitchell @hcho3 @trivialfis
=> add reference to gpu external memory

src/common/quantile.h
This is a fix to issue #5492 .
=> Fix out-of-bound array access in WQSummary::SetPrune()

include/xgboost/generic_parameters.h, jvm-packages/xgboost4j-flink/src/main/scala/ml/dmlc/xgboost4j/scala/flink/XGBoost.scala, jvm-packages/xgboost4j-flink/src/main/scala/ml/dmlc/xgboost4j/scala/flink/XGBoostModel.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/DataUtils.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/FeatureSizeValidatingSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/PersistenceSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/TrainTestData.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifierSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRabitRegressionSuite.scala, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/DataBatch.java, jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/LabeledPoint.scala, jvm-packages/xgboost4j/src/native/xgboost4j.cpp, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/DMatrixTest.java, src/data/simple_dmatrix.cc, src/learner.cc
add feature size for LabelPoint and DataBatch and pass it to xgboost native
This mr depends on https://github.com/dmlc/xgboost/pull/5202 and https://github.com/dmlc/xgboost/pull/5199
=> [jvm-packages]add feature size for LabelPoint and DataBatch

python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
* Use `get_params()` instead of `getattr` intrinsic.
* Parse str parameters too.
Closes #5503 .
=> Fix checking booster.

include/xgboost/tree_model.h, src/tree/tree_model.cc, src/tree/updater_colmaker.cc, src/tree/updater_gpu_hist.cu, src/tree/updater_histmaker.cc, src/tree/updater_quantile_hist.cc, src/tree/updater_skmaker.cc, tests/cpp/tree/test_prune.cc, tests/cpp/tree/test_refresh.cc, tests/cpp/tree/test_tree_model.cc, tests/cpp/tree/test_tree_stat.cc
Partly extracted from #5460.
* Fix GPU Hist feature importance.  The shap value computation requires leaf sum hess (cover), which is not set in GPU training.
=> Requires setting leaf stat when expanding tree.

jvm-packages/dev/Dockerfile, tests/ci_build/Dockerfile.gpu_build, tests/ci_build/Dockerfile.jvm
When running `build-linux.sh`, the building of docker image will fail due to devtoolset-4-xxx packages are not available now. We should change to use devtoolset-6-xxx.
Tested locally.
=> [CI] Use devtoolset-6 because devtoolset-4 is EOL and no longer available

python-package/xgboost/core.py, python-package/xgboost/dask.py
* Remove note for copying booster.
The issue is resolved in  #5312 .
* Add `versionadded` tag for recently added/changed APIs.
=> Update Python doc. [skip ci]

demo/README.md
Dear @hcho3,
In this issue #5440 we have discussed integration with neptune. We concluded that integration will be in our code-base, and here in the `demo` directory, I'll put info about the integration.
Please find this PR with that info. I also put optuna, because it's worth to mention it here.
Please let me know if you need more info.
Regards,
Kamil
=> Added integrations section with 2 examples

Jenkinsfile, doc/jvm/index.rst, doc/jvm/xgboost4j_spark_tutorial.rst, jvm-packages/pom.xml, tests/ci_build/deploy_jvm_packages.sh
Closes #4752.
Closes #5494.
Jenkins will now deploy freshly made JAR packages to a public S3 bucket `xgboost-maven-repo`.  Users can now access SNAPSHOT JARs by adding
```xml
<repository>
<id>XGBoost4J Snapshot Repo</id>
<name>XGBoost4J Snapshot Repo</name>
<url>https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/snapshot/</url>
</repository>
```
to their pom.xml.
[Updated installation instructions](https://xgboost.readthedocs.io/en/release_1.0.0/jvm/index.html#installation-from-maven-repository)
[File listing of `xgboost-maven-repo`](https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/list.html)
Pinging @trams @CodingCat @trivialfis @sperlingxx @wbo4958 @WeichenXu123 @chenqin who might be interested.
=> [jvm-packages] [CI] Create a Maven repository to host SNAPSHOT JARs

src/learner.cc
Fixes #5529 .
XGBoost used to support base64 encoded binary and plain binary, hence there's a 4 bytes header in the binary output model.  Now we reuse it.
Ugly, yes.  I will put more effort into JSON after this release so that we can speed up the process.
=> Write binary header.

src/common/device_helpers.cuh, src/linear/updater_gpu_coordinate.cu, src/tree/gpu_hist/gradient_based_sampler.cu, src/tree/gpu_hist/gradient_based_sampler.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/common/test_device_helpers.cu, tests/cpp/data/test_array_interface.h, tests/cpp/data/test_metainfo.cu, tests/cpp/tree/test_gpu_hist.cu
This PR removes unused and obsolete functions from device helpers.
Bulk allocator was still used in a couple of places and has been converted to new caching device vectors.
No change in behaviour or performance is expected.
=> Purge device_helpers.cuh

tests/ci_build/deploy_jvm_packages.sh
With #5533, XGBoost4J JARs are compiled with Scala 2.12. Per [this request](https://discuss.xgboost.ai/t/xgboost4j-spark-1-0-x-availability/1474/9?u=hcho3), we will now publish two variants of XGBoost4J JARs, one that uses Scala 2.11 and another that uses Scala 2.12.
=> [jvm-packages] [CI] Publish XGBoost4J JARs with Scala 2.11 and 2.12

python-package/xgboost/callback.py
Issue: [Dictionary key referenced before assignment during early stop](https://github.com/dmlc/xgboost/issues/5424)  Closes #5424 .
Bug in early stopping rounds callback function when calling xgboost.cv() where dictionary value is never set. In the case where the model makes no improvements starting in the first iteration, state['best_msg'] is never set and there is a KeyError when the callback function returns after the early stopping rounds. I added an initial value (default message) for state['best_msg'] in the place where state['best_score'], etc get initial values.
=> Fix uninitialized value bug in xgboost callback

src/common/device_helpers.cuh, src/data/device_adapter.cuh, src/data/ellpack_page.cu, src/objective/rank_obj.cu, src/tree/gpu_hist/row_partitioner.cu, tests/cpp/common/test_device_helpers.cu
Remove custom lower bound/upper bound in favour of thrust sequential versions.
Remove custom discard iterator in favour of thrust transform output + discard iterators.
=> Use thrust functions instead of custom functions

src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, tests/cpp/tree/test_quantile_hist.cc
This PR contains optimizations for case when `subsample` parameter less than `1`.
In big data sets, when `subsample < 1` `InitData` kernel requires ~ 25% of full training computational time.
=> Optimizations for RNG in InitData kernel

Jenkinsfile-win64, python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
Closes https://github.com/dmlc/xgboost/issues/5401 .
=> Fix skl nan tag.

python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
Closes https://github.com/dmlc/xgboost/issues/4913
=> Assert matching length of evaluation inputs.

R-package/tests/testthat/test_interaction_constraints.R, src/tree/constraints.cc, src/tree/constraints.cu, src/tree/constraints.cuh, src/tree/param.cc, src/tree/param.h, src/tree/updater_gpu_hist.cu, tests/cpp/tree/test_constraints.cu
* Migrate from dmlc JSON to xgboost JSON.
Closes #5179 .
=> Fix r interaction

src/common/device_helpers.cuh, src/linear/updater_gpu_coordinate.cu, src/metric/elementwise_metric.cu, src/metric/multiclass_metric.cu, src/tree/gpu_hist/row_partitioner.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/common/test_device_helpers.cu
There are a few fixes here:
- #5534 introduced a performance regression. Caching device vectors were used as temporary vectors in the EvaluateSplit code, creation of these vectors introduces synchronisation, slowing down the algorithm. This PR introduces TemporaryArray as a simple data structure, still using the same allocator internally, but avoiding the synchronisation overhead.
- Remove calls to cudaSetDevice on a per node basis. This function is called over 100,000 times when building 500 trees, which is a little excessive. While it is relatively cheap, this does have a noticeable impact. I have removed all calls during each node construction, but left calls that occur only once per tree.
- Fixed a bug where the histogram storage would double on every call up to `size_t …
=> gpu_hist performance fixes

src/tree/gpu_hist/row_partitioner.cu
This switches the inclusive scan in the row partitioner from thrust to cub to avoid the synchronisation of thrust APIs from cuda 10.1 onwards
=> Use non-synchronising scan

CMakeLists.txt, Jenkinsfile, src/CMakeLists.txt, src/common/column_matrix.h, src/common/threading_utils.h, src/metric/rank_metric.cc, tests/cpp/CMakeLists.txt, tests/cpp/common/test_threading_utils.cc, tests/cpp/helpers.cc
* Add test to Jenkins.
* Fix threading utils tests.
* Require thread library.
Closes #5518 .
=> Fix non-openmp build.

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java
According to the [doc](https://xgboost.readthedocs.io/en/latest/parameter.html), `rmsle` eval_metric can possibly output nan when prediction value is less than -1. Currently training with XGBoost Spark encounters following error when paring the output value:
```
2020-04-16 06:08:31 ERROR XGBoostTaskFailedListener:100 - Training Task Failed during XGBoost Training: ExceptionFailure(java.lang.NumberFormatException,For input string: "-nan",[Ljava.lang.StackTraceElement;@6107940c,java.lang.NumberFormatException: For input string: "-nan"
at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
at java.lang.Float.parseFloat(Float.java:451)
at java.lang.Float.valueOf(Float.java:416)
at …
```
=> [jvm-packages] XGBoost Spark should deal with NaN when parsing evaluation output

include/xgboost/data.h, src/common/hist_util.cu, src/common/hist_util.h, src/data/data.cc, src/learner.cc, tests/cpp/common/test_hist_util.cu, tests/cpp/common/test_hist_util.h, tests/cpp/data/test_metainfo.cc, tests/python-gpu/test_gpu_ranking.py
Closes #5548 .
* Distribute group weights to each data point.
* Relax the test.
* Validate input meta info.
TODOs:
=> Group aware GPU sketching.

src/common/device_helpers.cuh, src/tree/gpu_hist/histogram.cu, src/tree/gpu_hist/histogram.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/tree/gpu_hist/test_histogram.cu, tests/cpp/tree/test_gpu_hist.cu
- opt into more dynamic shared memory
- better launch configuration
=> Improve the histogram kernel performance

src/common/device_helpers.cuh
https://devblogs.nvidia.com/cuda-pro-tip-the-fast-way-to-query-device-properties/
This results in a nontrivial performance improvement on linux (~10%).
=> Use cudaDeviceGetAttribute instead of cudaGetDeviceProperties

R-package/R/xgb.Booster.R, R-package/R/xgb.load.R, R-package/tests/testthat/test_callbacks.R
Closes #5209 .
The attributes are loaded back in `xgb.Booster.complete`.  Early stopping is still quite weird, but at least now the behaviour is consistent between model serializations.
=> [R] Restore attributes in complete.

R-package/R/xgb.train.R, R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_glm.R, doc/parameter.rst
Closes https://github.com/dmlc/xgboost/issues/5568 .
* Fixed a wrong parameter in glm test.
After the fix, I ran all tests without generating any warning, so should be safe.
TO-DO:
=> Enable parameter validation for R.

R-package/tests/testthat/test_helpers.R, src/common/hist_util.cc, src/common/io.cc, src/common/observer.h
I made two patches to `release_1.0.0` branch in order to comply with CRAN package submission policy. The two patches are not yet in the master branch.
=> Port R compatibility patches from 1.0.0 release branch

Jenkinsfile, tests/ci_build/Dockerfile.gpu_build, tests/ci_build/Dockerfile.jvm, tests/ci_build/insert_vcomp140.py, tests/ci_build/rename_whl.py, tests/ci_build/test_python.sh
* `tests/ci_build/Dockerfile.gpu_build`: devtoolset-4 is no longer available from mirror.centos.org. So use vault.centos.org repository instead.
* `tests/ci_build/Dockerfile.jvm`: devtoolset-6 has been removed from centos-sclo-rh-testing repository, not too long after devtoolset-4 had been removed there (#5506). Use vault.centos.org repository instead.
* Use manylinux2010 tag, since we use CentOS 6 to build the Python wheel. The wheel will now be called `xgboost-1.x.x-py3-none-manylinux2010_x86_64.whl`. Tensorflow uses manylinux2010 tag too.
=> [CI] Use Vault repository to re-gain access to devtoolset-4

src/learner.cc, tests/distributed/test_basic.py, tests/distributed/test_issue3402.py
I had an issue in #5484 where trying to save the model only on one distributed worker resulted in a rabit error, in that case I modified the tests, but came across the same error today when running the cover type dataset with gbm-bench. 
I traced this back to learner.Configure() being called when the model is saved and then calling rabit allreduce to synchronise number of features. This rabit call should be unnecessary as DMatrix constructors are responsible for making sure they correctly set number of columns in distributed environments.
=> Avoid rabit calls in learner configuration

CMakeLists.txt, Jenkinsfile, include/xgboost/c_api.h, python-package/setup.py, src/CMakeLists.txt, tests/cpp/c_api/test_c_api.cc
Addresses https://github.com/apache/incubator-tvm/issues/4953.
I verified the fix by building this PR inside the `gpu_build` Docker container:
```bash
tests/ci_build/ci_build.sh gpu_build docker -it --build-arg CUDA_VERSION=9.0 \
tests/ci_build/build_via_cmake.sh -DUSE_CUDA=ON -DUSE_NCCL=ON -DOPEN_MP:BOOL=ON \
-DHIDE_CXX_SYMBOLS=ON
tests/ci_build/ci_build.sh gpu_build docker --build-arg CUDA_VERSION=9.0 bash -c \
"cd python-package && rm -rf dist/* && python setup.py bdist_wheel --universal"
tests/ci_build/ci_build.sh gpu_build docker --build-arg CUDA_VERSION=9.0 python3 \
tests/ci_build/rename_whl.py python-package/dist/*.whl e4f5b6c manylinux1_x86_64
```
Depends on https://github.com/dmlc/rabit/pull/138.
=> Hide C++ symbols in libxgboost.so when building Python wheel

include/xgboost/data.h, src/data/data.cc, src/data/device_dmatrix.cu, src/data/simple_dmatrix.cu, src/learner.cc, tests/cpp/data/test_metainfo.cc, tests/python-gpu/test_from_cupy.py, tests/python-gpu/test_gpu_prediction.py
Running pytest on all GPU tests on my machine resulted into a segfault.
=> Set device in device dmatrix.

.travis.yml, src/metric/survival_metric.cc, src/objective/aft_obj.cc, tests/ci_build/rename_whl.py, tests/travis/run_test.sh
Closes #5595.
* The `default(none)` clause of OpenMP has unclear semantics when const variables are present. Remove all occurrences of `default(none)` from the codebase to maintain portability.
* [CI] Run tests using Mac OSX High Sierra (10.13). Previously, we only tested with Mac OSX Mojave (10.14).
* [CI] Upload binary wheels for Mac OSX. Fixes #5586. The wheel name will be of form `xgboost-[version]-py3-none-macosx_10_13_x86_64.macosx_10_14_x86_64.macosx_10_15_x86_64.whl`. The goal is to support High Sierra (10.13), Mojave (10.14), and Catalina (10.15).
=> Fix compilation on Mac OSX High Sierra (10.13)

tests/travis/run_test.sh
Follow up to #5597. The wheel should be readable to the public.
=> [CI] Grant public read access to Mac OSX wheels

R-package/vignettes/xgboostPresentation.Rmd, include/xgboost/span.h
```
* checking compiled code ... NOTE
File ‘xgboost/libs/xgboost.so’:
Found ‘stderr’, possibly from ‘stderr’ (C)
Object: ‘./amalgamation/xgboost-all0.o’
Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs.
See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
--- re-building ‘xgboostPresentation.Rmd’ using rmarkdown
Loading required package: xgboost
Quitting from lines 412-424 (xgboostPresentation.Rmd)
Error: processing vignette 'xgboostPresentation.Rmd' failed with diagnostics:
[01:06:51] amalgamation/../src/learner.cc:506: Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is supplied.  Are you using raw Booster interface?
Stack trace:
[bt] (0) …
```
=> [R] Address warnings to comply with CRAN submission policy

include/xgboost/c_api.h, src/c_api/c_api.cc
fixes #5601 . Pre-empts questions about the breaking API change for v1.1.0 that downstream maintainers will have.
=> Clarify meaning of `training` parameter in XGBoosterPredict()

src/gbm/gbtree.cc, src/learner.cc, tests/python-gpu/load_pickle.py, tests/python-gpu/test_gpu_pickling.py
https://github.com/dmlc/xgboost/issues/5592
=> Better message when no GPU is found.

doc/tutorials/index.rst
These tutorials on distributed XGBoost should be bundled closer to each other.
=> Move dask tutorial closer other distributed tutorials

src/tree/constraints.cuh, src/tree/gpu_hist/evaluate_splits.cu, src/tree/gpu_hist/evaluate_splits.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/tree/gpu_hist/test_evaluate_splits.cu, tests/cpp/tree/gpu_hist/test_gradient_based_sampler.cu, tests/cpp/tree/test_gpu_hist.cu, tests/python-gpu/test_gpu_prediction.py
- Move split evaluation code out of updater_gpu_hist.cu
- Fuse left and right child split evaluation into a single kernel. (We can now run this kernel on a single stream, later I want to have each node construction running kernels asynchronously on its own stream).
- Remove dependency on EllPack data structure, accept spans instead so we can more easily test this component
- Clean up some unnecessary member variables in updater_gpu_hist.cu
Some possibilities for the next PR:
- Pass operators to split evaluation, handling gain calculation, constraints etc.
- Rewrite split evaluation using cub inclusive scan instead of custom kernels
=> Refactor gpu_hist split evaluation

include/xgboost/data.h, src/data/data.cc
Closes #5614.
* DMLC serializer cannot handle POD structs automatically for big endians. The reason is that we have to swap byte orders to serialize bytes in little endian order. Fix: Explicitly define serializer for `xgboost::Entry`.
* For the same reason, DMLC serializer cannot handle enum class. Cast to primitive type using `static_cast<>`.
Tested using s390x Debian docker container.
=> Fix build on big endian CPUs

include/xgboost/data.h
We need a common interface for creating DMatrix as `Adapter` is currently internal.  Right now I just remove the misleading comment and dead code.
=> Remove dead code.

include/xgboost/data.h, src/data/device_adapter.cuh, src/data/device_dmatrix.cu, src/data/ellpack_page.cu, src/data/ellpack_page.cuh, src/data/ellpack_page_source.cu, src/data/sparse_page_source.h
* Make ellpack more self contained.
To provide some contexts, I'm implementing #5571 .  The basic procedure for GPU is:
~- Define a callback function for each input type.~
- Use that call back function to iterate through each partition 3 times:
+ Accumulate total number of rows.
+ Sketch.
+ Build an ellpack for each partition.
- Concatenate all Ellpacks by gradient sampler, like current external memory implementation.
Hence I need `EllpackImpl` to be more independent.
=> Move device dmatrix construction code into ellpack.

src/common/column_matrix.h, src/common/device_helpers.cuh, src/tree/gpu_hist/driver.cuh, src/tree/gpu_hist/row_partitioner.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/test_serialization.cc, tests/cpp/tree/gpu_hist/test_driver.cu, tests/cpp/tree/test_tree_stat.cc
Creates a data structure called Driver which is a slightly more custom priority queue, returning batches of nodes that may be executed asynchronously.
With this we don't have to wait for the device to host copy at the end of split evaluation before starting construction on the next node in many cases.
I also fixed a slight performance bug in row_partitioner where a memory copy was not asynchronous because the memory was not pinned.
=> Reduce device synchronisation

src/common/column_matrix.h, src/tree/updater_quantile_hist.cc, tests/cpp/tree/test_quantile_hist.cc
While looking at the profile, I noticed that PartitionDenseKernel was taking surprising %% of time;
Looking at it a bit, large part of the cost comes from the column.IsMissing check; This check:
1) does lookup in `vector<bool>`
2) adds one more condition to the hot loop
3) fills the caches with the data from that vector<bool>
In my use-cases, as well as in several publicly available datasets (like
higgs), nothing is missing, so we can use that information and create a
separate path which won't do this check at all.
Benchmarking on higgs dataset (10m samples, 28 features, 100 trees, 256 leaves, 256 bins) on 4 core macbook pro (Kaby Lake Core i5) shows ~10% improvement in training time.
I do not have other machine to test it on, so I cannot really claim how much of the win will hold on …
=> skip missing lookup if nothing is missing in CPU hist partition kernel.

doc/dump.schema, src/tree/tree_model.cc, tests/cpp/tree/test_tree_model.cc, tests/python/test_basic_models.py
- Fixes incorrect JSON node stats, closes #5655. 
- Add JSON schema for model dump.
- Make member functions const.
=> Add JSON schema to model dump.

R-package/demo/boost_from_prediction.R, R-package/demo/cross_validation.R, R-package/demo/predict_first_ntree.R, R-package/demo/predict_leaf_indices.R, R-package/man/xgb.load.Rd, R-package/vignettes/xgboost.Rnw, demo/kaggle-higgs/higgs-train.R, demo/kaggle-higgs/speedtest.R, doc/get_started.rst, tests/cpp/test_logging.cc, tests/distributed/test_basic.py
It turns out there are independent demos in R subdir.  Along with https://github.com/xgboost-ai/xgboost-ai.github.io/pull/8 , the parameter should not be displayed in any place for R and Python and C.
Scala has a compatibility mapping for `silent` -> `verbosity`.
=> Remove silent from R demos.

doc/gpu/index.rst, doc/tutorials/external_memory.rst
=> add pointers to the gpu external memory paper

src/tree/updater_prune.cc, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, tests/cpp/tree/test_quantile_hist.cc
This PR consists changes to optimize distributed mode of training.
1) depthwise changes: Possibility to build 'smaller' nodes was introduced for distributed mode (before this only left nodes were build)  for more balanced work. Than 'subtraction trick' is applied for 'larger' node.
2) lossguide changes: similar to above.
3) number of rabit::Allreduce calls is the same as before due to structured histograms adding. 
4) Timers were added to track most time consuming parts for distributed also.
**mortgage 3.5Gb** 
6 workers x 8 threads | loss | depth
-- | -- | --
Master | 76.6 | 68.5
This PR | 48.7 | 44
**higgs 10m,  2.7Gb** 
running line: python .../dmlc-core/tracker/dmlc-submit --cluster=local --num-workers=4 --worker-cores=12 python distr_higgs10m.py
4 workers x 12 threads | depth
-- | -- …
=> Distributed optimizations

R-package/R/xgb.cv.R, R-package/R/xgb.train.R, R-package/man/xgb.cv.Rd, R-package/man/xgb.load.Rd, R-package/man/xgb.train.Rd
Closes #5657. I have also removed random documentation for `num_class` in the objective section (https://github.com/dmlc/xgboost/pull/5682/files#diff-1db03a673737dab89b7f0befb7a410b7L49). Since in `xgb.cv()`, only the most important objectives were documented, I made a reference to `xgb.train()`, where we now have the complete list from the [online doc](https://xgboost.readthedocs.io/en/latest/parameter.html#learning-task-parameters).
=> Document more objective parameters in R package

demo/guide-python/sklearn_examples.py, python-package/xgboost/compat.py, python-package/xgboost/core.py, python-package/xgboost/data.py, python-package/xgboost/sklearn.py, tests/python-gpu/test_from_cupy.py, tests/python/test_with_pandas.py
* Add a factory method for handling various data types.
This PR decouples DMatrix Python interface with various backends.
In the future I want to use the backends for all meta info setters.  This way we have have better support for non-numpy data structures for setting metainfo.
=> Implement Python data handler.

R-package/configure, R-package/configure.ac
I've been using `xgboost`'s `configure.ac` as a reference, and noticed an opportunity for reducing duplication. Right now the location for `libomp` and the `OPENMP_CXXFLAGS` are hard-coded in two places.
This small PR proposes removing the second hard-coding to reduce duplication and the risk of mistakes if that location or those flags are updated in the future.
=> [R-package] Reduce duplication in configure.ac

R-package/configure, R-package/configure.ac
Addresses #5496. The relevant error is
```
OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program.
```
=> [R] Fix duplicated libomp.dylib error on Mac OSX

python-package/xgboost/core.py, python-package/xgboost/sklearn.py
scikit learn catches `ValueError` instead of `Exception`.  Also I believe it's better to let user use `ValueError` as it's more common.
This is not entirely a breaking change as old code that catches XGBoostError or Exception will continue to work unless you catch ValueError and have another handler for XGBoostError.
=> Let XGBoostError inherit ValueError.

CMakeLists.txt, src/CMakeLists.txt, tests/cpp/CMakeLists.txt
MSVC prints out warnings like
* `warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead.`
* `warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead.`
We cannot use `fopen_s` or `_dupenv_s` because they are Microsoft extensions and are not supported by POSIX-like OSes (including Linux).
Fix: Define `_CRT_SECURE_NO_WARNINGS` macro to ignore such warnings. The effect will be to declutter build logs and to speed up builds slightly (console printing on Windows is slow).
Depends on https://github.com/dmlc/rabit/pull/136.
=> Define _CRT_SECURE_NO_WARNINGS to remove unneeded warnings in MSVC

Jenkinsfile, python-package/setup.py, python-package/xgboost/__init__.py, tests/ci_build/Dockerfile.cpu, tests/ci_build/test_python.sh
Extracted from #5388. We can now opt into new features introduced by Python 3.6, such as f-strings and numeric literals with underscores.
=> Require Python 3.6+; drop Python 3.5 from CI

python-package/xgboost/compat.py, python-package/xgboost/core.py, python-package/xgboost/dask.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/testing.py
* Check input data type.
* Refactor prediction function.
* Remove importing cudf on load.
=> [dask] Return GPU Series when input is from cuDF.

doc/tutorials/aft_survival_analysis.rst
Survival labels are always non-negative, so the left-censored label is `[0, b]`, not `(-inf, b]`.
=> [Doc] Fix typos in AFT tutorial

src/common/device_helpers.cuh, src/tree/gpu_hist/row_partitioner.cu, src/tree/gpu_hist/row_partitioner.cuh, src/tree/updater_gpu_hist.cu
- Remove the use of device vectors from RowPartitioner in favour of more lightweight TemporaryArray.
- Remove unnecessary synchronisation after AllReduce
=> gpu_hist performance tweaks

src/objective/regression_obj.cu
fix related to #5666
this PR reduce gaps between -DUSE_CUDA=ON and -DUSE_CUDA=OFF
dataset |  -DUSE_CUDA=ON | -DUSE_CUDA=OFF
-- | -- | --
higgs1m | 16.07s  | 15.9s
mortgage1Q | 17.9s | 17.67s
After profiling it was discovered that `GetGradient` step computational time was increased ~5x what introduce 25% degradation for full training.
Fix is related to lambda capturing (when this function was compiled with cuda, its performance was worse than with g++ usage). Without capturing performance is similar.
=> Fix release degradation

src/learner.cc, tests/pytest.ini, tests/python/test_model_compatibility.py
Quick and dirty patch for fixing https://github.com/dmlc/xgboost/issues/5699.  But as there's warning about loading old model, and can be fixed by user saving the model again before doing any further operations.  So please comment should we do the hacky fix @hcho3 @RAMitchell @sh1ng ;-)
=> Fix loading old model.

Jenkinsfile-win64, python-package/xgboost/core.py
* Remove CUDA 9.0 on Windows CI.
* Require cuda10 tag, to differentiate
Co-authored-by: Philip Hyunsu Cho <chohyu01@cs.washington.edu>
=> [CI] Backport Remove CUDA 9.0 from Windows CI. (#5674)

doc/index.rst
Please do not take this PR violently.
I made an announcement at [forum](https://discuss.xgboost.ai/t/xgboost-for-swift), and I would love to get Swift into one of the supported languages at official XGBoost documentation, and I thought that Github would be actually a better place to ask this.
[SwiftXGBoost](https://github.com/kongzii/SwiftXGBoost) currently support core features with more to come. Documentation is auto-generated, and tests are done against Python implementation.
Is there any checklist or previous discussion (when bindings for other languages were proposed) that I could look at in order to get this PR eventually merged?
Thanks.
=> Add swift package reference

src/data/array_interface.h, src/data/device_adapter.cuh
The implementation is incorrect with due to the line `array_interface_.valid.Check(row_idx)`, it didn't show up in the test because masked array itself is not supported by cupy.  So this PR makes it explicit that we are not supporting it either.
=> Don't use masked array in array interface.

Jenkinsfile
Now that we build XGBoost with CUDA 10.0 (#5649), we don't need to test it with CUDA 9.0. Also see #5674.
=> [CI] Remove CUDA 9.0 from CI

src/common/hist_util.cu, src/common/hist_util.cuh, src/common/hist_util.h, src/data/ellpack_page.cu, src/data/ellpack_page_source.cu, tests/cpp/common/test_hist_util.cu
=> Expose device sketching in header.

doc/parameter.rst, include/xgboost/base.h, src/common/hist_util.cc, src/common/hist_util.h, src/tree/param.h, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, tests/cpp/common/test_hist_util.cc, tests/cpp/tree/test_quantile_hist.cc, tests/python/test_updaters.py
copy of https://github.com/dmlc/xgboost/pull/5523
This PR is supposed to change internal type of GradStats to avoid conversion for hist method. Also bug related to numerical instability in NeedReplace method.
Accuracy ~ the same as was with double type, and ex. for mnist data set was even improved:
mnist | log-loss
-- | --
Master | 0.07304085
This PR | 0.07301824
Similar changes were provided in PR:#4529 but full scope of changes was reverted in #5008.
Performance improvements (1.5x for BuildHist):
santander | full train | InitData | BuildHist | SyncHist | PredictRaw
-- | -- | -- | -- | -- | --
Master | 179.71 | 47.24 | 58.01 | 14 | 46.48
This PR | 162.94 | 47.51 | 38.12 | 8.08 | 54.7
mnist| full train | BuildHist | SyncHist | ApplySplit
-- | -- | -- | -- | --
Master | 78.511 | 34.82 | …
=> Change type of hist buffer to float

python-package/xgboost/data.py, tests/python-gpu/test_device_quantile_dmatrix.py, tests/python-gpu/test_gpu_linear.py, tests/python-gpu/test_gpu_updaters.py, tests/python/regression_test_utilities.py
This PR speeds up tests to a more reasonable level, while maintaining most of the test coverage.
`pytest -s -v --profile tests/python-gpu/test_gpu_updaters.py` goes from around 120s to 22s.
I had a failing test for DeviceQuantileDMatrix as well where passing a label with type float64 was passing doubles directly into xgboost and reading them as floats. The root cause was the data handler refactor which was incorrectly handling types in this case. I also noticed that it is possible to create a DeviceQuantileDMatrix using numpy without causing the expected error. For now I have disabled numpy inputs to DeviceQuantileDMatrix altogether.
=> Speed up python test

tests/cpp/helpers.cc, tests/cpp/helpers.h, tests/cpp/test_helpers.cc
=> Add helper for generating batches of data.

src/c_api/c_api.cc, src/c_api/c_api.cu, src/data/adapter.h, src/data/device_adapter.cuh, src/data/ellpack_page.cu, src/data/simple_dmatrix.cu, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, tests/cpp/data/test_device_adapter.cu, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu
As cuDF is actually dense data, removing all the specializations.
* Use shared pointer for inplace prediction.  Using `dmlc::any` with `ArrayInterface` might lead to some subtle bugs as `dmlc::any` needs to copy the underlying value, while `ArrayInterface` contains stack allocated memory `char type[3]`.
=> Remove column major specialization.

.gitignore, doc/sphinx_util.py, python-package/xgboost/__init__.py, tests/benchmark/benchmark_linear.py
This pull request proposes removing some unused imports in Python code.
I ran two linters over the Python code in this project tonight, hoping I could find some things that could be fixed.
First, I ran `flake8`. This returned a bunch of issues that I think are minor and should be left to maintainers...things like extra blank lines, missing spaces around operators, and other whitespace and minor style things.
```shell
flake8 \
---ignore=W503,E501,E202,E231,E241,W504,E226,E271,E251,E121,E221,E111,E302,E305,E303,W293,E201,E211,W291,E261,E203,E402,E306,E225,E266,E265,E128,E127,W391
```
Next, I ran `mypy` to look for type mismatches. That didn't turn up anything obvious (it's more useful on projects that make heavy use of Python type hints), but might be worth it for maintainers to try some …
=> [python-package] remove unused imports

doc/requirements.txt, doc/xgboost_doc.yml
The formatting for the R package docs is [broken](https://xgboost.readthedocs.io/en/latest/R-package/xgboostPresentation.html), as mentioned in #5293. I want to work on fixing this. To get started, I followed the [instructions for building the docs](https://xgboost.readthedocs.io/en/latest/R-package/xgboostPresentation.html). I had a few issues getting the dependencies installed correctly, and figured I would share my conda environment to make building the docs easier.
If this PR is accepted, I can update the instructions to mention how to use this environment file to install the dependencies for the docs. I will likely address the issues with the R package formatting in the original issue as well.
=> Added conda environment file for building docs

R-package/demo/basic_walkthrough.R, R-package/demo/caret_wrapper.R, R-package/demo/create_sparse_matrix.R, R-package/demo/interaction_constraints.R, R-package/demo/tweedie_regression.R, R-package/tests/testthat/test_helpers.R, R-package/tests/testthat/test_interactions.R, R-package/tests/testthat/test_lint.R, R-package/vignettes/discoverYourData.Rmd, R-package/vignettes/xgboostPresentation.Rmd, demo/data/gen_autoclaims.R, demo/kaggle-otto/otto_train_pred.R, demo/kaggle-otto/understandingXGBoostModel.Rmd, doc/R-package/discoverYourData.md, doc/R-package/xgboostPresentation.md
This pull request proposes replacing uses of  `T` and `F` in R code with `TRUE`  and  `FALSE`. `T` and  `F` are dangerous because they are only aliases and can be overwritten.
```r
TRUE <- 4
T <- 4
T
```
Thanks for your time and consideration!
=> [R] replace uses of T and F with TRUE and FALSE

src/common/hist_util.cc, src/common/hist_util.cu, src/common/hist_util.cuh, src/common/hist_util.h, src/data/device_adapter.cuh, tests/cpp/common/test_hist_util.cu, tests/cpp/common/test_hist_util.h
* Implemented weighted sketching for adapter.
* Implemented a sketching interface for adapter batch instead of adapter.
The implementation is mostly for  #5629 .  I plan to replace the internal implementation of `DeviceDMatrix` with the iterative version in  #5629.  So this PR doesn't export the interface to Python.
I tried to extract some common code into functions, but still not very satisfying.  One idea for the future is we may just have an adapter for SparsePage so we can unify all sketching code.
=> Implement weighted sketching for adapter.

src/c_api/c_api.cc
Addresses warning from CRAN submission:
https://github.com/dmlc/xgboost/pull/5701#issuecomment-640438882
=> [R] Add explicit cast to pass 32-bit CRAN check

python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
Fixes an issue related to [#17353](https://github.com/scikit-learn/scikit-learn/issues/17353) in scikit-learn and [#3129](https://github.com/microsoft/LightGBM/pull/3129) in LightGBM (see [SLEP010](https://scikit-learn-enhancement-proposals.readthedocs.io/en/latest/slep010/proposal.html) for further details). It also fixes an issue related to the behavior of ```StackingClassifier```, where the returned error is ```AttributeError: 'XGBClassifier' object has no attribute 'n_features_in_'``` (see code below).
```
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import …
```
=> add new attribute for number of features

python-package/xgboost/compat.py, python-package/xgboost/core.py, python-package/xgboost/plotting.py
I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. If you're interested, I can do it here too. I've done it on just one file right now. 
The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.
Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The usage of `raise from` tells Python to put a …
=> Fix exception causes all over the codebase

Jenkinsfile-win64, tests/python-gpu/test_gpu_prediction.py
Multithreaded in-place prediction with cupy does not work on Windows (#5793). I am unable to find a workaround so have just disabled one test.
=> Add cupy to Windows CI

include/xgboost/data.h, include/xgboost/host_device_vector.h, src/common/host_device_vector.cc, src/common/host_device_vector.cu, src/data/data.cc, tests/cpp/data/test_metainfo.cc, tests/cpp/data/test_metainfo.cu
* Implement extend for host device vector.
Extracted from https://github.com/dmlc/xgboost/pull/5783 .
=> Implement extend method for meta info.

doc/tutorials/saving_model.rst, python-package/xgboost/core.py
=> Update document for model dump.

doc/conf.py
Fixes https://discuss.xgboost.ai/t/r-documentation-html-displays-source-code/1686.
According to https://www.sphinx-doc.org/en/master/usage/markdown.html, the option `source_parsers` no longer works in latest Sphinx. Use `extensions = ['recommonmark']` instead.
=> [Doc] Fix rendering of Markdown docs, e.g. R doc

src/data/array_interface.h, src/data/data.cu, tests/cpp/data/test_array_interface.cc, tests/cpp/helpers.cc
Extracted from https://github.com/dmlc/xgboost/pull/5783 .
Restore some checks from original implementation for `ArrayInterfaceHandler`.
=> Accept string for ArrayInterface constructor.

include/xgboost/data.h, src/data/proxy_dmatrix.cu, src/data/proxy_dmatrix.h, tests/cpp/data/test_proxy_dmatrix.cu
Extracted from #5783 .
The proxy is a staging area for data and the bridge between external iterator and internal device DMatrix.  External iterator stage data into this proxy, then internal DMatrix extracts the data from it.
=> Implement a DMatrix Proxy.

tests/python/test_linear.py
* Increased error in coordinate is mostly due to floating point error.
* Shotgun uses Hogwild!, which is non-deterministic and can have even greater
floating point error.
Closes #5845 .
If shotgun test is still flaky after the PR, we will have to adopt a more sparse sampled result.
=> Relax linear test.

include/xgboost/c_api.h, include/xgboost/data.h, src/c_api/c_api.cc, src/common/hist_util.cuh, src/data/data.cc, src/data/ellpack_page.cu, src/data/ellpack_page.cuh, src/data/iterative_device_dmatrix.cu, src/data/iterative_device_dmatrix.h, tests/cpp/data/test_iterative_device_dmatrix.cu, tests/cpp/helpers.cu, tests/cpp/helpers.h, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/predictor/test_predictor.cc, tests/cpp/predictor/test_predictor.h
Extracted from #5783 .
In the big PR, device DMatrix is removed and replaced by iterative DMatrix.  This PR hasn't removed it yet so I can extract the related parts without breaking XGBoost.
=> Implement iterative DMatrix.

demo/c-api/.gitignore
When running the C usage example we build the `c-api-demo` binary in `demo/c-api`.
As this file isn't listed in `.gitignore`, this is a bit annoying as one has to be careful about not accidentally checking it in.
This fixes it by adding a corresponding `.gitignore`.
=> Add c-api-demo to .gitignore

include/xgboost/c_api.h, include/xgboost/data.h, python-package/xgboost/core.py, python-package/xgboost/data.py, src/c_api/c_api.cc, src/common/host_device_vector.cc, src/common/host_device_vector.cu, src/data/data.cc, src/learner.cc, tests/cpp/c_api/test_c_api.cc, tests/cpp/data/test_metainfo.cc, tests/python/test_dmatrix.py
This way native code knows what data types we are dealing with.
* Add thread local return entry for DMatrix.
* Feature name is also moved.
* Save feature name and feature type in binary file.
=> Move feature names and types of DMatrix from Python to C++.

python-package/xgboost/core.py
Introduced in https://github.com/dmlc/xgboost/pull/5783 due to an oversight.  Sorry.
=> Remove print.

src/common/hist_util.cu, tests/cpp/common/test_hist_util.cu
Turns out the code already does the right thing, it's just the `CHECK` that's making an incorrect assumption.
Fixes #5866 
=> fix device sketch with weights in external memory mode

.travis.yml, CMakeLists.txt, Jenkinsfile, R-package/CMakeLists.txt, jvm-packages/CMakeLists.txt, plugin/CMakeLists.txt, plugin/lz4/sparse_page_lz4_format.cc, src/CMakeLists.txt, tests/ci_build/Dockerfile.cpu, tests/cpp/CMakeLists.txt
* Starting CMake 3.12, it is now possible to refer to object libraries in `target_link_libraries()` command. When a shared library links with an object library, the objects and compilation/link flags associated with the object library get automatically propagated to the shared library. So we don't need variables like `LINKED_LIBRARIES_PRIVATE`, `XGBOOST_OBJ_SOURCES`, and `XGBOOST_DEFINITIONS`. Automatic propagation of flags is less error-prone than using the variables to copy the flags. See [More Modern CMake](https://github.com/Bagira80/More-Modern-CMake).
* Use `target_sources()` instead of `PLUGIN_SOURCES` and `XGBOOST_OBJ_SOURCES`.
* Make sure that the LZ4 and Dense parser plugins can be built. #4879 broke the build for the plugins, but we didn't catch it because the CI wasn't testing …
=> [CI] Simplify CMake build with modern CMake techniques

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/BoosterParams.scala
Expose the existing 'singlePrecisionHistogram' param to the Spark layer.
=> [jvm-packages] Add new parameter singlePrecisionHistogram to xgboost4j-spark

src/common/hist_util.cu, src/common/hist_util.cuh, src/common/hist_util.h, src/common/quantile.h, src/data/ellpack_page.cu, src/data/ellpack_page.cuh, src/data/iterative_device_dmatrix.cu, tests/cpp/common/test_hist_util.cc, tests/cpp/common/test_hist_util.cu, tests/cpp/common/test_quantile.cu
* Remove old functions.
* Merge weighted and un-weighted into a common interface.
=> Cleanup on device sketch.

Jenkinsfile, Jenkinsfile-win64, tests/jenkins_get_approval.py
Fixes #5176 by enforcing a daily budget in Jenkins CI. @dmlc/xgboost-committer 
How it works: For each incoming pull request, Jenkins will first call the AWS Lambda (*) function `XGBoostCICostWatcher`. The Lambda function determines whether the expense incurred for today (\*\*) is under [the specified daily budget](https://github.com/hcho3/xgboost-devops/blob/c358525299489c0e1285bc525817e791aa46ef55/cost_watcher/metadata.py#L1-L2). The function returns `true` when today's expense did not yet exceed the budget; the function returns `false` if the expense exceeds the budget. When the expense is found to exceed the daily budget, all testing jobs for incoming pull requests gets terminated preemptively so that the CI server stops incurring more cloud expenses.
EC2 (compute) comprises the vast …
=> [CI] Enforce daily budget in Jenkins CI

demo/c-api/c-api-demo.c, include/xgboost/c_api.h, include/xgboost/learner.h, src/c_api/c_api.cc, src/learner.cc, tests/cpp/c_api/test_c_api.cc
- add `GetNumFeature` to `Learner`
- add `XGBoosterGetNumFeature` to C API
- update `c-api-demo` accordingly
Currently, it doesn't look like there is a way to obtain the number of features of a given `BoosterHandle` via the C API (without manually parsing the JSON model file).
This seems to be a bit limiting in practice.
For example, imagine one is attempting to deploy a pre-trained model via the C API. The model itself has 127 features, but not all of them are present for each sample.
Let's say we're given the following line:
```
1:1 9:1 19:1 21:1 24:1 34:1 36:1 39:1 42:1 53:1 56:1 65:1 69:1 77:1 86:1 88:1 92:1 95:1 102:1 106:1 117:1 122:1
```
As the model expects 127 columns, we'd somehow have to pad the resulting matrix. Otherwise, we'd get the following error:
```
c-api-demo.c:59: …
```
=> Add XGBoosterGetNumFeature

Jenkinsfile-win64
As discussed in #5891, tests for the Windows platform cost a disproportionate amount of the expenses, even though a majority of the tests overall run in Linux:
Until a better solution is found, we reduce the load by removing CUDA 10.0 target from the Jenkins pipeline for Windows.
=> [CI] Reduce load on Windows CI pipeline

R-package/CMakeLists.txt
Fixes #5894. 
The dependency graph in XGBoost build looks like this:
```
xgboost-r  ---> objxgboost  ---> xgboost
```
Previously, the R lib was linked to `xgboost-r` with `PRIVATE` designation, and if CMake 3.13 was used, the R lib requirement would not be progagated to `xgboost` target, so that is why the build failed in #5894.
This PR make the R lib a `PUBLIC` requirement of `xgboost-r`, so the build will work correctly with CMake 3.13.
Note that the fix does not apply to CMake 3.14 or newer. The Release Note for CMake 3.14 says:
> Object library linking has been fixed to propagate private link libraries of object libraries to consuming targets.
=> Fix R package build with CMake 3.13

python-package/xgboost/core.py, python-package/xgboost/data.py, src/data/proxy_dmatrix.cu, tests/python-gpu/test_device_quantile_dmatrix.py, tests/python-gpu/test_from_cudf.py, tests/python-gpu/test_from_cupy.py, tests/python/test_basic.py, tests/python/test_with_pandas.py
This PR removes data handler and just use plain old conditions with glue functions.  It doesn't simplify the logic for gluing various data sources, but merely makes the code easier to track.  After this PR, we will have explicit list of supported data for `DMatrix`, `DeviceQuantileDMatrix` and corresponding meta info.  3 entry functions are:
- `dispatch_data_backend`
- `dispatch_meta_backend`
- `dispatch_device_quantile_dmatrix_set_data`
After this PR, we need to renew our document for what's supported for `DMatrix` and meta info.
Another important issue in our `DMatrix` initialization code is, for CPU input we accept only floating point value and ulong sparse index.  Whenever there's a mismatch from user provided data, `ctypes` makes a copy.  Some feedback on XGBoost consuming too much …
=> Simplify the data backends.

jvm-packages/create_jni.py, python-package/setup.py, src/common/charconv.cc
Found during setting up github action.  There's still an external test `SparsePage, PushCSCAfterTranspose`  failing on latest Ubuntu and Windows.  I can't fix it right now with the complexity of external memory.  So I just port a small fix here.
=> Fix Windows 2016 build.

Jenkinsfile, Jenkinsfile-win64, tests/ci_build/deploy_jvm_packages.sh, tests/ci_build/win64_conda_env.yml, tests/python-gpu/test_gpu_demos.py, tests/python/test_plotting.py, tests/python/test_with_sklearn.py, tests/python/testing.py
> Each partial instance hour consumed is billed per-second for Linux instances and as a full hour for all other instance types.
For example, if we launch a Linux EC2 instance, run it for 10 minutes and shut it down, then we only pay 1/6 of the hourly price. On the other hand, if we launch a Windows instance and shut it down 10 minutes later, then we have to pay the full hourly price, since 10 minutes gets rounded up to the next full hour. The difference is more dramatic if we launch multiple machines. Using two Linux instances for 10 minutes each costs 1/3 of the hourly price, whereas using two Windows instances for 10 minutes each cost twice the hourly price!
Now let's look at how the Windows testing pipeline is Jenkins is affected by the hourly pricing. Since all steps in the pipeline …
=> Further improvements and savings in Jenkins pipeline

.github/workflows/main.yml, cmake/modules/FindLibR.cmake, tests/cpp/predictor/test_gpu_predictor.cu
Some fixes ported from https://github.com/dmlc/xgboost/pull/5917 .  Mostly fixing building R package with CMake and mingw.
=> Fix mingw build with R.

.github/workflows/main.yml, cmake/modules/FindLibR.cmake, tests/ci_build/test_r_package.py, tests/cpp/predictor/test_gpu_predictor.cu, tests/python/test_tracker.py
Existing tests are still here.  I plan to remove appveyor once this PR is approved as a replacement.  Also, it's possible to replace some Jenkins CPU tests.  As proposed by @hcho3, we can run all default tests on action and travis like linting and some CPU tests, and run Jenkins tests only when approved.  This PR should be able to get us closer to that goal.
* Add tests for R package on Windows, including mingw64, msvc with windows lastest and 2016.
~* Add CPP and Python tests on Windows latest and Ubuntu latest.~
* Add Java tests on Windows latest, Windows 2016 and Ubuntu latest. (no spark)
The test matrix can be changed, suggestions are welcomed.
- `SparsePage.PushCSCAfterTranspose'` in gtest is skipped due to an error in external memory.  So far I can't reproduce it on my local …
=> Setup github action.

appveyor.yml
Based on https://github.com/dmlc/xgboost/pull/5917 .
=> Remove r jvm from appveyor

R-package/R/utils.R, R-package/tests/testthat/test_custom_objective.R, cmake/RPackageInstall.cmake.in, tests/python/test_basic_models.py
Fix https://github.com/dmlc/xgboost/issues/5878 .
=> Fix r early stop with custom objective.

src/data/data.cc, src/tree/updater_quantile_hist.cc
According to rules of the Standard C++, the implementation of a template class must be available in a header:
* https://isocpp.org/wiki/faq/templates#templates-defn-vs-decl
* https://docs.microsoft.com/en-us/cpp/cpp/source-code-organization-cpp-templates?view=vs-2019
Many member functions of the template class `QuantileHistMaker::Builder` are implemented in the source `updater_quantile_hist.cc`, in violation of the guideline above. Both `updater_quantile_hist.cc` and `test_quantile_hist.cc` use `QuantileHistMaker::Builder`, and we'd get a link error when we compile `test_quantile_hist.cc`. When I tried building `testxgboost` with the code from #5825, I got
```
tests/cpp/CMakeFiles/testxgboost.dir/tree/test_quantile_hist.cc.o: In function `xgboost::tree::QuantileHistMock::TestInitData()': …
```
=> Add explicit template specialization for portability

src/tree/gpu_hist/histogram.cu
Restoring some perf on gtx 1080 ti:
|        | GPU       | Dataset | Time               |
|--------|-----------|---------|--------------------|
| Before | v100      | Higgs   | 25.431774566997774 |
|        | gtx1080ti | Higgs   | 135.91460225299988 |
|        | v100      | Epsilon | 93.19408854097128  |
|        | gtx1080ti | Epsilon | 272.334376795      |
| After  | v100      | Higgs   | 25.490044657010003 |
|        | gtx1080ti | Higgs   | 83.45110513200052  |
|        | v100      | Epsilon | 94.6916850550333   |
|        | gtx1080ti | Epsilon | 256.336098645      |
Not fully restored yet as previous on 1080ti higgs is `61.58244462100038`, but I don't have alternative solution.
=> Use `cudaOccupancyMaxPotentialBlockSize` to calculate the block size.

jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/MissingValueHandlingSuite.scala, src/data/data.cc, src/data/simple_dmatrix.cc, tests/cpp/data/test_adapter.cc, tests/cpp/data/test_simple_dmatrix.cc
Fixes #5848.
Diagnosis: https://github.com/dmlc/xgboost/issues/5848#issuecomment-662767268, https://github.com/dmlc/xgboost/issues/5848#issuecomment-662802416. The bug occurs whenever a CSR sparse matrix has empty rows at its end. (Empty rows in the middle of the matrix don't matter.)
Fix. Create a special logic for `IteratorAdapter` and `FileAdapter`, so that the empty rows at the end of the matrix are properly accounted for. I added test cases in Google Test.
=> [BLOCKING] Handle empty rows in data iterators correctly

tests/python/test_model_compatibility.py
I've made the artifact `xgboost_model_compatibility_test.zip` publicly accessible, so that developers can run 
the `test_model_compatibility` test locally.
=> [CI] Make Python model compatibility test runnable locally

demo/regression/machine.conf, jvm-packages/.gitignore, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/FeatureSizeValidatingSuite.scala, src/learner.cc, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/predictor/test_predictor.cc, tests/cpp/predictor/test_predictor.h, tests/python/test_cli.py, tests/python/test_demos.py, tests/python/testing.py
Fix https://github.com/dmlc/xgboost/issues/5709
Fix https://github.com/dmlc/xgboost/issues/5841
=> Fix prediction heuristic

R-package/R/utils.R, R-package/tests/testthat/test_custom_objective.R, demo/guide-python/custom_softmax.py, doc/parameter.rst, python-package/xgboost/core.py, src/learner.cc, tests/python/test_early_stopping.py
Close https://github.com/dmlc/xgboost/issues/5952 .
=> [Breaking] Fix custom metric for multi output.

python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
=> Disable feature validation on sklearn predict prob.

doc/tutorials/dask.rst, python-package/xgboost/dask.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_tracker.py, tests/python/test_with_dask.py
Closes https://github.com/dmlc/xgboost/issues/5639 .
~- [x] Rebase on #5408 .~
=> [BLOCKING] [Dask] Asyncio support.

include/xgboost/predictor.h, src/learner.cc, src/predictor/predictor.cc, src/tree/updater_quantile_hist.cc, tests/cpp/test_learner.cc
Also remove prediction cache mutex, which did not help: a race
condition still occured whenever the cache was cleaned but at the
same time entries pointing into the cache were alive.
=> [BLOCKING] Thread-safe prediction by making the prediction cache thread-local.

Jenkinsfile
Closes #5963. See diagnostic at https://github.com/dmlc/xgboost/issues/5963#issuecomment-667026573
#5873 depends on this PR.
Also add CUDA 10.0 -> 11.0 cross-version test.
=> [CI] Assign larger /dev/shm to NCCL

tests/python-gpu/test_gpu_with_dask.py
Mark `tests/python-gpu/test_gpu_with_dask:: test_with_asyncio` as `mgpu` so that it will run in a multi-GPU machine.
=> Add missing Pytest marks to AsyncIO unit test

python-package/xgboost/data.py, tests/python/test_dmatrix.py
Not critical as the missing field is converted to nan in `DMatrix.__init__`.  Just fixing the correctness of the helper function and making it self-contained.
=> Fix missing data warning.

src/gbm/gbtree_model.cc, tests/cpp/test_learner.cc
It's not a bug.  Right now the order is implicitly enforced, this PR makes it explicit.  Marked as blocking because with explicit behaviour, we can be sure there's no chance for mistake.
* Put in omp parallel.  On large number of trees this is about 20% faster, not very impressive so I can revert it if needed.
=> Force tree order in JSON.

python-package/xgboost/dask.py, tests/python/test_with_dask.py
Fixes https://github.com/dmlc/xgboost/issues/5984 .
=> Fix dask predict shape infer.

R-package/R/xgb.DMatrix.R, R-package/R/xgb.plot.importance.R, R-package/R/xgb.plot.shap.R, R-package/demo/interaction_constraints.R, R-package/tests/run_lint.R, R-package/tests/testthat/test_dmatrix.R, R-package/tests/testthat/test_helpers.R
This PR proposes adding a few more R linters that catch issues related to code correctness, per #5779. There are others available from `{lintr}`, but they are style-only things that are best left to maintainers.
The most important addition in this PR is `seq = lintr::seq_linter,`. That catches this case in R where unintended things can happen.
```r
x <- data.frame(m = rnorm(3))
for (i in 1:nrow(x)) {
print(i)
}
x <- data.frame()
for (i in 1:nrow(x)) {
print(i)
}
x <- data.frame()
for (i in seq_len(nrow(x))) {
print(i)
}
```
=> [R] fix uses of 1:length(x) and other small things

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala
https://github.com/dmlc/rabit/pull/143
=> Rabit update.

src/learner.cc, src/metric/elementwise_metric.cu, src/objective/regression_obj.cu
Merge 2 warnings into `ValidateDMatrix`.  Also now it works for all objectives and metrics.
=> Move warning about empty dataset.

python-package/xgboost/dask.py, tests/python/test_with_dask.py
Fixes #5985
This is cannot be merged before #5984 is resolved because [this line](https://github.com/jameskrach/xgboost/blob/fix-dask-sklearn-api/python-package/xgboost/dask.py#L1103) will raise an exception about there not being another axis if the model is a multiclass classifier.
=> [Breaking] Fix .predict() method and add .predict_proba() in xgboost.dask.DaskXGBClassifier

doc/build.rst, doc/parameter.rst
Fixes https://github.com/dmlc/xgboost/issues/5991
=> Fix nightly build doc. [skip ci]

src/common/hist_util.cc
Closes https://github.com/dmlc/xgboost/issues/5579 .  Just perform an reinterpret cast.
=> Remove warning about memset.

Jenkinsfile, Jenkinsfile-win64
If a branch or a pull requests receives successive pushes in a short duration of time, Jenkins may be running multiple builds. Only the latest build should be carried out and the others cancelled, to conserve CI resources.
=> [CI] Cancel builds on subsequent pushes

amalgamation/xgboost-all0.cc, demo/guide-python/feature_weights.py, demo/json-model/json_parser.py, doc/parameter.rst, include/xgboost/c_api.h, include/xgboost/data.h, python-package/xgboost/core.py, python-package/xgboost/data.py, python-package/xgboost/sklearn.py, src/c_api/c_api.cc, src/common/common.h, src/common/random.cc, src/common/random.h, src/data/data.cc, src/data/data.cu, src/tree/updater_colmaker.cc, src/tree/updater_gpu_hist.cu, src/tree/updater_quantile_hist.cc, tests/cpp/common/test_common.cc, tests/cpp/common/test_random.cc, tests/cpp/tree/test_gpu_hist.cu, tests/python-gpu/test_device_quantile_dmatrix.py, tests/python/test_demos.py, tests/python/test_dmatrix.py, tests/python/test_with_sklearn.py
Closes #3754, closes #5308 .  Currently supported tree methods: `exact`, `hist`, `gpu_hist`.
I spent some time on looking through the code base in hist, and want to unify it with `approx` and `grow_local_histmaker` in coming release.  So right now only 3 tree methods that use column sampler are supported.
The API also handles 4 different data types including f32, f64, uint32, uint64.  It can be further extended, but the important point is I think we should move toward more general data backend, otherwise we will be making an extra copy every time user specifies a different type than f32.  (the default type for numpy is f64).
=> Feature weights

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/DataUtils.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/DeterministicPartitioningSuite.scala
The functions featureValueOfSparseVector or featureValueOfDenseVector could return a Float.NaN if the input vector was containing any missing values. This would make fail the partition key computation and most of the rows would end up in the same partition and therefore leading to memory issues on one of the executor. We fixed this by avoid returning a NaN and simply use the row HashCode in this case.
We added a test to ensure that the repartition is indeed now uniform on input dataset containing missing values by checking that the partitions size variance is below a certain threshold.
Another remark about the computation of the key:
- If the values contained in your DataFrame are only below let's say 1e-4 / 1e-5, then this computation:
`rowHashCode.toLong + featureValue` is equivalent to …
=> [jvm-packages] Fix deterministic partitioning with dataset containing Double.NaN

include/xgboost/generic_parameters.h, tests/cpp/test_serialization.cc, tests/python/test_cli.py
Saving model is still using binary as default, but serialization like pickle will be default to JSON.
=> Make JSON the default full serialization format.

src/common/hist_util.h, src/common/quantile.cc, src/common/quantile.h, tests/cpp/c_api/test_c_api.cc, tests/cpp/common/test_hist_util.cc, tests/cpp/common/test_hist_util.h, tests/cpp/common/test_json.cc, tests/cpp/common/test_quantile.cc, tests/cpp/common/test_quantile.h, tests/python/test_with_dask.py
Follow up on https://github.com/dmlc/xgboost/pull/5880 . @ShvetsKS @SmirnovEgorRu   Previously sketching on URL dataset on distributed environment was not possible due to memory usage blow up.  After this PR I can unify the sketching for `hist` and `approx` and proceed with other refactoring to unify the codebase.
Also fixed a bug in distributed training with incorrect allreduce call, and added tests.
Previous perf is from #5880.
- URL
GmatInitialization: 10.3033s, 1 calls @ 10303323us
GmatInitialization: 10.2406s, 1 calls @ 10240576us
GmatInitialization: 10.224s, 1 calls @ 10224020us
- HIGGS
GmatInitialization: 3.74322s, 1 calls @ 3743224us
GmatInitialization: 3.63079s, 1 calls @ 3630793us
GmatInitialization: 3.67905s, 1 calls @ 3679049us
- HIGGS
GmatInitialization: 3.7794s, 1 calls @ …
=> Optimize cpu sketch allreduce for sparse data.

python-package/xgboost/core.py, src/common/group_data.h, src/data/data.cc
Observed https://github.com/dmlc/xgboost/issues/5530 slowdown in DMatrix creation was fixed.
Performance improvements:
Data set | DMatrix create time(master), s | DMatrix create time | Speedup
-- | -- | -- | --
airline-ohe with pandas DF | 13.25 |  8.3 |  1.6
airline-ohe as contiguous numpy| 6.6 |  1.75 |  3.7
higgs1m as contiguous numpy| 0.28 |  0.077 |  3.6
"Dmatrix create + Prediction" improvements (**depth = 1, n_iterations = 10**):
  | airline-ohe with pandas DF | airline-ohe contiguous numpy | higgs1m contiguous numpy
-- | -- | -- | --
Master | 13.37 | 6.8 | 0.296
Dmatrix Opt | 8.44 | 1.86 | 0.085
Speedup | 1.58 | 3.65 | 3.4
=> DMatrix optimizations

.github/workflows/main.yml
It's constantly failing on PR with network errors.  After the removal we still have win-latest.  Suggestions are welcomed.
=> Remove win2016 jvm github action test.

doc/jvm/index.rst, jvm-packages/README.md
* Add instructions for installing GPU-enabled XGBoost4J-Spark
* Update `jvm-packages/README.md` to refer to [our Maven repository](https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/list.html), to which our CI server automatically pushes SNAPSHOT builds.
* Add a note about Windows not being supported.
=> [jvm-packages] [doc] Update install doc for JVM packages

R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_callbacks.R, include/xgboost/base.h, include/xgboost/data.h, include/xgboost/span.h, include/xgboost/tree_model.h, python-package/xgboost/core.py, python-package/xgboost/sklearn.py, src/common/bitfield.h, src/common/categorical.h, src/common/json.cc, src/data/data.cc, src/tree/tree_model.cc, tests/cpp/tree/test_tree_model.cc
This PR includes expanding tree on categorical feature, saving/loading such trees.  It's partly extracted from https://github.com/dmlc/xgboost/pull/5949 , with changes that now the saved tree model contains actual categories instead of bitsets.
=> Expand categorical node.

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/BoosterParams.scala
related to issue  #5977. set the default value of maxBins to 256, align with c code. 
Looks all other parameters have the same default value.
=> [jvm-packages, Spark]  set maxBins to 256. Align with c code

include/xgboost/tree_model.h, src/common/host_device_vector.cu, src/predictor/gpu_predictor.cu
Accuracy and performance updates to submodule.
Moving the extract paths xgboost code to run on the GPU, easing the overheads of preprocessing large models from up to 3s -> 0.3s.
=> Updates to GPUTreeShap

demo/guide-python/external_memory.py
In the external memory Python demo, the suffixes that enable external memory were removed in PR #5651 (presumably inadvertently). This PR adds back the suffixes.
Cc: @trivialfis, @hcho3
=> Add cache name suffixes back to external_memory.py files.

CMakeLists.txt
Fixes #6085 by adding `objxgboost` to the install targets. Adding `objxgboost` to `install(TARGETS)` has no real impact but keeps CMake configuration happy:
* The `install(TARGETS)` command in line 277 does not specify any `DESTINATION` for `OBJECTS` targets, so object libraries will not be actually installed into the system prefix.
* We still need to specify `objxgboost`, according to the rule of `install(TARGETS)`: whenever we export a static library target, we need to export every dependency of it. Since `xgboost` is a static library, we need to also export `objxgboost`.
Here are the files that are installed by CMake:
<details><summary>BUILD_STATIC_LIB=ON</summary>
<p>
```
include/xgboost
include/xgboost/data.h
include/xgboost/tree_updater.h
include/xgboost/host_device_vector.h …
```
=> Fix CMake build with BUILD_STATIC_LIB option

src/CMakeLists.txt
On cmake 3.18 this will generate an error as `GPUTreeShap::GPUTreeShap` is an imported target and we didn't import it explicitly with `find_package`.
=> Don't link imported target.

demo/json-model/json_parser.py, doc/model.schema, src/tree/tree_model.cc
The field is deprecated and not used anywhere in XGBoost.
=> [Breaking] Don't save leaf child count in JSON.

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoostJNI.java, jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/Booster.scala, jvm-packages/xgboost4j/src/native/xgboost4j.cpp, jvm-packages/xgboost4j/src/native/xgboost4j.h, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/BoosterImplTest.java, jvm-packages/xgboost4j/src/test/scala/ml/dmlc/xgboost4j/scala/ScalaBoosterImplSuite.scala
This PR makes the functionality of XGBoosterGetNumFeature accessible from Java and Scala.
=> [jvm-packages] Add getNumFeature method

Jenkinsfile
#6096 merged Rabit's gtest into XGBoost's gtest, and as part of that Rabit's standalone test executables are now invoked by the CTest command.
CTest command is currently not working because it is run in the wrong working directory:
```
[2020-09-09T04:35:54.022Z] *********************************
[2020-09-09T04:35:54.022Z] No test configuration file found!
[2020-09-09T04:35:54.022Z] *********************************
[2020-09-09T04:35:54.022Z] Usage
[2020-09-09T04:35:54.022Z] 
[2020-09-09T04:35:54.022Z]   ctest [options]
[2020-09-09T04:35:54.022Z]
```
(https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/master/471/pipeline/58)
So change to the correct working directory before running CTest.
=> [CI] Fix CTest by running it in a correct directory

.github/workflows/main.yml, .travis.yml, plugin/CMakeLists.txt, src/common/threading_utils.h, tests/travis/run_test.sh, tests/travis/setup.sh
Fixes #6102 by avoiding a variable capture in `xgboost::common::ParallelFor2d`. This works around a compiler bug in AppleClang 11.0.3 while preserving the semantics.
Also, add MacOS Catalina to the testing matrix, which has AppleClang 11.0.3.
=> Work around a compiler bug in MacOS AppleClang 11

doc/jvm/xgboost4j_spark_tutorial.rst
doc for kill_spark_context_on_worker_failure
=> [Doc] add doc for kill_spark_context_on_worker_failure parameter

doc/build.rst, doc/jvm/index.rst
The latest xgboost 1.2.0 request cmake 3.13+, but the document has not been updated
=> The requirements for the CMAKE version in the document are wrong.

python-package/xgboost/dask.py
Prepare for more meta data support.
=> [dask] Refactor meta data handling.

include/xgboost/tree_model.h, src/tree/tree_model.cc
* This PR reduces the saved categories to a single vector instead of vector per-node.
=> Improve JSON format for categorical features.

python-package/xgboost/core.py, python-package/xgboost/dask.py, tests/python/test_survival.py, tests/python/test_with_dask.py
* label_lower_bound
* label_upper_bound
* base_margin
=> [dask] Support more meta data.

tests/ci_build/test_python.sh
I noticed that some tests are running too slow on CI recently.  This PR adds timing for each test.
=> Time GPU Python tests on CI.

R-package/configure, R-package/configure.ac
This PR proposes a fix for #6151 . I think it will resolve the WARNING on https://cran.r-project.org/web/checks/check_results_xgboost.html
```text
Version: 1.2.0.1
Check: whether package can be installed
Result: WARN
Found the following significant warnings:
WARNING: OpenMP is unavailable on this Mac OSX system. Training speed may be suboptimal.
Flavor: r-release-macos-x86_64
```
=> [R] remove warning in configure.ac (fixes #6151)

tests/ci_build/Dockerfile.gpu, tests/ci_build/Dockerfile.rmm
Follow-up to #6146 
This will ensure that XGBoost is compatible with RAPIDS 0.16.
=> [CI] Upgrade cuDF and RMM to 0.16 nightlies; upgrade to Ubuntu 18.04

doc/faq.rst
- consistent cases in headings
- add missing "the"
- plural: "missing values"
- add question marks to questions
=> cosmetic fixes in faq.rst

python-package/xgboost/data.py, tests/python/test_dmatrix.py
See https://discuss.xgboost.ai/t/sparse-matrix-no-longer-supported-in-scikit-learn/1850?u=hcho3. Previous versions of XGBoost used to support the COO sparse matrix but the latest (1.2.0) does not support it.
This pull request restores the support.
=> Add back support for scipy.sparse.coo_matrix

.github/workflows/main.yml, CMakeLists.txt, cmake/xgboost-config.cmake.in, demo/c-api/CMakeLists.txt, demo/c-api/c-api-demo.c
Closes #5910
* Fix building the static library with `BUILD_STATIC_LIB` option. The dmlc-core lib should also be installed.
* Revise `xgboost-config.cmake.in` to account of dependencies of XGBoost, such as OpenMP and Threads. We need to specify the dependencies so that applications linking with XGBoost will also link with these dependencies. Also log the XGBoost version when `find_package(xgboost)` is run:
```
-- Found XGBoost (found version "1.3.0")
```
* Update CMakeLists.txt in the C API demo to follow modern CMake practices.
* In CI, build and install the static library `libxgboost.a` into a system prefix. (Conda is used as an "sandboxed" prefix.)
* In CI, build and run the C API demo to make sure that we won't break it in the future.
=> [CI] Test C API demo

demo/c-api/c-api-demo.c
I had a bit of a hard time using the C API given that there aren't that many usage examples, so maybe this will be useful for people.
This PR extends the C API demo to construct a dense matrix using `XGDMatrixCreateFromMat`. I'm planning on adding additional examples for `XGDMatrixCreateFromCSREx`, `XGDMatrixCreateFromCSCEx`, but unfortunately I haven't been able to get those working yet.
The matrix being constructed is equivalent to the first line of the test data.z
```
alexanders-mbp:c-api alex$ make run
cc -O3 -I../../include -I../../dmlc-core/include -I../../rabit/include -L../../lib -o c-api-demo c-api-demo.c -lxgboost
LD_LIBRARY_PATH=../../lib ./c-api-demo
[17:32:50] 6513x127 matrix with 143286 entries loaded from ../data/agaricus.txt.train
[17:32:50] 1611x127 matrix with 35442 …
```
=> Add DMatrix usage examples to c-api-demo

python-package/xgboost/dask.py, tests/python/test_with_dask.py
Add `base_margin` to sklearn predict and predict_proba
Add `output_margin` to sklearn predict and predict_proba
Add `base_margin` to sklearn fit
Update `_get_worker_x_ordered` to `_get_worker_parts_ordered`. This allows us to get ordered base_margin to create the DMatrix object used for dispatched_predict
Add dask test to confirm this is functioning correctly. Mirrors the same test in `test_with_sklearn`
=> Update base margin dask

python-package/xgboost/core.py, python-package/xgboost/data.py, tests/python/test_with_modin.py, tests/python/test_with_pandas.py
=> Enable categorical data support on Python DMatrix.

src/common/device_helpers.cuh, src/common/hist_util.cu, src/common/hist_util.cuh, src/common/quantile.cu, src/common/quantile.cuh
* Revert RMM allocator detection on caching allocator.
* Use `thrust::device_vector` for sketching, the perf doesn't seem to have any visible change.
This means even if compiled with RMM, XGBoost will continue to allocate a small runtime memory outside of RMM pool.  This seems to be the cleanest way to proceed.  Other options are discussed in https://github.com/rapidsai/rmm/issues/583 .
cc @hcho3 @RAMitchell
=> Use default allocator in sketching.

CMakeLists.txt
Follow-up to #5590. The `HIDE_CXX_SYMBOLS` option is currently incomplete since it does not hide C++ symbols from dmlc-core. This pull request plugs the gap.
Before:
```
$ readelf -a --wide  lib/libxgboost.so | grep Open | grep LocalFileSystem
000000000b52a218  000006fd00000001 R_X86_64_64            0000000000528960 _ZN4dmlc2io15LocalFileSystem4OpenERKNS0_3URIEPKcb + 0
000000000b52a220  000007f700000001 R_X86_64_64            0000000000528150 _ZN4dmlc2io15LocalFileSystem11OpenForReadERKNS0_3URIEb + 0
1789: 0000000000528960  2457 FUNC    GLOBAL DEFAULT   12 _ZN4dmlc2io15LocalFileSystem4OpenERKNS0_3URIEPKcb
2039: 0000000000528150    19 FUNC    GLOBAL DEFAULT   12 _ZN4dmlc2io15LocalFileSystem11OpenForReadERKNS0_3URIEb
16349: 0000000000528960  2457 FUNC    GLOBAL DEFAULT   12 …
```
=> Hide C++ symbols from dmlc-core

R-package/tests/testthat/test_basic.R, R-package/tests/testthat/test_callbacks.R, R-package/tests/testthat/test_glm.R, demo/guide-python/custom_softmax.py, doc/parameter.rst, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, plugin/example/custom_obj.cc, plugin/updater_oneapi/regression_loss_oneapi.h, src/learner.cc, src/objective/multiclass_obj.cu, src/objective/regression_loss.h, tests/cpp/plugin/test_example_objective.cc, tests/python/test_basic.py, tests/python/test_basic_models.py, tests/python/test_dmatrix.py, tests/python/test_early_stopping.py, tests/python/test_with_dask.py, tests/python/test_with_pandas.py
Closes #6070.
Change default evaluation metric for binary classification to `"logloss"`, and for muli-class classification to "`mlogloss`".
=> [Breaking] Change default evaluation metric for classification to logloss / mlogloss

README.md
`style=plastic` is not necessary.
=> Consistent style for build status badge

include/xgboost/tree_model.h, src/predictor/cpu_predictor.cc, src/tree/updater_quantile_hist.cc
the main idea of this PR is keeping cache locality for predicted rows.
Results:
Data set | predict time (master), s | predict time (this PR), s | Speedup
-- | -- | -- | --
higgs1m | 4.12 | 1.32 | 3.12
msrank |  13.9 | 6.07 |  2.29
without Dmatrix create:
Data set | predict time (master), s | predict time (this PR), s | Speedup
-- | -- | -- | --
higgs1m | 4.12 - 0.25 | 1.32 - 0.25 | 3.62
msrank |  13.9 - 2.6 | 6.07 - 2.6 |  3.25
Data set | logloss (master) | logloss (this PR) 
-- | -- | -- 
higgs1m | 0.4036675 | 0.4036675 
msrank |  0.8550638 | 0.8550638
=> Predict improvement

demo/guide-python/callbacks.py, demo/guide-python/data_iterator.py, doc/python/callbacks.rst, doc/python/index.rst, python-package/xgboost/callback.py, python-package/xgboost/dask.py, python-package/xgboost/training.py, tests/python-gpu/test_gpu_basic_models.py, tests/python/test_basic_models.py, tests/python/test_callback.py, tests/python/test_demos.py, tests/python/test_with_dask.py, tests/python/testing.py
This PR adds a new callback function interface for Python, also a new type of callback for checkpointing is added.
Please see documentation and demo for details.  I added a demo for plotting animated evaluation scores, try it out. ;-)
Related https://github.com/dmlc/xgboost/pull/5612 I haven't made the parameter to dask.  The PR is already huge as it is.
Related https://github.com/dmlc/xgboost/issues/3822 this is only for Python.  Other language bindings are not supported.
Close https://github.com/dmlc/xgboost/issues/4955
Close https://github.com/dmlc/xgboost/issues/5495 now we can use early stopping on dask.
=> Rework Python callback functions.

src/common/device_helpers.cuh, src/common/hist_util.cu, src/data/simple_dmatrix.cu, tests/cpp/common/test_device_helpers.cu
Loop over batches with copy_if in DMatrix construction, because we get an int overflow with thrust. See: https://github.com/NVIDIA/thrust/issues/1302
=> Loop over copy_if

doc/tutorials/saving_model.rst, python-package/xgboost/core.py, python-package/xgboost/dask.py, src/common/device_helpers.cuh, src/data/device_adapter.cuh, src/data/ellpack_page.cu, src/tree/gpu_hist/histogram.cu, src/tree/updater_gpu_hist.cu, tests/cpp/common/test_device_helpers.cu, tests/cpp/data/test_ellpack_page.cu
* Document the limitation.
* Loop over `thrust::reduce`.
* Check the batch size.
=> Loop over reduce.

python-package/xgboost/dask.py, tests/python/test_with_dask.py
Close https://github.com/dmlc/xgboost/issues/6237
=> Fix typo in dask interface.

R-package/tests/testthat/test_callbacks.R, include/xgboost/generic_parameters.h, tests/cpp/test_serialization.cc, tests/python/test_cli.py
* Multi-class classification is checkpointing for each iteration.
This brings significant overhead.
=> Disable JSON full serialization for now.

tests/python-gpu/conftest.py
The introduction of the RMM plugin has nearly doubled the size of the Python test suite. Reduce the burden on our CI system by excluding a few heavy unit tests when RMM is enabled (with `--use-rmm-pool` flag to Pytest)
=> [CI] Reduce testing load with RMM

.github/FUNDING.yml
Since the website contains some additional information and [GitHub allows to display custom links](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository), we should probably add this to the sponsors button as well.
=> Add sponsors link to FUNDING.yml

src/gbm/gblinear.cc, tests/cpp/gbm/test_gblinear.cc, tests/python-gpu/test_gpu_linear.py
Close https://github.com/dmlc/xgboost/issues/6235
=> Fix linear gpu input

src/common/threading_utils.h, src/data/data.cc, src/data/simple_dmatrix.cc, src/learner.cc, tests/cpp/common/test_threading_utils.cc
Close https://github.com/dmlc/xgboost/issues/5703
Close https://github.com/dmlc/xgboost/pull/4975
=> Unify thread configuration.

demo/guide-python/sklearn_examples.py, demo/guide-python/sklearn_parallel.py, doc/parameter.rst, python-package/xgboost/sklearn.py, tests/ci_build/test_python.sh, tests/python/test_demos.py, tests/python/test_early_stopping.py, tests/python/test_with_dask.py, tests/python/testing.py, tests/travis/run_test.sh
#6186 made parallel training as default.  But it seems on Jenkins thread contention is severe when used with sklearn.  I can only reproduce 1 slowdown in a demo.  So timing the tests on CI.
=> Time the CPU tests on Jenkins.

tests/python/testing.py
The current typo causes the scikit-learn test suite to be skipped on x86-64. Sorry for not catching this typo in my last review.
=> Fix a typo in is_arm() in testing.py

python-package/xgboost/training.py, tests/python/test_callback.py
`DeprecationWarning` is not visible by default, so use `UserWarning` when the old-style callback is used.
=> Use UserWarning for old callback, as DeprecationWarning is not visible

python-package/xgboost/sklearn.py, tests/python-gpu/test_from_cudf.py, tests/python-gpu/test_from_cupy.py, tests/python/test_with_sklearn.py
=> Deprecate LabelEncoder in XGBClassifier; Enable cuDF/cuPy inputs in XGBClassifier

plugin/example/README.md
Fixed an example of CMake rule so that it can successfully build a plugin.
=> Update plugin instructions for CMake build

tests/ci_build/Dockerfile.gpu_build, tests/ci_build/Dockerfile.gpu_build_centos6, tests/ci_build/Dockerfile.jvm_gpu_build, tests/ci_build/Dockerfile.rmm, tests/ci_build/ci_build.sh
A few weeks ago [on Twitter](https://twitter.com/b0rk/status/1315831992253116417), I learned about [`shellcheck`](https://github.com/koalaman/shellcheck), a linter for shell scripts. To try to learn it tonight, I've been trying it out on a few repos that I know have a lot of shell scripts.
While running it over `xgboost` tonight, I found a minor issue that I think should be fixed: `egrep` is deprecated and can be replaced with `grep -E`.
From [the grep docs](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/grep.html) (which are linked by [the shellcheck docs for this issue](https://github.com/koalaman/shellcheck/wiki/SC2196):
> This grep has been enhanced in an upwards-compatible way to provide the exact functionality of the historical egrep and fgrep commands as well. It was …
=> [ci] replace 'egrep' with 'grep -E'

tests/ci_build/ci_build.sh
Closes #6301. This will greatly reduce the number of times the Docker container images are re-built.
#6202 introduced a subtle bug that pushed all GPU containers to the same registry `xgb-ci.gpu`, regardless of their CUDA version used. With this patch, GPU containers will be pushed to appropriate registries that are labeled with CUDA versions: `xgb-ci.gpu10.0`, `xgb-ci.gpu10.2`, and `xgb-ci.gpu11.0`.
=> [CI] Use separate Docker cache for each CUDA version

Jenkinsfile-win64, src/CMakeLists.txt, src/predictor/predictor.cc, tests/cpp/common/test_span.cu, tests/cpp/common/test_transform_range.cc, tests/cpp/common/test_transform_range.cu
See https://github.com/dmlc/xgboost/issues/6293 for details.  The speedup may help some build machines for distribution, but I don't think it's useful for daily development.  XGBoost's CPU compilation time on my machine is usually within a minute so not much room for improvement.
Update: Will be enabled on Windows CI.
Close https://github.com/dmlc/xgboost/issues/6293 .
=> Support unity build.

R-package/R/xgb.plot.importance.R
Closes #4863
I was looking for [issues tagged r-package](https://github.com/dmlc/xgboost/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+r-package%22) tonight and found #4863 . I think this PR fixes it.
Currently, `xgb.plot.importance()` overwrites all of the graphical parameters when it exits, which means that consecutive calls don't respect `par(mfcol)`, and don't fill a grid. This PR changes that, and just resets the specific value `mar` in the parameters.
Here are the results on 4 consecutive calls of `xgb.plot.importance()`:
**before**
**after**
<details><summary>code (click me)</summary>
```r
library(data.table)
data(agaricus.train, package = "xgboost")
bst <- xgboost::xgboost(
data = agaricus.train$data
, label = agaricus.train$label
, max_depth = 3
, eta = 1
, nthread = 2
, …
```
=> [R] allow xgb.plot.importance() calls to fill a grid (fixes #4863)

python-package/xgboost/training.py, tests/python/test_callback.py
Copy the user provided callback parameter.  Python is pass by reference, manipulating parameter directly has unexpected result.
Close https://github.com/dmlc/xgboost/issues/6319 .
=> Fix Python callback.

python-package/xgboost/dask.py, tests/python/test_with_dask.py
* Unify the meta info handling for training and prediction.
=> [dask] Fix prediction on `DaskDMatrix` with multiple meta data.

doc/jvm/xgboost4j_spark_tutorial.rst, doc/python/callbacks.rst, doc/python/index.rst, doc/python/model.rst, include/xgboost/c_api.h, include/xgboost/gbm.h, include/xgboost/learner.h, python-package/xgboost/callback.py, python-package/xgboost/core.py, python-package/xgboost/training.py, src/c_api/c_api.cc, src/gbm/gbtree.cc, src/gbm/gbtree.h, src/gbm/gbtree_model.cc, src/gbm/gbtree_model.h, src/learner.cc, tests/cpp/gbm/test_gbtree.cc, tests/cpp/test_learner.cc, tests/python/test_basic_models.py, tests/python/test_callback.py
This PR is meant the end the confusion around `best_ntree_limit` and unify model slicing.  We have multi-class and random forests, asking users to understand how to set `ntree_limit` is difficult and error prone.
Close #5531 Close #4052.
* Implement the `save_best` option in early stopping.
* Negative index is not supported.
=> Support slicing tree model

.gitignore
While working on #6345 , I found that some files generated by running the code in https://xgboost.readthedocs.io/en/latest/tutorials/dask.html#overview aren't ignored by `.gitignore`, and I think they should be.
* `dask-worker-space/`: directory automatically created by Dask for when it needs to spill to disk
* `.ipynb_checkpoints`: checkpoint files or Jupyter notebooks
I just made the same PR over in LightGBM (https://github.com/microsoft/LightGBM/pull/3527) 😀 
=> [dask] ignore files from local Dask development

doc/parameter.rst, include/xgboost/generic_parameters.h, src/learner.cc, tests/cpp/test_learner.cc
Close https://github.com/dmlc/xgboost/issues/5443 .
=> Avoid setting seed for every configuration.

src/predictor/cpu_predictor.cc
guided schedule affects predict by each tree during training 
santander, train |  guided, s | static, s | Speedup
-- | -- | -- | --
PredictRaw| 97.4115 | 50.663 | 1.92
Full train | 324.56 | 271.57 | 1.2
No significant impact on full (usage of all trees in model) predict stage.
=> Simple fix for PredictRaw kernel performance

doc/build.rst, python-package/setup.py, python-package/xgboost/libpath.py
Another attempt on https://github.com/dmlc/xgboost/pull/6292 .  Differences:
- `sysconfig.get_config_var('LIBDIR')` in #6292 is not used here as I think `sys.prefix + 'lib'` should be sufficient although I haven't tested it on freebsd.  `sys.prefix` can be altered by `virtualenv` while `sysconfig` is invariant.
- `setup.py` is changed to omit building or copying `libxgboost.so` when the user option `--use-system-libxgboost` is specified.  So the Python package will not contain a redundant shared object.  Combined with the ordering of candidate paths in `find_lib`, correct `libxgboost.so` should be loaded.
Closes #6291 
Closes #5705
=> Support shared library in system path.

include/xgboost/gbm.h, include/xgboost/predictor.h, src/gbm/gblinear.cc, src/gbm/gbtree.h, src/learner.cc, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, tests/cpp/helpers.cc, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu, tests/python-gpu/test_gpu_prediction.py, tests/python/test_predict.py
* Add tests.
Close https://github.com/dmlc/xgboost/issues/5847 .
=> Implement GPU predict leaf.

python-package/xgboost/dask.py, tests/python-gpu/conftest.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_tracker.py, tests/python/test_with_dask.py
Close https://github.com/dmlc/xgboost/issues/5765
* Use `socket` from Python.
* Only use workers associated with input data instead of all workers from client.  This avoids accessing `client.scheduler_info()['workers']`.
* Avoid calling `client.gather` inside task function.
~XGBoost still cannot be run on GKE yet.~  See https://github.com/dask/dask/issues/6800 for details.
=> [dask] Fix running on k8s.

doc/tutorials/dask.rst
Hello! I've been getting more familiar with the XGBoost Dask interface, as part of https://github.com/dask/community/issues/104. I was working through the documentation at https://xgboost.readthedocs.io/en/latest/tutorials/dask.html#overview tonight, and I'd like to suggest an improvement to them.
This PR proposes adding some Dask Array code to generate random data, instead of relying on users to figure that out themselves based on a code comment. I think making the examples easy to run by just copying and pasting will make it easier for users to start experimenting with `xgboost.dask`.
This also proposes adding links to the Dask DataFrame and Dask Array documentation, to help users who might not be familiar with those collections.
=> [docs] [dask] make Dask distributed example copy-pastable

R-package/R/callbacks.R
Closes #5935. Unfortunately, no unit test was added, because it's quite difficult to setup an environment with noLD R (it involves building R from the source with a custom flag).
@vnijs @jameslamb  Can you review?
=> [R] Fix a crash that occurs with noLD R

.github/workflows/main.yml, .github/workflows/r_nold.yml, R-package/DESCRIPTION, R-package/tests/testthat/test_callbacks.R, doc/contrib/ci.rst, doc/contrib/index.rst
Address comment https://github.com/dmlc/xgboost/pull/6378#issuecomment-725861901 https://github.com/dmlc/xgboost/pull/6378#issuecomment-725867810
* Add a unit test to cover the edge case that previously had failed in noLD R environment
* Use the Docker container `rhub/debian-gcc-devel-nold` to set up noLD R environment
* Make the test optional. The test must be manually invoked by adding a pull request comment `/gha run r-nold-test`
Example run: https://github.com/hcho3/xgboost/runs/1389096410
cc @jameslamb @vnijs
=> [CI] Add noLD R test

src/metric/survival_metric.cu, tests/python/test_survival.py, tests/python/test_with_dask.py
=> [dask] Allow empty data matrix in AFT survival

python-package/xgboost/core.py, python-package/xgboost/dask.py, python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
Deprecate positional arguments in following functions:
- `__init__` for all classes in sklearn module.
- `fit` method for all classes in sklearn module.
- `set_info` for `DMatrix` class.
Refactor the evaluation matrices handling.
Close https://github.com/dmlc/xgboost/issues/6172 .
=> Deprecate positional arguments.

python-package/xgboost/dask.py, tests/python/test_with_dask.py
* Fix union of workers.
* Submit with future of `DMatrix` directly, simplifying training.
* Avoid the use of `**kwargs`.
=> [dask] Fix union of workers.

python-package/xgboost/dask.py
Small cleanup left from https://github.com/dmlc/xgboost/pull/6375 .  I tried to replace the future object in previous PR with delayed.  But somehow rabit have the wrong rank.
=> [dask] Small cleanup.

src/common/threading_utils.h, src/data/data.cc, src/data/simple_dmatrix.cc
Recently introduced `OmpSetNumThreads` function brings up to 2x slowdown on HW with enabled Hyper-threading.
DMatrix create time| master, s | this PR, s | Speedup
-- | -- | -- | --
mortgage | 11.67 | 5.68 | 2.05
higgs | 0.96 | 0.51 | 1.88
msrank | 4.36 | 3.53 | 1.23
It significantly affects inference stage as was mentioned in https://github.com/dmlc/xgboost/issues/6283.
Reason: there is still overheads on memory allocation\initialization (`InitBudget`, `InitStorage`) so there is no gain from usage HT here.
=> Disable HT for DMatrix creation

R-package/R/utils.R
This PR comes from https://github.com/dmlc/xgboost/pull/6380#discussion_r521858878. There are some places in the R package where `exists()` is being used to check a value in a list, but like I mentioned in that comment this is potentially unsafe.
This PR just eliminates those cases. When you  try to access a non-exists element in a list in R, it just returns `NULL`. So `if (exists("objective", where = params) && is.character(params$objective)` will always give the same answer as `if (is.character(params$objective))`.
Thanks for your time and consideration
=> [R] remove uses of exists()

.travis.yml, tests/travis/run_test.sh
Homebrew just added support for MacOS Big Sur (11.0) and dropped High Sierra (10.13), according to their policy of supporting three latest MacOS releases. So we require MacOS Mojave from now on.
@trivialfis This should unblock the CI.
=> [CI] Upgrade to MacOS Mojave image

src/tree/split_evaluator.h
* Pass by reference instead of value
* Remove unused parameter.
=> Small cleanup to evaluator.

python-package/xgboost/dask.py
Close https://github.com/dmlc/xgboost/issues/6407 .
=> Fix dask predict

cmake/RPackageInstallTargetSetup.cmake
Closes #6421 
The expression `src/*` is a globbing pattern and not a regular expression. So in the `install` command, we need to use the `PATTERN` keyword to specify the exclusion pattern `src/*`.
**Why did we not find the bug so far?**
The `src/*` expression is an ill-formed regular expression and thus triggers a platform-specific behavior, which broke installation of the R package only on some platforms:
* On Ubuntu and MacOS, `src/*` was interpreted as the set of all files under the `src/` directory. So only the files under `src/` directory got excluded from copying. With this behavior, installation works fine:
```
Install the project...
-- Install configuration: "Release"
-- Installing: /home/hcho3/src/xgboost/build/R-package-install/R-package
-- Installing: …
```
=> [R] Fix R package installation via CMake

tests/ci_build/Dockerfile.gpu, tests/ci_build/Dockerfile.rmm
This will ensure that XGBoost is compatible with RAPIDS 0.17.
=> [CI] Upgrade cuDF and RMM to 0.17 nightlies

include/xgboost/generic_parameters.h, src/learner.cc, src/predictor/gpu_predictor.cu, tests/python-gpu/test_gpu_basic_models.py
I need a way to find out how many GPUs are available in the system. The current behaviour is that XGBoost just replaces invalid gpu IDs with a valid one. I would like to add a param that allows me to switch this off.
=> Optionaly fail when gpu_id is set to invalid value

python-package/xgboost/config.py
Follow-up to #6414
The `versionadded` field of `set_config` should be 1.4.0, since global configuration won't be part of the upcoming 1.3.0 release.
=> Fix docstring of config.py to use correct versionadded

.travis.yml, Jenkinsfile, tests/ci_build/CentOS-Base.repo, tests/ci_build/Dockerfile.gpu_build_centos6, tests/ci_build/conda_env/aarch64_test.yml, tests/travis/run_test.sh
Run `auditwheel repair` command to vendor (bundle) `libgomp.so` inside the Python wheel. This is required by the Python packaging standard. See https://github.com/dmlc/xgboost/pull/6253#issuecomment-738188907. In practice, CentOS does not install `libgomp`, so vendoring libgomp in the wheel lets CentOS users to use XGBoost out-of-the-box.
Note: After 1.3.0 release, we should upgrade the Docker image to CentOS 7, as CentOS 6 reached EOL.
=> Vendor libgomp in the manylinux Python wheel

tests/ci_build/Dockerfile.jvm, tests/ci_build/Dockerfile.jvm_gpu_build
CentOS 6 has reached its end-of-life on Nov 30, and the repositories are no longer available.
For now, switch to the vault repository to repair the CentOS images.
=> [CI] Fix CentOS 6 Docker images

python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
Fix https://github.com/dmlc/xgboost/issues/6460 .
=> Fix filtering callable objects in skl xgb param.

python-package/xgboost/core.py, python-package/xgboost/dask.py, tests/python/test_with_dask.py
Close https://github.com/dmlc/xgboost/issues/6268 .
The script provided by @pseudotensor still fails due to auc doesn't handle empty dataset.  But that will be tracked in https://github.com/dmlc/xgboost/issues/6272 .
=> Don't validate feature when number of rows is 0.

python-package/xgboost/dask.py, python-package/xgboost/tracker.py
This adopts the solution used in https://github.com/dask/dask-xgboost/pull/40 which employs the `get_host_ip` from dmlc-core tracker.  It was referred in https://github.com/dmlc/xgboost/issues/5765 .
Close https://github.com/dmlc/xgboost/issues/6469 .
TODOs
=> Fix dask ip resolution.

src/predictor/gpu_predictor.cu, tests/python-gpu/test_gpu_prediction.py
The GPU predictor was producing incorrect prediction for models with categorical splits, because the whole `d_tree_split_types` span was being passed to the `GetLeafWeight` kernel, when the kernel had expected a subspan corresponding to a single tree.
This PR also adds a test example that fails with the current code and passes with the proposed patch.
=> Pass correct split_type to GPU predictor

doc/tutorials/dask.rst, python-package/xgboost/dask.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_with_dask.py, tests/python/test_with_sklearn.py
* Add eval_metric.
* Add custom objective.
* Add callback.
* Add feature weights.
=> [dask] Complete features in regressor and classifier.

NEWS.md, dev/query_contributors.py
=> Add release note for 1.3.0 in NEWS.md

python-package/xgboost/callback.py, tests/python/test_callback.py
Currently `verbose_eval` parameter is not taking into account due simple typo in callback.py
If we set `verbose_eval=100` print log is:
[1] eval-auc:0.54791 train-auc:0.54620
...
[98] eval-auc:0.88926 train-auc:0.90105
[99] eval-auc:0.88921 train-auc:0.90110
[101] eval-auc:0.88928 train-auc:0.90114
...
After fix:
[0] eval-auc:0.53902 train-auc:0.53251
[100] eval-auc:0.88931 train-auc:0.90116
...
Similar to v1.2.0 print log
=> Fix handling of print period in EvaluationMonitor

doc/tutorials/dask.rst
I've been testing the new Dask features released in XGBoost 1.3.0 recently. Thanks so much for all the hard work!
I was trying to use early stopping and couldn't figure out what the expectation was for passing validation sets. This PR proposes adding a small section on evaluation + early stopping to the Dask tutorial. I think it might help people who are trying to figure this out, and it brings some attention to this new feature.
=> [doc] [dask] Add example on early stopping with Dask

python-package/xgboost/dask.py
Related https://github.com/dmlc/xgboost/issues/6364 .  Let the assert error show partition status for easier debugging in the future.
=> Show partition status in dask error.

src/tree/updater_quantile_hist.cc
This PR is connected with #6411 
Discarding elements from generators takes up most of the working time in `InitSampling`.
Since stdlibc++ doesn't have any random engines with o(n) complexity (little-o), we only can optimize the number of discarded elements.
`std::bernoulli_distribution` requires 64-bit input, so in previous version we had to discard twice as much elements as now.
This little optimization gives us ~2.12 speed up of `InitSampling` time, which translates into up to 16% speed up of the whole training time when `subsampling < 1`
The quality remains the same:
Mortgage dataset |  |  |
-- | -- | --
version | training time | RMSE
original | 35.479 | 0.009271
optimized | 30.538 | 0.009262
Santander dataset |   |   |  | |
-- | -- | -- | -- | --
version | training time, s | InitData …
=> Improved InitSampling function speed by 2.12 times

src/common/hist_util.cu, tests/cpp/common/test_hist_util.cu
Related: https://github.com/dmlc/xgboost/issues/6503 .
=> Support categorical data in GPU weighted sketching.

python-package/xgboost/core.py, src/data/data.cc, tests/python/test_dmatrix.py
Close https://github.com/dmlc/xgboost/issues/6324 .
=> Accept numpy array for DMatrix slice index.

include/xgboost/c_api.h
After upgrading XGBoost to the master version, I found that when I set the param num_col to 0 as usual in `XGDMatrixCreateFromFile`, it could not get the correct columns. 
Signed-off-by: Hao Ziyu <haoziyu@qiyi.com>
=> Update the comments

doc/tutorials/saving_model.rst, include/xgboost/generic_parameters.h, src/learner.cc, tests/python/test_pickling.py, tests/python/test_training_continuation.py
* Remove saving binary snapshot.  Loading is preserved for now.
=> Drop binary format for memory snapshot.

src/common/device_helpers.cuh, tests/ci_build/Dockerfile.gpu, tests/ci_build/Dockerfile.rmm
Also update the RMM plugin code to account for the updated signature of the template class `rmm::mr::thrust_allocator<T>` (https://github.com/rapidsai/rmm/pull/647).
cc @harrism @jrhemstad
=> [Breaking] Upgrade cuDF and RMM to 0.18 nightlies; require RMM 0.18+ for RMM plugin

R-package/tests/helper_scripts/generate_models.R, R-package/tests/testthat/test_model_compatibility.R, src/learner.cc, src/objective/regression_loss.h, tests/python/generate_models.py, tests/python/test_model_compatibility.py
Closes #6509 
* Override `ProbToMargin()` for the `binary:logitraw` objective, since no transformation is necessary.
* Augment model compatibility suite with `binary:logitraw`. I also updated the files `xgboost_model_compatibility_test.zip` and `xgboost_r_model_compatibility_test.zip`.
=> Enable loading model from <1.0.0 trained with objective='binary:logitraw'

include/xgboost/c_api.h, include/xgboost/gbm.h, include/xgboost/learner.h, python-package/xgboost/callback.py, python-package/xgboost/core.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py, src/c_api/c_api.cc, src/gbm/gblinear.cc, src/gbm/gblinear_model.h, src/gbm/gbtree.h, src/learner.cc, tests/python/test_basic_models.py, tests/python/test_callback.py, tests/python/test_early_stopping.py, tests/python/test_with_sklearn.py
Close https://github.com/dmlc/xgboost/issues/6322
Close https://github.com/dmlc/xgboost/issues/6514
Close https://github.com/dmlc/xgboost/issues/5192 .
=> Support early stopping with training continuation, correct num boosted rounds.

python-package/xgboost/sklearn.py
Closes #6527
`cupy.array_equal` was added in cuPy 8.0 and is not available in cuPy 7.8.
=> Remove cupy.array_equal, since it's not compatible with cuPy 7.8

demo/README.md
@saturncloud has put up an [excellent tutorial on using XGBoost with Dask](https://www.saturncloud.io/docs/tutorials/xgboost/). It's informative, accessible, and gives many concrete advice. I believe this tutorial would make a great addition to `demo/README.md`.
cc @jameslamb
=> Add Saturn Cloud Dask XGBoost tutorial to Awesome XGBoost

R-package/R/xgb.Booster.R, R-package/R/xgb.DMatrix.R, R-package/R/xgb.DMatrix.save.R, R-package/R/xgb.dump.R, R-package/R/xgb.save.R, python-package/xgboost/core.py, python-package/xgboost/data.py
According to https://discuss.xgboost.ai/t/xgb-save-setting-a-file-path/2020/7?u=hcho3, XGBoost could not handle path containing `~`, the shorthand for the home directory on Linux and MacOS platforms. This PR enables XGBoost to handle such paths, by expanding `~` in paths into the full path of the home directory.
Example:
```R
xgb.save(bst, '~/Desktop/xgboost/test.model')
```
The fix uses `os.path.expanduser` (Python) and `path.expand` (R).
=> Expand `~` into the home directory on Linux and MacOS

src/metric/elementwise_metric.cu
For the `gamma-nloglik` eval metric, small positive values in the labels are causing `NaN`'s in the outputs, as reported here: https://github.com/dmlc/xgboost/issues/5349. This will add clipping on them, similar to what is done in other metrics like `poisson-nloglik` and `logloss`.
=> Clip small positive values in gamma-nloglik

dev/release-tarball.sh, tests/ci_build/ci_build.sh
I created a script for generating source tarball for release, with this we can generate a compressed tarball containing xgboost source code and all git submodules, but without git history.  The tarball is meant to be uploaded to our release page, so individual who want to deploy or package xgboost can eliminate git as a build dependency.
I'm not sure if we want to support this as part of the future releases and would like to hear inputs from @hcho3.  I will come back to this after holiday.
=> Add script for generating release tarball.

python-package/xgboost/dask.py, python-package/xgboost/sklearn.py, tests/ci_build/conda_env/win64_test.yml
* New Scikit-Learn version uses keyword argument, and `X` is the predefined
keyword.
Fix CI failure in https://github.com/dmlc/xgboost/pull/6554 and https://github.com/dmlc/xgboost/pull/6550 .
=> [Breaking] Rename `data` to `X` in `predict_proba`.

.github/workflows/main.yml, doc/conf.py, python-package/xgboost/core.py, python-package/xgboost/dask.py, python-package/xgboost/libpath.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_with_dask.py
Related https://github.com/dmlc/xgboost/issues/6496 .
* Add type hints to dask interface.
* Add a `py.typed` file to python package.  See https://www.python.org/dev/peps/pep-0561/#id18 for details.
* Add various parameters to match the interface with single node.
=> [dask] Add type hints.

.gitignore
This PR proposes adding some rules to `.gitignore` to prevent sensitive information like passwords and access keys from being checked into source control.
I've added common extensions for key material, plus the specific files that the AWS CLI docs encourage people to create: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html.
=> add credentials to .gitignore

python-package/xgboost/sklearn.py
Closes #6536
Calling `fit()` twice with a scikit-learn model object should cause the model to be cleared, e.g.
```python
from sklearn.datasets import load_boston
X, y = load_boston(return_X_y=True)
clf = xgb.XGBRegressor(n_estimators=5, max_depth=3, tree_method='hist', objective='reg:squarederror')
clf.fit(X, y, eval_set=[(X, y)])
clf.fit(X, y, eval_set=[(X, y)])  # should start training from scratch
```
Expected output:
```
[0]	validation_0-rmse:17.08995
[1]	validation_0-rmse:12.32976
[2]	validation_0-rmse:9.03587
[3]	validation_0-rmse:6.76642
[4]	validation_0-rmse:5.22241
[0]	validation_0-rmse:17.08995
[1]	validation_0-rmse:12.32976
[2]	validation_0-rmse:9.03587
[3]	validation_0-rmse:6.76642
[4]	validation_0-rmse:5.22241
```
Currently, XGBoost will automatically …
=> Calling XGBModel.fit() should clear the Booster by default

python-package/MANIFEST.in
This PR fixes #6560.
Right now, the packages at https://pypi.org/project/xgboost/#files include some files like documentation and tests that I think could be safely removed. This PR proposes making the rules in `MANIFEST.in` more specific, to reduce the size of distributions of the Python package.
|                                        |  `master`  | this PR   |
|:-----------------------:|:----------:|:--------:|
| sdist (compressed)       |     772K      |  664K    |
| sdist (uncompressed)   |     4.2M      |   3.5M    |
<details><summary>how I calculated these sizes</summary>
```shell
pushd python-package
rm -rf xgboost.egg-info
rm -rf dist/
rm -rf __pycache__
rm -rf build/
echo ""
echo "building source distribution"
echo ""
python setup.py sdist > /dev/null
cp …
```
=> [python-package] remove unnecessary files to reduce sdist size (fixes #6560)

include/xgboost/base.h, rabit/include/rabit/internal/socket.h
Related: https://github.com/dmlc/xgboost/issues/6542
I ran a test on https://builder.r-hub.io/ mentioned by @hcho3 .  The rabit issue is fixed, but the toolchain itself on the test machine seems a bit weird.
os: Oracle Solaris 10, x86, 32 bit, R-release.  A snippet of log is copied here, complete log is uploaded at the end.
```
./dmlc-core/include/dmlc/./base.h:207:65: note: #pragma message: Warning: FILE OFFSET BITS defined to be 32 bit
#pragma message("Warning: FILE OFFSET BITS defined to be 32 bit")
^
In file included from /opt/csw/include/c++/5.5.0/tr1/random:46:0,
from /opt/csw/include/c++/5.5.0/parallel/random_number.h:36,
from /opt/csw/include/c++/5.5.0/parallel/partition.h:38,
from /opt/csw/include/c++/5.5.0/parallel/quicksort.h:36,
from …
```
=> Support Solaris.

python-package/xgboost/sklearn.py, tests/python/test_with_dask.py, tests/python/test_with_sklearn.py
For more info, see: https://scikit-learn.org/stable/developers/develop.html#estimator-types
* Model trained from dask can be loaded by single node skl interface.  Close https://github.com/dmlc/xgboost/issues/6547 .
=> Support `_estimator_type`.

include/xgboost/base.h, rabit/include/rabit/internal/socket.h
* Add system header.
* Remove use of TR1 on Solaris
Co-authored-by: Hyunsu Cho <chohyu01@cs.washington.edu>
=> [backport] Support Solaris. (#6578)

tests/python-gpu/test_gpu_with_dask.py, tests/python/test_with_dask.py
The client fixture is not reset for each hypothesis test case and it's fine for xgboost.
=> Suppress hypothesis health check for dask client.

include/xgboost/data.h, src/common/hist_util.cc, src/data/data.cc, src/data/simple_dmatrix.cc, src/gbm/gblinear.cc, src/gbm/gbtree.cc, src/linear/coordinate_common.h, src/linear/updater_gpu_coordinate.cu, src/linear/updater_shotgun.cc, src/predictor/cpu_predictor.cc, src/tree/updater_basemaker-inl.h, src/tree/updater_colmaker.cc, src/tree/updater_histmaker.cc, src/tree/updater_refresh.cc, tests/cpp/c_api/test_c_api.cc, tests/cpp/common/test_hist_util.h, tests/cpp/data/test_adapter.cc, tests/cpp/data/test_data.cc, tests/cpp/data/test_simple_dmatrix.cc, tests/cpp/data/test_simple_dmatrix.cu, tests/cpp/data/test_sparse_page_dmatrix.cc, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/tree/test_quantile_hist.cc
This is to prevent race access of `host_device_vector.HostVector()`.  We have fixed a few bugs caused by the `[]` operator in `SparsePage`, but I encountered a new one in `SparsePage.GetTranspose()` today.  This PR is for nuking the `operator[]` to prevent any related bug in the future.
From now on, accessing instances in `SparsePage` must go through a `SparsePageView`, which contains span to host data.  No change is made to GPU code since the `operator[]` is not available on device code.
=> Remove instance access to SparsePage.

python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
* Remove duplicated code, which fixes typo `evals_result` -> `evals_result_`.
=> [backport] Fix evaluation result for XGBRanker. (#6594)

python-package/xgboost/core.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py, tests/python/test_basic_models.py
* Use inheritance to remove duplicated code.
* Fix attributes not being restored.
* Rename all `data` to `X`. [breaking]
=>   [breaking] Remove duplicated predict functions, Fix attributes IO. 

python-package/xgboost/training.py, tests/python/test_predict.py, tests/python/test_training_continuation.py, tests/python/test_with_sklearn.py
The old (before fix) best_ntree_limit ignores the num_class parameters, which is incorrect. In before we workarounded it in c++ layer to avoid possible breaking changes on other language bindings. But the Python interpretation stayed incorrect. The PR fixed that in Python to consider num_class, but didn't remove the old workaround, so tree calculation in predictor is incorrect, see PredictBatch in CPUPredictor.
=> [backport] Revert ntree limit fix (#6616)

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
there is a possibility that onJobStart of TaskFailedListener won't be called, if
the job is submitted before the other thread call addSparkListener.
detail can be found at https://github.com/dmlc/xgboost/pull/6019#issuecomment-760937628
=> [jvm-packages] fix potential TaskFailedListener's callback won't be called

python-package/xgboost/rabit.py, python-package/xgboost/tracker.py, tests/python/test_with_dask.py
The dask training doesn't print out the evaluation result even if one passes the `verbose_eval` argument.  This PR fixes it.  I don't know how to setup a test as the printing is not done in current process so the stdout cannot be easily captured.
=> Use simple print in tracker print function.

jvm-packages/create_jni.py, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/NativeLibLoader.java
This PR modifies the JVM library loader, the `create_jni.py` script and the jar file structure so that the native libraries are stored in `/lib/<os_name>/<arch_name>/<library_name>` inside the jar. This means you can pack all the native libraries into a single jar file and have it work on all the supported platforms.
I need to double check that the Windows values reported by Python's `platform.machine()` are correct, I've tested Linux x86_64 and macOS arm64 and x86_64. I think it might be missing some values for Linux arm64 as it looks like that might report itself as armv8 or a variety of other things, but I don't have access to such a machine to check. The JVM will always report 64-bit ARM as `aarch64` so it's only the mapping in `create_jni.py` that will need updating. I poked in …
=> [jvm-packages] JVM library loader extensions

python-package/xgboost/core.py, python-package/xgboost/dask.py, python-package/xgboost/data.py, python-package/xgboost/sklearn.py, tests/python-gpu/test_device_quantile_dmatrix.py, tests/python-gpu/test_gpu_with_dask.py
A small part extracted from https://github.com/dmlc/xgboost/pull/6591 to ease reviewing.
* Add check for consistency between 4 different DMatrix types.  They should share a number of common arguments in constructor with correct ordering.
=> Define metainfo for all DMatrix interfaces.

doc/tutorials/dask.rst, python-package/xgboost/core.py, python-package/xgboost/dask.py, tests/python/test_with_dask.py
Using dask collection directly should work out of box, this fix is for dask dmatrix with multi-class.  I will push the inplace predict API later.
Close https://github.com/dmlc/xgboost/issues/6568
=> [dask] Specify shape in prediction contrib and interaction.

python-package/xgboost/dask.py, python-package/xgboost/sklearn.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_with_dask.py, tests/python/test_with_sklearn.py
Close https://github.com/dmlc/xgboost/issues/6583 .
Close https://github.com/dmlc/xgboost/issues/6300 .
* Add `base_margin` to evaluation dataset in skl.
* Add all available meta info `DMatrix` constructor, and deprecate the pos arguments.
* Apply similar changes to dask.
* This PR also unifies the evaluation metric configuration between dask and non-dask code paths.  This adds additional validation and saves computation when training data is used for evaluation.
I will split up this mono PR after getting all the pieces together.  With growing size of meta info, I need to do some refactoring.
Small parts are extracted to:
- https://github.com/dmlc/xgboost/pull/6601
- https://github.com/dmlc/xgboost/pull/6627
=> Add base_margin for evaluation dataset.

.travis.yml
(https://github.com/dmlc/xgboost/pull/6638) https://travis-ci.org/github/dmlc/xgboost/builds/756313309
(https://github.com/dmlc/xgboost/pull/6640) https://travis-ci.org/github/dmlc/xgboost/builds/756317012
=> Disable s390x and arm64 tests on travis for now.

Jenkinsfile, tests/ci_build/test_python.sh
Follow-up to #6641 
Use AWS's ARM64 offering to build and run XGBoost Python package for the ARM64 platform.
=> [CI] Add ARM64 test to Jenkins pipeline

Jenkinsfile
Fix error from https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/master/724/pipeline/227:
```
OSError: [Errno 8] Exec format error: '/workspace/xgboost'
```
which is thrown when we try to run an executable built for ARM platform on a x86_64 worker, or vice versa. Every stash name must be unique to avoid the mix up.
=> [CI] Do not mix up stashed executable built for ARM and x86_64 platforms

plugin/updater_oneapi/regression_loss_oneapi.h, src/learner.cc, src/objective/regression_loss.h
Closes #6618
cc @lorentzenchr @mayer79
=> [Breaking] Change default evaluation metric for binary:logitraw objective to logloss

include/xgboost/predictor.h, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, tests/cpp/test_learner.cc
As https://github.com/dmlc/xgboost/pull/6645#issuecomment-768359052 fixed a performance issue, the booster object in dask are no longer copied.  So thread safety in predict must be guaranteed.
=> Make prediction thread safe.

doc/tutorials/dask.rst, python-package/xgboost/dask.py, tests/python/test_with_dask.py
This is for inferring shape with direct prediction (without DaskDMatrix).
There are a few things that requires known output shape before carrying out
actual prediction, including dask meta data, output dataframe columns.
* Infer output shape based on local prediction.
* Remove set param in predict function as it's not thread safe nor necessary as
we now let dask to decide the parallelism.
* Simplify prediction on `DaskDMatrix`.
* Remove unnecessary serialization.
A small part extracted from https://github.com/dmlc/xgboost/pull/6638 with added test and remove redundant serialization.
=> [dask] Add a dummy sample to infer output shape.

doc/tutorials/dask.rst, python-package/xgboost/dask.py, python-package/xgboost/sklearn.py, src/learner.cc, tests/python/test_with_dask.py
This PR changes `predict` and `inplace_predict` to accept a Future of model, to avoid sending models to workers repeatably.
=> [dask] Accept `Future` of model for prediction.

include/xgboost/gbm.h, include/xgboost/json.h, include/xgboost/learner.h, include/xgboost/predictor.h, python-package/xgboost/core.py, python-package/xgboost/dask.py, python-package/xgboost/data.py, src/c_api/c_api.cc, src/c_api/c_api.cu, src/c_api/c_api_utils.h, src/data/adapter.h, src/data/array_interface.h, src/data/data.cu, src/gbm/gbtree.h, src/learner.cc, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, tests/cpp/predictor/test_predictor.cc, tests/python-gpu/test_device_quantile_dmatrix.py, tests/python-gpu/test_gpu_prediction.py, tests/python/test_predict.py, tests/python/test_with_dask.py, tests/python/test_with_shap.py
* Accept array interface for csr and array.
* Accept an optional proxy dmatrix for metainfo.
Extracted from https://github.com/dmlc/xgboost/pull/6638 .
=> Enhance inplace prediction.

src/data/array_interface.h, tests/cpp/data/test_array_interface.cc, tests/cpp/helpers.cc, tests/cpp/helpers.h
This helps obtaining element size, which is used for gpu jvm iterator in rapids.  Also, for more complicated data type like gpu sparse data (cupyx csr_matrix), we need to have more flexible dispatching function.
=> Refactor array interface to use generic dispatching routine.

include/xgboost/c_api.h, python-package/xgboost/data.py, src/c_api/c_api.cc, src/data/adapter.h, src/data/data.cc, src/data/simple_dmatrix.cc, tests/python/test_dmatrix.py
Related https://github.com/dmlc/xgboost/issues/6671 .  Keeping the issue open as I expect there's similar issue for other inputs like csc and even dense.
=> Use __array_interface__ for creating DMatrix from CSR.

include/xgboost/c_api.h, include/xgboost/gbm.h, include/xgboost/learner.h, include/xgboost/predictor.h, python-package/xgboost/core.py, python-package/xgboost/dask.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py, src/c_api/c_api.cc, src/c_api/c_api.cu, src/c_api/c_api_utils.h, src/cli_main.cc, src/gbm/gblinear.cc, src/gbm/gbtree.cc, src/gbm/gbtree.h, src/learner.cc, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, tests/ci_build/conda_env/cpu_test.yml, tests/cpp/gbm/test_gbtree.cc, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/predictor/test_predictor.cc, tests/cpp/test_learner.cc, tests/python-gpu/test_from_cupy.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_basic_models.py, tests/python/test_predict.py, tests/python/test_with_dask.py
This PR is about to wrap up https://github.com/dmlc/xgboost/pull/6638, only that `sklearn` is still using `DMatrix` for prediction by default instead of `inplace_predict`.
* Add a new API function for predicting on `DMatrix`.  This function aligns with rest of the `InplacePredictFrom*` functions on semantic of function arguments.
* Purge `ntree_limit` from libxgboost, use iteration instead.
* [dask] Use `inplace_predict` by default for dask sklearn models.
* [dask] Run prediction shape inference on worker instead of client.
The breaking change is in the Python sklearn `apply` function, I made it to be consistent with other prediction functions where `best_iteration` is used by default. Also, close https://github.com/dmlc/xgboost/issues/6553
=> [breaking] Add prediction fucntion for DMatrix and use inplace predict for dask.

include/xgboost/span.h, tests/cpp/common/test_span.cc
* Stop printing out messages.
* Remove R specialization.
The printed message is not really useful anyway, without a reproducible example
there's no way to fix it.  But if there's a reproducible example, we can always
obtain this information by a debugger.  Removing the `printf` function avoids
creating the context in kernels.
=> Simplify Span checks.

src/data/data.cc, tests/python/test_with_pandas.py
Close https://github.com/dmlc/xgboost/issues/6688 .
=> Fix DMatrix slice with feature types.

doc/python/python_api.rst, python-package/xgboost/dask.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_with_dask.py
* Add tag for versions.
* use autoclass in sphinx build.
I made some class methods private to avoid exporting documents.
=> [dask] Improve documents.

include/xgboost/predictor.h, python-package/xgboost/dask.py, python-package/xgboost/sklearn.py, src/gbm/gbtree.cc, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, tests/cpp/gbm/test_gbtree.cc, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/predictor/test_predictor.cc, tests/cpp/predictor/test_predictor.h, tests/python/test_predict.py, tests/python/test_with_dask.py
* Use normal predictor for dart booster.
* Implement `inplace_predict` for dart.
* Enable `dart` for dask interface now that it's thread-safe.
* categorical data should be working out of box for dart now, but I will do some extra testing later.
The implementation is not very efficient as it has to pull back the data and apply weight for each tree, but still a significant improvement over previous implementation as now we no longer binary search for each sample.
=> Use `Predictor` for `dart`.

python-package/setup.py
we don't want to `copy_tree` and then skip the build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dmlc/xgboost/6694)
=> python: bail out of build early if libxgboost exists

python-package/xgboost/core.py
```
in get_dump
if self.feature_types is None:
AttributeError: 'Booster' object has no attribute 'feature_types'
```
=> [python-package] Fix class Booster: feature_types = None

python-package/xgboost/dask.py
I was reading through the Dask module today and noticed a comment that I think is outdated. It mentions CV and Ranking as TODOs, but both of these features exist in `xgboost.dask`.
This PR proposes removing that comment.
=> [dask] remove outdated comment

src/predictor/cpu_predictor.cc
As in https://github.com/dmlc/xgboost/pull/6648 local `RegTree::FVec` storage was introduced to preserve thread safety each training iteration requires buffer initialization in case of subsampling. 
stages (santander dataset) | before https://github.com/dmlc/xgboost/pull/6648 | thread safe https://github.com/dmlc/xgboost/pull/6648 and master | current PR
--| -- | -- | --
full training |136s | 165s | 140s
PredictRaw | 55s | 78s | 59s
this PR introduces threading for local buffers initialization.
But as still some gaps are exist is it possible to have not thread safe `PredictDMatrix` call during training?
=> Fix perf gap in thread safe prediction

python-package/xgboost/sklearn.py
Replaces "dowm" with "down" on parameter n_jobs
=> Fixes small typo in sklearn documentation

python-package/xgboost/dask.py, tests/python/test_with_dask.py
This attempts to solve #6712 by using the `client` object when persisting collections. This ensures that the futures are computed by the `client` passed to `xgb.dask.DaskDMatrix` and allows for several trainings to happen concurrently on different clusters.
=> [dask] Use client to persist collections

doc/model.schema, include/xgboost/c_api.h, include/xgboost/learner.h, python-package/xgboost/core.py, python-package/xgboost/sklearn.py, src/c_api/c_api.cc, src/learner.cc, src/tree/tree_model.cc, tests/cpp/test_learner.cc, tests/python/test_basic_models.py, tests/python/test_cli.py, tests/python/test_dmatrix.py
* [breaking] Remove feature name generation.
* Pass feature names and types into libxgboost.
* Save them in JSON model.
~The feature name generation is still preserved as many other places like `feature_importance_` and `plotting` are depending on it.~
One concern of this PR is it might introduce overhead in wide datasets, some sparse datasets can scale to millions of features.
Close https://github.com/dmlc/xgboost/issues/6520
=> [breaking] Save booster feature info in JSON, remove feature name generation.

tests/cpp/metric/test_elementwise_metric.cc
Tests for regression metrics with weights.
=> Tests for regression metrics with weights.

python-package/xgboost/callback.py, python-package/xgboost/training.py, tests/python/test_callback.py
Close https://github.com/dmlc/xgboost/issues/6701
* Expose more methods in cvpack and packed booster.
* Fix cv context in deprecated callbacks.
* Fix document.
=> Fix learning rate scheduler with cv.

src/data/data.cc, tests/cpp/data/test_simple_dmatrix.cc
Related https://github.com/dmlc/xgboost/issues/6741 https://github.com/dmlc/xgboost/pull/6740
=> Check for invalid data.

.github/workflows/r_tests.yml
=> [CI] Clear R package cache

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/ParameterSuite.scala
credit to @sammynammari . Pleas check https://github.com/dmlc/xgboost/issues/6657 and https://github.com/dmlc/xgboost/pull/6708
=> [jvm-packages] fix early stopping doesn't work even without custom_eval setting

src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/tree/test_quantile_hist.cc
Currently, the prediction cache is not enabled for models with `subsample < 1`, so a full prediction is made after each training iteration. This PR allows to partially update the predictions using the existing cache and make the actual prediction only on the rows that were not used for training.
We noticed an almost 2x acceleration for the `PredictRaw` section (on santander, where `subsample == 0.5`)
We also encountered a slowdown in the `InitData` section, where we now do more calculations (this will only be observed on `subsample < 1` datasets). This could be improved in future updates.
**UPD:**
Here are some measurements:
| Higgs, 1m, `subsample == 0.9` | PredictRaw | InitData | Overall time |
| ----------------------------- | ---------- | -------- | ------------ |
| current master …
=> Prediction by indices (subsample < 1)

python-package/xgboost/dask.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_tracker.py, tests/python/test_with_dask.py
This enables training multiple models in parallel.
* Conditionally import `MultiLock`.
* Use async train directly in scikit learn interface.
* Use `worker_client` when available.
Close https://github.com/dmlc/xgboost/issues/6649 Close https://github.com/dmlc/xgboost/pull/6677 .
Currently depends on https://github.com/dask/distributed/pull/4503 .
=> [dask] Use `distributed.MultiLock`

src/tree/updater_gpu_hist.cu, tests/cpp/tree/test_gpu_hist.cu, tests/python-gpu/test_gpu_with_sklearn.py, tests/python/test_with_sklearn.py
Close https://github.com/dmlc/xgboost/issues/6754 .
Fix by copying out the gradient before sampling.
=> Fix GPU RF

src/common/device_helpers.cuh, src/tree/gpu_hist/row_partitioner.cu, src/tree/gpu_hist/row_partitioner.cuh
Closes #6552 by partially reverting the commit f779980f7ea7f6f07e86229b8e78144e8a74e6b3
=> Re-introduce double buffer in UpdatePosition, to fix perf regression in gpu_hist

R-package/tests/testthat/test_basic.R, src/learner.cc, tests/cpp/test_learner.cc
Close https://github.com/dmlc/xgboost/issues/6766 .
- Display quotes around invalid parameters.
- Check for white space.
Should be a little bit better.
=> Add quotes to unused parameters.

python-package/xgboost/data.py, src/data/adapter.h, src/data/array_interface.h, src/data/data.cu, src/data/device_adapter.cuh, tests/cpp/data/test_adapter.cc, tests/cpp/data/test_array_interface.cc, tests/python-gpu/test_gpu_prediction.py, tests/python/test_predict.py
Close https://github.com/dmlc/xgboost/issues/6762 .
Close https://github.com/dmlc/xgboost/issues/6752 .
=> Support column major array.

src/data/array_interface.cu, src/data/array_interface.h, tests/cpp/data/test_array_interface.cu
Close https://github.com/dmlc/xgboost/issues/6753 .
=> Support v3 cuda array interface.

src/common/hist_util.cu, src/common/host_device_vector.cu, src/data/ellpack_page.cu, src/gbm/gbtree.cc, src/gbm/gbtree.cu, tests/python-gpu/test_gpu_prediction.py
* On C API there's a check for output prediction being device-readable.  With dart this doesn't hold.
* Added optimization to avoid memory copying whenever possible.  Will post the result later.
=> Fix dart inplace prediction with GPU input.

python-package/xgboost/dask.py
I recently found an issue with `lightgbm.dask`'s uses of `distributed.Client.submit()`. Essentially, LightGBM training relies on running exactly one training task per worker, and it was not setting `workers` on `client.submit()` to guarantee this (https://github.com/microsoft/LightGBM/pull/4132).
After discovering this, I came over here to check if XGBoost suffered from a similar issue, since this bug was in a piece of `lightgbm.dask` that has not been changed since `dask-lightgbm`, and `dask-lightgbm` was based on `dask-xgboost` :joy: .
It seems like `xgboost.dask` is already setting `workers=[worker_addr]` to prevent this situation. However, I think that `xgboost.dask` would also benefit from setting `allow_other_workers=False` when submitting `dispatched_train()` calls. This can be …
=> [dask] disable work stealing for training tasks

R-package/README.md
https://xgboost.readthedocs.io/en/latest/contribute.html#r-package returns a 404 believe the right address should be https://xgboost.readthedocs.io/en/latest/contrib/coding_guide.html#r-coding-guideline
=> UPDATE broken url

src/gbm/gbtree.cc, src/gbm/gbtree.cu, tests/python-gpu/test_gpu_prediction.py
Similar to optimization done in https://github.com/dmlc/xgboost/pull/6777 , but for in-place prediction.
=> Optimize dart inplace predict perf.

demo/rmm_plugin/README.md, demo/rmm_plugin/rmm_mgpu_with_dask.py, demo/rmm_plugin/rmm_singlegpu.py, plugin/CMakeLists.txt
* Clarify the `use_rmm` flag in the document and demo.
* ~Use better CMake command.~
Close https://github.com/dmlc/xgboost/issues/6801 .
=> Clarify the behavior of `use_rmm`.

python-package/xgboost/dask.py, python-package/xgboost/sklearn.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_with_dask.py
* Use `output_margin` for `softmax`.
* Add test for dask binary cls.
* Remove unused output margin.
=> More general predict proba.

include/xgboost/generic_parameters.h, src/learner.cc
Deprecated and disabled in 1.0 https://github.com/dmlc/xgboost/pull/4749
=> Remove deprecated `n_gpus` parameter.

src/common/device_helpers.cuh, src/common/hist_util.cuh, src/data/simple_dmatrix.cu
Close https://github.com/dmlc/xgboost/issues/6822 .
=> Use batched copy if.

Jenkinsfile, doc/build.rst, tests/ci_build/Dockerfile.gpu_build_r_centos6, tests/ci_build/build_r_pkg.sh, tests/ci_build/build_r_pkg_with_cuda.sh
Closes #6654
Usage. Users will now be able to install XGBoost with the following simple commands:
```bash
R -q -e "install.packages(c('data.table', 'magrittr', 'jsonlite', 'remotes'))"
R CMD INSTALL ./xgboost.tar.gz
```
No need to use `cmake` or suffer setup issues from `nvcc`. It just works.
=> [CI] Pack R package tarball with pre-built xgboost.so (with GPU support)

.github/workflows/main.yml, Makefile, python-package/setup.cfg, python-package/xgboost/callback.py, python-package/xgboost/compat.py, python-package/xgboost/core.py, python-package/xgboost/dask.py, python-package/xgboost/sklearn.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_interaction_constraints.py, tests/python/test_monotone_constraints.py
TODO:
~- [ ] Remove type from doc string.~  Need to update CI sphinx-build .
=> Typehint for Sklearn.

.github/workflows/main.yml
The link for the C API doc was not working: https://xgboost.readthedocs.io/en/stable/dev/c__api_8h.html. When we ported the Doxygen build from Jenkins to GitHub Actions, we made a small typo that broke the C API doc.
This commit has already been ported to `release_1.3.0` and `release_1.4.0` and now the links are back online:
* https://xgboost.readthedocs.io/en/release_1.3.0/dev/c__api_8h.html
* https://xgboost.readthedocs.io/en/release_1.4.0/dev/c__api_8h.html
=> [CI] Upload Doxygen doc to correct destination

R-package/R/callbacks.R
To close issue #6852, I've removed the magrittr dependency in the relevant documentation. The simple path of replacing each call like `xgb.gblinear.history(bst) %>% matplot(type = 'l')` with its corresponding `matplot(xgb.gblinear.history(bst), type = 'l')` was taken. For some calls, I get different results when I run the code before and after this change. However, there is sufficient randomness in said code that I get different results each time that I run it, regardless of any changes.
One thing that definitely has changed is that the plot y-axes now have titles matching the argument that they are called with. For example, where we previously had no titles on our y-axes that were generated using magrittr pipes, we now have something like "xgb.gblinear.history(bst)". If this is …
=> Removed magrittr dependency in callbacks.R (closes #6852)

src/common/device_helpers.cuh, src/metric/auc.cu, tests/cpp/common/test_device_helpers.cu
Close https://github.com/dmlc/xgboost/issues/6865 .
=> Copy output data for sort.

include/xgboost/linalg.h, include/xgboost/tree_updater.h, src/gbm/gbtree.cc, src/gbm/gbtree.cu, src/tree/updater_gpu_hist.cu, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, tests/cpp/common/test_linalg.cc, tests/cpp/test_learner.cc, tests/cpp/tree/test_gpu_hist.cu
* Optimize the perf for gpu multi-class.
* Implement some utilities for slicing matrix.
* Remove the `update prediction cache multi class` function.
TODOs:
100 rounds for covtype:
Before:
22.598s
After:
15.911s
=> Implement unified update prediction cache for (gpu_)hist.

tests/python-gpu/test_gpu_with_dask.py
This reverts commit 74f3a2f4b5c2654af90d1477fd543b5d97280fbe.
=> Revert "Use CPU input for test_boost_from_prediction. (#6818)"

doc/requirements.txt, doc/tutorials/index.rst, doc/tutorials/ray.rst
This PR adds a new tutorial for XGBoost-Ray.
The code samples are included and unit tested in the XGBoost-Ray repository.
I added xgboost_ray as a dependency to sphinx so that the documentation of the RayParams can automatically be fetched from the latest XGBoost-Ray release. Let me know if this is fine
cc @trivialfis @hcho3
=> [docs] Add tutorial for XGBoost-Ray

src/c_api/c_api.cc
Targeted at 1.4 branch, will port to master once merged.  Address warning found by @hetong007  in https://github.com/dmlc/xgboost/issues/6793#issuecomment-823849915 .
Do not merge until all tests on R-hub have passed.  (Huge thanks to R-hub).  Progress can be tracked here:
https://builder.r-hub.io/status/xgboost_1.4.1.1.tar.gz-0c3c8a0f078d60e5fb1d1b19430036d9
https://builder.r-hub.io/status/xgboost_1.4.1.1.tar.gz-bc2de41bceddd51493632f62f3434c78
https://builder.r-hub.io/status/xgboost_1.4.1.1.tar.gz-66c959222fbaf97afac3f721205f9ae4
Failing due to compiler couldn't infer dispatching type.
https://builder.r-hub.io/status/xgboost_1.4.1.1.tar.gz-bdf750d127a041e6fcc77bba0017480c
https://builder.r-hub.io/status/xgboost_1.4.1.1.tar.gz-bc0161ccee0b610ce564d0f2b51892e4
Failing in dependency …
=> Fix warning on Windows.

python-package/xgboost/core.py, src/c_api/c_api.cc, src/c_api/c_api.cu, src/c_api/c_api_error.h, src/c_api/c_api_utils.h, src/common/device_helpers.cu, tests/cpp/c_api/test_c_api.cc
Fixes the failure on CI where other libraries like cupy and cudf don't necessarily handle the non-default device.
Also, I think it's a good idea to prevent xgboost from changing any global variable in runtimes.
=> Add an API guard to prevent global variables being changed.

doc/prediction.rst, src/c_api/c_api_utils.h, tests/python/test_predict.py
Before the output shape for predict leaf with 1 tree is `(n_samples, )`, after 1.4 it's `(n_samples, 1)`.  The shape for other cases like more than 1 num_boost_round or more than 1 class/num_parallel_tree is unchanged.
We added a parameter called `strict_shape` in 1.4 to get consistent shape across all model types and I recommend using it: https://xgboost.readthedocs.io/en/latest/prediction.html .  When specified, predict leaf always output a 4 dim tensor with clear meaning for each dim.
=> Ensure predict leaf output 1-dim vector where there's only 1 tree.

cmake/RPackageInstall.cmake.in
Looking at the R package tonight, I saw that the dependency on `{stringi}` was removed a few months ago, in #6109.
Since that package is no longer needed for `{xgboost}`, this PR proposes changing `RPackageInstall.cmake.in` to not install it when building the R package with CMake. I think that might help to speed up installs a bit and reduces the risk of a failed install caused by failure to build `{stringi}`.
=> [R-package] remove stringi from CMake-based installation

R-package/R/xgb.Booster.R, R-package/R/xgb.unserialize.R, R-package/man/xgb.unserialize.Rd, R-package/src/init.c, R-package/src/xgboost_R.cc, R-package/src/xgboost_R.h, R-package/tests/testthat/test_helpers.R, R-package/tests/testthat/test_model_compatibility.R
Addressing issue https://github.com/dmlc/xgboost/issues/6896
When de-serializing an object in R from raw bytes, the R handles become null as there is no C++ object to which to point to in-memory. In these situations, the C++ objects are recreated from raw bytes as needed, but the R handle objects are not modified in-place, which can lead to de-serializing multiple times.
This PR changes it so that R external pointer objects would be modified in-place in order to avoid redundant operations and memory usage. After the PR:
```r
library(xgboost)
data(mtcars)
xgb_data <- xgb.DMatrix(as.matrix(mtcars[,-1]), label=mtcars[,1,drop=TRUE])
model <- xgb.train(list(objective="reg:squarederror"), xgb_data, nrounds=10)
saveRDS(model, file.path(tempdir(), "model.rds"))
model_new <- …
```
=> Update R handles in-place

.github/workflows/main.yml
On updated libomp@12, the external memory test causes internal error in libomp:
```
1: OMP: Error #131: Thread identifier invalid.
```
So far non of us can reproduce it on outside of CI environment.  This PR tried to switch different xcode versions but all ran into various failures.  So to unblock the CI I just disable 1 c++ test.
=> [CI] Skip external memory gtest on osx.

tests/python/testing.py
In numpy `1.20.2`, for an empty array `predt` with shape `[]`, the comparison of `predt < 0.5` returns a 2-dim array with shape `(0, 1)`.  This causes later indexing error.
=> [CI] Fix custom metric test with empty dataset.

.travis.yml, tests/ci_build/conda_env/macos_cpu_test.yml, tests/travis/run_test.sh, tests/travis/setup.sh
* Remove unused r from travis.
* Don't update homebrew.
* Don't install indirect/unused dependencies like libgit2, wget, openssl.
* Move graphviz installation to conda.
* lz4 test is still omitted.  The test was dropped at some point probably due to oversight.  This PR doesn't restore it due to the Python test is responsible for generating wheels and I can't add an optional dependency into the generated binary.
* Another failure is addressed in https://github.com/dmlc/xgboost/pull/6917.
These are the package updates for homebrew:
```
ansible 2.9.0 -> 3.3.0, boost 1.71.0 -> 1.75.0_3, cgal 4.14.1 -> 5.2.1, geos 3.8.0 -> 3.9.1, git 2.24.0 -> 2.31.1, libevent 2.1.11_1 -> 2.1.12, libgeotiff 1.5.1 -> 1.6.0, libidn2 2.2.0_1 -> 2.3.0, gnutls 3.6.10 -> 3.6.15, gnupg 2.2.17 -> 2.3.1, libpq 11.5_1 …
```
=> Reduce Travis environment setup time.

tests/python/test_with_dask.py
This relaxes the test when the `max_bin` is set to `2` and trees are limited to stumps.  In this case, the floating-point error can overweight the learning result.
https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-6901/6/pipeline
=> Relax test for decision stump in distributed environment.

python-package/xgboost/core.py, python-package/xgboost/data.py, src/data/array_interface.h, tests/python/test_predict.py
Close https://github.com/dmlc/xgboost/issues/6925 .
For some reason, panda returns an array of `object` when dataframe contains boolean values.  When the data is `object` array interface doesn't specify its `itemsize`, leading to error reported from the above issue.
Will be backported 1.4.2.
=> Enforce input data is not `object`.

R-package/cleanup
currently installing the R-pacakge will leave the repo in dirty state, since
`CmakeLists.txt` is already checked in. This fixes the `cleanup`
script to not delete this file.
=> [R] don't remove CMakeLists in cleanup

python-package/xgboost/data.py
The UserWarning prompted when using numpy subsets was a bit difficult to understand. I also added a suggestion on how to fix the warning.
=> Improve warning when using np.ndarray subsets

python-package/xgboost/core.py, python-package/xgboost/data.py, src/data/array_interface.h, tests/python/test_predict.py
* Check for object data type.
* Allow strided arrays with greater underlying buffer size.
=> [backport] Enforce input data is not `object`. (#6927)

jvm-packages/create_jni.py, jvm-packages/xgboost4j-gpu/src, jvm-packages/xgboost4j-gpu/src/main/java, jvm-packages/xgboost4j-gpu/src/main/resources/xgboost4j-version.properties, jvm-packages/xgboost4j-gpu/src/main/scala, jvm-packages/xgboost4j-gpu/src/native, jvm-packages/xgboost4j-gpu/src/test, jvm-packages/xgboost4j-spark-gpu/src, jvm-packages/xgboost4j-spark-gpu/src/main/scala, jvm-packages/xgboost4j-spark-gpu/src/test
When I was running the following commands, 
```
mvn package -Dspark.version=3.0.0 -DskipTests -Duse.cuda=ON -Pgpu-with-gpu-tests
mvn deploy -Prelease -DskipTests
```
I expected to have two JAR files, `xgboost4j_2.12-1.4.1.jar` and `xgboost4j-gpu_2.12-1.4.1.jar`, the second of which contains CUDA code and the first does not. As a result, the second JAR is expected to be bigger than the first (160 MB vs 4.4 MB). But when I ran the commands, I often ended up with two JAR files with equal size (160 MB), indicating a mix-up.
This PR ensures that `xgboost4j-gpu_2.12-1.4.1.jar` gets the bigger `libxgboost4j.so` with CUDA code and that `xgboost4j_2.12-1.4.1.jar` gets the smaller `libxgboost4j.so` without CUDA code.
=> [jvm-packages] Make it easier to release GPU/CPU code artifacts to Maven Central

python-package/xgboost/sklearn.py
Within the Python sklearn API reference it's mentioned that `tree_method` should come from the parameters document, but there doesn't appear to be an easy way to find that document. I'm assuming this is what's meant, in which case I think it would be helpful to provide a link in the docstring: https://xgboost.readthedocs.io/en/latest/python/python_api.html#module-xgboost.sklearn
=> Link to valid tree_method values in docs 

Jenkinsfile, tests/ci_build/insert_vcomp140.py, tests/ci_build/rename_whl.py
The latest auditwheel change the formatting of the name of the file it outputs. See https://github.com/pypa/auditwheel/pull/288. So introduce an extra file renaming operation so that we have a single unique Python wheel in the location `python-package/dist/`.
=> [CI] Fix CI/CD pipeline broken by latest auditwheel (4.0.0)

python-package/xgboost/core.py
data.shape[0] denotes the number of samples, data.shape[1] is the number of features
=> Fixed incorrect feature mismatch error message

src/metric/auc.cc, src/metric/auc.cu, src/metric/auc.h, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_with_dask.py
Continue https://github.com/dmlc/xgboost/pull/6946 .
* Make sure all reduce is called for cuda code path.
* Make sure we are using multi-class auc when there's empty dataset.
=> Fix multiclass auc with empty dataset.

src/metric/auc.cc, src/metric/auc.cu, src/metric/auc.h, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_with_dask.py
Not necessary to backport, but the CI is flaky due to this bug.
=> [backport] Fix multiclass auc with empty dataset. (#6947)

python-package/xgboost/callback.py, tests/python/test_callback.py
Close https://github.com/dmlc/xgboost/issues/4982 .
=> Add tolerance to early stopping.

R-package/R/callbacks.R
`list2mat` is a function of one argument, so the call can be simplified.
=> Simplify list2mat call from lapply in callbacks.R

src/c_api/c_api.cc, src/gbm/gbtree.cc
Following `size_t` conversion errors were fixed in x86 release build:
```
Error C2398: Element '4': conversion from 'xgboost::bst_ulong' to 'size_t' requires a narrowing conversion, xgboost\src\c_api\c_api.cc 738	
Error C2397: conversion from 'uint64_t' to '_Ty' requires a narrowing conversion, xgboost\src\gbm\gbtree.cc 234
```
=> Fix compiler error in x86 building - 2nd request

R-package/R/callbacks.R
The comment was made false by the removal of the pipes. What was originally the first `lapply` is now the second. I've done what I can on my own machine to confirm that the second call is indeed doing the job, although one could argue that it's actually the second and the third that are doing the job.
Given that we're using two `lapply`s for one job, I can't help but think that there is an `mapply` or `Map` way to do this better. However, I've tried my best and come up with nothing.
=> Corrected lapply comment in callbacks.R

python-package/xgboost/dask.py
For some unknown reasons in dask 2021.05.0, list is turned into a future for `map_blocks`.  Use tuple instead.
=> [dask] Fix prediction on df with latest dask.

python-package/xgboost/compat.py
In order to support object wrappers/proxies like [`weakref.proxy`](https://docs.python.org/3/library/weakref.html#weakref.proxy) and rapidsai/dask-cuda#451, this PR implements type checking using `x.__class__` instead of `type(x)`.
This PR shouldn't change any semantic other than the support of proxies.
We did something similar in Dask, for a detailed discussion of the difference between  `__class__` and `type` see https://github.com/dask/dask/pull/6981
This change is motivated by https://github.com/rapidsai/dask-cuda/issues/610
cc @trivialfis @VibhuJawa
=> lazy_isinstance(): use .__class__ for type checking

src/c_api/c_api_utils.h, tests/cpp/c_api/test_c_api.cc
The guard protects the global variable from being changed by XGBoost.  But this leads to a
bug that the `n_threads` parameter is no longer used after the first iteration.  This is
due to the fact that `omp_set_num_threads` is only called once in `Learner::Configure` at
the beginning of the training process.
The guard is still useful for `gpu_id` since `cudaSetDevice` is called all the time in our code base.
=> Revert OMP guard.

.github/workflows/r_tests.yml
It was removed before due to stalled cache.  Since I'm moving mingw and VS15 Python tests to github action, to avoid slowing down the tests too much I think it's still best to use cache.  If the stalled cache becomes an issue in the future, we can update the cache key with version number (currently 1).
=> [CI] Restore R cache on github action.

python-package/xgboost/callback.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py, src/gbm/gbtree.cc, tests/python/test_predict.py
* Remove `best_ntree_limit` from document.
Close https://github.com/dmlc/xgboost/issues/6973 .
=> Guard against index error in prediction.

src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, tests/cpp/tree/test_quantile_hist.cc
Complexity of discard operation of MT generator is linear so current InitSampling implementation is not efficient due to unbalanced local thread's discards. In this PR similar [approach](https://github.com/dmlc/xgboost/blob/master/src/tree/gpu_hist/gradient_based_sampler.cu#L26) to GPU sampler was implemented:
- generate new seed for each iteration by global mt19937 rng.
- apply uniform distribution with default_random_engine (linear_congruential_engine) and generated seed.
- set gradients to zero for i-th row with condition rnd(i) > p
results for binary classification for synthetic data [61 x 10723651] with 'sample': 0.8:
|  | Master | This PR |
| ------------- | ------------- | ------------- |
| InitSampling |  27.06s | 0.78s |
| ApplySplit|  10.25s | 11.83s |
| BuildLocalHistograms| …
=> Reduce 'InitSampling' complexity and set gradients to zero

include/xgboost/c_api.h, python-package/xgboost/core.py, python-package/xgboost/data.py, src/c_api/c_api.cc, src/data/array_interface.h, tests/ci_build/conda_env/macos_cpu_test.yml, tests/python-gpu/test_gpu_prediction.py, tests/python/test_predict.py
* Add native support for CPU 128 float.  cupy doesn't have float128, and CUDA treats long double as double in device code.
* Convert boolean and float16 in Python.
* The C API for constructing DMatrix from numpy array added in https://github.com/dmlc/xgboost/pull/6998 is renamed from `Array` to `Dense` for consistency.
Close https://github.com/dmlc/xgboost/issues/6999 .
=> Support for all primitive types from array.

Jenkinsfile, tests/ci_build/Dockerfile.gpu, tests/ci_build/Dockerfile.rmm
Replaces #6825
Ensure that XGBoost works with the upcoming 21.06 release of RAPIDS software.
=> [CI] Upgrade cuDF and RMM to 21.06 nightly

CMakeLists.txt, tests/ci_build/build_via_cmake.sh
Recently I ran into an issue where `cub::DeviceRadixSort` runs into a cuda invalid value error when used with cuDF.  I believe it's due to mixed C++ symbols exported from both libraries.  ~This might also be the cause of https://github.com/rapidsai/cudf/issues/7722~.  This PR enables "hidden" visibility for all c++ symbols by default on our CI build.
=> Hide symbols in CI build + hide symbols for C and CUDA

src/common/hist_util.h
Fix for bug described in #7025.
With this fix, training as described in #7025 with tree_method=gpu_hist produces results comparable to tree_method=hist.
Dev/Test environment:
Linux: Linux acfa9079b903 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
CUDA: NVIDIA-SMI 460.80, Driver Version: 460.80, CUDA Version: 11.2
=> Fix BinarySearchBin() argument types

src/gbm/gbtree.cc, tests/python-gpu/test_gpu_basic_models.py, tests/python/test_basic_models.py
Close https://github.com/dmlc/xgboost/issues/6989 .
https://github.com/dmlc/xgboost/pull/6971 tries to have a more rigid configuration for `gpu_id`, but turns out to be impossible.  This PR is a hot fix for the custom objective issue.
=> Fix `gpu_id` with custom objective.

include/xgboost/tree_model.h, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, src/predictor/predict_fn.h, src/tree/tree_model.cc, src/tree/updater_refresh.cc, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/predictor/test_predictor.cc, tests/cpp/predictor/test_predictor.h
* Implement categorical prediction for CPU prediction.
* Implement categorical prediction for GPU predict leaf.
* Refactor the prediction functions to have unified get next node.
Related: https://github.com/dmlc/xgboost/issues/6503 .
=> Implement categorical prediction for CPU and GPU predict leaf.

tests/python/test_with_dask.py
This aims to reduce the runtime of the dask tests. Following https://github.com/dmlc/xgboost/issues/6816#issuecomment-852831437, the first step was to replace the `client` fixture with one that reuses the same cluster and just creates new clients in every test, and makes the least changes to the existing code. 
There are some other tests that are building clusters instead of using the `client` fixture that could be benefited by this, however adding this only reduced the runtime by about a minute, so I ran `pytest` with `--durations=0` and got this:
```
=============================================================== slowest durations ================================================================
155.91s call     python/test_with_dask.py::TestWithDask::test_approx
138.92s call …
```
=> [dask] speed up tests

R-package/R/callbacks.R, R-package/R/utils.R, R-package/R/xgb.Booster.R, R-package/R/xgb.cv.R, R-package/R/xgb.train.R, R-package/man/cb.early.stop.Rd, R-package/man/predict.xgb.Booster.Rd, R-package/man/xgb.cv.Rd, R-package/man/xgb.train.Rd, R-package/src/init.c, R-package/src/xgboost_R.cc, R-package/src/xgboost_R.h, R-package/tests/testthat/test_basic.R, doc/prediction.rst, python-package/xgboost/core.py, src/c_api/c_api.cc, src/c_api/c_api_utils.h, src/tree/updater_quantile_hist.cc
This is an early PR so I can get some suggestions from R experts.  The primary change in R interface is the use of `iterationrange` and deprecation of `ntreelimit`.
TODOs:
=> Use new predict function for R.

python-package/xgboost/core.py, python-package/xgboost/data.py, tests/python-gpu/test_from_cudf.py, tests/python-gpu/test_gpu_updaters.py, tests/python/testing.py
* Support from DMatrix.
* Support from DQM, except for iterator, which is implemented in #7043
=> Categorical data support for cuDF.

include/xgboost/c_api.h, include/xgboost/gbm.h, include/xgboost/learner.h, python-package/xgboost/core.py, src/c_api/c_api.cc, src/c_api/c_api_utils.h, src/gbm/gbtree.h, src/learner.cc, tests/cpp/gbm/test_gbtree.cc, tests/python/test_basic.py
Related: https://github.com/dmlc/xgboost/issues/6091 .
Other than eliminating parsing, this is also for categorical data support.  The old text parsing implementation doesn't understand categorical split outputs.
=> Implement feature score in GBTree.

include/xgboost/feature_map.h, python-package/xgboost/plotting.py, src/predictor/cpu_predictor.cc, src/tree/tree_model.cc, tests/cpp/tree/test_tree_model.cc, tests/python-gpu/test_gpu_plotting.py, tests/python-gpu/test_gpu_updaters.py, tests/python-gpu/test_gpu_with_sklearn.py
Support categorical tree node for text dump.
Related https://github.com/dmlc/xgboost/issues/6503 .
Close https://github.com/dmlc/xgboost/issues/6298 .
=> Support categorical split in tree model dump.

python-package/xgboost/core.py, tests/python/test_basic.py
Address issue raised by @harupy in https://github.com/dmlc/xgboost/pull/7041#discussion_r654226008
=> Convert numpy float to Python float in feat score.

CMakeLists.txt, tests/ci_build/Dockerfile.clang_tidy, tests/ci_build/Dockerfile.cpu, tests/ci_build/Dockerfile.gpu_build, tests/ci_build/Dockerfile.gpu_build_centos6, tests/ci_build/Dockerfile.gpu_build_r_centos6, tests/ci_build/Dockerfile.jvm, tests/ci_build/Dockerfile.jvm_gpu_build, tests/ci_build/Dockerfile.rmm
GPUTreeSHAP now requires CMake 3.14, and XGBoost depends on GPUTreeSHAP. While GPUTreeSHAP is strictly an optional dependency (it's only enabled when GPU support is enabled), it is not too big of a jump to upgrade from CMake 3.13 to CMake 3.14.
Unblocks #7053
=> [CI] Upgrade to CMake 3.14

include/xgboost/tree_model.h, src/common/bitfield.h, src/common/categorical.h, src/common/quantile.cuh, src/predictor/gpu_predictor.cu, src/tree/tree_model.cc, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/predictor/test_predictor.cc, tests/cpp/predictor/test_predictor.h, tests/python-gpu/test_gpu_prediction.py
Depends on https://github.com/rapidsai/gputreeshap/pull/26 .
=> Categorical split support for SHAP

amalgamation/xgboost-all0.cc, include/xgboost/data.h, src/common/column_matrix.h, src/common/hist_util.cc, src/common/hist_util.h, src/data/gradient_index.cc, src/data/gradient_index.h, src/data/iterative_device_dmatrix.h, src/data/proxy_dmatrix.h, src/data/simple_dmatrix.cc, src/data/simple_dmatrix.h, src/data/sparse_page_dmatrix.h, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, tests/cpp/common/test_column_matrix.cc, tests/cpp/common/test_hist_util.cc, tests/cpp/tree/test_quantile_hist.cc
See https://github.com/dmlc/xgboost/issues/4354 for details.  This PR moves `GHistIndex`, we also need to move column matrix in future PRs.  Also related: https://github.com/dmlc/xgboost/issues/5143 , https://github.com/dmlc/xgboost/issues/6148
Few more bonus:
- We can remove the `is_gmat_initialized_` in hist builder.
- We can implement external memory support if desired.
- We can reuse it in approx tree method.
I will update with benchmarks later.
@SmirnovEgorRu @ShvetsKS
=> Move `GHistIndex` into `DMatrix`.

python-package/xgboost/data.py
You can reproduce the error with `test_pandas` using pandas==1.3.2.
=> Fix with latest panda range index.

src/data/simple_dmatrix.cu, src/data/simple_dmatrix.cuh
Extracted from https://github.com/dmlc/xgboost/pull/7070 .
=> Make `SimpleDMatrix` ctor reusable.

doc/tutorials/model.rst
treelite.io is no longer a valid site and re-directs users to a parked domain. Re-directing to the documentation is safer at this point.
=> Update reference to treelite website

src/tree/hist/evaluate_splits.h, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, tests/cpp/tree/hist/test_evaluate_splits.cc, tests/cpp/tree/test_evaluate_splits.cc, tests/cpp/tree/test_quantile_hist.cc
Other than modularizing the split evaluation function, this PR also removes some more functions including `InitNewNodes` and `BuildNodeStats` among some other unused variables.  Also, scattered code like setting leaf weights is grouped into the split evaluator and `NodeEntry` is simplified and made private.  Another subtle difference with the original implementation is that the modified code doesn't call `tree[nidx].Parent()` to traversal upward.
I think it's faster after the PR.  URL is only run for 100 rounds, others are 500 rounds.
|        | HIGGS              | covtype           | URL                |
|:-------|:-------------------|:------------------|:-------------------|
| master | 180.24662968399934 | 76.94775568600744 | 196.1527223587036  |
| PR     | 177.9364239120041  | …
=> Extract evaluate splits from CPU hist.

src/data/ellpack_page_raw_format.cu, src/data/sparse_page_raw_format.cc, src/data/sparse_page_writer.h, tests/cpp/data/test_ellpack_page_raw_format.cu, tests/cpp/data/test_sparse_page_raw_format.cc
* Save base_rowid.
* Return write size.
* Remove unused function.
* Add tests.
Part of https://github.com/dmlc/xgboost/pull/7070 .
=> Refactor external memory formats.

include/xgboost/c_api.h, python-package/xgboost/core.py, python-package/xgboost/data.py, src/c_api/c_api.cc, tests/cpp/helpers.cu
The role of `ProxyDMatrix` is extended to beyond what it was designed.  Now it's used by both
`QuantileDeviceDMatrix` and `inplace prediction`.  After the refactoring of `SparseDMatrix`, it
will also be used for external memory support.  Renaming the C API to extract it from
`QuantileDeviceDMatrix`.
Part of https://github.com/dmlc/xgboost/pull/7070 .
=> [Breaking] Rename Quantile DMatrix C API.

src/data/adapter.h, src/data/array_interface.h, src/data/iterative_device_dmatrix.cu, src/data/proxy_dmatrix.cc, src/data/proxy_dmatrix.cuh, src/data/proxy_dmatrix.h, tests/cpp/data/test_adapter.cc, tests/cpp/data/test_proxy_dmatrix.cc, tests/cpp/data/test_proxy_dmatrix.cu
Part of https://github.com/dmlc/xgboost/pull/7070 .
=> Support host data in proxy DMatrix.

doc/tutorials/c_api_tutorial.rst
hi,
this patch fixes a small typo that i noticed while following along the c api examples.
=> fix typo in `XGDMatrixSetFloatInfo` example

.github/workflows/main.yml, .github/workflows/python_tests.yml, tests/travis/setup.sh
Works around #7039 by using libomp 11.1.0 in CI.
=> [CI] Pin libomp to 11.1.0 

src/common/partition_builder.h
fix typo in PartionBuilder::Init
the third argument seems to be corrected to funcNTask from funcNTaks
=> fix typo in PartitionBuilder::Init(..., Func funcNTaks -> Func funcNTask)

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoost.java, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoostJNI.java, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/BoosterImplTest.java
As per discussions in #6893, adding bestIteration and bestScore attributes.
sample code snippet to access the attributes
```
.
.
.
val xgbClassificationModel = xgbClassifier.fit(train)
val bestScore = xgbClassificationModel.nativeBooster.getAttr("bestScore")
val bestIteration = xgbClassificationModel.nativeBooster.getAttr("bestIteration")
```
=> [XGBoost4J-Spark] bestIteration and bestScore for early stopping

src/common/hist_util.cc
prefetch may be abbreviated in two different ways (prftch or prefect), or small typos?
=> fix typo in src/common/hist.cc BuildHistKernel

src/common/quantile.h
When the last value of `queue` is equal to the input value `x`, its weight is added to the weight of the last entry of `queue` instead of creating a new entry. However, this is ignored when the `queue` is full.
=> Check input value is duplicated when quantile queue is full

tests/python-gpu/test_gpu_with_dask.py, tests/python/test_with_dask.py
* Add tests to GPU.
* Assert cover in children sums up to parent.
Related https://github.com/dmlc/xgboost/issues/7114 .
Extends tests created by @ShvetsKS to more cases.
=> [dask] Extend tree stats tests.

tests/cpp/common/test_quantile.h, tests/python/test_ranking.py
Suppress warning like:
```
[2021-07-24T18:58:50.339Z] tests/python-gpu/test_gpu_with_dask.py::TestDistributedGPU::test_quantile_basic [18:58:49] WARNING: ../rabit/src/allreduce_base.cc:240: Retry connect to ip(retry time 1): [127.0.0.1]
```
The real IP can be something like 192.168.0.103 , doesn't have to be loop back.
=> Use upstream URI in distributed quantile tests.

jvm-packages/create_jni.py, python-package/xgboost/dask.py, python-package/xgboost/tracker.py
The old dmlc tracker is causing test failure https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/master/931/pipeline .  See if we can take this as a chance to merge 2 trackers.
=> [JVM-Packages] Use Python tracker in XGBoost for JVM package.

src/common/device_helpers.cuh, src/data/ellpack_page.cu, src/metric/auc.cu, src/predictor/gpu_predictor.cu, src/tree/gpu_hist/row_partitioner.cu
This allows xgboost to compile with nvcc 11.4
I haven't looked into `dh::ArgSort` fully, but if it requires full 64bit support we can't update to cub 1.12+ due tohttps://github.com/NVIDIA/cub/issues/336. If xgboost is happy with 32bit space we can support cub 1.12+ by updating `ArgSort` to explicitly use `int` for offset type.
=> Allow compilation with nvcc 11.4

python-package/xgboost/dask.py
This is mostly a style change, but also avoids a user error (that I have
committed on a few occasions).  Since `XGBRegressor` and `XGBClassifier`
are imported as parent classes for the `dask` estimators, without
defining an `__all__`, autocomplete (or muscle) memory will produce the
following with little prompting:
```
from xgboost.dask import XGBClassifier
```
There's nothing inherently wrong with that, but given that
`XGBClassifier` is not `dask` enabled, it can lead to confusing behavior
until you figure out you should've typed
```
from xgboost.dask import DaskXGBClassifier
```
Another option is to alias import the existing non-dask estimators.
=> Disallow importing non-dask estimators from xgboost.dask

python-package/xgboost/callback.py, tests/python/test_callback.py
Close https://github.com/dmlc/xgboost/issues/7136 .
Close https://github.com/dmlc/xgboost/pull/7066 .
=> Support `min_delta` in early stopping.

R-package/R/xgb.DMatrix.R, R-package/R/xgboost.R, R-package/src/init.c, R-package/src/xgboost_R.cc, R-package/src/xgboost_R.h
Close https://github.com/dmlc/xgboost/issues/7098 .
Restricting the construction of DMatrix to be single threaded.
=> [R] Fix nthread in DMatrix constructor.

CMakeLists.txt
This PR adds `include(CPack)` to CMakeLists.txt to support generating source packages for `xgboost`.
cc: @trxcllnt
=> Include `cpack` to generate source packages

.github/workflows/r_tests.yml, src/data/data.cc
Work around #7156, by removing `resize()` of the thread-local vector inside the OpenMP block.
=> Work around a segfault observed in SparsePage::Push()

src/common/hist_util.h, src/tree/hist/histogram.h, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, tests/cpp/tree/hist/test_histogram.cc, tests/cpp/tree/test_quantile_hist.cc
- Fixes incorrect tests where distributed methods are not actually tested.
- Extract histogram builder to be a reusable module.
|        | Dataset | Train time         | Accuracy           |
|--------|:--------|:-------------------|:-------------------|
| Before | HIGGS   | 191.195842235989   | 0.7342790909090909 |
|        | covtype | 74.0480548529886   | 0.9398466476769103 |
| After  | HIGGS   | 184.16188054496888 | 0.7342790909090909 |
|        | covtype | 68.06914013501955  | 0.9398466476769103 |
=> Extract histogram builder from CPU Hist.

src/common/timer.cc, src/common/timer.h
Calling rabit functions during destruction is flaky.
* Display information on each worker instead.
* Add xgboost prefix to nvtx marker.
=> Remove synchronization in monitor.

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoost.java
Fix bug introduced in 17913713b554d820a8ce94226d854b4a5f1d8bbc (allow loading from byte array)
When loading model from stream, only last buffer read from the input stream is used to construct the model.
This may work for models smaller than 1 MiB (if you are lucky enough to read the whole model at once), but will always fail if the model is larger.
=> Fix model loading from stream

python-package/xgboost/sklearn.py
Close https://github.com/dmlc/xgboost/issues/6158 .
We have removed the feature name generation in DMatrix.
=> Re-enable feature validation in predict proba.

Jenkinsfile-win64, tests/ci_build/conda_env/win64_cpu_test.yml, tests/ci_build/conda_env/win64_test.yml
Sometimes, Conda hangs while installing Python packages.
1. Use `mamba` instead, which is a faster method for installing Python packages from Conda.
2. Download all Python packages from Conda. Previously, some packages were being downloaded from PyPI. Why this is a problem? Recently, `pip` became more strict about dependency resolution and download multiple packages upon running into a conflict:
>[2021-08-25T01:35:45.183Z] INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
(https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/PR-7 …
=> [CI] Fix hanging Python setup in Windows CI

Jenkinsfile-win64, doc/install.rst, tests/ci_build/build_r_pkg_with_cuda_win64.sh
Follow up with https://github.com/dmlc/xgboost/pull/6827 by building the binary R package for Windows too. This will greatly simplify using GPUs with the R package on Windows.
Users will now be able to install XGBoost with the following simple commands:
```
R -q -e "install.packages(c('data.table', 'magrittr', 'jsonlite', 'remotes'))"
R CMD INSTALL ./xgboost.tar.gz
```
and they will be able to use the GPU algorithm (as long as the machine has a working GPU).
I re-built the image of the Windows CI worker as part of this PR, in order to install R.
=> [CI] Automatically build GPU-enabled R package for Windows

src/common/device_helpers.cuh
=> Restore the custom double atomic add.

include/xgboost/json.h, src/common/json.cc, tests/cpp/common/test_json.cc
Performance doesn't change much, just for better code.  For max_depth=12, round=500, HIGGS:
* Master
Load average: 3.6808622678120932
Save average: 3.2464772860209146
* No except
Load average: 3.1963095664978027
Save average: 3.3569795290629068
=> Add noexcept to JSON objects.

include/xgboost/c_api.h, python-package/xgboost/data.py, src/c_api/c_api.cc, src/c_api/c_api.cu
* Use JSON encoded configurations.
* Expose them into header file.
Preparing for https://github.com/dmlc/xgboost/pull/7195 .
=> Expose DMatrix API for CUDA columnar and array.

amalgamation/xgboost-all0.cc, include/xgboost/data.h, src/common/hist_util.h, src/common/quantile.cc, src/common/quantile.h, src/data/data.cc, src/data/ellpack_page_raw_format.cu, src/data/ellpack_page_source.h, src/data/gradient_index.cc, src/data/gradient_index.h, src/data/gradient_index_format.cc, src/data/gradient_index_page_source.cc, src/data/gradient_index_page_source.h, src/data/histogram_cut_format.h, src/data/simple_dmatrix.cc, src/data/sparse_page_dmatrix.cc, src/data/sparse_page_dmatrix.cu, src/data/sparse_page_dmatrix.h, src/data/sparse_page_writer.h, src/tree/gpu_hist/gradient_based_sampler.cu, src/tree/gpu_hist/gradient_based_sampler.cuh, src/tree/updater_gpu_hist.cu, src/tree/updater_quantile_hist.cc, tests/cpp/data/test_gradient_index.cc, tests/cpp/data/test_gradient_index_page_raw_format.cc, tests/cpp/helpers.cc
* Add hessian to batch param in preparasion of new approx impl.
* Extract a push method for gradient index matrix.
* Use span instead of vector ref for hessian in sketching.
* Create a binary format for gradient index.
=> Initial support for external memory in gradient index.

src/common/hist_util.cu, tests/cpp/common/test_hist_util.cu
Close https://github.com/dmlc/xgboost/issues/7227 .
=> Fix mixed types in GPU sketching.

demo/guide-python/categorical.py, include/xgboost/feature_map.h, python-package/xgboost/core.py, python-package/xgboost/data.py, python-package/xgboost/sklearn.py, src/data/data.cc, tests/cpp/tree/test_tree_model.cc, tests/python-gpu/test_from_cudf.py, tests/python-gpu/test_from_cupy.py, tests/python/test_dmatrix.py, tests/python/test_with_pandas.py
* Shorten the type name from "categorical" to "c".
* Tests for np/cp array, scipy csr/csc/coo and uri.
* Specify the type for feature info.
Remaining type:
- pydatatable, xgboost will throw an error when categorical data is specified.
=> Support more input types for categorical data.

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/DMatrix.java, jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/DMatrix.scala, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/DMatrixTest.java, jvm-packages/xgboost4j/src/test/scala/ml/dmlc/xgboost4j/scala/DMatrixSuite.scala
During debugging https://github.com/dmlc/xgboost/issues/7210 , I found the java implementation has a constructor the uses 0 as the default value for `missing`, which doesn't make sense since 0 is a meaningful input for XGBoost.  `NaN` would be a better choice and is in fact used by both Python and R.  However, I don't think it's a good idea for us to swap the missing value silently.  Therefore, I propose that we deprecate those constructors and let users specify `missing` explicitly.
=> [jvm-packages] Deprecate constructors with implicit missing value.

src/common/hist_util.h, src/common/quantile.cc, src/common/quantile.h, tests/cpp/common/test_hist_util.cc, tests/cpp/common/test_hist_util.cu, tests/cpp/common/test_hist_util.h, tests/cpp/common/test_quantile.cc
Add categorical data support for single node sketching.
=> Categorical data support in CPU sketching.

python-package/xgboost/data.py, src/tree/updater_gpu_hist.cu, tests/python/test_with_pandas.py
~Stack on top of https://github.com/dmlc/xgboost/pull/7220~
=> Encode pandas categorical feature automatically.

CMakeLists.txt, cmake/Utils.cmake, src/common/device_helpers.cuh, src/data/ellpack_page.cu, src/metric/auc.cu, src/tree/gpu_hist/row_partitioner.cu
~- This works only with CUDA 11.4, for CUDA 11.2 there are some obscure errors with inclusive scan and custom iterators.~
- Tested with all CUDA 11.x.
- Workaround cub scan by using discard iterator in AUC.
- Limit the size of Argsort when compiled with CUDA cub.
=> Enable compiling with system cub.

R-package/src/Makevars.in, R-package/src/init.c, R-package/src/xgboost-win.def
I am experiencing an issue with some packages crashing when used in the same session. I'm unable to provide a reproducer, and I don't know exactly what is causing it or which package(s) are at fault, but I suspect it might be due to a symbol naming conflict in the compiled shared objects.
As it is right now, XGBoost registers all its symbols in the R dynamic object when it loads, which can cause issues if multiple packages are loaded and define symbols with the same name. This PR limits the exported symbol visibility to only the necessary - see https://cran.r-project.org/doc/manuals/R-exts.html#Controlling-visibility
Note that it modifies the R file `src/Makevars.in` by adding the R-defined `$(CXX_VISIBILITY)` variable. I don't know how that plays out when using the CMake build system, as …
=> [R] Avoid symbol naming conflicts with other packages

src/learner.cc
This warning sounds  a bit ungrammatical. Additionally, the second part of the warning is not clear. This PR changes the wording to make it clearer.
=> Improve wording for warning

src/objective/regression_obj.cu
it's part of https://github.com/dmlc/xgboost/pull/7192
Before this changes spans were created for each individual sample. Additional overheads of span `operator[]` were also avoided by usage raw pointers.
|       GetGradient     | airline | higgs | 
|------------|---------|---------|
| master, s  | 50.62 | 4.99 | 
| this PR, s | 16.34 | 1.64 | 
| speedup    | 3.1 | 3.04 |
=> Reduced span overheads in objective function calculate

doc/jvm/xgboost4j_spark_tutorial.rst, jvm-packages/xgboost4j-example/README.md, jvm-packages/xgboost4j-example/src/main/java/ml/dmlc/xgboost4j/java/example/BasicWalkThrough.java, jvm-packages/xgboost4j-example/src/main/java/ml/dmlc/xgboost4j/java/example/EarlyStopping.java, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/BoosterImplTest.java
Close https://github.com/dmlc/xgboost/issues/6893
=> [jvm-packages] Create demo and test for xgboost4j early stopping.

src/predictor/cpu_predictor.cc, tests/cpp/common/test_hist_util.h, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/predictor/test_predictor.cc, tests/cpp/predictor/test_predictor.h
The 0.5 threshold is just a heuristic not a result of a rigorous benchmark.  For now, I need to close https://github.com/dmlc/xgboost/issues/6659 since sparse datasets are quite usual with one-hot encoding.
@ShvetsKS
=> Avoid thread block with sparse data.

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/DefaultXGBoostParamsWriter.scala
Spark 3.2 depends on 3.7.0-M11 which has changed some implicited functions'
signatures. And it will result the xgboost4j built against spark 3.0/3.1
failed when saving the model.
=> [jvm-packages] Fix json4s binary compatibility issue

.github/workflows/jvm_tests.yml, .github/workflows/python_tests.yml, .travis.yml, tests/travis/setup.sh
From https://app.travis-ci.com/github/dmlc/xgboost/jobs/545794841#L7491 .
```
Warning: You are using macOS 10.14.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
```
I think this is the right time for us to move the remaining macos tests. This PR moves the JVM test and Python test to GitHub action.
=> Move macos test to github action.

include/xgboost/metric.h, src/learner.cc, src/metric/auc.cc, src/metric/auc.cu, src/metric/auc.h, src/metric/elementwise_metric.cu, src/metric/multiclass_metric.cu, src/metric/rank_metric.cc, src/metric/rank_metric.cu, src/metric/survival_metric.cu, tests/cpp/helpers.h, tests/python/test_with_sklearn.py
~Stacked on top of https://github.com/dmlc/xgboost/pull/7362 so marked as draft.~
This PR replaces some variables that store accumulated results from float to double-precision, for instance, the reduction result from elementwise metric and FP/TP in AUC.
The result is still serialized by `std::stringstream`, which is a little bit weird since if we use scientific notation with precision then it might contain trailing zeros.  But the `to_chars` implementation in XGBoost handles only float at the moment.
Close https://github.com/dmlc/xgboost/issues/7340 .
Close https://github.com/dmlc/xgboost/issues/4665 .
=> Use double precision in metric calculation.

.clang-format
Generated using `clang-format -style=google -dump-config > .clang-format`, with column
width changed from 80 to 100 to be consistent with existing cpplint check.
No actual change is made.
=> Add clang-format.

include/xgboost/span.h, src/common/device_helpers.cuh, tests/cpp/common/test_span.h
* Disable `rbegin` on device code to avoid calling host function.
* Add `trbegin` and friends.
Extracted from https://github.com/dmlc/xgboost/pull/7214 .
=> Fix span reverse iterator.

python-package/xgboost/core.py, python-package/xgboost/dask.py, python-package/xgboost/data.py, src/data/array_interface.h, src/data/data.cu, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, tests/cpp/data/test_metainfo.cc, tests/python-gpu/test_from_cudf.py, tests/python-gpu/test_from_cupy.py, tests/python-gpu/test_gpu_with_dask.py, tests/python-gpu/test_gpu_with_sklearn.py, tests/python/test_dmatrix.py, tests/python/test_with_dask.py, tests/python/test_with_modin.py, tests/python/test_with_pandas.py, tests/python/test_with_sklearn.py, tests/python/testing.py
* cudf
* cupy
* numpy
* pandas
* modin
* dask
This is already partially supported but never properly tested.  So the only possible way to use it is calling `numpy.array.flatten` with `base_margin` before passing it into XGBoost.  This PR adds proper support for most of the data types along with tests.
Close https://github.com/dmlc/xgboost/issues/7083 .
=> Support multi-class with base margin.

CMakeLists.txt, doc/build.rst, src/common/device_helpers.cuh
* Require system cub installation for CTK11.4+.
* Check thrust version for segmented sort.
For CUDA toolkit >= 11.4:
```
cmake -DBUILD_WITH_CUDA_CUB=ON -DUSE_CUDA=ON
```
Close https://github.com/dmlc/xgboost/issues/7378 .
=> Support building with CTK11.5.

demo/CLI/binary_classification/mapfeat.py, demo/CLI/binary_classification/mknfold.py, demo/CLI/regression/mapfeat.py, demo/CLI/regression/mknfold.py, demo/CLI/yearpredMSD/csv2libsvm.py
Change from system Python to environment python3.  For Ubuntu 20.04, only `python3` is
available and there's no `python`.  So at least `python3` is consistent with Python
virtual env, Ubuntu and anaconda.
Related https://github.com/dmlc/xgboost/issues/7384 .
=> Change shebang used in CLI demo.

R-package/R/xgboost.R, src/common/threading_utils.h, tests/python/test_openmp.py, tests/python/with_omp_limit.py
Fixes R win builder.
cc @hetong007 
Details, `OMP_THREAD_LIMIT` is an environment variable defined by OpenMP standard.  Users can set it to limit the number of threads in each thread group.  However, the `omp_get_max_threads()` function used by XGBoost is not affected by this env var.  So when the env var is set, XGBoost naively thought it can obtain `omp_get_max_threads()` number of threads, while the received number of threads is much smaller.
I ran it on win builder for a quick test https://win-builder.r-project.org/vCrjkrlXZE0l/00check.log we should run it again after backporting to 1.5 branch.
=> Handle `OMP_THREAD_LIMIT` in environment.

include/xgboost/learner.h, include/xgboost/objective.h, include/xgboost/task.h, include/xgboost/tree_updater.h, plugin/example/custom_obj.cc, src/gbm/gbtree.cc, src/learner.cc, src/objective/aft_obj.cu, src/objective/hinge.cu, src/objective/multiclass_obj.cu, src/objective/rank_obj.cu, src/objective/regression_loss.h, src/objective/regression_obj.cu, src/tree/tree_updater.cc, src/tree/updater_colmaker.cc, src/tree/updater_gpu_hist.cu, src/tree/updater_histmaker.cc, src/tree/updater_prune.cc, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, src/tree/updater_refresh.cc, src/tree/updater_sync.cc, tests/cpp/tree/test_gpu_hist.cu, tests/cpp/tree/test_histmaker.cc, tests/cpp/tree/test_prune.cc, tests/cpp/tree/test_quantile_hist.cc, tests/cpp/tree/test_refresh.cc, tests/cpp/tree/test_tree_stat.cc
This PR adds a new struct for obtaining some information about the objective. The struct is not used yet but is required for the future development of categorical split.  In https://github.com/dmlc/xgboost/pull/7214 , the optimal partitioning is only available for binary classification and regression.  Copying inlined comment here:
```
* The task field is useful for tree split finding, also for some metrics like auc.
* While const_hess is useful for algorithms like adaptive tree where one needs to update
* the leaf value after building the tree.  Lastly, knowing whether hessian is constant
* can allow some optimizations like skipping the quantile sketching.
```
* Define `ObjInfo`.
* Pass it to tree methods.
=> Pass infomation about objective to tree methods.

include/xgboost/linalg.h, include/xgboost/tree_updater.h, src/gbm/gblinear.cc, src/gbm/gbtree.cc, src/gbm/gbtree.cu, src/metric/auc.cc, src/tree/updater_gpu_hist.cu, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, tests/cpp/common/test_linalg.cc, tests/cpp/tree/test_gpu_hist.cu
* Replace existing matrix and vector view.
Makes https://github.com/dmlc/xgboost/pull/7309 easier.  Once we go to multi-target multi-class, predict leaf will have 5-dim output.
=> Implement a general array view.

R-package/R/xgb.Booster.R, R-package/R/xgb.importance.R, R-package/tests/testthat/test_helpers.R, doc/prediction.rst, include/xgboost/gbm.h, include/xgboost/learner.h, src/c_api/c_api.cc, src/gbm/gblinear.cc, src/gbm/gbtree.h, src/learner.cc, tests/cpp/gbm/test_gbtree.cc
* Add implementation for tree index.  The parameter is not documented in C API since we
should work on porting the model slicing to R instead of supporting more use of tree
index.
* Fix the difference between "gain" and "total_gain".
Related: https://github.com/dmlc/xgboost/issues/7260#issuecomment-960535728.
=> [R] Fix global feature importance and predict with 1 sample.

src/common/categorical.h, src/tree/hist/evaluate_splits.h, src/tree/param.h, src/tree/split_evaluator.h, src/tree/updater_colmaker.cc, src/tree/updater_histmaker.cc, src/tree/updater_quantile_hist.cc, tests/cpp/categorical_helpers.h, tests/cpp/common/test_quantile.cu, tests/cpp/common/test_quantile.h, tests/cpp/helpers.cc, tests/cpp/helpers.h, tests/cpp/tree/gpu_hist/test_histogram.cu, tests/cpp/tree/hist/test_evaluate_splits.cc, tests/cpp/tree/test_param.cc
* Implementation for one hot based.
* Implementation for partition based for regression. (LightGBM)
Currently, the evaluation function is using parameters from numerical split.  We should set up a new set of training parameters later.  But before that, I want to have a working implementation and some experiment results first.
Extracted from https://github.com/dmlc/xgboost/pull/7214 .
=> CPU evaluation for cat data.

CMakeLists.txt, doc/build.rst, src/common/device_helpers.cuh
* Support building with CTK11.5.
* Require system cub installation for CTK11.4+.
* Check thrust version for segmented sort.
=> [backport] Support building with CTK11.5. (#7379)

python-package/xgboost/core.py, python-package/xgboost/data.py, src/common/categorical.h, src/common/hist_util.cu, src/common/hist_util.cuh, src/data/adapter.h, src/data/data.cc, src/data/device_adapter.cuh, src/data/iterative_device_dmatrix.cu, src/tree/updater_gpu_hist.cu, tests/cpp/common/test_hist_util.cu, tests/python-gpu/test_from_cudf.py, tests/python/test_with_pandas.py
* Replace -1 in pandas initializer.
* Unify `IsValid` functor.
* Mimic pandas data handling in cuDF glue code.
* Check invalid categories.
* Fix DDM sketching.
=> [backport] Handle missing values in dataframe with category dtype. (#7331)

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/DefaultXGBoostParamsWriter.scala
Spark 3.2 depends on 3.7.0-M11 which has changed some implicited functions'
signatures. And it will result the xgboost4j built against spark 3.0/3.1
failed when saving the model.
=> [backport] [jvm-packages] Fix json4s binary compatibility issue (#7376)

include/xgboost/data.h, jvm-packages/xgboost4j-gpu/src/native/xgboost4j-gpu.cu, src/common/device_helpers.cuh, src/data/adapter.h, src/data/array_interface.cu, src/data/array_interface.h, src/data/data.cc, src/data/data.cu, src/data/device_adapter.cuh, src/data/file_iterator.h, src/data/validation.h, tests/cpp/data/test_adapter.cc, tests/cpp/data/test_array_interface.cc, tests/cpp/data/test_array_interface.cu, tests/cpp/data/test_array_interface.h, tests/cpp/data/test_iterative_device_dmatrix.cu, tests/cpp/data/test_metainfo.cu, tests/cpp/helpers.h
Part of https://github.com/dmlc/xgboost/pull/7405
The `ArrayInterface` class is extended to support multi-dim array inputs. Previously this class handles only 2-dim (vector is also matrix).  This PR specifies the expected dimension at compile-time and the array interface can perform various checks automatically for input data. Also, adapters like CSR are more rigorous about their input.  Lastly, row vector and column vector are handled without intervention from the caller.
=> Extend array interface to handle ndarray.

R-package/tests/testthat/test_helpers.R, include/xgboost/data.h, src/data/simple_dmatrix.h, src/tree/updater_colmaker.cc, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h
Related: https://github.com/dmlc/xgboost/issues/7260#issuecomment-962985358
* Remove hist builder dtor.
I did not reproduce the warning using clang-14, might be missing some flags in my config or it's just a bug in clang-12 used by CRAN test.  Anyway, this is a cleanup that removes unnecessary code.
* Initialize some variables.
=> Fix R CRAN failures.

doc/contrib/coding_guide.rst, include/xgboost/c_api.h, include/xgboost/data.h, include/xgboost/intrusive_ptr.h, include/xgboost/predictor.h, include/xgboost/task.h, python-package/xgboost/data.py, src/common/common.cu, src/data/data.cc, src/data/data.cu, src/data/simple_dmatrix.cc, src/gbm/gblinear.cc, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, src/predictor/predictor.cc, tests/cpp/common/test_hist_util.h, tests/cpp/data/test_metainfo.cc, tests/cpp/data/test_metainfo.cu, tests/cpp/data/test_metainfo.h, tests/cpp/data/test_simple_dmatrix.cc, tests/cpp/data/test_simple_dmatrix.cu, tests/cpp/helpers.cc, tests/cpp/helpers.h, tests/cpp/predictor/test_gpu_predictor.cu, tests/python/test_dmatrix.py
This is the last part of the original PR for extending meta info to multi-dimension arrays.  This PR changes base_margin into a 3-dim array, with one of them being reserved for multi-target classification.  Also, a breaking change is made for binary serialization due to extra dimension along with a fix for saving the feature weights.  Lastly, it unifies the prediction initialization between CPU and GPU.  After this PR, the meta info setter in Python will be based on array interface.
* Extend the array interface class to multi-dim.
* Define tensor storage class as an extension to host device vector.
* Move some calculation of tensor view to compile time for better checks.
* Use them for base margin.
* Use array interface for Python meta info.
* Unify `InitPredOutput` function from both …
=> [Breaking] Accept multi-dim meta info.

R-package/tests/testthat/test_helpers.R, include/xgboost/data.h, src/data/simple_dmatrix.h, src/tree/updater_colmaker.cc, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h
* Remove hist builder dtor.
* Initialize values.
* Tolerance.
* Remove the use of nthread in col maker.
=> [backport] Fix R CRAN failures. (#7404)

src/common/hist_util.cc, src/common/hist_util.h, src/tree/hist/histogram.h, src/tree/updater_quantile_hist.cc, tests/cpp/tree/hist/test_evaluate_splits.cc, tests/cpp/tree/hist/test_histogram.cc
Extracted from https://github.com/dmlc/xgboost/pull/7214
The perf change for the complete PR is in https://github.com/dmlc/xgboost/pull/7214#issuecomment-952971039 .  Might have some small overhead (within variance), but the benefit is hist/approx will be able to support both categorical data and external memory in the future.
* Support external memory in histogram building.
* Remove unused `SubtractionTrick` function.  The builder class can be completely removed, but I will keep the cleanup out of the scope.
=> Support external memory in CPU histogram building.

python-package/xgboost/training.py
`Bost` -> `Both`, mentioned in #7463.
Close #7463 .
=> Minor typo fix

src/data/array_interface.h
Close https://github.com/dmlc/xgboost/issues/7464.
I did not reproduce the error in linked issue.  But the constexpr is not necessary anyway so I just remove it in the PR.
=> Remove unnecessary constexpr.

python-package/xgboost/compat.py, python-package/xgboost/dask.py, tests/python/test_with_dask.py
Close https://github.com/dmlc/xgboost/issues/7454 .
pydata sparse is not yet supported.  Would be great if we can add a new adapter in c++.
=> Support scipy sparse in dask.

.github/workflows/python_tests.yml, tests/ci_build/conda_env/macos_cpu_test.yml
This splits up the macos and win tests so they can use different conda env.
=> Fix macos package upload.

jvm-packages/xgboost4j-gpu/src/main/java/ml/dmlc/xgboost4j/gpu/java/CudfColumn.java, jvm-packages/xgboost4j-gpu/src/test/scala/ml/dmlc/xgboost4j/scala/DeviceQuantileDMatrixSuite.scala, jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/DMatrix.scala, jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/DeviceQuantileDMatrix.scala
This PR tries to add DeviceQuantileDMatrix scala support. And it's a part of https://github.com/dmlc/xgboost/pull/7361
=> [jvm-packages] Add DeviceQuantileDMatrix for scala supporting

tests/cpp/tree/hist/test_histogram.cc
Extracted from https://github.com/dmlc/xgboost/pull/7214 .
=> Test CPU histogram with cat data.

include/xgboost/data.h, src/data/data.cc, src/data/simple_dmatrix.cc, src/predictor/predictor.cc, tests/cpp/data/test_metainfo.h, tests/cpp/data/test_simple_dmatrix.cc, tests/cpp/predictor/test_gpu_predictor.cu
Different targets might have a different number of classes, simply adding dim doesn't cut it.
=> Reduce base margin to 2 dim for now.

doc/build.rst
The documentation states that to build from source you need CMake 3.13 or higher. However, according to https://github.com/dmlc/xgboost/blob/master/CMakeLists.txt#L1 CMake 3.14 or higher is required. This PR updates the documentation to state that CMake 3.14 or higher is required
=> Updated CMake version requirement in build.rst

src/tree/param.h, src/tree/updater_colmaker.cc
- Remove unused parameters.
- Move `default_direction` into the exact tree method since it's the only consumer.
=> Remove unused parameters.

python-package/xgboost/core.py, python-package/xgboost/dask.py, src/data/data.cc, src/data/device_adapter.cuh, src/data/simple_dmatrix.cu, tests/cpp/data/test_metainfo.cc, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_with_dask.py
Close https://github.com/dmlc/xgboost/issues/7494 .
Empty partition is different from empty DMatrix, the former has only some partitions that are empty, but the dataset on each worker as a whole is not empty.
=> [dask] Fix ddqdm with empty partition.

jvm-packages/pom.xml, jvm-packages/xgboost4j-gpu/pom.xml, jvm-packages/xgboost4j-spark-gpu/pom.xml, jvm-packages/xgboost4j-spark-gpu/src/main/java/ml/dmlc/xgboost4j/java/nvidia/spark/GpuColumnBatch.java, jvm-packages/xgboost4j-spark-gpu/src/main/resources/META-INF/services/ml.dmlc.xgboost4j.scala.spark.PreXGBoostProvider, jvm-packages/xgboost4j-spark-gpu/src/main/scala, jvm-packages/xgboost4j-spark-gpu/src/main/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuPreXGBoost.scala, jvm-packages/xgboost4j-spark-gpu/src/main/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuUtils.scala, jvm-packages/xgboost4j-spark-gpu/src/main/scala/ml/dmlc/xgboost4j/scala/spark, jvm-packages/xgboost4j-spark-gpu/src/main/scala/org, jvm-packages/xgboost4j-spark-gpu/src/test, jvm-packages/xgboost4j-spark-gpu/src/test/resources, jvm-packages/xgboost4j-spark-gpu/src/test/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuPerTest.scala, jvm-packages/xgboost4j-spark-gpu/src/test/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuTestSuite.scala, jvm-packages/xgboost4j-spark-gpu/src/test/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuXGBoostClassifierSuite.scala, jvm-packages/xgboost4j-spark-gpu/src/test/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuXGBoostGeneralSuite.scala, jvm-packages/xgboost4j-spark-gpu/src/test/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuXGBoostRegressorSuite.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/PreXGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/PreXGBoostProvider.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/BoosterParams.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GpuParams.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/XGBoostEstimatorCommon.scala
This PR is the final PR for https://github.com/dmlc/xgboost/pull/7361.
For now, there is an issue for CPU transform.  Model A  transforms CPU dataset which reads from fileABC and get the result AA, while Model A  transforms GPU dataset which reads from fileABC and get the result BB. We expect AA should be equal BB, but in fact, they are different.
I've figured out why. will create an following PR to fix that after this PR merged.
=> [jvm-packages] add Rapids plugin support

tests/python/test_demos.py
callbacks.py is using matplotlib, the test will be failed if matplotlib is not available.
=> [TEST][MINOR] Add skipif no_matplotlib for test_callbacks_demo

R-package/R/xgb.Booster.R, R-package/tests/testthat/test_interactions.R
Close https://github.com/dmlc/xgboost/issues/7483 .
The PR prevents R from reshaping the return arrays.
@hetong007
=> [R] Fix single sample prediction with SHAP.

src/tree/gpu_hist/evaluate_splits.cu, src/tree/gpu_hist/evaluate_splits.cuh, src/tree/updater_gpu_common.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/tree/gpu_hist/test_evaluate_splits.cu
Close https://github.com/dmlc/xgboost/issues/7488 .
* PR
| dataset | algorithm | train_time         | test_time | AUC                | Accuracy           | F1                 | Precision            | Recall              | MeanAbsError      | MeanSquaredError | MedianAbsError  |
|---------|-----------|--------------------|-----------|--------------------|--------------------|--------------------|----------------------|---------------------|-------------------|------------------|-----------------|
| airline | xgb-gpu   | 66.33061233296758  | -na-      | 0.8084086879850008 | 0.6645717066157337 | -na-               | 0.5994090037583283   | 0.883954407897074   | -na-              | -na-             | -na-            |
| bosch   | xgb-gpu   | 12.716636892000679 | -na-      | 0.7026122514402441 …
=> Use double for GPU Hist node sum.

src/tree/gpu_hist/gradient_based_sampler.cu, src/tree/gpu_hist/gradient_based_sampler.cuh, tests/python-gpu/test_gpu_data_iterator.py, tests/python/test_data_iterator.py, tests/python/testing.py
- The error happens because when reading from external memory the batch is
reassembled for every new iteration. The variable `original_page_` is
initialized from the first batch, when the constructor of `GradiendBasedSample`
is called. After iterating through the batches the original memory is not
accessible, so when trying to access the memory pointed by `original_page_`
causes an error.
- The solution is instead of accessing data from the `original_page_`, to access
the data from the first page of the available batch.
fix #7476
=> Fix external memory, gpu_hist and subsampling combination bug. (#7476)

rabit/include/rabit/internal/utils.h
These macros can create problems in projects that include xgboost and use vsnprintf/snprintf.
vsnprintf and snprintf are supported since Visual Studio 14, so we don't need these macros anymore.
=> Remove macro definitions of snprintf and vsnprintf

doc/tutorials/model.rst
As suggested on issue #7480
I think it should be fine to merge.
=> [doc] Lowercase omega for per tree complexity

include/xgboost/generic_parameters.h, include/xgboost/predictor.h, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, src/predictor/predictor.cc, tests/cpp/predictor/test_predictor.cc
This is part of the ongoing effort to remove the dependency on global omp variables.
Rename the `generic_param_` to `ctx_` (as context) to better reflect its usage.
=> Remove `omp_get_max_threads` in CPU predictor.

doc/tutorials/index.rst, doc/tutorials/multioutput.rst, python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
* Add support for sklearn prediction function.
* Add basic documents.
* Add tests.
Related: https://github.com/dmlc/xgboost/issues/2087 .
=> Initial support for multi-label classification.

doc/parameter.rst, doc/python/callbacks.rst, doc/python/python_api.rst, doc/treemethod.rst, doc/tutorials/custom_metric_obj.rst, python-package/xgboost/callback.py, python-package/xgboost/config.py, python-package/xgboost/core.py, python-package/xgboost/dask.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py
* Use cross references instead of URL.
* Fix auto doc for callback.
=> [doc] Use cross references in sphinx doc.

include/xgboost/json_io.h, src/c_api/c_api_utils.h, src/tree/updater_quantile_hist.h
* Unused variable.
* Unnecessary virtual function.
=> Remove some warnings from clang.

include/xgboost/gbm.h, include/xgboost/linear_updater.h, src/gbm/gblinear.cc, src/gbm/gbm.cc, src/gbm/gbtree.cc, src/gbm/gbtree.h, src/gbm/gbtree_model.h, src/linear/coordinate_common.h, src/linear/linear_updater.cc, src/linear/updater_coordinate.cc, src/linear/updater_gpu_coordinate.cu, src/linear/updater_shotgun.cc
This is part of the ongoing effort to remove the dependency on global omp variables.
Rename the `generic_param_` to `ctx_` (as context) to better reflect its usage.
=> Remove `omp_get_max_threads` in gbm and linear.

src/gbm/gblinear_model.cc, tests/python-gpu/test_gpu_linear.py, tests/python/test_linear.py
=> Fix num_boosted_rounds for linear model.

jvm-packages/xgboost4j/src/native/xgboost4j.cpp, jvm-packages/xgboost4j/src/native/xgboost4j.h
Regenerated using:
```
javah -o ./xgboost4j/src/native/xgboost4j.h -classpath ./xgboost4j/target/classes/ ml.dmlc.xgboost4j.java.XGBoostJNI
```
with
```
javah -version
javah version "1.8.0_312"
```
=> [jvm-packages] Update JNI header.

include/xgboost/intrusive_ptr.h, include/xgboost/json.h, include/xgboost/json_io.h, src/common/json.cc, tests/cpp/common/test_json.cc, tests/cpp/test_serialization.cc
This is a partial implementation of UBJSON with support for typed arrays.  Some missing
features are `f64`, typed object, and the no-op.
Extracted from https://github.com/dmlc/xgboost/pull/7545 .
=> Implement ubjson.

src/data/ellpack_page_source.h, src/data/iterative_device_dmatrix.h
Some variables are not used if XGBoost is not compiled with CUDA.
=> Silent some warnings for unused variable.

R-package/tests/testthat/test_glm.R, src/gbm/gblinear.cc
Close https://github.com/dmlc/xgboost/issues/7460 
TODOs:
=> Fix early stopping with linear model.

include/xgboost/c_api.h, python-package/xgboost/core.py, src/c_api/c_api.cc, tests/cpp/c_api/test_c_api.cc
This is not a breaking change as it was introduced in this version.
=> Rename build info function to be consistent with rest of the API.

python-package/xgboost/core.py, python-package/xgboost/dask.py, python-package/xgboost/data.py, python-package/xgboost/sklearn.py
Just to get the CI pass on the 1.5.1 branch.
=> [backport] Fix pylint and mypy.

tests/python-gpu/test_gpu_parse_tree.py, tests/python-gpu/test_gpu_plotting.py, tests/python/test_parse_tree.py, tests/python/test_plotting.py
* Add tree to df tests.
* Add plotting tests.
* Add histogram tests.
=> Cover approx tree method for categorical data tests.

doc/tutorials/categorical.rst, src/common/categorical.h, src/common/quantile.cc, src/common/quantile.h, src/tree/hist/evaluate_splits.h, src/tree/updater_gpu_hist.cu, tests/python-gpu/test_gpu_updaters.py, tests/python/test_updaters.py
* Use float in CPU categorical set to preserve the input value.
* Check out of range values.
=> Validate out of range categorical value.

CMakeLists.txt
Note that when cub inside CUDA is being used, XGBoost performs checks on input size
instead of using internal cub function to accept inputs larger than maximum integer.
This helps jvm packages and Python package build.
=> Configure cub version automatically.

tests/python/test_eval_metrics.py, tests/python/test_with_dask.py
* Use random port in dask tests to avoid warnings for occupied port.
* Increase the difficulty of AUC tests.
avoiding warnings makes the CI log easier to parse.
=> Small cleanup to tests.

doc/tutorials/dask.rst, python-package/xgboost/dask.py, python-package/xgboost/tracker.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_tracker.py, tests/python/test_with_dask.py
See added doc for use case.
- Add user configuration.
- Bring back to the logic of using scheduler address from dask.  This was removed when we were trying to support GKE, now we bring it back and let xgboost try it if direct guess or host IP from user config failed.
=> [dask] Add scheduler address to dask config.

R-package/R/xgb.load.R, R-package/R/xgb.save.raw.R, R-package/demo/basic_walkthrough.R, R-package/src/init.c, R-package/src/xgboost_R.cc, R-package/src/xgboost_R.h, R-package/tests/testthat/test_io.R
From https://github.com/dmlc/xgboost/pull/7545 .
=> [R] Implement new `save_raw` in R.

src/data/gradient_index.cc, src/data/gradient_index.h, src/data/simple_dmatrix.cc, src/data/sparse_page_dmatrix.cc, src/data/sparse_page_dmatrix.cu, src/tree/hist/evaluate_splits.h, src/tree/updater_approx.cc
~Stacked on https://github.com/dmlc/xgboost/pull/7588 .~
Don't regenerate the gradient index if the hessian is constant (RMSE).  For the year dataset, runtime for 500 rounds is dropped from 194.6772 to 63.6052
=> Avoid regenerating the gradient index for approx.

doc/install.rst
https://github.com/conda-forge/xgboost-feedstock/pull/79 added a build for `osx-arm64`. This build is a cross-build, using Azure Pipelines to build a binary for Apple Silicon. Given the high complexity of setting up a cross-build, we won't be able to replicate it ourselves. As a result, we won't upload a M1-native Python wheel on PyPI. Instead, we'll tell Apple Silicon users to use Conda to install XGBoost.
=> [Doc] Add instruction to install XGBoost for Apple Silicon using Conda

R-package/tests/testthat/test_dmatrix.R
This guarantees the removal will trigger for unexpected early exits
=> use exit hook to remove temp file

R-package/R/xgb.Booster.R, R-package/R/xgb.DMatrix.R, R-package/man/predict.xgb.Booster.Rd, R-package/man/xgb.DMatrix.Rd, R-package/src/init.c, R-package/src/xgboost_R.cc, R-package/src/xgboost_R.h, R-package/tests/testthat/test_basic.R
Fixes #7610
This PR wraps the C function to create a DMatrix from CSR data in the R interface, allowing to pass prediction data in CSR format. The code is a copycat version of the existing CSC wrapper.
=> (R) Accept CSR data for predictions

demo/guide-python/sklearn_examples.py, demo/guide-python/sklearn_parallel.py, demo/guide-python/update_process.py, src/gbm/gblinear_model.cc, tests/python-gpu/test_gpu_linear.py, tests/python-gpu/test_gpu_with_sklearn.py, tests/python/test_callback.py, tests/python/test_demos.py, tests/python/test_linear.py, tests/python/test_predict.py, tests/python/test_with_dask.py, tests/python/test_with_shap.py, tests/python/test_with_sklearn.py, tests/python/testing.py
`sklearn.datasets.load_boston` was marked as deprecated in scikit-learn 1.0.0: https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_boston.html
Replace all uses of `sklearn.datasets.load_boston` with `sklearn.datasets.fetch_california_housing`.
=> Replace all uses of deprecated function sklearn.datasets.load_boston

.github/workflows/main.yml, .github/workflows/python_tests.yml, .github/workflows/python_wheels.yml, dev/release-py-r.py, doc/contrib/ci.rst, python-package/setup.py, tests/ci_build/build_python_wheels.sh, tests/ci_build/conda_env/macos_cpu_test.yml
* Use cibuildwheel to build Python wheels targeting MacOS x86_64 and MacOS arm64 (aka Apple Silicon)
* Bundle libomp 11.1.0 into the Python wheels. This step is automatically done by cibuildwheel. Using the version 11.1.0 ensures that we don't get random segfaults when running inside a Conda environment. (See https://github.com/scikit-learn/scikit-learn/pull/21227#issuecomment-933001394 for the list of configurations where segfaults occur.)
* Users no longer need to run `brew instal libomp` prior to installing XGBoost.
* Create a separate YAML file dedicated for wheel building, since there's lots of details involved.
This PR is inspired by https://github.com/scikit-learn/scikit-learn/pull/22109.
Closes #7039
=> [CI] Build Python wheels for MacOS (x86_64 and arm64)

.github/workflows/python_wheels.yml, Jenkinsfile, Jenkinsfile-win64, tests/ci_build/build_python_wheels.sh
* Consistently upload all artifacts to `s3://xgboost-nightly-builds/[branch-name]/`.
* Move env var setup and other details into `build_python_wheels.sh`, to reduce clutter in the pipeline definition of `python_wheels.yml`.
=> [CI] Clean up Python wheel build pipeline

python-package/xgboost/dask.py, tests/python/test_with_dask.py
This affects using sklearn wrapper on local cluster with n_workers > 1.
=> [dask] Fix nthread config with dask sklearn wrapper.

python-package/xgboost/dask.py, src/predictor/predictor.cc, tests/python-gpu/test_gpu_with_dask.py
Empty partition is different from empty dataset.  For the former case, each worker has
non-empty dask collections, but each collection might contain empty partitions.
Close https://github.com/dmlc/xgboost/issues/7639 .
=> [dask] Fix empty partition with pandas input.

cmake/Utils.cmake, demo/guide-python/cat_in_the_dat.py, demo/guide-python/categorical.py, doc/parameter.rst, doc/tutorials/categorical.rst, include/xgboost/task.h, python-package/xgboost/core.py, python-package/xgboost/sklearn.py, src/common/categorical.h, src/common/device_helpers.cuh, src/common/hist_util.h, src/common/quantile.cc, src/common/quantile.cu, src/tree/gpu_hist/evaluate_splits.cu, src/tree/gpu_hist/evaluate_splits.cuh, src/tree/gpu_hist/evaluator.cu, src/tree/gpu_hist/expand_entry.cuh, src/tree/hist/evaluate_splits.h, src/tree/split_evaluator.h, src/tree/updater_gpu_common.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/common/test_hist_util.h, tests/cpp/tree/gpu_hist/test_evaluate_splits.cu, tests/cpp/tree/hist/test_evaluate_splits.cc, tests/cpp/tree/test_evaluate_splits.h, tests/cpp/tree/test_gpu_hist.cu, tests/python/test_updaters.py
* Implement `MaxCategory` in quantile.
* Implement partition-based split for GPU evaluation.  Currently, it's based on the existing evaluation function.
* Extract an evaluator from GPU Hist to store the needed states.
* Added some CUDA stream/event utilities.
* Update document with references.
* Fixed a bug in approx evaluator where the number of data points is less than the number of categories.
=> Support optimal partitioning for GPU hist.

R-package/R/xgb.DMatrix.R, R-package/tests/testthat/test_feature_weights.R, doc/parameter.rst
Add feature weights to R DMatrix.  Please note that the "approx" tree method was rewritten very recently and doesn't support feature weights in released versions.
cc @hetong007 @tibshirani
Close https://github.com/dmlc/xgboost/issues/7657
=> [R] Implement feature weights.

include/xgboost/span.h, src/tree/hist/evaluate_splits.h
This is part of CRAN policies.
Close https://github.com/dmlc/xgboost/issues/7651 .
=> Avoid `std::terminate` for R package.

include/xgboost/span.h
My mistake, didn't remember R package doesn't like standard output.  For now, the span doesn't perform any check for the R package.
=> Avoid print for R package.

include/xgboost/span.h, src/tree/gpu_hist/row_partitioner.cuh
This fixes the failing build on master branch.
* Remove kernel check.
=> Work around nvcc error.

python-package/xgboost/core.py, python-package/xgboost/dask.py, python-package/xgboost/rabit.py, python-package/xgboost/tracker.py, tests/python/test_tracker.py
* Cleanup pylint errors in rabit modules.
* Make data iter an abstract class and cleanup private access.
* Cleanup no-self-use for booster.
=> Cleanup some pylint errors.

jvm-packages/xgboost4j-spark-gpu/src/main/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuPreXGBoost.scala
If num worker is set to 1, we don't need to repartition option, since it will cause the shuffle. Instead, we use coaelsce.
=> [jvm-packages] Do not repartition when nWorker = 1

amalgamation/xgboost-all0.cc, include/xgboost/generic_parameters.h, src/common/threading_utils.cc, src/common/threading_utils.h, src/learner.cc
Close https://github.com/dmlc/xgboost/issues/7653 .
Need some testing.
=> Honor CPU counts from CFS.

doc/requirements.txt
- Update sphinx, this is not necessary.
- Install sklearn when building the doc.
Close https://github.com/dmlc/xgboost/issues/6433 .
=> Fix document build with scikit-learn

python-package/xgboost/callback.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py
* Fix copy for cv.  This prevents inserting default callbacks into the input list.
* Clarify the behavior of callbacks in training/cv.
* Fix typos in doc.
Close https://github.com/dmlc/xgboost/issues/7637 .
=> [doc] Clarify that states in callbacks are mutated.

jvm-packages/xgboost4j-spark-gpu/src/test/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuXGBoostClassifierSuite.scala, jvm-packages/xgboost4j-spark-gpu/src/test/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuXGBoostGeneralSuite.scala, jvm-packages/xgboost4j-spark-gpu/src/test/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuXGBoostRegressorSuite.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GpuParams.scala
For now, xgboost4j-spark has provided 2 APIs for setting features, 1 API for CPU, another for GPU, which may cause user confusion.
This PR deleted the GPU API and added an override CPU API  setFeaturesCol to accept Array[String] parameters.
=> [jvm-packages] unify the set features API

src/common/column_matrix.h, src/common/hist_util.h, src/common/threading_utils.h, src/data/gradient_index.cc, src/data/gradient_index.h, src/data/gradient_index_format.cc, src/tree/updater_approx.h, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, tests/cpp/common/test_hist_util.cc, tests/cpp/tree/hist/test_histogram.cc, tests/cpp/tree/test_quantile_hist.cc
Extracted from https://github.com/dmlc/xgboost/pull/7659
* Code comments.
* Const accessor to index.
* Remove/rename some variables in the `Index` class.
* Simplify the `MemStackAllocator`.
=> Small cleanup to gradient index and hist.

R-package/R/xgb.load.raw.R, R-package/man/xgb.load.raw.Rd, R-package/tests/testthat/test_io.R
Close https://github.com/dmlc/xgboost/issues/7351 .
=> [R] Construct booster object in `load.raw`.

doc/parameter.rst, doc/tutorials/categorical.rst, include/xgboost/tree_model.h, python-package/xgboost/core.py, python-package/xgboost/sklearn.py, src/common/partition_builder.h, src/common/threading_utils.h, src/tree/hist/evaluate_splits.h, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, tests/cpp/tree/hist/test_evaluate_splits.cc, tests/cpp/tree/test_approx.cc, tests/cpp/tree/test_partitioner.h, tests/cpp/tree/test_quantile_hist.cc, tests/python/test_updaters.py
* Extract partitioner from hist.
* Implement categorical data support by passing the gradient index directly into the partitioner.
* Organize/update document.
* Remove code for negative hessian.
Extracted from https://github.com/dmlc/xgboost/pull/7659 .
Close https://github.com/dmlc/xgboost/issues/4372.
=> Support categorical data for hist.

doc/parameter.rst, doc/treemethod.rst, doc/tutorials/feature_interaction_constraint.rst, doc/tutorials/monotonic.rst, src/tree/updater_colmaker.cc, tests/cpp/tree/test_tree_policy.cc, tests/python-gpu/test_gpu_prediction.py
* Revise documents after recent refactoring and cat support.
* Add tests for behavior of max_depth and max_leaves.
=> Update documents and tests.

demo/guide-python/cat_in_the_dat.py, src/tree/gpu_hist/evaluate_splits.cuh, src/tree/gpu_hist/evaluator.cu
* Use transform the pre-compute some of the values.
The time used for the `cat-in-the-dat.py` demo is reduced by about half from 4.2 seconds to about 2.1 seconds.
Suggested by @RAMitchell .
=> Optimize GPU evaluation function for categorical data.

python-package/xgboost/core.py
- Addressing https://github.com/dmlc/xgboost/issues/7712
- Corrected integer types
- also referred current implementation of `num_row()`, `num_col()`
=> Fix for Feature shape mismatch error

python-package/xgboost/core.py, python-package/xgboost/dask.py, python-package/xgboost/data.py, tests/python/test_with_dask.py
* Predict with raw data.
* Inplace predict.
=> [dask] prediction with categorical data.

include/xgboost/tree_updater.h
MemorySanitizer build complains that https://github.com/dmlc/xgboost/blob/a62a3d991d8826719e13f6e7b502b9c0409bbaac/src/tree/updater_prune.cc#L27 use-of-uninitialized-value.
=> Initialize TreeUpdater ctx_ with nullptr

tests/cpp/data/test_simple_dmatrix.cc, tests/cpp/data/test_sparse_page_dmatrix.cc
Fix some tests to run in a temporary directory in case the root
directory is not writable. Note that most of tests are already
running in the temporary directory, so this PR just makes them
consistent.
=> Run tests in a temporary directory

jvm-packages/xgboost4j-tester/generate_pom.py, jvm-packages/xgboost4j/pom.xml, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/NativeLibLoader.java, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/ArchDetectionTest.java, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/OsDetectionTest.java
This PR adds support for detecting musl-based Linux operating systems, when the NativeLibLoader tries to determine the path of the XGBoost4j shared library to load.
The solution for detecting a musl-based Linux system is based on how the the [sqlite-jdbc](https://github.com/xerial/sqlite-jdbc) project does it [here](https://github.com/xerial/sqlite-jdbc/blob/ada2b147dc858ef557a995e2f4ef25f7c65fc6a7/src/main/java/org/sqlite/util/OSInfo.java#L115-L131): it lists the memory-mapped files of a Linux system and checks whether any name contains the string "musl". If that's the case, the OS is considered a musl-based Linux system.
The path of the shared library for a regular Linux-based system for x86_64 architecture is still linux/x86_64/libxgboost4j.so. For a musl-based system this would now be …
=> VM-Packages: Adding support for detecting musl-based Linux

CMakeLists.txt
Currently, `xgboost-config.cmake` is created in the `CMAKE_CURRENT_BINARY_DIR` directory, but we attempt to install it from the `CMAKE_BINARY_DIR` directory. For downstream projects attempting to consume xgboost from e.g. CPM, this prevents the install from going through successfully.
=> Correct xgboost-config directory for inclusion in other projects

include/xgboost/c_api.h, python-package/xgboost/data.py, src/c_api/c_api.cc, src/data/adapter.h, src/data/arrow-cdi.h, src/data/data.cc, src/data/simple_dmatrix.cc, tests/ci_build/conda_env/aarch64_test.yml, tests/ci_build/conda_env/cpu_test.yml, tests/ci_build/conda_env/macos_cpu_test.yml, tests/ci_build/conda_env/win64_cpu_test.yml, tests/ci_build/conda_env/win64_test.yml, tests/python/test_with_arrow.py, tests/python/testing.py
=> [FOLLOW-UP] Support for building DMatrix from Apache Arrow data format

include/xgboost/data.h, src/data/data.cc, src/data/simple_dmatrix.cc, tests/cpp/data/test_data.cc
Close https://github.com/dmlc/xgboost/issues/7729 .
Close https://github.com/dmlc/xgboost/issues/5301 .
GPU DMatrix constructor is unaffected as it doesn't support cupyx yet, all the other inputs are dense.
This might hit performance, another way to fix the issue with scipy sparse is to sort the index in Python instead of the low-level constructor, however, it won't prevent issues with other inputs.  Lastly, we can simply check for sorted data and raise an error for unsorted inputs.
=> Sort sparse page index when constructing DMatrix.

R-package/R/xgb.model.dt.tree.R, R-package/R/xgb.plot.tree.R, R-package/tests/testthat/test_helpers.R
* Fix in dataframe construction.
* Fix in plotting.
Still need tests for more sophisticated cases like mixed tree types.
Close https://github.com/dmlc/xgboost/issues/7669
=> [R] Fix parsing decision stump.

jvm-packages/dev/Dockerfile, jvm-packages/dev/build-linux.cmd, jvm-packages/dev/build-linux.sh
Since centos:6 has come to its end of life. Bump the centos version to centos:7  and meanwhile bump the devtoolset to 7 as well
=> [JVM] Update jvm dev Dockefile and shell script

python-package/xgboost/_typing.py, python-package/xgboost/core.py, python-package/xgboost/dask.py, python-package/xgboost/data.py, python-package/xgboost/sklearn.py
I attempted to add type hints to core.py. I wasn't able to eliminate all mypy errors, but I hoped to make incremental changes because adding type hints seemed very intrusive and could easily trigger conflicts. 
Related to #6496
=> Add type hints to core.py

python-package/xgboost/core.py, python-package/xgboost/data.py
Close https://github.com/dmlc/xgboost/issues/7720
Sometimes python import can generate unexpected behaviors, this happened to cuDF before.
=> Check cupy lazily.

include/xgboost/data.h
XGBOOST_PARALLEL_SORT cannot preserve the original order of
equal elements. It causes flaky failure for the cox regression
unittest. Use stable sort to make sure the result is deterministic.
Fix #7754
=> Fix cox objective test by using XGBOOST_PARALLEL_STABLE_SORT

tests/python-gpu/test_gpu_data_iterator.py, tests/python-gpu/test_gpu_linear.py, tests/python-gpu/test_gpu_prediction.py, tests/python-gpu/test_gpu_updaters.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_data_iterator.py, tests/python/test_linear.py, tests/python/test_updaters.py, tests/python/test_with_dask.py
* Skip non-increasing test with external memory when subsample is used.
* Increase bin numbers for boost from prediction test. This mitigates the effect of
non-deterministic partitioning.
Close https://github.com/dmlc/xgboost/issues/7748 .
=> Mitigate flaky tests.

doc/model.schema, python-package/xgboost/core.py, src/c_api/c_api_utils.h, src/common/quantile.cc, src/gbm/gbtree.cc, src/gbm/gbtree.h, src/gbm/gbtree_model.h, tests/cpp/gbm/test_gbtree.cc, tests/python/test_basic_models.py, tests/python/test_with_dask.py, tests/python/test_with_sklearn.py
The size of forest should be a property of model itself instead of a training
hyper-parameter.
Close https://github.com/dmlc/xgboost/issues/7721 .
=> Move `num_parallel_tree` to model parameter.

python-package/xgboost/data.py, tests/python/test_with_pandas.py
* Check for nullable type input.
cuDF uses nullable type by default, no special support is needed.
Close https://github.com/dmlc/xgboost/issues/6851 .
=> Support pandas nullable types.

Jenkinsfile-win64, tests/ci_build/conda_env/win64_test.yml
From https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/release_1.6.0/2/pipeline:
```
=========================== short test summary info ===========================
SKIPPED [1] tests\python\test_tracker.py:9: Skipping dask tests on Windows
SKIPPED [1] tests\python\test_with_dask.py:28: Skipping dask tests on Windows
SKIPPED [1] tests\python\test_demos.py:160: Test requires sh execution.
SKIPPED [1] tests\python\test_dt.py:21: Datatable is not installed. or Pandas is not installed.
SKIPPED [1] tests\python\test_with_shap.py:16: Requires shap package
========== 277 passed, 5 skipped, 144 warnings in 411.14s (0:06:51) ===========
script returned exit code -1073741819
```
To show more details, enable the faulthandler in Python (see …
=> [CI] Enable faulthandler to show details when 0xC0000005 error occurs

Jenkinsfile
The CPU Python tests are currently sharing a worker machine with a build job. They should run on different machines so that the Python tests don't get slowed down.
=> [CI] Speed up CPU test pipeline

jvm-packages/xgboost4j-spark-gpu/src/main/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuUtils.scala, jvm-packages/xgboost4j-spark-gpu/src/test/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuXGBoostClassifierSuite.scala, jvm-packages/xgboost4j-spark-gpu/src/test/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuXGBoostRegressorSuite.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala
This is kind of follow-up of https://github.com/dmlc/xgboost/pull/7692.
I hope this PR can be merged into 1.6.0 release @trivialfis
=> [jvm-packages] unify setFeaturesCol API for XGBoostRegressor

jvm-packages/xgboost4j-gpu/pom.xml, jvm-packages/xgboost4j-gpu/src/main/java/ml/dmlc/xgboost4j/gpu/java/CudfUtils.java
There is no need to add jackson for handling array inferface, since
the json of array interface is really simple.
To fix https://github.com/dmlc/xgboost/pull/7788
=> [jvm-packages] remove the dep of com.fasterxml.jackson

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/PreXGBoost.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifierSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressorSuite.scala
when set the feature columns by setFeatureCols(value: Array[String]), the evalSets will not work, since the dataset specified by evalSets has not been vectorized.
This PR add vectorizing for eval datasets.
@trivialfis this PR should be backported to 1.6.0
Sorry for that
=> [jvm-packages] fix eval sets can't work when featuresCols is using

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/RabitRobustnessSuite.scala, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/RabitTracker.java
To close https://github.com/dmlc/xgboost/issues/7700.
This PR add cusomized rabit tracker host IP and the python exec,
user needs to add tracker_conf parameter like
"tracker_conf" -> TrackerConf(0L, "python", "192.168.22.111", "/usr/bin/python3)
Please note that, both he hostIp and pythonExec are optional
=> [jvm-packages] add hostIp and python exec for rabit tracker

src/learner.cc
* Make sure the task is initialized before construction of tree updater.
This is a quick fix meant to be backported to 1.6, for a full fix we should pass the model
param into tree updater by reference instead.
=> Fix training continuation with categorical model.

demo/guide-python/cat_in_the_dat.py, demo/guide-python/continuation.py, demo/guide-python/predict_first_ntree.py, doc/tutorials/categorical.rst, python-package/xgboost/sklearn.py, tests/python/test_training_continuation.py, tests/python/test_with_dask.py, tests/python/test_with_sklearn.py
* We have removed the encoder, now prepare to remove the indicator.
=> Deprecate `use_label_encoder` in XGBClassifier.

src/learner.cc
Need a full test to see if it's possible to clear the cache.  Limiting the scope of a cache can clean up the configuration process.
=> Clear configuration cache.

doc/treemethod.rst
As we are moving forward, the gap between them is becoming more and more "irrevelant". I guess "irrevelant" should be "irrelevant"
=> "irrevelant" to "irrelevant"

jvm-packages/xgboost4j-gpu/src/test/java/ml/dmlc/xgboost4j/gpu/java/BoosterTest.java, jvm-packages/xgboost4j-spark-gpu/src/main/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuPreXGBoost.scala, jvm-packages/xgboost4j-spark-gpu/src/test/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuTestSuite.scala
Barrier mode doesn't allow coalesce operation, which should fail
all tests of xgboost4j-spark-gpu, but it doesn't. That's because
the test file is extremly small which result in only 1 PartitionedFile
and finally bypass the checking.
This PR makes at least multi-PartitionedFiles for a test file, and
then the existing tests can cover this PR
=> [jvm-package] remove the coalesce in barrier mode

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/NativeLibLoader.java
Ignore all Java exceptions when looking for Linux musl support, not just `IOException`.
The current (1.6.0) implementation of the musl support detection code catches and ignores exceptions of type `java.io.IOException`. However, in our case the detection code is throwing an instance of `java.io.UncheckedIOException`, which is not a subtype of `java.io.IOException`. As a result, XGBoost fails to load.
To resolve this issue, this PR catches and ignores all exceptions. I don't think we should or can assume that all failures of this code will be of a particular subtype of `java.io.Exception`, as our experience shows.
Here is our complete exception stack trace:
```
java.lang.ExceptionInInitializerError
at ml.dmlc.xgboost4j.java.DMatrix.(DMatrix.java:54)
at …
```
=> Ignore all Java exceptions when looking for Linux musl support

include/xgboost/base.h, src/common/column_matrix.h, src/common/hist_util.h, src/data/gradient_index.h
This PR defines a `bst_bin_t` similar to `bst_feature_t` and friends. The conversions
between signedness in function calls and returns are confusing sometimes. I hope that we
can unify them in the future. Also, this provides a better document for the parameters
like `index_base`, at least we should know from the first glance that it's referring to
something related to histogram bins.
I chose `int32_t` instead of `uint32_t` as sometimes we use -1 to indicate an invalid bin.
=> Define bin type.

tests/ci_build/entrypoint.sh
When re-starting the container, it will fail in entrypoint.sh which
will exit when adding an existing group or user
=> [CI] make container be able to re-attached

doc/tutorials/categorical.rst, include/xgboost/task.h, src/common/categorical.h, src/tree/gpu_hist/evaluate_splits.cu, src/tree/gpu_hist/evaluate_splits.cuh, src/tree/gpu_hist/evaluator.cu, src/tree/hist/evaluate_splits.h, src/tree/updater_approx.cc, src/tree/updater_gpu_hist.cu, src/tree/updater_quantile_hist.cc, tests/cpp/tree/gpu_hist/test_evaluate_splits.cu, tests/cpp/tree/hist/test_evaluate_splits.cc, tests/cpp/tree/test_gpu_hist.cu
My mistake, we are always using regression trees.
=> Always use partition based categorical splits.

dev/prepare_jvm_release.py
Automate fetching of binary artifacts from the CI pipeline. Previously, this step was performed manually, and it's easy to make mistakes.
=> [CI] Automate artifact fetch step in JVM release process

python-package/xgboost/data.py
=> Remove pyarrow workaround.

python-package/xgboost/core.py, tests/python/test_monotone_constraints.py
Close https://github.com/dmlc/xgboost/issues/7888 .
=> Fix monotone constraint with tuple input.

src/common/common.h, src/common/numeric.h, src/data/data.cc, src/data/gradient_index.cc, src/objective/adaptive.cc, tests/cpp/common/test_numeric.cc, tests/cpp/tree/test_approx.cc
* Add a module for numeric algorithms.
* Extract the partial sum.
* Add a test.
=> Extract partial sum into an independent function.

jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/spark/SparkTraining.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala
To fix https://github.com/dmlc/xgboost/issues/7837.
Please note, with https://github.com/dmlc/xgboost/pull/7836, we don't need timeoutRequestWorkers parameter and its setting API.
=> [Breaking][jvm-packages] remove timeoutRequestWorkers parameter

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/DefaultXGBoostParamsReader.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/DefaultXGBoostParamsWriter.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifierSuite.scala
To fix https://github.com/dmlc/xgboost/issues/7895.
It's a breaking issue. The trained xgboost classification model in 2.0.0 can't be loaded by the previous xgboost version, but xgboost 2.0.0 still can load the previous model.
=> [Breaking][jvm-packages] make classification model be xgboost-compatible

src/common/column_matrix.h, src/common/partition_builder.h, tests/cpp/common/test_column_matrix.cc
* Define forward iterator to hide the internal state.
=> Small cleanup to Column.

doc/model.schema, src/metric/elementwise_metric.cu, src/objective/regression_obj.cu
Follow-up to https://github.com/dmlc/xgboost/pull/7727.
This is a breaking change in the config. The impact is limited as https://github.com/dmlc/xgboost/pull/7864 disabled loading config for old models.
=> Rename misspelled config parameter for pseudo-Huber

doc/python/python_intro.rst
Users who follow the code of specify validations set ( evallist = [(dtest, 'eval'), (dtrain, 'train')] ) in the Setting Parameters section will make the train score rather than the eval score as the criteria of early stopping, therefore propose reverse the order as 、evallist = [(dtrain, 'train'), (dtest, 'eval')]、.
Closes #7878
=> Correct a mistake in Setting Parameters section

doc/jvm/xgboost4j_spark_tutorial.rst
With PR https://github.com/dmlc/xgboost/pull/7896 merged, the saved XGBoostClassificationModel is compatible with xgboost other language bindings. So submit this PR to update some outdated doc for this information
=> [doc] update the doc for jvm model compatible [skip ci]

jvm-packages/xgboost4j-spark-gpu/src/main/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuPreXGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/PreXGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/PreXGBoostProvider.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/FeatureSizeValidatingSuite.scala
Previous https://github.com/dmlc/xgboost/pull/7823 has moved the DMatrix building into Rabit context for XGBoost4j-Spark-GPU, but for some rabit and un-stable error-handling issues, this feature has not been applied to XGBoost4j-Spark. With barrier mode introduced recently, it's time to apply this feature to XGBoost4j-Spark.
=> [jvm-packages] move dmatrix building into rabit context for cpu pipeline

python-package/xgboost/_typing.py, python-package/xgboost/callback.py, python-package/xgboost/compat.py, python-package/xgboost/config.py, python-package/xgboost/core.py, python-package/xgboost/dask.py, python-package/xgboost/data.py, python-package/xgboost/plotting.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py
Following https://github.com/dmlc/xgboost/pull/7707, I plan to resolve most mypy errors across the python package if not all. 
We should probably populate compat.py with stubs for even more packages, such as cupy.
=> Add Type Hints for Python Package

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/LearningTaskParams.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/ParameterSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/PersistenceSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifierSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressorSuite.scala
This PR deletes the default value of "objective" and sets it correctly if the user does not explicitly set it.
For example, If the user does not see objective 
- XGBoostClassifier will set the objective according to the num class
- XGBoostRegressor will default the objective to "reg:squarederror"
=> [jvm-packges] set the correct objective if user doesn't explicitly set it

src/common/column_matrix.h, src/common/hist_util.h, src/data/adapter.h, tests/cpp/common/test_column_matrix.cc
* Add an adapter for SparsePage. Might seem weird, but we already have something similar in GPU code and predictor. We can unify the code further by treating SparsePage as an ordinary adapter batch.
* Implement initilaization for column matrix from adapter.
* More precise tests.
=> Use adapter to initialize column matrix.

include/xgboost/gbm.h, include/xgboost/learner.h, include/xgboost/predictor.h, src/c_api/c_api.cc, src/c_api/c_api.cu, src/data/proxy_dmatrix.h, src/gbm/gbtree.cc, src/gbm/gbtree.h, src/learner.cc, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, tests/cpp/data/test_proxy_dmatrix.cu, tests/cpp/gbm/test_gbtree.cc, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/predictor/test_predictor.cc, tests/cpp/predictor/test_predictor.h
Pass the `X` as part of Proxy DMatrix instead of an independent `dmlc::any`.
I'm preparing to add optimal initialization, when it's ready we need to move `InitOutPrediction` from predictor to objective.
=> Simplify inplace-predict.

src/tree/driver.h
```
warning: comparison of integer expressions of different signedness: ‘std::size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
63 |     if (param_.max_leaves > 0 && num_leaves_ >= param_.max_leaves) return false;
```
=> Fix type conversion warning.

src/tree/split_evaluator.h, src/tree/updater_gpu_hist.cu
This change results in significant performance improvements when the tree is sparse, i.e. the user specifies some large max depth, but final tree size is significantly smaller than the maximum possible size.
Performance is otherwise unchanged.
Fraud dataset at max_depth=22 with gpu_hist:
before - 18.4165s
after - 1.7270s
=> Do not initialise data structures to maximum possible tree size.

python-package/xgboost/__init__.py, python-package/xgboost/core.py
Close https://github.com/dmlc/xgboost/issues/7926 .
=> Verify shared object version at load.

src/common/hist_util.h, src/data/gradient_index.cc, src/data/gradient_index.h, tests/cpp/common/test_column_matrix.cc, tests/cpp/data/test_gradient_index.cc, tests/cpp/tree/hist/test_histogram.cc
* Pass sparse page as adapter, which prepares for quantile dmatrix.
* Remove old external memory code like `rbegin` and extra `Init` function.
* Simplify type dispatch.
=> Refactor for GHistIndex.

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/NativeLibLoader.java, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/LibraryPathProviderTest.java, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/OsDetectionTest.java
This PR removes auto-detection of MUSL-based Linux systems in favor of system properties the user can set to configure a specific path for a native library.
At the moment, there's only a single library with the name `xgboost4j` that we need. A user who wants to configure a specific path, has to set the system property `xgboostruntime.native.xgboost4j`. If this system property is present, its value is used as a library path inside the JAR.
A user who runs xgboost4j on a MUSL-based Linux system, will get an additional error message `Alternatively, if your Linux OS is musl-based, you should set the path for the native library xgboost4j via the system property xgboostruntime.native.xgboost4j`.
Resolves #7915
=> VM-Packages: Auto-detection of MUSL is replaced by system properties

include/xgboost/tree_model.h, src/tree/hist/evaluate_splits.h, src/tree/split_evaluator.h, src/tree/tree_model.cc, tests/python/test_updaters.py
Use the bitset inside the split entry for both OHE split and partition-based split.
=> Unify the cat split storage for CPU.

tests/ci_build/build_python_wheels.sh
Currently, Mac CD pipelines are failing with error
```
CondaHTTPError: HTTP 403 FORBIDDEN for url <https://anaconda.org/conda-forge/llvm-openmp/11.1.0/download/osx-64/llvm-openmp-11.1.0-hda6cdc1_1.tar.bz2>
```
Curiously, I was able to manually download from the same URL. It could be that GitHub Actions workers are being throttled by Conda-forge.
To fix this error, host the same file on our own private mirror (an S3 bucket).
=> [CI] Use private mirror to host llvm-openmp tarballs

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/BoosterParams.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/InferenceParams.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/LearningTaskParams.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/RabitParams.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/XGBoostEstimatorCommon.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/ParameterSuite.scala
This PR is to remove the most booster default parameters, which will be defaulted by xgboost native.
=> [jvm-packages] remove default parameters

python-package/xgboost/libpath.py, src/common/host_device_vector.cc
Hi, I'm from the [Pyodide project](https://github.com/pyodide/pyodide) and I would like to add some build patches to support the WebAssembly(Emscripten) build of XGboost.
These patches are applied in https://github.com/pyodide/pyodide/pull/2537.
=> Add minimal emscripten build support

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/utils/XGBoostReadWrite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/PerTest.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifierSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressorSuite.scala, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java, jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/Booster.scala
This PR adds a format option which allows the booster to be dumped into json or ubj.
For now, we still use "deprecated" format as the default when dumping the booster model, but we're able to choose the different booster formats like json, ubj to be dumped.
eg,
``` scala
model.write.option("format", "json").save(modelJsonPath)
```
or 
``` scala
model.write.option("format", "ubj").save(modelJsonPath)
```
=> [jvm-packages] add format option when saving a model

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/RabitTracker.java
Generally, in order to avoid too many spark logs, we usually do
`val sc = new SparkContext(conf)
sc.setLogLevel("WARN")`
Using XGBoostClassifier by Spark Application, there are nothing error logs when lacking python3 in cluster environment, 
and we can see the following log when set log info level.
I think it is more useful to find error when loging stderr using error level.
> 22/05/23 15:11:02 WARN XGBoostSpark: train_test_ratio is deprecated since XGBoost 0.82, we recommend to explicitly pass a training and multiple evaluation datasets by passing 'eval_sets' and 'eval_set_names'
22/05/23 15:11:03 INFO RabitTracker$TrackerProcessLogger:   File "/mnt/sata05/hadoop/yarn/local/usercache/ubd_obx_test/appcache/application_1653287501496_0002/container_e29_1653287501496_0002_01_000001/tmp/tracke …
=> set log level as ERROR when trackerProcess has some stderr output

plugin/federated/federated_client.h, plugin/federated/federated_server.cc
While testing federated learning, found it sometimes throws an error for the receive message size.
=> Increase gRPC max receive message size for federated learning

demo/nvflare/README.md, demo/nvflare/config/config_fed_client.json, demo/nvflare/custom/trainer.py, plugin/federated/README.md
=> Support GPU training in the NVFlare demo

jvm-packages/xgboost4j-gpu/src/test/java/ml/dmlc/xgboost4j/gpu/java/DMatrixTest.java, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/DMatrix.java, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoostJNI.java, jvm-packages/xgboost4j/src/native/xgboost4j.cpp, jvm-packages/xgboost4j/src/native/xgboost4j.h, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/DMatrixTest.java
This PR adds jni APIs for XGDMatrixGetStrFeatureInfo and XGDMatrixSetStrFeatureInfo to set/get feature information including feature_name and feature_type which will be typically used in categorical feature supporting. I will file a followup to support categorical feature in jvm-packages.
=> [jvm-packages] add jni for setting feature name and type

doc/parameter.rst, doc/tutorials/categorical.rst, src/common/categorical.h, src/tree/hist/evaluate_splits.h, src/tree/param.h, tests/python-gpu/test_gpu_updaters.py, tests/python/test_updaters.py, tests/python/testing.py
* Implement `max_cat_threshold` for CPU evaluator.
* Add tests with hypothesis.
Close https://github.com/dmlc/xgboost/issues/7856 .
=> Implement `max_cat_threshold` for CPU.

src/common/hist_util.cc, src/common/hist_util.h, src/common/quantile.cc, src/common/quantile.h, src/data/gradient_index.h, tests/cpp/common/test_quantile.cc
Same as https://github.com/dmlc/xgboost/pull/7960 . Started a new PR to avoid the docker cache on Jenkins.
Part of the effort to implement https://github.com/dmlc/xgboost/issues/7890 .
=> Implement sketching with adapter.

jvm-packages/xgboost4j-spark-gpu/src/main/scala/ml/dmlc/xgboost4j/scala/rapids/spark/GpuPreXGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/PreXGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala
the API XGBoosterSetParam is not thread-safe. During the phase of transforming,
XGBoost runs several transforming tasks at a time, and each of them will set
the "gpu_id" and "predictor" parameters, so if several tasks (multi-threads)
all XGBoosterSetParam simultaneously, it may cause the memory to be corrupted
and cause SIGSEGV.
This PR first gets the booster from broadcast and set to the correct gpu_id
and predictor, and then all transforming tasks will use the same booster to
do the transforming.
To fix https://github.com/dmlc/xgboost/issues/8016
=> [jvm-packages] fix executor crashing issue when transforming on xgboost4j-spark-gpu

plugin/federated/engine_federated.cc
The recent change to rabit broke the federated learning plugin. We should try to get this built in the CI soon.
@trivialfis
=> fix federated learning plugin

python-package/xgboost/plotting.py
Fix 4 "graphiz" instead of "graphviz".
=> Fix multiple typos

demo/nvflare/README.md
=> Update nvflare demo for release 2.1.2

src/metric/auc.cc, src/metric/metric.cc
So that its registration logic can be run, and thus 'auc' metric function can be found.
discuss.xgboost.ai discussion: [Should src/metric/auc.{h,cc,cu} be forced to be linked statically?](https://discuss.xgboost.ai/t/should-src-metric-auc-h-cc-cu-be-forced-to-be-linked-statically/2830)
=> Force auc.cc to be statically linked

python-package/xgboost/sklearn.py
We are adding more optional dependencies (dask, pyspark), this unifies the error being raised when a dependency is not met.
=> [py-skl] Raise import error if sklearn is not installed.

python-package/xgboost/dask.py
Dask is adding type hints to its codebase and as the result, checks in XGBoost can be
performed more rigorously.
- Remove compatibility with old dask version where multi lock was missing.
- Restrict input of `X` to be non-series.
- Adopt latest definition of `Delayed`.
- Avoid passing optional `host_ip`.
- Avoid deprecated `worker.nthreads`.
=> Fix mypy error with the latest dask.

src/tree/gpu_hist/evaluate_splits.cuh, src/tree/gpu_hist/evaluator.cu, src/tree/split_evaluator.h
Removing spans in favour of raw pointers decreases register pressure in the GPU kernel significantly.
Use of double/single precision in gain calculations is inconsistent. Prefer single precision.
=> Use single precision in gain calculation, use pointers instead of span.

Jenkinsfile, Jenkinsfile-win64
Follow-up to #7662
Always use `awscli` when uploading to S3; the built-in command `s3Upload` in Jenkins sometimes fails to get the correct AWS credentials.
=> [CI] Fix S3 uploads

amalgamation/xgboost-all0.cc, src/common/column_matrix.cc, src/common/column_matrix.h, src/data/gradient_index.h
This PR splits the column matrix initialization into 2 steps, the first one initializes
the storage while the second one does the transpose. By doing so, we can reuse the code
for Quantile DMatrix.
Extracted from https://github.com/dmlc/xgboost/pull/8050 .
=> Split up column matrix initialization.

.github/workflows/main.yml, .github/workflows/python_wheels.yml, .github/workflows/r_tests.yml, python-package/setup.py, tests/ci_build/Dockerfile.cpu, tests/ci_build/build_python_wheels.sh, tests/ci_build/conda_env/aarch64_test.yml, tests/ci_build/conda_env/cpu_test.yml, tests/ci_build/conda_env/macos_cpu_test.yml, tests/python/test_with_modin.py
Following the latest numpy and modin. This helps us solve dependencies for tests.
Additional changes:
- Use mamba for CPU test on Jenkins.
- Cleanup CPU test dependencies.
=> Update Python requirement to >=3.8.

tests/python-gpu/test_gpu_updaters.py
The flakiness is caused by the global random engine, which will take some time to fix.
=> Mitigate flaky GPU test.

python-package/xgboost/spark/core.py, python-package/xgboost/spark/estimator.py
This PR is to fix raw_prediction_col parameter instead of raw_prediction_ol and clean up some comments
=> [PySpark] fix raw_prediction_col parameter and minor cleanup

python-package/xgboost/spark/core.py, python-package/xgboost/spark/utils.py
This PR is to support gpu training (use_gpu=True) on Spark local mode.
Please note that, 
1. Spark local mode does not support GPU configuration, so it will fail if the user adds related GPU configurations.
2. For now, we only support num_workers=1 when running on GPU on Spark local mode.
This feature is needed since it's really convenient for local debugging.
=> [PySpark] add gpu support for spark local mode

python-package/xgboost/data.py
In some cases the "import cudf" can raise a RuntimeError or other errors while loading. Doing a lazy check is safer for these cases. Similiar to #7752.
Example of RuntimeError that could be generated by import:
```python
File "cuda/_cuda/ccuda.pyx", line 3671, in cuda._cuda.ccuda._cuInit
File "cuda/_cuda/ccuda.pyx", line 435, in cuda._cuda.ccuda.cuPythonInit
RuntimeError: Failed to dlopen libcuda.so
```
=> Check cuDF lazily

doc/conf.py, doc/python/python_api.rst, doc/requirements.txt, python-package/xgboost/spark/estimator.py
=> [doc] Integrate pyspark module into sphinx doc [skip ci]

include/xgboost/data.h, src/common/hist_util.cc, src/common/quantile.cc, src/common/quantile.h, src/data/adapter.h, src/data/device_adapter.cuh, src/data/proxy_dmatrix.cu, src/data/proxy_dmatrix.h, tests/cpp/common/test_quantile.cc
- Use `bst_bin_t` in batch param constructor.
- Use `StringView` to avoid `std::string` when appropriate.
- Avoid using `MetaInfo` in quantile constructor to limit the scope of parameter.
Extracted from https://github.com/dmlc/xgboost/pull/8050
=> Small cleanups to various data types.

Jenkinsfile, Jenkinsfile-win64
Clear the workspace after performing the budget check in the CI. This ensures that clutters don't accumulate in the `job_initializer` node.
=> [CI] Clear workspace after budget check

python-package/xgboost/spark/core.py, tests/python/test_spark/test_spark_local.py
[RAPIDS Accelerator](https://nvidia.github.io/spark-rapids/) is a Spark plugin that leverages the GPUs to accelerate the spark SQL and dataframe API.  But not all types can be supported by RAPIDS Accelerator. For example, It has not supported the `BINARY type` when doing mapInPandas.
``` console
22/07/17 09:06:41 WARN GpuOverrides: 
!Exec <MapInPandasExec> cannot run even partially on the GPU because unsupported data types in output: BinaryType [booster_bytes#31]; not all expressions can be replaced
!Expression <AttributeReference> booster_bytes#31 cannot run on GPU because expression AttributeReference booster_bytes#31 produces an unsupported type BinaryType
!Expression <PythonUDF> _train_booster(values#15, label#14) blocks running on GPU because expression PythonUDF …
```
=> [PySpark] change the returning model type to string from binary

demo/guide-python/spark_estimator_examples.py, doc/tutorials/spark_estimator.rst, python-package/xgboost/spark/core.py, python-package/xgboost/spark/estimator.py
Xgboost pyspark integration: User guide doc and tutorials
=> Xgboost pyspark integration: User guide doc and tutorials

.github/workflows/main.yml, .github/workflows/python_tests.yml, Makefile, python-package/xgboost/dask.py, python-package/xgboost/spark/core.py, python-package/xgboost/spark/data.py, python-package/xgboost/spark/estimator.py, python-package/xgboost/spark/model.py, python-package/xgboost/spark/utils.py, tests/ci_build/conda_env/python_lint.yml, tests/ci_build/lint_python.py, tests/ci_build/test_r_package.py, tests/ci_build/test_utils.py
- Require black and isort for spark and dask module.
These files are relatively new and are more conform to the black formatter. We will
convert the rest of the library as we move forward.
Other libraries including dask/distributed and optuna use the same formatting style and
have a more strict standard. The black formatter is indeed quite nice, automating it can
help us unify the code style.
- Gather Python checks into a single script.
=> [Python] Require black and isort for new Python files.

src/tree/param.h
Fix https://github.com/dmlc/xgboost/issues/8095
=> Limit `max_depth` to 30 for GPU.

tests/cpp/data/test_iterative_dmatrix.cu, tests/cpp/helpers.cc, tests/cpp/helpers.cu, tests/cpp/helpers.h
- Avoid duplicated definitions of data shape.
- Explicitly define numpy iterator for CPU data.
Extracted from https://github.com/dmlc/xgboost/pull/8050 .
=> Cleanup data generator.

src/common/column_matrix.h
When building XGBoost with /std:c++latest on MSVC, we got the following errors, now fix it.
`F:\dmlc\xgboost\src\common\column_matrix.h(288,29): error C2440: 'initializing': cannot convert from 'ColumnBinT *' to '_T17 *' [F:\dmlc\xgboost\build_amd64\src\objxgboost.vcxproj]`
`F:\dmlc\xgboost\src\common\column_matrix.h(294,29): error C2440: 'initializing': cannot convert from 'ColumnBinT *' to '_T17 *' [F:\dmlc\xgboost\build_amd64\src\objxgboost.vcxproj]`
`F:\dmlc\xgboost\src\data\../common/column_matrix.h(288,29): error C2440: 'initializing': cannot convert from 'ColumnBinT *' to '_T17 *' [F:\dmlc\xgboost\build_amd64\src\objxgboost.vcxproj]`
`F:\dmlc\xgboost\src\data\../common/column_matrix.h(294,29): error C2440: 'initializing': cannot convert from 'ColumnBinT *' to '_T17 *' …
=> [MSVC][std:c++latest] Fix compiler error

src/common/partition_builder.h
There is a small typo in src/common/partition_builder.h.
Should read `canonical` rather than `cannonical`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, cannonical -> canonical

src/data/gradient_index.cc, src/data/gradient_index.h, src/data/gradient_index_page_source.cc, tests/cpp/data/test_gradient_index.cc, tests/cpp/predictor/test_predictor.cc, tests/cpp/tree/hist/test_histogram.cc, tests/cpp/tree/test_quantile_hist.cc
- Extract `PushBatchImpl` for reusing code. This is the common function between pushing a sparse page and a adapter, the former doesn't need to count row size and it known to be the single page.
- Implement `GetFvalue` for prediction.
Extracted from: https://github.com/dmlc/xgboost/pull/8050 .
=> Prepare gradient index for Quantile DMatrix.

src/common/random.cc, tests/cpp/common/test_random.cc
The issue was raised in the discussion forum: https://discuss.xgboost.ai/t/colsample-by-params-cannot-be-used-together-with-feature-weights/2841
=> Fix feature weights with multiple column sampling.

python-package/xgboost/compat.py, python-package/xgboost/dask.py, python-package/xgboost/sklearn.py, python-package/xgboost/spark/core.py, python-package/xgboost/spark/data.py, tests/ci_build/lint_python.py, tests/python-gpu/test_spark_with_gpu/test_data.py, tests/python/test_spark/test_data.py, tests/python/test_spark/test_spark_local.py
This PR does some cleanups for the data processing precedures for the newly gained pyspark interface.
- Use numpy stack for handling list of arrays.
- Reuse concat function from dask.
- Remove unused code.
- Use iterator for prediction to avoid initializing xgboost model (pickle is not cheap).
To-dos:
I'm not entirely sure how to work with sparse data since it hasn't been supported yet in current codebase.
@WeichenXu123
=> [pyspark] Cleanup data processing.

amalgamation/xgboost-all0.cc, include/xgboost/data.h, src/c_api/c_api.cc, src/data/data.cc, src/data/iterative_dmatrix.cc, src/data/iterative_dmatrix.cu, src/data/iterative_dmatrix.h, src/data/proxy_dmatrix.cc, src/data/proxy_dmatrix.cu, src/data/proxy_dmatrix.h, src/data/simple_dmatrix.h, src/data/sparse_page_dmatrix.h, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, tests/cpp/data/test_iterative_dmatrix.cc, tests/cpp/data/test_iterative_dmatrix.cu, tests/cpp/data/test_iterative_dmatrix.h, tests/cpp/helpers.cc, tests/cpp/helpers.cu, tests/cpp/predictor/test_cpu_predictor.cc
Extracted from https://github.com/dmlc/xgboost/pull/8050 .
- Implement IterativeDMatrix for CPU.
- Add reference DMatrix (usually the training DMatrix), which allows evaluation DMatrix to reuse the quantile cuts.
=> Implement iterative DMatrix for CPU.

doc/install.rst
https://discuss.xgboost.ai/t/xgboost-gpu-for-windows-is-not-available-on-conda-anymore/2868?u=hcho3
=> [Doc] Indicate lack of py-xgboost-gpu on Windows

doc/python/python_api.rst, include/xgboost/c_api.h, python-package/xgboost/__init__.py, python-package/xgboost/core.py, python-package/xgboost/dask.py, python-package/xgboost/data.py, src/c_api/c_api.cc, tests/python-gpu/test_device_quantile_dmatrix.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_data_iterator.py, tests/python/test_quantile_dmatrix.py, tests/python/test_with_dask.py, tests/python/testing.py, tests/python/with_omp_limit.py
https://github.com/dmlc/xgboost/pull/8050 reopened for cleared docker cache.
=>  Quantile DMatrix for CPU.

demo/guide-python/spark_estimator_examples.py
The example was not using `xgb_regressor2` or `xgb_classifier2` which actually has `validation_indicator_col` property defined.
=> In PySpark Estimator example use the model with validation_indicator

tests/ci_build/rename_whl.py
Close https://github.com/dmlc/xgboost/issues/8135 .
Thanks to the upgrade from the PyPI maintainer, the limit for XGBoost is now 300MB. But we still need to think of a more future-proofed way to reduce the overall binary size.
=> Update PyPi wheel size limit.

doc/get_started.rst
This PR aims to resolve issue #8146. 
The current Python [getting started example](https://xgboost.readthedocs.io/en/stable/get_started.html) requires the user to manually set the local file path to the Agaricus data set in libsvm format before being able to run the example code. 
This PR leverages `sklearn` to load the data set. Hence, as long as the user has `sklearn` installed, after a `pip install xgboost`, the user should be able to run the getting started example as is (reducing friction, especially for new users). 
- The well-known Iris data set is used, since the Agaricus data set is not available in `sklearn.datasets`. 
- The `xgboost.XGBClassifier` class is used here rather than the `xgboost.fit` function to train the model as the latter would require an extra step of converting …
=> Simplify Python getting started example

src/common/hist_util.cuh, src/data/device_adapter.cuh, src/data/ellpack_page.cu, src/data/ellpack_page.cuh, src/data/gradient_index.cc, src/data/iterative_dmatrix.cc, src/data/iterative_dmatrix.cu, src/data/iterative_dmatrix.h, tests/ci_build/lint_python.py, tests/cpp/data/test_ellpack_page.cu, tests/python-gpu/test_device_quantile_dmatrix.py
- Copy `GHistIndexMatrix` to `Ellpack` when needed.
=> Support CPU input for device `QuantileDMatrix`.

doc/tutorials/custom_metric_obj.rst
This PR corrects various grammar typos in `./doc/tutorials/custom_metric_obj.rst`. 
Summary of edits:
1) inserted "the" and fix spacing in "...implementing the Squared Log Error (SLE)"
2) Changed "needs not" -> "need not"
3) Changed "as result" -> "as the result" and "of metric" -> "of the metric"
4) inserted "a" in "When a custom objective is provided"
5) inserted "the" in "However, when the custom objective is..."
6) inserted "the" in "The following example provides..."
=> Edit grammar in custom metric tutorial

doc/tutorials/model.rst
Added "of" to "objective functions is that they consist of two parts" in line 32 of ./doc/tutorials/model.rst
=> Grammar Fix in Introduction to Boosted Trees

python-package/setup.py
We prefer to use "make" for build_tool on IBM i system. Please help to review and kindly merge. thanks.
=> ninja on i do not support non-ELF format

python-package/xgboost/spark/core.py, python-package/xgboost/spark/data.py, python-package/xgboost/spark/params.py, tests/ci_build/conda_env/cpu_test.yml, tests/python/test_spark/test_data.py, tests/python/test_spark/test_spark_local.py, tests/python/test_spark/test_spark_local_cluster.py, tests/python/test_spark/utils.py
Closes https://github.com/dmlc/xgboost/issues/8108
Make Xgboost estimator support using sparse matrix as optimization.
=> [pyspark] Make Xgboost estimator support using sparse matrix as optimization

src/c_api/c_api.cc, src/data/data.cc, tests/python/test_with_dask.py
- Try to load DMatrix binary before trying to parse text input.
- Remove some unmaintained code.
=> [backport] Fix loading DMatrix binary in distributed env. (#8149)

plugin/federated/engine_federated.cc, plugin/federated/federated_client.h, plugin/federated/federated_server.cc, plugin/federated/federated_server.h, python-package/xgboost/federated.py, src/c_api/c_api.cc, tests/distributed/test_federated.py
For NVFLARE integration, we plan to run a local gRPC proxy, which doesn't really need SSL.
@trivialfis
=> Allow insecure gRPC connections for federated learning

CMakeLists.txt, Jenkinsfile, tests/ci_build/Dockerfile.gpu_build_centos7, tests/ci_build/prune_libnccl.sh
This further reduces the size of the compiled binary.
=> [CI] Prune unused archs from libnccl

python-package/xgboost/spark/estimator.py
Signed-off-by: Weichen Xu <weichen.xu@databricks.com>
Fixed xgboost.spark python doc.
Fixed some typos and example code.
=> [spark] Fixing xgboost.spark python doc

python-package/xgboost/dask.py
CI is complaining about pylint error:
```
/home/runner/work/xgboost/xgboost/python-package/xgboost/dask.py:1687: convention (C0201, consider-iterating-dictionary, DaskScikitLearnBase.__getstate__) Consider iterating the dictionary directly instead of calling .keys()
```
@trivialfis
=> Fix dask.py lint error

python-package/setup.py, python-package/xgboost/spark/core.py, python-package/xgboost/spark/params.py
@WeichenXu123 @trivialfis Add a small PR to cleanup some comments and add some log printing
Thx
=> [pyspark] Cleanup the comments

include/xgboost/json.h
Deleted virtual functions are not supported in earlier versions of MacOS (<10.15). See https://github.com/JuliaPackaging/Yggdrasil/pull/5430.
=> Drop use of deleted virtual function to support older MacOS

tests/python-gpu/test_gpu_data_iterator.py, tests/python/test_data_iterator.py, tests/python/testing.py
- Reduce the number of batches.
- Verify labels.
Close https://github.com/dmlc/xgboost/issues/8161.
=> Mitigate flaky data iter test.

python-package/xgboost/spark/core.py
Signed-off-by: Weichen Xu <weichen.xu@databricks.com>
Fix xgboost spark estimator dataset repartition issues
1. Fix issue of repartition generating empty partitions, via repartition on `rand(1)` column.
2. For num_worker=1, if setting force_repartition=True, does not raise error but still repartition to 1 partition.
3. When `validationIndicatorCol` set, always trigger repartition.
Closes https://github.com/dmlc/xgboost/issues/8221
=> [pyspark] Fix xgboost spark estimator dataset repartition issues

.github/workflows/scorecards.yml, README.md
Closes #8255 
As discussed in the #8255 here are the changes to enable the [Scorecard GitHub Action](https://github.com/ossf/scorecard-action) and the [badge](https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/) to the repo.
The changes are:
- A configuration file in .github/workflow to enable the action
- the badge in the README file
Thanks for considering it and any doubts or concers I'll be happy to help.
=> Enable OpenSSF Scorecard Github Action

python-package/xgboost/spark/core.py, tests/python/test_spark/test_spark_local.py
Signed-off-by: Weichen Xu <weichen.xu@databricks.com>
Add validation for param 'early_stopping_rounds' and 'validation_indicator_col'
=> [spark] Add validation for param 'early_stopping_rounds' and 'validation_indicator_col'

.github/workflows/jvm_tests.yml, .github/workflows/main.yml, .github/workflows/python_tests.yml, .github/workflows/python_wheels.yml, .github/workflows/r_nold.yml, .github/workflows/r_tests.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening
