dmlc/xgboost

.travis.yml, tests/ci_build/Dockerfile.aarch64, tests/ci_build/conda_env/aarch64_test.yml, tests/ci_build/conda_env/cpu_test.yml, tests/ci_build/conda_env/macos_cpu_test.yml, tests/travis/run_test.sh, tests/travis/setup.sh
=> [CI] Build a Python wheel for aarch64 platform

CMakeLists.txt, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/FeatureSizeValidatingSuite.scala, jvm-packages/xgboost4j/src/native/xgboost4j.cpp, python-package/xgboost/rabit.py, rabit/CMakeLists.txt, rabit/include/rabit/c_api.h, rabit/include/rabit/internal/socket.h, rabit/include/rabit/internal/utils.h, rabit/src/allreduce_base.cc, rabit/src/c_api.cc, src/CMakeLists.txt, src/c_api/c_api_error.h
* Now it's built as part of libxgboost.
* Set correct C API error in RABIT initialization and finalization.
=> Remove RABIT CMake targets.

R-package/tests/testthat/test_callbacks.R, include/xgboost/generic_parameters.h, tests/cpp/test_serialization.cc, tests/python/test_cli.py
=> Revert "Disable JSON full serialization for now."

doc/conf.py, doc/tutorials/c_api_tutorial.rst, doc/tutorials/index.rst
Respected, I have created a small tutorial for using C API.
=> Create a tutorial for using the C API in a C/C++ application #6174

src/gbm/gbtree.cc
Change from warning to info.  These warnings show up for every iteration and I don't think they are that important.
=> Reduce warning.

include/xgboost/learner.h, src/c_api/c_api.cc, src/c_api/c_api.cu, src/gbm/gbtree.h, src/learner.cc, tests/python/test_predict.py
* Add back the interval in call.
* Make the interval non-optional.
=> Fix inplace prediction interval.

tests/python-gpu/test_gpu_updaters.py, tests/python/test_with_dask.py
Tracking issue: #6298
https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/master/553/pipeline
https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-6286/2/pipeline
=> Mark flaky tests as XFAIL

doc/parameter.rst, python-package/xgboost/sklearn.py
Ended up not having enough time to do the refactoring for `approx` and `local`.   So document the limitation for now.
=> Document tree method for feature weights.

cmake/modules/FindNccl.cmake
=> Added USE_NCCL_LIB_PATH option to enable user to set NCCL_LIBRARY during build

python-package/xgboost/compat.py, python-package/xgboost/dask.py
Close https://github.com/dmlc/xgboost/issues/6282 .
=> Lazy import dask libraries.

doc/jvm/xgboost4j_spark_tutorial.rst
add example to handle missing value other than 0 under Dealing with missing values section
=> [jvm-packages] add example to handle missing value other than 0

tests/python/test_with_dask.py
Close https://github.com/dmlc/xgboost/issues/6314 .
=> Fix flaky data initialization test.

README.md
Added missed badge for github actions.
=> added a new github actions badge

include/xgboost/data.h, include/xgboost/predictor.h, src/c_api/c_api.cc, src/common/hist_util.cc, src/common/version.cc, src/common/version.h, src/data/sparse_page_dmatrix.h, src/gbm/gblinear_model.h, src/learner.cc, src/metric/metric.cc, src/metric/rank_metric.cc, src/predictor/predictor.cc, src/tree/split_evaluator.h, src/tree/tree_model.cc, src/tree/updater_colmaker.cc, src/tree/updater_histmaker.cc
=> Clean up warnings

tests/python-gpu/test_gpu_prediction.py
Close https://github.com/dmlc/xgboost/issues/6074 .
=> Enable shap sparse test.

python-package/xgboost/callback.py, python-package/xgboost/training.py, tests/python-gpu/load_pickle.py, tests/python-gpu/test_gpu_pickling.py, tests/python/test_basic.py, tests/python/test_callback.py, tests/python/test_with_sklearn.py, tests/python/testing.py
Close https://github.com/dmlc/xgboost/issues/6334
=> Add period to evaluation monitor.

.github/workflows/main.yml
Close https://github.com/dmlc/xgboost/issues/6068 .
=> Run R check as cran on action. [skip ci]

Makefile, R-package/R/xgb.ggplot.R, R-package/R/xgb.plot.shap.R, R-package/man/xgb.shap.data.Rd, rabit/include/rabit/internal/utils.h, rabit/src/allreduce_base.cc, rabit/src/allreduce_base.h
* Remove printf in rabit.
* Run `devtools::document` and adjust some doc for linter.
=> [R] Fix warnings from R check --as-cran

src/tree/tree_model.cc, tests/cpp/tree/test_tree_model.cc
Close https://github.com/dmlc/xgboost/issues/6278 .
=> Fix plotting.

tests/python-gpu/test_gpu_updaters.py
https://github.com/dmlc/xgboost/issues/6307  Disable it for now.
=> Expect gpu external memory to fail.

doc/cli.rst
=> Fix broken link in CLI doc

R-package/R/utils.R, R-package/tests/testthat/test_helpers.R
Closes #5829
cc @benmarchi @jameslamb @mayer79
=> [R] Do not convert continuous labels to factors

jvm-packages/xgboost4j-spark/src/main/scala/org/apache/spark/SparkParallelismTracker.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/PerTest.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRabitRegressionSuite.scala
problem described https://github.com/dmlc/xgboost/pull/6360 , credits to @wbo4958 for the investigation
=> [jvm-packages] fix potential unit test suites aborted issue

tests/cpp/data/test_sparse_page_dmatrix.cc
https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/PR-6416/1/
=> Fix flaky sparse page dmatrix test.

python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
Address comment in https://github.com/dmlc/xgboost/issues/6405#issuecomment-730883983 .
=> [SKL] Propagate parameters to booster during set_params.

rabit/src/engine_mpi.cc, src/CMakeLists.txt, tests/distributed/runtests-mpi.sh, tests/distributed/test_issue3402.py
* Fix build.
* Fix use after finalization.
* Added a small test.  But haven't ported it to action yet.
Close https://github.com/dmlc/xgboost/issues/6377 .
=> Fix MPI build.

demo/rank/mq2008.conf, src/cli_main.cc, tests/python/test_cli.py
=> Fix CLI ranking demo.

demo/CLI/binary_classification/README.md, demo/CLI/regression/README.md, demo/README.md, doc/tutorials/model.rst
Signed-off-by: Hao Ziyu <haoziyu@qiyi.com>
=> Fix broken links.

doc/parameter.rst
=> [Doc] Document that AUC and AUCPR are for binary classification/ranking

Jenkinsfile, tests/ci_build/Dockerfile.auditwheel_x86_64
Port #6482 to the `master` branch.
=> [CI] Use manylinux2010_x86_64 container to vendor libgomp

python-package/xgboost/core.py, python-package/xgboost/training.py, tests/python/test_basic.py
Close https://github.com/dmlc/xgboost/issues/6442 .
=> Move metric configuration into booster.

python-package/xgboost/core.py, tests/python/test_dmatrix.py
* Added type hints.
Close https://github.com/dmlc/xgboost/issues/6452 .
=> Fix DMatrix feature names/types IO.

.github/workflows/main.yml, .github/workflows/r_tests.yml, python-package/setup.cfg
Related https://github.com/dmlc/xgboost/issues/6496 .
- Split up the main.yml to isolate R tests.
- mypy is added to CI, but passing is not required for now.
=> [CI] Split up main.yml, add mypy.

python-package/xgboost/compat.py, python-package/xgboost/dask.py
=> Lazy import cuDF and Dask

demo/guide-python/feature_weights.py
"featue_map" typo changed to  "feature_map"
=> "featue_map" typo changed to  "feature_map"

doc/index.rst, doc/parameter.rst, doc/treemethod.rst
@dmlc/xgboost-committer Please help reviewing and correcting any mistake.
=> Document various tree methods.

python-package/xgboost/training.py, tests/python/test_training_continuation.py
Fix https://github.com/dmlc/xgboost/pull/6567#issuecomment-753519668 .
@hcho3 Although the bug is quite old, but I consider it to be serious.  Do you think it's worth of a new patch rel?
=> Fix `best_ntree_limit` for multi-class.

python-package/xgboost/dask.py, python-package/xgboost/sklearn.py, tests/python/test_with_dask.py, tests/python/test_with_sklearn.py, tests/python/testing.py
* For sklearn:
- Handles user defined objective function.
- Handles `softmax`.
* For dask:
- Use the implementation from sklearn, the previous implementation doesn't perform any extra handling.
=> [dask, sklearn] Fix predict proba.

python-package/xgboost/training.py, tests/python/test_with_sklearn.py
Close https://github.com/dmlc/xgboost/issues/3789
Close https://github.com/dmlc/xgboost/issues/5116
=> Fix `best_ntree_limit` for dart and gblinear.

python-package/xgboost/dask.py, python-package/xgboost/sklearn.py, tests/ci_build/conda_env/win64_test.yml, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_with_dask.py
New Scikit-Learn version uses keyword argument, and `X` is the predefined
keyword.
* Use pip to install latest Python graphviz on Windows CI.
=> [Backport] Rename `data` to `X` in `predict_proba`. (#6555)

python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
* Remove duplicated code, which fixes typo `evals_result` -> `evals_result_`.
=> Fix evaluation result for XGBRanker.

src/gbm/gblinear_model.cc
Porting it to master branch from 1.3.
=> Remove type check for solaris.

dev/release-pypi.py, doc/contrib/release.rst, python-package/setup.py
* Fix `long_description_content_type` warning.
=> Add helper script and doc for releasing pip package.

tests/python/test_with_dask.py
A small part extracted from https://github.com/dmlc/xgboost/pull/6591 .
Close #6300
=> [dask] Rework base margin test.

.github/workflows/main.yml, .travis.yml
* Move sdist tests to github action
* Add windows test.
=> Move x86 linux and osx sdist test to action.

include/xgboost/json.h, src/c_api/c_api.cc, src/common/json.cc, tests/cpp/common/test_json.cc
Small part extracted from https://github.com/dmlc/xgboost/pull/6638 .
=> Improve string view to reduce string allocation.

python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
Close https://github.com/dmlc/xgboost/issues/6639
=> Fix divide by 0 in feature importance when no split is found.

python-package/xgboost/core.py
https://github.com/dmlc/xgboost/pull/6708/checks?check_run_id=1906345707
=> Fix pylint.

python-package/xgboost/sklearn.py
* Use inplace predict for sklearn when possible.
Close https://github.com/dmlc/xgboost/pull/6638 .
=> Use inplace predict for sklearn.

R-package/src/xgboost_R.cc, include/xgboost/data.h, plugin/lz4/sparse_page_lz4_format.cc, src/common/column_matrix.h, src/common/hist_util.cc, src/common/hist_util.h, src/common/quantile.cc, src/common/threading_utils.h, src/common/transform.h, src/data/data.cc, src/gbm/gblinear.cc, src/gbm/gbtree.cc, src/linear/coordinate_common.h, src/linear/updater_shotgun.cc, src/metric/elementwise_metric.cu, src/metric/multiclass_metric.cu, src/metric/rank_metric.cc, src/metric/survival_metric.cu, src/objective/rank_obj.cu, src/objective/regression_obj.cu, src/predictor/cpu_predictor.cc, src/tree/updater_basemaker-inl.h, src/tree/updater_colmaker.cc, src/tree/updater_histmaker.cc, src/tree/updater_quantile_hist.cc, src/tree/updater_refresh.cc
See https://github.com/dmlc/xgboost/issues/6664.
All OpenMP regions now use an exception collector to rethrow the exceptions in the main thread.
=> Improve OpenMP exception handling

CMakeLists.txt
This is the fix for the issues #6734
=> fix relocatable include in CMakeList (#6734)

include/xgboost/span.h, src/common/device_helpers.cuh, tests/cpp/common/test_device_helpers.cu
Extracted from https://github.com/dmlc/xgboost/pull/6747 .
=> Add device argsort.

src/metric/elementwise_metric.cu, tests/python/test_eval_metrics.py
Close https://github.com/dmlc/xgboost/pull/6728 .
=> Fix gamma deviance

src/metric/elementwise_metric.cu, src/objective/regression_obj.cu, tests/cpp/objective/test_regression_obj.cc
Close https://github.com/dmlc/xgboost/issues/6723 .
=> Verify strictly positive for gamma regression.

.github/workflows/main.yml
Closes #6748
See the test result at https://github.com/hcho3/xgboost/runs/2190551947
cc @Craigacp
=> [CI] Upload `xgboost4j.dll` to public S3 bucket

demo/guide-python/predict_first_ntree.py
- Remove use of deprecated `ntree_limit`.
- Add sklearn demo.
=> Update demo for prediction.

src/c_api/c_api.cc, src/c_api/c_api.cu, src/c_api/c_api_utils.h, src/data/device_adapter.cuh, src/predictor/gpu_predictor.cu, tests/cpp/common/test_json.cc, tests/python-gpu/test_gpu_prediction.py, tests/python/test_predict.py
* Fix missing value on GPU in-place predict.
* Accept integer as missing value.
=> Fix inplace predict missing value.

python-package/xgboost/core.py, python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
* Update the use of JSON.
* Remove unnecessary type cast.
=> Update document for sklearn model IO.

tests/python-gpu/test_gpu_with_dask.py
Unblock the CI for now.  Tracking issue: https://github.com/rapidsai/cudf/issues/7722 .
=> Use CPU input for test_boost_from_prediction.

include/xgboost/c_api.h, include/xgboost/learner.h, python-package/xgboost/core.py, src/c_api/c_api.cc, src/c_api/c_api_utils.h, tests/python/test_predict.py
Add a prediction type for approximated interaction.
=> Fix approximated predict contribution.

python-package/xgboost/core.py, tests/python/test_interaction_constraints.py, tests/python/test_monotone_constraints.py
=> Support configuring constraints by feature names

python-package/xgboost/dask.py, python-package/xgboost/sklearn.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_with_dask.py
* Use `output_margin` for `softmax`.
* Add test for dask binary cls.
=> [back port] More general predict proba. (#6817)

src/common/device_helpers.cuh
Address comment https://github.com/dmlc/xgboost/pull/6826#discussion_r607460695 by @vkuzmin-uber
=> Use constexpr in `dh::CopyIf`.

demo/dask/cpu_survival.py
https://github.com/dmlc/xgboost/issues/6139#issuecomment-818996062
=> Add demo for using AFT survival with Dask

.github/workflows/r_tests.yml
* Install pandoc, pandoc-citeproc on CI.
=> [backport] Update dmlc-core. (#6862)

R-package/R/callbacks.R
=> Removed typo in callbacks.R

src/common/device_helpers.cuh, src/metric/auc.cu
=> [back port] Copy output data for argsort. (#6866)

NEWS.md
Waiting for https://github.com/dmlc/xgboost/pull/6874 .
=> 1.4.1 release news.

python-package/xgboost/tracker.py
Close https://github.com/dmlc/xgboost/issues/6871 .
=> Remove `setDaemon` in tracker.

.github/workflows/main.yml, doc/jvm/xgboost4j_spark_tutorial.rst, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/TrackerProperties.java
This fixes the CI failure due to internal IP on github action.
=> [jvm-packages] Add `XGBOOST_RABIT_TRACKER_IP_FOR_TEST` to set rabit tracker IP.

.github/workflows/main.yml, doc/jvm/xgboost4j_spark_tutorial.rst, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/TrackerProperties.java
=> Revert "[jvm-packages] Add `XGBOOST_RABIT_TRACKER_IP_FOR_TEST` to set rabit tracker IP."

tests/python/test_linear.py
It's non-deterministic algorithm, the test is flaky.
=> Relax shotgun test.

R-package/man/cb.gblinear.history.Rd, R-package/man/getinfo.Rd, R-package/man/print.xgb.DMatrix.Rd, R-package/man/setinfo.Rd, R-package/man/slice.xgb.DMatrix.Rd, R-package/man/xgb.DMatrix.Rd, R-package/man/xgb.DMatrix.save.Rd, R-package/man/xgb.create.features.Rd, R-package/man/xgb.cv.Rd, R-package/man/xgb.train.Rd
=> [R] Re-generate Roxygen2 doc

jvm-packages/create_jni.py, jvm-packages/xgboost4j-gpu/src, jvm-packages/xgboost4j-gpu/src/main/java, jvm-packages/xgboost4j-gpu/src/main/resources/xgboost4j-version.properties, jvm-packages/xgboost4j-gpu/src/main/scala, jvm-packages/xgboost4j-gpu/src/native, jvm-packages/xgboost4j-gpu/src/test, jvm-packages/xgboost4j-spark-gpu/src, jvm-packages/xgboost4j-spark-gpu/src/main/scala, jvm-packages/xgboost4j-spark-gpu/src/test
=> [jvm-packages] Make it easier to release GPU/CPU code artifacts to Maven Central

python-package/xgboost/dask.py, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_with_dask.py
Close https://github.com/dmlc/xgboost/issues/6939 .  Thanks for the detailed information provided by @jkc1 .
=> [dask] Set predict dataframe index.

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/NativeLibLoader.java
As discussed in #6767 and #6793 I've updated the error messages thrown when the native xgboost library fails to load in Java. It now exposes the OS and architecture and emits a different error message depending on the platform, requesting that the user installs libomp in various forms. I also added a note saying the Linux one requires glibc, as we've hit this issue when deploying XGBoost into small containers based on Alpine Linux which uses musl libc.
An example of the new error message on macOS under Java 11 is below:
```
[04/30/21 10:17:37:406] SEVERE NativeLibLoader.initXGBoost Failed to load xgboost4j due to missing native dependencies for platform macos/x86_64, this is likely due to a missing OpenMP dependency
[04/30/21 10:17:37:406] SEVERE NativeLibLoader.initXGBoost You may need …
```
=> [jvm-packages] Making the Java library loader emit helpful error messages on missing dependencies

doc/index.rst
Capitalize documentation section titles for consistency.
=> Change: contents capitalization

include/xgboost/c_api.h, python-package/xgboost/data.py, src/c_api/c_api.cc, src/data/adapter.h, src/data/data.cc, src/data/simple_dmatrix.cc
=> Support numpy array interface

python-package/xgboost/dask.py, tests/python/test_with_dask.py
Close https://github.com/dmlc/xgboost/issues/7004 .
=> Fix dask predict on `DaskDMatrix` with `iteration_range`.

python-package/xgboost/sklearn.py, src/gbm/gbtree.cc, src/gbm/gbtree.h
* Better error message.
Close https://github.com/dmlc/xgboost/issues/6990 .
=> Add predictor to skl constructor.

.travis.yml, src/data/array_interface.h, src/data/device_adapter.cuh, tests/cpp/data/test_array_interface.cc, tests/python/test_basic.py, tests/python/testing.py, tests/travis/run_test.sh
Close https://github.com/dmlc/xgboost/issues/7037 .
=> Test on s390x.

include/xgboost/predictor.h, include/xgboost/tree_model.h, src/predictor/cpu_predictor.cc, src/predictor/gpu_predictor.cu, src/tree/tree_model.cc
The error appears in our CI test for dask shap values computation.  Move the `mean_values` computation into free functions.
=> Fix race condition in CPU shap.

python-package/xgboost/callback.py
=> Fix early stopping behavior with MAPE metric

src/common/device_helpers.cuh, src/common/hist_util.cu, src/common/hist_util.cuh, src/common/host_device_vector.cu, src/common/quantile.cu, src/common/ranking_utils.cuh, src/data/data.cu, src/data/device_adapter.cuh, src/data/ellpack_page.cu, src/data/simple_dmatrix.cu, src/gbm/gbtree.cu, src/linear/updater_gpu_coordinate.cu, src/metric/auc.cu, src/metric/rank_metric.cu, src/objective/rank_obj.cu, src/predictor/gpu_predictor.cu, src/tree/gpu_hist/row_partitioner.cu, src/tree/gpu_hist/row_partitioner.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/common/test_device_helpers.cu, tests/cpp/common/test_gpu_compressed_iterator.cu, tests/cpp/common/test_span.cu, tests/cpp/data/test_device_adapter.cu, tests/cpp/data/test_ellpack_page.cu, tests/cpp/data/test_sparse_page_dmatrix.cu
It's an unused parameter, removing it can make the CI log more readable.
=> Remove use of `device_idx` in `dh::LaunchN`.

tests/python/test_with_dask.py
Prevents non-deterministic behavior like https://app.travis-ci.com/github/dmlc/xgboost/jobs/521555496 .
=> Persist data in dask test.

python-package/xgboost/dask.py
https://github.com/dmlc/xgboost/issues/7111
- make data copy for `base_margin`.
- Specify the workers.
=> [dask] Work around segfault in prediction.

demo/guide-python/README.md, demo/guide-python/continuation.py, python-package/xgboost/core.py, tests/python/test_demos.py, tests/python/test_training_continuation.py
* Set the parameters after the model being loaded.
* Add a demo for training continuation.
=> Fix parameter loading with training continuation.

R-package/R/xgb.Booster.R, R-package/tests/testthat/test_basic.R
Close https://github.com/dmlc/xgboost/issues/7125 .
=> [R] Fix softprob reshape.

python-package/xgboost/dask.py
Close https://github.com/dmlc/xgboost/issues/7111 .
=> [dask] Remove the workaround for segfault.

demo/c-api/CMakeLists.txt, demo/c-api/inference/CMakeLists.txt, demo/c-api/inference/inference.c
Close https://github.com/dmlc/xgboost/issues/7150
Close https://github.com/dmlc/xgboost/issues/7085
=> C API demo for inference.

python-package/xgboost/core.py, python-package/xgboost/training.py, src/gbm/gbtree.cc, src/learner.cc, tests/cpp/gbm/test_gbtree.cc, tests/python/test_cli.py, tests/python/test_data_iterator.py
* Use correct pointer.
* Remove best_iteration/best_score.
=> Fix model slicing.

demo/guide-python/update_process.py, doc/parameter.rst, doc/treemethod.rst, tests/python-gpu/test_gpu_demos.py, tests/python/test_demos.py
* A demo for using `prune` and `refresh`.
* Clarify the updater a bit more.
Close https://github.com/dmlc/xgboost/issues/6873 .
Close https://github.com/dmlc/xgboost/issues/7108.
=> Document for `process_type`.

doc/tutorials/feature_interaction_constraint.rst
Close https://github.com/dmlc/xgboost/issues/7142 .
=> [doc] Use figure directive.

python-package/xgboost/core.py, python-package/xgboost/data.py, python-package/xgboost/sklearn.py, src/data/data.cc, src/data/data.cu, tests/python/test_dmatrix.py, tests/python/test_with_sklearn.py
* Validate labels.
* Handle array protocal.
* Handle list with numpy.
=> Pass scikit learn estimator tests for regressor.

python-package/setup.py, python-package/xgboost/__init__.py, python-package/xgboost/compat.py, python-package/xgboost/core.py, python-package/xgboost/sklearn.py, src/tree/gpu_hist/histogram.cuh
Extracted from https://github.com/dmlc/xgboost/pull/7180 .
Along with some linter fixes.
=> Fix histogram truncation.

Jenkinsfile-win64
https://github.com/dmlc/xgboost/pull/7185#issuecomment-905392575
@trivialfis
=> [CI] Clean up in beginning of each task in Win CI

src/gbm/gblinear.cc, src/linear/updater_gpu_coordinate.cu, tests/python-gpu/load_pickle.py, tests/python-gpu/test_gpu_pickling.py
Close https://github.com/dmlc/xgboost/issues/7153 .
=> Avoid calling set device during destruction.

doc/tutorials/feature_interaction_constraint.rst
Some slight text improvements in the feature interaction tutorial. (And an attempt to place 2 tree figures correctly.)
=> DOC improve tutorial on feature interactions

python-package/xgboost/sklearn.py, tests/python-gpu/test_gpu_with_sklearn.py
Fix CI error:
https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/master/948/pipeline
https://app.travis-ci.com/github/dmlc/xgboost/jobs/537451005
=> Implement `__sklearn_is_fitted__`.

.travis.yml, tests/travis/run_test.sh, tests/travis/setup.sh
https://app.travis-ci.com/github/dmlc/xgboost/jobs/537824539
=> Fix travis.

python-package/setup.py, python-package/xgboost/callback.py, python-package/xgboost/core.py, python-package/xgboost/dask.py, python-package/xgboost/data.py, python-package/xgboost/plotting.py, python-package/xgboost/rabit.py, python-package/xgboost/sklearn.py, python-package/xgboost/tracker.py
=> Fix pylint

python-package/xgboost/dask.py, python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
Related https://github.com/dmlc/xgboost/issues/7144
=> Disable callback and ES on random forest.

doc/faq.rst, doc/python/python_intro.rst, doc/treemethod.rst
* Fix the link to demo.
* Stop recommending text file inputs.
* Brief mention to scikit-learn interface.
* Fix indent warning in tree method doc.
=> [doc] Update Python intro. [skip ci]

python-package/xgboost/data.py
A bug was found when working on https://github.com/dmlc/xgboost/pull/7242 . I will leave the test to type checking.
=> Fix initialization from pandas series.

.travis.yml
=> [CI] Rotate access keys for uploading MacOS artifacts from Travis CI

CMakeLists.txt, cmake/Utils.cmake
=> Add CMake option to use /MD runtime

src/metric/elementwise_metric.cu, tests/python/test_eval_metrics.py
Close https://github.com/dmlc/xgboost/issues/7273 .
Revert a small part of https://github.com/dmlc/xgboost/pull/6778 .
Thanks @rwjmiller for noticing.
=> Fix gamma negloglik

python-package/xgboost/dask.py, python-package/xgboost/sklearn.py, tests/python/test_callback.py
Continue the work on https://github.com/dmlc/xgboost/pull/6751 .
=> Move callbacks from `fit` to `__init__`.

.github/workflows/jvm_tests.yml, .github/workflows/python_tests.yml, .travis.yml, tests/travis/setup.sh
Co-authored-by: Hyunsu Cho <chohyu01@cs.washington.edu>
=> [backport] Move macos test to github action. (#7382)

doc/jvm/xgboost4j_spark_tutorial.rst
Close https://github.com/dmlc/xgboost/issues/7350 .
=> [doc][jvm-packages] Update information about Python tracker. [skip ci]

src/data/sparse_page_dmatrix.h, tests/cpp/helpers.cc, tests/cpp/helpers.h, tests/cpp/tree/gpu_hist/test_gradient_based_sampler.cu, tests/cpp/tree/test_gpu_hist.cu
* Add parquet build.
* Fix unity build.
Close https://github.com/dmlc/xgboost/pull/7139
=> Update dmlc-core and use data iter for GPU sampling tests.

doc/gpu/index.rst
* Remove outdated workaround and description.
Close https://github.com/dmlc/xgboost/issues/7402.
=> [doc] Update document for GPU. [skip ci]

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/DataUtils.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/PreXGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/XGBoostEstimatorCommon.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/DeterministicPartitioningSuite.scala, jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala
1. Add PreXGBoost to build RDD[Watches] from Dataset
2. Feed RDD[Watches] built from PreXGBoost to XGBoost to train
=> [jvm-packages] Rework the train pipeline

doc/gpu/index.rst, doc/jvm/xgboost4j_spark_tutorial.rst, doc/parameter.rst, doc/tutorials/kubernetes.rst, doc/tutorials/saving_model.rst, python-package/xgboost/core.py
* Fix most of the link checks from sphinx.
* Remove duplicate explicit target name.
=> [backport] Fix broken link

doc/tutorials/custom_metric_obj.rst, python-package/xgboost/sklearn.py, python-package/xgboost/training.py
The patch is too big to be backported.
=> Delay breaking changes to 1.6.

include/xgboost/intrusive_ptr.h, include/xgboost/json.h, include/xgboost/json_io.h, include/xgboost/string_view.h, src/common/json.cc, tests/cpp/common/test_json.cc, tests/cpp/common/test_string_view.cc
* Add equality operators.
* Return a view in substr.
* Add proper iterator types.
Part of https://github.com/dmlc/xgboost/pull/7405 .
=> Extract string view.

include/xgboost/c_api.h, python-package/xgboost/__init__.py, python-package/xgboost/core.py, src/c_api/c_api.cc, src/c_api/c_api.cu, src/c_api/c_api_utils.h, tests/cpp/c_api/test_c_api.cc
=> Expose build info

tests/python/test_with_dask.py, tests/python/test_with_sklearn.py
* Remove some duplicated tests.
* Remove Grid search test for dask. It doesn't work, we need a dask implementation instead of the skl impl.
=> Cleanup Python tests.

include/xgboost/linalg.h, src/common/host_device_vector.cc, src/common/host_device_vector.cu, src/common/linalg_op.cuh, src/common/linalg_op.h, tests/cpp/common/test_linalg.cc, tests/cpp/common/test_linalg.cu
* Add `Tensor` class.
* Add elementwise kernel for CPU and GPU.
* Add unravel index.
* Move some computation to compile time.
Part of https://github.com/dmlc/xgboost/pull/7405 .
=> Implement typed storage for tensor.

python-package/xgboost/tracker.py
Related https://github.com/dmlc/xgboost/issues/7436 .
Avoid a breaking change to other libraries.
=> Set use_logger in tracker to false.

R-package/tests/testthat/test_helpers.R, include/xgboost/data.h, src/data/simple_dmatrix.h, src/tree/updater_colmaker.cc, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h
* Remove hist builder dtor.
* Initialize values.
* Tolerance.
* Remove the use of nthread in col maker.
=> [backport] Fix R CRAN failures. (#7404)

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/PreXGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala
extract the common part of transform code into PreXGBoost from
XGBoostClassifier and XGBoostRegressor.
This is the second PR of https://github.com/dmlc/xgboost/pull/7361
=> Rework the transform pipeline

.github/workflows/python_tests.yml
=> [CI] Add missing step extract_branch

src/common/partition_builder.h, src/tree/updater_approx.h, tests/cpp/tree/test_approx.cc
Extracted from https://github.com/dmlc/xgboost/pull/7214 .
=> Add approx partitioner.

doc/parameter.rst, python-package/xgboost/training.py
Improving readability.
* adding url links to corresponding tutorial pages.
* correcting some highlighting mistakes.
=> Minor edits to Parameters doc page.

demo/guide-python/multioutput_regression.py, include/xgboost/objective.h, python-package/xgboost/data.py, src/data/data.cc, src/data/data.cu, src/learner.cc, src/metric/elementwise_metric.cu, src/objective/regression_obj.cu, tests/cpp/c_api/test_c_api.cc, tests/cpp/data/test_metainfo.h, tests/cpp/helpers.cc, tests/cpp/helpers.h, tests/cpp/metric/test_elementwise_metric.cc, tests/cpp/metric/test_multiclass_metric.cc, tests/cpp/test_learner.cc, tests/python-gpu/test_from_cudf.py, tests/python-gpu/test_from_cupy.py, tests/python-gpu/test_gpu_with_dask.py, tests/python-gpu/test_gpu_with_sklearn.py, tests/python/test_demos.py, tests/python/test_with_dask.py, tests/python/test_with_sklearn.py, tests/python/testing.py
Close https://github.com/dmlc/xgboost/pull/7309 .
* Add num target model parameter, which is configured from input labels.
* Change elementwise metric and indexing for weights.
* Add demo.
* Add tests.
=> Initial support for multioutput regression.

src/tree/tree_model.cc
=> Fix typo in tree_model.cc

python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
It's an attribute usually defined by sklearn estimators.
=> Define `feature_names_in_`.

src/common/bitfield.h, tests/cpp/common/test_bitfield.cc
Went unnoticed due to lack of tests for overflow.
=> Fix index type for bitfield.

src/tree/updater_quantile_hist.cc, tests/python/test_tree_regularization.py
=> Restore functionality of max_depth=0 in hist

python-package/setup.py
* Add new classifiers.
* Typehint.
=> [backport] Update setup.py. (#7360)

python-package/xgboost/core.py, tests/python/test_dmatrix.py
Close https://github.com/dmlc/xgboost/issues/7314 .
=> Implement `get_group`.

include/xgboost/tree_model.h, tests/cpp/tree/test_tree_model.cc
Changed from `int` to `uint32_t`.
=> Fix tree param feature type.

src/common/quantile.cc, tests/cpp/common/test_quantile.cc, tests/cpp/helpers.cc, tests/python-gpu/test_gpu_with_dask.py, tests/python/test_with_dask.py
* Add support for cat data in sketch allreduce.
* Share tests between CPU and GPU.
=> Support distributed CPU env for categorical data.

tests/ci_build/conda_env/cpu_test.yml
Close https://github.com/dmlc/xgboost/issues/6744
=> Test latest numpy.

demo/guide-python/custom_rmsle.py, demo/guide-python/multioutput_regression.py, doc/tutorials/categorical.rst, doc/tutorials/multioutput.rst, python-package/xgboost/sklearn.py
* Group together categorical related parameters.
* Update documents about multioutput and categorical.
=> Update document for multi output and categorical.

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoostJNI.java, jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/Booster.scala, jvm-packages/xgboost4j/src/native/xgboost4j.cpp, jvm-packages/xgboost4j/src/native/xgboost4j.h, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/BoosterImplTest.java, jvm-packages/xgboost4j/src/test/scala/ml/dmlc/xgboost4j/scala/ScalaBoosterImplSuite.scala
From https://github.com/dmlc/xgboost/pull/7545 .
=> [jvm-packages] Implement new `save_raw` in jvm-packages.

python-package/xgboost/compat.py, python-package/xgboost/data.py, tests/python/test_with_pandas.py
Close https://github.com/dmlc/xgboost/issues/7593 .
=> Support latest pandas Index type.

include/xgboost/data.h, include/xgboost/tree_updater.h, src/common/column_matrix.h, src/data/data.cc, src/data/simple_dmatrix.cc, src/data/sparse_page_source.h, src/tree/tree_updater.cc, src/tree/updater_approx.cc, src/tree/updater_basemaker-inl.h, src/tree/updater_colmaker.cc, src/tree/updater_gpu_hist.cu, src/tree/updater_histmaker.cc, src/tree/updater_prune.cc, src/tree/updater_quantile_hist.cc, src/tree/updater_quantile_hist.h, src/tree/updater_refresh.cc, tests/cpp/common/test_column_matrix.cc, tests/cpp/data/test_data.cc, tests/cpp/tree/test_quantile_hist.cc
~Stacked on https://github.com/dmlc/xgboost/pull/7589 .~
=> Remove `omp_get_max_threads` in tree updaters.

R-package/R/xgb.Booster.R
https://discuss.xgboost.ai/t/predict-with-iteration-range-bug-in-r/2639?u=hcho3
=> [R] Fix typo in docstring

python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
=> Add special handling for multi:softmax in sklearn predict

python-package/xgboost/sklearn.py
Some other parameters are still missing and rely on **kwargs, for instance parameters from
dart.
=> Add missing train parameter for sklearn interface.

R-package/DESCRIPTION
Sorry for the long delay. I will submit the CRAN package once the maintainer field is changed.
I read the cran policy:
> When a new maintainer wishes to take over a package, this should be accompanied by the written agreement of the previous maintainer (unless the package has been formally orphaned). 
@hetong007 Would you like to continue the submission (which would be great) or would you like to share the maintenance (I'm happy to do so but might not be the best person)?
=> Add cran maintainer.

R-package/DESCRIPTION
=> Add maintainer for R package.

src/tree/updater_approx.cc, src/tree/updater_gpu_hist.cu, tests/cpp/tree/test_approx.cc, tests/cpp/tree/test_prediction_cache.cc, tests/python-gpu/test_gpu_updaters.py
* Extract the test from approx for other tree methods.
* Add note on how it works.
=> Add tests for prediction cache.

Jenkinsfile, tests/ci_build/Dockerfile.gpu_build_centos7, tests/ci_build/Dockerfile.gpu_build_r_centos7, tests/ci_build/conda_env/aarch64_test.yml
For unknown reason, the `s3Upload` step in Jenkins is failing. For now, explicitly invoke `awscli`.
=> [CI] Fix S3 upload

R-package/DESCRIPTION, R-package/R/xgb.create.features.R, R-package/R/xgb.dump.R, R-package/man/xgb.create.features.Rd, R-package/man/xgb.dump.Rd, R-package/man/xgb.load.Rd, R-package/man/xgb.save.raw.Rd, R-package/vignettes/discoverYourData.Rmd
=> [R] Fix broken links.

R-package/DESCRIPTION, R-package/R/xgb.create.features.R, R-package/R/xgb.dump.R, R-package/man/xgb.create.features.Rd, R-package/man/xgb.dump.Rd, R-package/vignettes/discoverYourData.Rmd
Same as https://github.com/dmlc/xgboost/pull/7670 but for 1.5.2.
=> [1.5.2] [R] Fix broken links.

python-package/setup.py
* Update setup.py.
All our current tests are running on 3.7+.
Close https://github.com/dmlc/xgboost/issues/7367 .
=> Require Python 3.7.

Makefile, R-package/DESCRIPTION, doc/contrib/release.rst
* Change role.
* Remove cmake file when building the package.
=> Update R package description.

Jenkinsfile, tests/ci_build/Dockerfile.clang_tidy, tests/ci_build/tidy.py
Close #7366
* Upgrade to clang-tidy 11
=> Use CUDA 11 in clang-tidy

python-package/xgboost/core.py, tests/python/test_interaction_constraints.py
issue https://github.com/dmlc/xgboost/issues/7710
=> multi groups in the interaction constraints

demo/guide-python/multioutput_regression.py
@StatMixedML Feel free to take a look, would love to hear more inputs about the future development of multi-target models.
=> Demo for using custom objective with multi-target regression.

doc/install.rst
* Show Conda as an alternative installation option for Python
* Add Apple Silicon support.
=> Update install doc

Jenkinsfile-win64, tests/ci_build/conda_env/win64_test.yml
Port #7771 to the `master` branch.
=> [CI] Enable faulthandler to show details when 0xC0000005 error occurs 

dev/release-py-r.py, python-package/setup.cfg, python-package/setup.py
distutils is deprecated and replaced by other stdlib constructs.
=> Remove use of distutils.

doc/tutorials/kubernetes.rst
Updating doc links since the original XGBoost Operator has been moved into the Kubeflow Training Operator
=> Kubernetes Operator

doc/install.rst, doc/jvm/index.rst, doc/jvm/xgboost4j_spark_gpu_tutorial.rst, doc/tutorials/index.rst
This PR adds the tutorial for how to use the XGBoost4j-Spark-GPU.
=> [jvm-packages] add doc for xgboost4j-spark-gpu

doc/build.rst
=> [doc] Fix typo in build.rst

doc/jvm/index.rst
@trivialfis please help to review. Thx
=> [doc] fix a typo in jvm/index.rst [skip ci]

src/learner.cc
=> Remove warning created in 1.4.

python-package/xgboost/callback.py, python-package/xgboost/compat.py, python-package/xgboost/core.py, python-package/xgboost/rabit.py
It's a relic from Python 2 support.
=> Remove `STRING_TYPES`.

python-package/xgboost/data.py
- Copy the dataframe and perform inplace operation.
- Split up the function to avoid pylint errors.
Close https://github.com/dmlc/xgboost/issues/7842
=> Refactor pandas dataframe handling.

doc/jvm/xgboost4j_spark_tutorial.rst
=> Fix typo [skip ci]

demo/README.md
Added one more winning solution which uses XGBoost
=> updated winning solution under readme.md

src/c_api/c_api_utils.h, tests/python-gpu/test_large_input.py
Close https://github.com/dmlc/xgboost/issues/7880 .
=> Fix overflow in prediction size.

Makefile, python-package/setup.py, python-package/xgboost/compat.py, python-package/xgboost/config.py, python-package/xgboost/core.py, tests/python/testing.py
Thanks to the excellent work by @bridgream, we can run mypy on the whole Python package now.
=> Address remaining mypy errors in python package.

doc/tutorials/saving_model.rst
Follow-up to #7902
Closes #7903
=> [Doc] Warn against loading JSON from external source

tests/ci_build/Dockerfile.clang_tidy, tests/ci_build/Dockerfile.gpu, tests/ci_build/Dockerfile.gpu_build, tests/ci_build/Dockerfile.gpu_build_centos7, tests/ci_build/Dockerfile.gpu_build_r_centos7, tests/ci_build/Dockerfile.gpu_jvm, tests/ci_build/Dockerfile.jvm_gpu_build, tests/ci_build/Dockerfile.rmm, tests/ci_build/conda_env/cpu_test.yml
=> [CI] Rotate package repository keys

doc/jvm/xgboost4j_spark_tutorial.rst, doc/tutorials/saving_model.rst
@trivialfis could you help to check it
=> [doc] update doc for dumping model to be json or ubj for jvm packages

src/common/hist_util.cuh, src/common/quantile.cc, src/common/quantile.h, tests/cpp/common/test_hist_util.cc, tests/cpp/common/test_hist_util.cu, tests/cpp/common/test_hist_util.h
`constant_iterator` -> `counting_iterator` for weights.
=> Fix LTR with weighted Quantile DMatrix.

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/RabitTracker.java
Close https://github.com/dmlc/xgboost/issues/7962 .
=> [jvm-packages] Change log level for tracker message.

tests/ci_build/Dockerfile.rmm
=> Use 22.04 for RMM.

tests/cpp/tree/gpu_hist/test_driver.cu
* Initialize the training parameter.
=> Fix GPU driver test.

.github/workflows/r_tests.yml, R-package/tests/helper_scripts/run_lint.R
- Fix helper script.
- Disable test errors for now. Tracking issue: https://github.com/dmlc/xgboost/issues/8012 .
=> Fix lintr error.

tests/python-gpu/test_gpu_linear.py
Mitigate CI error: https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-8008/1/pipeline/181/
=> Reduce regularization in GPU gblinear test.

tests/ci_build/Dockerfile.jvm_gpu_build
To fix https://github.com/dmlc/xgboost/issues/7994
=> [jvm-packages] update nccl version to 2.12.12-1

R-package/src/xgboost_R.cc
https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/master/16/pipeline
=> Fix R package Windows build.

src/tree/gpu_hist/evaluate_splits.cu, src/tree/gpu_hist/evaluate_splits.cuh, src/tree/gpu_hist/row_partitioner.cuh, src/tree/hist/evaluate_splits.h, src/tree/updater_approx.cc, src/tree/updater_gpu_hist.cu, src/tree/updater_quantile_hist.cc, tests/cpp/tree/gpu_hist/test_evaluate_splits.cu, tests/cpp/tree/gpu_hist/test_row_partitioner.cu, tests/cpp/tree/test_gpu_hist.cu
- Remove unused parameter.
- Avoid comparison of different signedness.
=> Fix compiler warnings.

tests/python-gpu/test_gpu_updaters.py, tests/python/test_updaters.py
https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/master/21/pipeline/191
=> Make test for categorical data deterministic.

tests/python/test_with_dask.py
Try the repartition script from https://github.com/dmlc/xgboost/issues/7927 .
=> [dask] Mitigate non-deterministic test.

.github/workflows/main.yml, .github/workflows/python_tests.yml, tests/ci_build/conda_env/python_lint.yml, tests/ci_build/lint_python.py
- Move the helper into the XGBoost ci_build.
- Run it with multiprocessing.
=> Move pylint helper from dmlc-core.

demo/dask/README.rst, doc/conf.py, doc/tutorials/dask.rst, doc/tutorials/index.rst, python-package/xgboost/config.py, python-package/xgboost/sklearn.py, tests/ci_build/lint_python.py, tests/python/test_config.py
Related https://github.com/dmlc/xgboost/issues/7308
- Test for nested `config_context`.
- Test for thread safety of global config.
- Use config context in sklearn interface.
- Format the sklearn module.
=> Use config_context in sklearn interface.

src/c_api/c_api.cc, src/data/data.cc, tests/python/test_with_dask.py
- Try to load DMatrix binary before trying to parse text input.
- Remove some unmaintained code.
Close https://github.com/dmlc/xgboost/issues/8138 .
=> Fix loading DMatrix binary in distributed env.

python-package/xgboost/sklearn.py
Related https://github.com/dmlc/xgboost/issues/8147 .
=> [doc] Clarification for feature importance.

demo/guide-python/cat_in_the_dat.py, demo/guide-python/categorical.py, demo/guide-python/spark_estimator_examples.py, python-package/xgboost/__init__.py, python-package/xgboost/_typing.py, python-package/xgboost/compat.py, python-package/xgboost/config.py, python-package/xgboost/core.py, python-package/xgboost/dask.py, python-package/xgboost/federated.py, tests/ci_build/lint_python.py, tests/python/test_spark/test_spark_local.py, tests/python/test_spark/test_spark_local_cluster.py, tests/python/test_spark/utils.py
Picked some other files that require relatively little change.
=> Use black on more Python files.

tests/ci_build/Dockerfile.gpu_build_r_centos7
https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/master/59/pipeline
=> [CI] Fix R build on Jenkins.

python-package/xgboost/data.py
* Fix compatibility with latest cupy.
* Freeze mypy.
=> [backport] Fix compatibility with latest cupy. (#8129)

src/common/hist_util.cuh, src/common/quantile.cc, src/common/quantile.h, tests/cpp/common/test_hist_util.cc, tests/cpp/common/test_hist_util.cu, tests/cpp/common/test_hist_util.h
* Fix LTR with weighted Quantile DMatrix.
* Better tests.
=> [backport] Fix LTR with weighted Quantile DMatrix. (#7975)

dev/release-py-r.py, python-package/MANIFEST.in
- Allow optional branch.
- Add gputreeshap to manifest.
=> Fix release script.

dev/release-py-r.py, python-package/MANIFEST.in
=> Fix release script. (#8187)

plugin/federated/federated_client.h
Missed this with the last PR.
@trivialfis
=> Set max message size in insecure gRPC

doc/prediction.rst
Corrected Minor Typo in Prediction.rst Document on Line 156
=> Corrected Minor Typo in Prediction.rst Document

src/tree/gpu_hist/histogram.cu
=> Work around MSVC behavior wrt constexpr capture

doc/tutorials/dart.rst
Updated the DART paper link as it was invalid and link was broken.
=> Updated dart.rst with correct links

src/c_api/c_api.cc, src/c_api/c_api.cu, src/c_api/c_api_error.h, src/data/data.cc, tests/cpp/c_api/test_c_api.cc
This PR checks every input pointer for the C API to increase the robustness and provide informative error messages.
=> Add checks to C pointer arguments.

tests/buildkite/conftest.ps1, tests/buildkite/conftest.sh, tests/buildkite/enforce_daily_budget.sh, tests/buildkite/pipeline-mgpu.yml, tests/buildkite/pipeline-win64.yml, tests/buildkite/pipeline.yml
* Don't run other test suites until the budget tests are complete
* Ensure that multi-GPU tests run for the master branch
=> Additional improvements to CI

tests/ci_build/Dockerfile.gpu, tests/ci_build/ci_build.sh
Reduces gpu image size from 11.5GB to 8.73GB.
=> [CI] Reduce docker image size.

tests/python-gpu/test_device_quantile_dmatrix.py
Close https://github.com/dmlc/xgboost/issues/8307 .
=> Use gpu predictor for get csr test.

tests/buildkite/test-python-cpu.sh, tests/ci_build/Dockerfile.cpu
=> [CI] Set up test analytics for CPU Python tests

demo/nvflare/custom/trainer.py
Missed this during the migration.
=> Fix NVFLARE demo

SECURITY.md
Regarding the issue #8349, I've created the document but It still needs the reliability version specification and an email to report security issues.
Any other changes just let me know.
Closes #8349
=> Create Security Police

python-package/xgboost/core.py, tests/python/test_with_sklearn.py
Fixes https://github.com/dmlc/xgboost/issues/8357 .
=> Validate features for inplace predict.

doc/tutorials/spark_estimator.rst
- Quote the databricks doc on how to manage dependencies.
- Some wording changes.
=> [backport] [pyspark] Improve tutorial on enabling GPU support. (#8385) [skip ci]

tests/buildkite/build-gpu-rpkg.sh, tests/buildkite/build-rpkg-win64-gpu.ps1, tests/ci_build/build_r_pkg_with_cuda.sh, tests/ci_build/build_r_pkg_with_cuda_win64.sh, tests/ci_build/test_r_package.py
@hcho3 Is it possible to trigger a build for the R package on the PR branch instead of the master branch?
=> Fix R package build on CI.

python-package/xgboost/callback.py, python-package/xgboost/dask.py, python-package/xgboost/rabit.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py
I reproduced it on my local machine using a relative path, see https://github.com/python/mypy/issues/14042 for more info.
=> Fix mypy errors.

Makefile
For some reason, this didn't get included in https://github.com/dmlc/xgboost/pull/8428 .
=> Fix CRAN note on cleanup.

include/xgboost/data.h
=> Remove unused page size constant

python-package/xgboost/data.py, src/data/adapter.h, tests/ci_build/lint_python.py, tests/python/test_dt.py
Try to avoid a transform with a dense table.
Close https://github.com/dmlc/xgboost/issues/7642
Using 1e6x16:
MA: t(DT->XG)/t(NP->XG):  2.3788813664780304
PR: t(DT->XG)/t(NP->XG):  0.8311551647390493
=> Take datatable as row major input.

src/data/adapter.h, src/data/array_interface.h, tests/python-gpu/test_from_cupy.py
Close https://github.com/dmlc/xgboost/issues/8485 .
=> Support half type from cupy.

include/xgboost/collective/socket.h
Co-authored-by: GavinZhang <zhanggan@cn.ibm.com>
=> [backport] SO_DOMAIN do not support on IBM i, using getsockname instead (#8437)

.github/dependabot.yml
This may help us keep dependencies up to date.
=> [jvm-packages] Set up dependabot

tests/test_distributed/test_with_spark/test_spark_local.py
- Use pytest fixture for spark session.
- Replace hardcoded results.
A small part of https://github.com/dmlc/xgboost/pull/8339 https://github.com/dmlc/xgboost/pull/8272.
=> [pyspark] Refactor local tests.

doc/parameter.rst, doc/python/python_api.rst
- Remove the incorrect note about `max_cat_to_onehot`.
- Remove experimental tag on validate parameters.
=> [doc] Fix outdated document [skip ci]

.github/workflows/main.yml, .github/workflows/python_tests.yml, tests/ci_build/conda_env/cpp_test.yml, tests/ci_build/conda_env/sdist_test.yml
- Split up Linux-based test to use toolchain from conda forge.
=> [CI] Fix github action mismatched glibcxx.

src/objective/regression_loss.h
Extracted from https://github.com/dmlc/xgboost/pull/8272 .
=> Cleanup regression objectives.

python-package/xgboost/spark/core.py, tests/python/test_spark/test_spark_local.py
* [pyspark] sort qid for SparkRandker
* resolve comments
=> [backport] [pyspark] sort qid for SparkRanker (#8497)

doc/model.schema
=> Typo in model schema

python-package/xgboost/data.py, tests/python/test_quantile_dmatrix.py
Just to be consistent with DMatrix.
=> Support list and tuple for QDM.

python-package/xgboost/core.py, python-package/xgboost/dask.py
This saves us from the trouble of checking the booster.
=> Set `enable_categorical` to True in predict.

tests/cpp/common/test_categorical.cc
Apologies for the noise, did not expect msvc on buildkite to fail.
=> Fix windows build on buildkite.

tests/buildkite/test-cpp-gpu.sh
#8619
This should unblock the CI.
=> [CI] Disable gtest with RMM

python-package/xgboost/testing/data.py
fix the test failure on the CI.
=> Fix mypy errors with the latest numpy.

jvm-packages/xgboost4j-tester/get_iris.py, tests/python/test_with_shap.py
- Fix jvm package get iris.
- Skip SHAP test for now due to the failure of importing numba inside the SHAP package.
https://buildkite.com/xgboost/xgboost-ci/builds/1167
=> [CI] Fix CI with updated dependencies.

tests/test_distributed/test_with_spark/test_spark_local.py
- Convert classifier tests to pytest tests.
- Replace hardcoded tests.
Extracted from https://github.com/dmlc/xgboost/pull/8272 .
=> Refactor PySpark tests.

doc/python/python_intro.rst, python-package/xgboost/core.py, python-package/xgboost/sklearn.py, tests/python/test_with_sklearn.py
Close https://github.com/dmlc/xgboost/issues/8541 .
Close https://github.com/dmlc/xgboost/issues/8618 .
=> [doc] Document Python inputs.

R-package/src/xgboost_R.cc, R-package/tests/testthat/test_dmatrix.R
=> [R] fix CSR input.

include/xgboost/json.h, src/c_api/c_api_utils.h, tests/cpp/common/test_json.cc
- Reuse it in `GetMissing`.
- Add test.
=> Extract JSON type check.

python-package/xgboost/core.py, python-package/xgboost/data.py, src/data/array_interface.h, tests/cpp/data/test_array_interface.cc, tests/python/test_dmatrix.py
- use `np.require` to specify that the alignment is required.
- scipy csr as well.
- validate input pointer in `ArrayInterface`.
=> Make sure input numpy array is aligned.

src/data/array_interface.h
=> Workaround CUDA warning.

python-package/xgboost/callback.py, python-package/xgboost/sklearn.py, python-package/xgboost/training.py, tests/ci_build/lint_python.py
- Cleanup pylint markers.
- run formatter.
- Update examples of using callback.
=> Cleanup the callback module.

R-package/R/xgb.train.R, R-package/tests/testthat/test_basic.R
=> [R-package] Alter xgb.train() to accept multiple eval metrics as a list

.github/workflows/main.yml, .github/workflows/python_tests.yml
use `bash -l {0}` as the default so you don't have to repeat it
Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaults
=> Use `bash -l {0}` as the default so you don't have to repeat it in GitHub Actions

src/common/common.h, src/common/optional_weight.h, src/common/quantile.h, src/common/stats.cu, src/common/stats.h, src/metric/auc.cc, src/metric/auc.cu, src/metric/elementwise_metric.cu, src/objective/regression_obj.cu, tests/cpp/common/test_optional_weight.cc
- Extract optional weight from coommon.h to reduce dependency on this header.
- Add test.
=> Extract optional weight.

tests/python/test_linear.py
Close https://github.com/dmlc/xgboost/issues/8368 .
Mitigate flakey tests like https://github.com/dmlc/xgboost/actions/runs/4130695309/jobs/7137629836 .
=> Increase timeout limit for linear.

R-package/src/Makevars.in, R-package/src/Makevars.win, include/xgboost/string_view.h, src/common/ranking_utils.cc, src/common/ranking_utils.h, src/metric/rank_metric.cc, tests/cpp/common/test_ranking_utils.cc, tests/cpp/common/test_ranking_utils.cu, tests/cpp/common/test_string_view.cc
- Extract the metric parsing routine from ranking.
- Add test.
- Accept null for string view.
=> Extract make metric name from ranking metric.

README.md, demo/guide-python/categorical.py, doc/conf.py, doc/faq.rst, doc/python/model.rst, doc/tutorials/aws_yarn.rst, doc/tutorials/categorical.rst, doc/tutorials/index.rst
- Remove version specifics in cat demo.
- Remove aws yarn.
- Update faq.
- Stop mentioning MPI.
- Update sphinx inventory links.
- Fix typo.
=> [doc] Document update [skip ci]

python-package/xgboost/spark/core.py
Signed-off-by: Weichen Xu <weichen.xu@databricks.com>
=> [backport]  Fix feature types param (#8772)

src/collective/communicator-inl.h
=> Add convenience method for allgather

R-package/src/Makevars.in, R-package/src/Makevars.win, src/objective/init_estimation.cc, src/objective/init_estimation.h, src/objective/regression_obj.cu
Extract `RegInitEstimation` and rename it to `FitIntercept`. This is to prepare for reusing it with objectives other than regression.
=> Extract fit intercept.

doc/tutorials/dask.rst
Add troubleshooting notes for rabit port usage inside a container.
=> [doc] Add note for rabit port. [skip ci]

doc/tutorials/dask.rst
Related:
- https://github.com/dmlc/xgboost/issues/6905
- https://github.com/dmlc/xgboost/issues/8701
- https://github.com/dmlc/xgboost/issues/5864
=> [doc][dask] Note on reproducible result. [skip ci]

src/common/ranking_utils.cc, src/common/ranking_utils.cu, src/common/ranking_utils.cuh, src/common/ranking_utils.h, tests/cpp/common/test_ranking_utils.cc, tests/cpp/common/test_ranking_utils.cu, tests/cpp/common/test_ranking_utils.h
The cache provides storage for rank list and some utilities like sorting.
=> Implement NDCG cache.

src/predictor/cpu_predictor.cc, src/predictor/predict_fn.h, tests/cpp/helpers.cc, tests/cpp/helpers.h, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_predictor.cc, tests/cpp/predictor/test_predictor.h
- Define new tree walking routines for multi-target trees.
=> Predictor for vector leaf.

include/xgboost/cache.h, src/learner.cc, tests/python/test_basic_models.py
Close https://github.com/dmlc/xgboost/issues/8899 .
=> Clear all cache after model load.

doc/tutorials/dask.rst, src/common/device_helpers.cuh, tests/cpp/collective/test_nccl_device_communicator.cu
Shared by @eordentlich in https://github.com/dmlc/xgboost/issues/7982#issuecomment-1379390906
Close #7982 .
=> [doc] [dask] Troubleshooting NCCL errors.

python-package/xgboost/callback.py
Close https://github.com/dmlc/xgboost/issues/8862 .
=> [doc] Fix callback example.

tests/ci_build/insert_vcomp140.py
* [CI] Fix Windows wheel to be compatible with Poetry
=> [backport] [CI] Fix Windows wheel to be compatible with Poetry (#8991)

src/data/iterative_dmatrix.cc
Not a bug fix, just a safer condition.
=> [backport] Fill column size.

include/xgboost/collective/socket.h
Fix the following warning from gcc:
```
//rabit/src/allreduce_base.o
In file included from ../..//rabit/include/rabit/internal/socket.h:8,
from ../..//rabit/src/allreduce_base.h:22,
from ../..//rabit/src/allreduce_base.cc:14:
../..//include/xgboost/collective/socket.h:65:22: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
65 | #if xgboost_IS_MINGW()
|                      ^
```
=> Portable macro definition.

tests/cpp/test_learner.cc
- Add specialization for learning to rank.
After #8822, only integer label is accepted for `ndcg` and `pairwise`, and only binary is accepted for `map`. This PR assigns binary label for LTR, along with which, the tests are converted into gtest parametrized tests.
=> Convert federated tests into test suite.

tests/cpp/objective_helpers.h, tests/cpp/plugin/helpers.h, tests/cpp/plugin/test_federated_adapter.cu, tests/cpp/plugin/test_federated_communicator.cc, tests/cpp/plugin/test_federated_data.cc, tests/cpp/plugin/test_federated_learner.cc, tests/cpp/plugin/test_federated_server.cc, tests/cpp/test_learner.cc
- Add specialization to learning to rank.
Similar to #9006 .
cc @rongou
=> Convert federated learner test into test suite.

src/metric/elementwise_metric.cu
Close https://github.com/dmlc/xgboost/issues/9047
cc @rongou .
=> Fix race condition in cpp metric tests.

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/PreXGBoost.scala
As discuss in https://github.com/dmlc/xgboost/issues/4628
[PreXGBoost.scala:transformDataset](https://github.com/dmlc/xgboost/blob/a68580e2a7d84d7206165ab1f3c911886d45dcba/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/PreXGBoost.scala#L190) cause succession  training fail because it can not shutdown Rabit if iterator did not reach the end.
We shutdown Rabit only on the next() being call and hasNext() is false. As it show below.
```
override def next(): Row = {
val ret = batchIterImpl.next()
if (!batchIterImpl.hasNext) {
Rabit.shutdown()
}
ret
}
```
But when we call show() or limit() instead of collect() or write() iterator won't reach hasNext() == false
And as for prediction, we don't need Rabit anyway, so there is no point to start it at all.
This PR is to …
=> Stop using Rabit in prediction

jvm-packages/pom.xml, jvm-packages/xgboost4j-gpu/pom.xml, jvm-packages/xgboost4j-spark-gpu/pom.xml
Close https://github.com/dmlc/xgboost/pull/9042 .
Close https://github.com/dmlc/xgboost/pull/8840 .
=> [jvm-packages] Bump rapids version.

doc/conf.py, doc/requirements.txt
Close https://github.com/dmlc/xgboost/issues/9121 .
=> [doc] Replace `recommonmark` with `myst-parser`.

jvm-packages/xgboost4j-tester/generate_pom.py
Followup on https://github.com/dmlc/xgboost/pull/9078 .
=> [jvm-packages] Remove akka in tester.

python-package/xgboost/testing/__init__.py, tests/python-gpu/test_gpu_linear.py, tests/python-gpu/test_gpu_prediction.py, tests/python-gpu/test_gpu_updaters.py, tests/python/test_linear.py, tests/python/test_updaters.py, tests/test_distributed/test_gpu_with_dask/test_gpu_with_dask.py, tests/test_distributed/test_with_dask/test_with_dask.py
Do not construct or fetch data at import.
=> Import data lazily during tests.

tests/ci_build/deploy_jvm_packages.sh
Reverts dmlc/xgboost#9224 to fix the CI.
=> Revert "Publishing scala-2.13 artifacts to the maven S3 repo."

README.md, jvm-packages/README.md
=> Update outdated build badges

.github/workflows/main.yml, doc/c++.rst, doc/c.rst, doc/conf.py
* Remove Sphinx build from GH Action
* Build Doxygen as part of RTD build
* Add jQuery
=> [backport] Improve doxygen (#8959)

python-package/xgboost/sklearn.py
Close https://github.com/dmlc/xgboost/issues/9198 .
=> [doc] Clarify early stopping.

R-package/tests/testthat/test_basic.R, demo/aft_survival/aft_survival_viz_demo.py, tests/ci_build/lint_python.py
- Update the callback function.
- Add lint check.
=> Fix callback in AFT viz demo.

src/common/hist_util.cu, src/common/hist_util.cuh, tests/cpp/common/test_hist_util.cu
Close https://github.com/dmlc/xgboost/issues/9335 .
=> Remove unused weight from buffer for cat features.

src/data/gradient_index_format.cc
Close https://github.com/dmlc/xgboost/issues/9359 .
=> Allow empty page in external memory.

python-package/xgboost/core.py
If the booster doesn't have feature names while the prediction input has, there's a race condition.
=> Make feature validation immutable.

src/learner.cc, tests/cpp/test_learner.cc
Close https://github.com/dmlc/xgboost/issues/9391 .
=> Fix metric serialization.

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala
to fix https://github.com/dmlc/xgboost/issues/9409
=> [jvm-packages] set device to cuda when tree method is "gpu_hist"

cmake/Utils.cmake, src/collective/nccl_device_communicator.cu, src/collective/nccl_device_communicator.cuh, src/common/device_helpers.cuh, src/common/hist_util.cuh, src/tree/gpu_hist/row_partitioner.cu, src/tree/gpu_hist/row_partitioner.cuh, tests/cpp/tree/gpu_hist/test_row_partitioner.cu
This reverts commit f7f673b00c15458fb4dd74a2a0d2ba80369c5faf.
Close https://github.com/dmlc/xgboost/issues/9410 .
@rongou .
=> Revert "Switch to per-thread default stream (#9396)"

jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/LearningTaskParams.scala, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoost.java, jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/XGBoostTest.java
To fix https://github.com/dmlc/xgboost/issues/9377
=> [jvm-packages] automatically set the max/min direction for best score

.github/workflows/scorecards.yml
Would be great if the bots can do it.
=> [CI] Update github actions.

python-package/xgboost/spark/core.py, python-package/xgboost/spark/utils.py
Add some log for training phase
=> [pyspark] add some log

tests/python/test_with_sklearn.py
- Test model IO with gblinear.
- Fix out-dated test. `max_leaves` is now a parameter in the constructor.
=> Test scikit-learn model IO with gblinear.

R-package/R/utils.R, R-package/src/xgboost_R.cc, R-package/tests/testthat/test_custom_objective.R, include/xgboost/linalg.h, jvm-packages/xgboost4j/src/native/xgboost4j.cpp, src/c_api/c_api_utils.h
Currently, the gradient is passed as a numeric vector. We will enforce it to be a matrix instead.
Correctly handle the f-order of R matrix.
=> [R] Support multi-class custom objective.

python-package/xgboost/data.py, tests/python/test_with_pandas.py
CI is not yet enabled since pandas requires Python 3.9 now.
Close https://github.com/dmlc/xgboost/issues/9543 .
=> Support pandas 2.1.0.

doc/contrib/python_packaging.rst
=> Fix typo in python_packaging.rst

include/xgboost/c_api.h, include/xgboost/collective/socket.h, include/xgboost/json.h, include/xgboost/string_view.h, plugin/federated/federated_client.h, plugin/federated/federated_communicator.h, plugin/federated/federated_server.cc, rabit/src/allreduce_base.cc, src/collective/communicator.cc, src/collective/socket.cc, tests/cpp/collective/test_socket.cc, tests/cpp/common/test_json.cc
- Use c++-17 nodiscard and nested ns.
- Add bind method to socket.
- Remove rabit parameters.
=> Utilities and cleanups for socket.

doc/prediction.rst
Adding links to privacy-preserving Concrete ML library.
refs #9598 
CC @trivialfis 
CC @rongou
=> Adding privacy-preserving Concrete ML links (#9598)

doc/tutorials/privacy_preserving.rst
Hello this is the PR following the discussion in https://github.com/dmlc/xgboost/issues/9598.
Let me know if I should change anything!
CC @trivialfis
=> Add privacy preserving tutorial

doc/tutorials/index.rst
closes #9598
fixing a small oversight in #9610
=> Add privacy preserving tutorial to index

src/common/io.h
Related: https://github.com/dmlc/xgboost/issues/9601 https://github.com/NixOS/nixpkgs/issues/257752
=> Workaround Apple clang issue.

R-package/src/Makevars.in, R-package/src/Makevars.win, src/c_api/c_api.cc, src/data/adapter.cc, src/data/adapter.h
- Remove header dependency on c_api
- Remove remaining code for arrow.
=> Small cleanup to jvm iter adapter.

include/xgboost/c_api.h, src/c_api/c_api.cc
=> Remove `XGBoosterGetModelRaw`.

.github/workflows/main.yml, python-package/xgboost/spark/estimator.py, tests/ci_build/lint_cpp.py
- copy cpp lint from dmlc core to xgboost.
- Fix pylint errors in the spark module.
=> Fix lint errors.

.github/workflows/main.yml, tests/ci_build/lint_cmake.sh
Contributes to #9630.
Proposes added `cmakelint` to the C++ linting job in this project's CI.
Followed the suggestions from https://github.com/dmlc/xgboost/issues/9630#issuecomment-1751915022.
=> [CI] add cmakelint to C++ linting task

src/common/threading_utils.cc, src/common/threading_utils.h
Close https://github.com/dmlc/xgboost/issues/9622 .
=> Add support for cgroupv2.

CMakeLists.txt
=> Fix build for GCC 8.x

doc/tutorials/learning_to_rank.rst
`qid` should be sorted in the first snippet.
=> Update learning_to_rank.rst; Correct qid sort in snippet

src/common/ref_resource_view.h, tests/cpp/common/test_io.cc
Forward-port #9684 to the `master` branch.
=> Fix build for AppleClang 11 (#9684)

python-package/packager/nativelib.py, python-package/xgboost/libpath.py
Ref: https://github.com/conda-forge/xgboost-feedstock/pull/132#issuecomment-1767719122
=> Fix libpath logic for Windows

R-package/src/Makevars.in, R-package/src/Makevars.win, src/collective/allgather.cc, src/collective/allgather.h, src/collective/coll.cc, src/collective/coll.h, tests/cpp/collective/test_allreduce.cc
* Define the basic interface that will shared by nccl, federated and native.
=> [coll] Define interface for bridging.

plugin/federated/federated_tracker.cc, plugin/federated/federated_tracker.h, src/collective/coll.cc, src/collective/tracker.cc, src/collective/tracker.h, src/common/timer.h, tests/cpp/collective/test_tracker.cc, tests/cpp/plugin/federated/test_federated_tracker.cc
- Allow tracker to wait.
- Fix allreduce type cast
- Return args from federated tracker.
=> [coll] Improvements and fixes for tracker and allreduce.

.github/workflows/main.yml, doc/contrib/coding_guide.rst, tests/ci_build/lint_cpp.py
Close https://github.com/dmlc/xgboost/issues/9744 .
cc @david-cortes .
=> Add doc for linters and simplify c++ lint script.

python-package/xgboost/sklearn.py, python-package/xgboost/testing/ranking.py, tests/python-gpu/test_gpu_with_sklearn.py, tests/python/test_with_sklearn.py
Close https://github.com/dmlc/xgboost/issues/9718 .
=> Fix using categorical data with the score function of ranker.

jvm-packages/pom.xml, jvm-packages/xgboost4j-gpu/pom.xml, jvm-packages/xgboost4j/pom.xml
- scalatest: 3.2.17 https://github.com/dmlc/xgboost/pull/9561
- maven-checkstyle-plugin: 3.3.1 https://github.com/dmlc/xgboost/pull/9720
- maven-surefire-plugin: 3.2.2 https://github.com/dmlc/xgboost/pull/9766
- maven-project-info-reports-plugin: 3.5.0 https://github.com/dmlc/xgboost/pull/9803
- maven-javadoc-plugin: 3.6.2 https://github.com/dmlc/xgboost/pull/9767
=> [jvm-packages] Update dependencies.

tests/buildkite/test-macos-m1-clang11.sh
=> [CI] Upload libxgboost4j.dylib (M1) to S3 bucket

plugin/sycl/data.h, plugin/sycl/predictor/predictor.cc
This PR improves inference speed on sycl devices. Perf measurements demonstrate up to 2x speed up.
=> SYCL inference optimization

tests/test_distributed/test_gpu_with_dask/test_gpu_demos.py, tests/test_distributed/test_gpu_with_dask/test_gpu_with_dask.py, tests/test_distributed/test_gpu_with_spark/test_data.py, tests/test_distributed/test_gpu_with_spark/test_gpu_spark.py
Help prevent https://buildkite.com/xgboost/xgboost-ci-multi-gpu/builds/3926#018c8a1b-6310-4f4b-94b9-07eba5d456ac .
=> Add timeout for distributed GPU tests.

src/common/common.h, src/tree/tree_model.cc, tests/cpp/tree/test_tree_model.cc, tests/python/test_basic_models.py
Close https://github.com/dmlc/xgboost/issues/9922 .
=> Fix feature names with special characters.

R-package/src/xgboost_R.cc
As a follow up from https://github.com/dmlc/xgboost/pull/9929
This PR makes a check before copying data into an R array of 'int' type (32-bit, signed) that the data being copied into it can fit into the corresponding data type, and chooses a `float64` (R's 'real') otherwise, which has a wider range.
=> [R] Ensure translation from array_interface uses type of sufficient width

jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/ExternalCheckpointManagerSuite.scala, jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/ExternalCheckpointManager.java
Close https://github.com/dmlc/xgboost/issues/9953 .
=> [jvm-packages] Use UBJ for checkpoints.

python-package/xgboost/testing/data.py
Prevent future flaky tests caused by network errors like https://buildkite.com/xgboost/xgboost-ci/builds/4347 .
=> Synthesize the AMES housing dataset for tests.

demo/guide-python/callbacks.py, doc/python/python_api.rst, python-package/xgboost/callback.py, python-package/xgboost/core.py, tests/ci_build/lint_python.py, tests/python/test_callback.py, tests/test_distributed/test_with_dask/test_with_dask.py
- Update document.
Close https://github.com/dmlc/xgboost/issues/9956 .
=> Use UBJ in Python checkpoint.

demo/guide-python/quantile_regression.py
Close https://github.com/dmlc/xgboost/issues/9989 .
=> Fix quantile regression demo.

doc/R-package/index.rst, doc/requirements.txt, doc/xgboost_doc.yml
https://github.com/dmlc/xgboost/pull/10019#issuecomment-1924438225
See rendered doc at https://xgboost--10030.org.readthedocs.build/en/10030/R-package/index_base.html
=> [Doc] Fix formatting for R package doc

doc/python/python_intro.rst
update  some spelling errors in  `python_intro.rst`
=> update python intro doc

python-package/xgboost/core.py, python-package/xgboost/sklearn.py, python-package/xgboost/testing/__init__.py, tests/ci_build/lint_python.py, tests/python/test_with_sklearn.py, tests/test_distributed/test_with_dask/test_with_dask.py
Close https://github.com/dmlc/xgboost/issues/10040 .
=> Support sample weight in sklearn custom objective.

.github/workflows/python_wheels.yml
Apologies, GitHub silently failed the test.
=> [CI] Fix yml in github action.

src/common/device_helpers.cuh, src/common/timer.cc, src/data/sparse_page_source.h
Pass the thread-local configuration between threads.
=> Fix global config for external memory.

jvm-packages/pom.xml, jvm-packages/xgboost4j-gpu/pom.xml, jvm-packages/xgboost4j-tester/generate_pom.py, jvm-packages/xgboost4j/pom.xml, tests/ci_build/Dockerfile.jvm, tests/ci_build/Dockerfile.jvm_cross, tests/ci_build/Dockerfile.jvm_gpu_build
Closes #10184
Closes #10176
Closes #10168
Closes #10165
Closes #10164
Closes #10155
Closes #10062
Closes #9984
Closes #9843
=> [jvm-packages] Ombinus patch to update all minor dependencies

src/metric/auc.cc
Close https://github.com/dmlc/xgboost/issues/10183 .
=> Be more lenient on floating point error for AUC.

.github/workflows/main.yml, doc/build.rst, plugin/federated/README.md, tests/ci_build/conda_env/cpp_test.yml
- Test federated plugin with dependencies from conda.
- Revise the document for building the plugin.
Close https://github.com/dmlc/xgboost/issues/10333
=> Test federated plugin using GitHub action.

include/xgboost/c_api.h
=> ✏️ Fix typo

demo/dask/gpu_training.py, demo/dask/sklearn_gpu_training.py
Close https://github.com/dmlc/xgboost/issues/10292 .
=> [dask] Update dask demo for using the new dask backend.

.github/workflows/jvm_tests.yml, .github/workflows/r_tests.yml
Close https://github.com/dmlc/xgboost/pull/10367 .
=> Bump the cache github action to 4.0.2.

tests/buildkite/conftest.sh
Help others who want to test the latest development on that branch without building a binary wheel.
=> Enable CI binary build for the vertical federated learning branch.

doc/tutorials/external_memory.rst
- Fix typo.
- Add Python references.
=> [doc] Fixes for external memory document.

demo/guide-python/external_memory.py, src/common/hist_util.h, src/data/gradient_index.cc, src/data/histogram_cut_format.h, tests/python/test_data_iterator.py
- Fix the cut IO functions.
Close #10036
=> Fix categorical data with external memory.

doc/conf.py
https://app.readthedocs.org/projects/xgboost/builds/24754868/
I'm not entirely sure why it fails. I can build it on my machine with RTD environment variables set.
cc @hcho3 .
=> Fix read the doc on 2.1.

doc/conf.py
Port #10460 to the `master` branch.
=> Fix read the doc on 2.1. (#10460)

python-package/pyproject.toml
=> Require Pandas 1.2+

.github/workflows/main.yml, tests/ci_build/conda_env/python_lint.yml
https://github.com/pylint-dev/pylint/issues/9751
=> [CI] Temporarily pin pylint to 3.2.3

.github/workflows/freebsd.yml, rabit/include/rabit/internal/socket.h, src/c_api/coll_c_api.cc, src/collective/socket.cc, tests/cpp/collective/test_worker.h, tests/cpp/common/test_random.cc, tests/cpp/test_cache.cc, tests/cpp/test_learner.cc
@yurivict Please use this to create a patch for the 2.1.0 release.
=> Fix build and C++ tests for FreeBSD (#10480)

include/xgboost/data.h, src/common/quantile.cc, src/tree/hist/evaluate_splits.h, src/tree/hist/histogram.h, src/tree/updater_approx.cc, src/tree/updater_quantile_hist.cc, tests/cpp/tree/hist/test_histogram.cc
Cherry-pick https://github.com/dmlc/xgboost/pull/10037 . The commit author should remain unchanged.
=> [secure boost] Vertical pipeline with hist sync (#10037)

src/collective/tracker.cc, src/common/cuda_pinned_allocator.h
- Don't try to retrieve the IP address if a host is specified.
- Fix compiler deprecation warning.
=> [coll] Allow using local host w/o network for testing.

src/common/quantile.cc, src/tree/hist/evaluate_splits.h, tests/cpp/common/test_quantile.cc, tests/cpp/tree/hist/test_evaluate_splits.cc
=> [CP] [fed] Evaluation and validation w/o local feature leakage (#10079)

.github/workflows/main.yml, .github/workflows/python_tests.yml, CMakeLists.txt, plugin/CMakeLists.txt
This PR slightly changes building process for `sycl-plugin` to avoid potential problem with compilation.
=> SYCL. Minor changes in building

src/tree/gpu_hist/histogram.cu, src/tree/gpu_hist/histogram.cuh, src/tree/gpu_hist/row_partitioner.cu, src/tree/gpu_hist/row_partitioner.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/tree/gpu_hist/test_histogram.cu, tests/cpp/tree/gpu_hist/test_row_partitioner.cu, tests/cpp/tree/test_gpu_hist.cu
- support base index in histogram.
- initialize row partitions with base index
=> [EM] Handle base idx in GPU histogram.

tests/cpp/CMakeLists.txt, tests/cpp/plugin/federated/CMakeLists.txt, tests/cpp/plugin/federated/test_federated_data.cc, tests/cpp/plugin/federated/test_federated_learner.cc
- Collect all federated test files into the same directory.
- Independently list the files.
=> [fed] Split up federated test CMake file.

src/CMakeLists.txt
=> Small cleanup for CMake scripts.

tests/ci_build/conda_env/linux_sycl_test.yml
Replace conda channel for sycl dependencies.
=> SYCL. Replace channel for sycl dependencies

src/common/threading_utils.cc
Close https://github.com/dmlc/xgboost/issues/10250 .
=> Catch exceptions during file read.

plugin/federated/federated_comm.cc, plugin/federated/federated_hist.cc, plugin/federated/federated_plugin.cc, plugin/federated/federated_plugin.h
- Cleanup plugin creation.
- Initialize the histogram for both horizontal and vertical.
=> [fed] Fix horizontal hist initialization.

R-package/src/xgboost_R.cc, R-package/src/xgboost_R.h
Mostly the same work as https://github.com/dmlc/xgboost/pull/10465 .
=> [backport][R] Add `Rf_` prefix.

dev/release-artifacts.py, tests/ci_build/conda_env/python_lint.yml
Download three wheels for `xgboost-cpu`.
=> Update the release script to download xgboost-cpu

tests/python/test_tracker.py
This makes the tests easier to run and debug. In addition, they can now work on Windows as well.
=> [coll] Use loky for tests.

python-package/xgboost/core.py, python-package/xgboost/sklearn.py, tests/ci_build/conda_env/linux_cpu_test.yml, tests/ci_build/conda_env/macos_cpu_test.yml, tests/ci_build/conda_env/win64_cpu_test.yml, tests/python/test_basic.py, tests/python/test_with_sklearn.py, tests/test_distributed/test_with_dask/test_with_dask.py
See https://scikit-learn.org/stable/developers/develop.html#developer-api-for-html-representation for more info.
It's a small enhancement for having a link to XGBoost's documentation site when an object is rendered in a jupyter notebook, see the upper right corner of the object description in the figure below.
=> Support doc link for the sklearn module.

src/collective/comm.cc, src/collective/socket.cc, tests/cpp/collective/test_coll_c_api.cc
Reduce the chance of hitting `Too many open files`.
=> [coll] Reduce the amount of open files (socket).

include/xgboost/c_api.h, include/xgboost/data.h, include/xgboost/predictor.h, src/data/ellpack_page.cuh, src/predictor/gpu_predictor.cu, tests/cpp/predictor/test_gpu_predictor.cu
- Remove the unused `entry_start` parameter.
- Support batch-local row index in ellpack.
=> [EM] Support ExtMemQdm in the GPU predictor.

jvm-packages/xgboost4j/src/native/xgboost4j-gpu.cu, src/common/cuda_pinned_allocator.h, src/data/ellpack_page_source.cu, src/tree/gpu_hist/evaluate_splits.cuh, tests/cpp/common/test_cuda_host_allocator.cu
For experimenting with external memory.
=> Add managed memory allocator.

src/common/bitfield.h, src/tree/constraints.cu, tests/cpp/tree/test_constraints.cu
Ran into gtest error when testing on H100.
=> Fix potential race in feature constraint.

src/predictor/gpu_predictor.cu, tests/ci_build/Dockerfile.clang_tidy, tests/cpp/data/test_simple_dmatrix.cc, tests/cpp/gbm/test_gbtree.cc, tests/cpp/helpers.cc, tests/cpp/helpers.h, tests/cpp/objective/test_lambdarank_obj.cc, tests/cpp/predictor/test_cpu_predictor.cc, tests/cpp/predictor/test_gpu_predictor.cu, tests/cpp/predictor/test_predictor.cc, tests/cpp/predictor/test_predictor.h, tests/cpp/test_learner.cc, tests/python-gpu/test_gpu_prediction.py
- Add GPU support.
- Add external memory support.
- Update the GPU tree shap.
Close https://github.com/dmlc/xgboost/issues/8224 .
todos:
=> [EM] Support SHAP contribution with QDM.

include/xgboost/data.h, src/data/ellpack_page_raw_format.cu, src/data/ellpack_page_raw_format.h, src/data/ellpack_page_source.cu, src/data/ellpack_page_source.h, src/data/extmem_quantile_dmatrix.cc, src/data/extmem_quantile_dmatrix.cu, src/data/gradient_index_page_source.cc, src/data/gradient_index_page_source.h, src/data/sparse_page_dmatrix.cc, src/data/sparse_page_dmatrix.cu, src/data/sparse_page_source.cu, src/data/sparse_page_source.h, src/tree/updater_gpu_common.cuh, tests/cpp/data/test_ellpack_page_raw_format.cu, tests/cpp/data/test_sparse_page_raw_format.cc
- Allow customization for format read.
- Customization for the number of pre-fetch batches.
=> [EM] Pass batch parameter into extmem format.

python-package/xgboost/dask/__init__.py, tests/ci_build/conda_env/python_lint.yml, tests/test_distributed/test_gpu_with_dask/test_gpu_with_dask.py
This enables us to use the latest mypy instead of waiting for the fix from the upstream.
=> [CI] Workaround mypy errors.

src/common/device_helpers.cuh, src/common/threading_utils.cc, src/tree/gpu_hist/gradient_based_sampler.cu, src/tree/gpu_hist/gradient_based_sampler.cuh, src/tree/gpu_hist/row_partitioner.cu, src/tree/gpu_hist/row_partitioner.cuh, src/tree/updater_gpu_hist.cu, tests/cpp/tree/gpu_hist/test_gradient_based_sampler.cu, tests/python-gpu/test_gpu_data_iterator.py, tests/python/test_data_iterator.py
- Initialize one partitioner for each batch.
- Collect partition size during initialization.
- Support base ridx in the finalization.
todos:
=> [EM] Have one partitioner for each batch.

include/xgboost/c_api.h, python-package/xgboost/__init__.py, python-package/xgboost/core.py, python-package/xgboost/testing/updater.py, src/c_api/c_api.cc, src/data/batch_utils.cc, tests/python/test_data_iterator.py
Not exposed to the document yet.
- Add C API.
- Add Python API.
- Basic CPU tests.
=> [EM] Python wrapper for the `ExtMemQuantileDMatrix`.

doc/tutorials/model.rst
Typo, wrong index for ensemble members,  and some missing introductions.
=> Fix documentation in model.rst:

src/gbm/gblinear_model.h, tests/cpp/gbm/test_gblinear.cc
Close https://github.com/dmlc/xgboost/issues/10819 .
=> Check correct dump format for gblinear.

jvm-packages/pom.xml
fix https://github.com/dmlc/xgboost/issues/10316
=> [jvm-packages] fix surefire

.gitignore
Close https://github.com/dmlc/xgboost/issues/10852 .
=> Fix git ignore. [skip ci]

src/common/threading_utils.cc, src/common/threading_utils.h, tests/cpp/common/test_threading_utils.cc
Close https://github.com/dmlc/xgboost/issues/10869
=> Limit the maximum number of threads.

.github/workflows/main.yml
Related https://github.com/cpplint/cpplint/issues/293
Errors: https://github.com/dmlc/xgboost/actions/runs/11226088550/job/31205962449
=> [CI] Freeze cpplint for now.

dev/release-artifacts.py
Continue #10809
* Use precise terminologies
* Use `pathlib` instead of `os.path`
* Remove unused variables and arguments
=> Clean up and modernize release-artifacts.py

src/objective/lambdarank_obj.cc, tests/python/test_ranking.py
Close https://github.com/dmlc/xgboost/issues/10905
=> Fix unbiased ltr with training continuation.

demo/guide-python/distributed_extmem_basic.py, demo/guide-python/external_memory.py, doc/tutorials/external_memory.rst
Previously I planned to add interpolation between CPU and GPU inputs. After some thought, I believe it's not worth the effort for now. If one is using external memory, the data is likely to be large. In such a case, the GPU implementation can use up all the memory in both the host and device, making another copy of data is unwise.
=> [EM][doc] Update document for the GPU implementation.

demo/guide-python/distributed_extmem_basic.py
- Setup rmm in the initializer.
=> [EM] Small fixes for the example

src/common/quantile.cu, src/data/ellpack_page.cu, src/tree/updater_gpu_common.cuh
Make it easier to compare with old releases.
=> [backport] Fix compiling with latest CTK for the 1.7 branch.

jvm-packages/pom.xml
Close https://github.com/dmlc/xgboost/pull/10964 .
=> [jvm packages] Bump rapids version.

include/xgboost/c_api.h, jvm-packages/xgboost4j/src/native/xgboost4j-gpu.cpp, jvm-packages/xgboost4j/src/native/xgboost4j-gpu.cu, jvm-packages/xgboost4j/src/native/xgboost4j.cpp, src/c_api/c_api.cc
=> [Breaking] Remove deprecated Device QDM.

python-package/xgboost/plotting.py, tests/python/test_plotting.py, tests/python/test_with_sklearn.py
Implements https://github.com/dmlc/xgboost/issues/11008
=> Better xlabel in plot_importance()

python-package/xgboost/compat.py, python-package/xgboost/data.py
- Use cache.
- Consistent naming.
Followup of https://github.com/dmlc/xgboost/pull/11058 .
=> Consistent cached lazy load.

cmake/Utils.cmake, include/xgboost/c_api.h, include/xgboost/data.h, include/xgboost/span.h, include/xgboost/tree_model.h, src/common/host_device_vector.cu, src/common/transform_iterator.h, src/data/data.cc, src/data/iterative_dmatrix.cu, src/data/proxy_dmatrix.h, src/data/simple_dmatrix.cc, src/data/simple_dmatrix.cu, src/data/simple_dmatrix.h, tests/cpp/common/test_span.cc
- Add deduction guide for Span.
- Merge data split mode setter into the `MetaInfo` column sync method.
- Check CUDA warning for cross space function calls.
=> Various small cleanups.

tests/test_distributed/test_gpu_with_dask/test_gpu_with_dask.py
https://github.com/dmlc/xgboost/actions/runs/12366071133/job/34512736794
=> Increase timeout for Multi-GPU approx tests.

.github/workflows/r_tests.yml
https://github.com/dmlc/xgboost/actions/runs/12636079795/job/35207362833
=> [CI] Fix R error.

.github/workflows/main.yml, tests/test_distributed/test_gpu_with_dask/test_gpu_ranking.py, tests/test_distributed/test_gpu_with_dask/test_gpu_with_dask.py, tests/test_distributed/test_with_dask/test_with_dask.py
- Impose timeout.
- Fix an error when there are only two workers.
=> Some fixes for dask tests.

include/xgboost/predictor.h, src/learner.cc
https://github.com/dmlc/xgboost/actions/runs/12753664381/job/35545814750?pr=11123 .
Close https://github.com/dmlc/xgboost/issues/11103
=> Fix prediction error.

R-package/DESCRIPTION
ref https://github.com/dmlc/xgboost/issues/9734#issuecomment-2596533334
=> [R] Add myself to `DESCRIPTION`

python-package/xgboost/core.py, python-package/xgboost/dask/data.py
https://github.com/dmlc/xgboost/actions/runs/12863725003/job/35860855956
=> [dask] Remove dconcat.

tests/python/test_cli.py
Close https://github.com/dmlc/xgboost/issues/11215 .
=> Skip CLI tests if not built.

python-package/xgboost/testing/metrics.py, src/metric/elementwise_metric.cu, tests/cpp/metric/test_elementwise_metric.h
A quick-fix I used to get the evaluation metric working and some tests which catch the error.
closes #11278
=> Correct computation of metrics in multi-quantile regression.

python-package/xgboost/testing/dask.py, tests/test_distributed/test_gpu_with_dask/test_gpu_with_dask.py, tests/test_distributed/test_with_dask/test_with_dask.py
- Move the datagen function and add str inputs.
Ref: https://github.com/dmlc/xgboost/issues/11088 .
=> Test dataset for dask dataframe with str columns.

ops/script/release_artifacts.py
Port https://github.com/dmlc/xgboost/pull/11337 to the master branch.
=> [PORT] Update release script for sdist. (#11337)

src/data/ellpack_page_source.cu, src/data/ellpack_page_source.h, tests/cpp/data/test_ellpack_page_raw_format.cu
=> [EM] Fix page concatenation for validation dataset.

python-package/pyproject.toml.in
Close https://github.com/dmlc/xgboost/issues/11363 .
=> Set minimum version of pyspark to 3.4.

src/common/device_helpers.cu
Extracted from https://github.com/dmlc/xgboost/pull/11391 .
=> Make CUDA version check compatible with future versions.

dev/prepare_jvm_release.py, jvm-packages/pom.xml, jvm-packages/xgboost4j-spark-gpu/pom.xml, ops/script/change_scala_version.py
Backport #11393 to the `master` branch.
=> [jvm-packages] Update helper script for publishing Maven Central (#11393)

doc/gpu/index.rst
=> [doc] Update notes about GPU memory usage.

src/common/common.h, src/common/cuda_dr_utils.cc, src/common/cuda_dr_utils.h, src/common/device_helpers.cu, src/common/io.cc, src/common/io.h, tests/cpp/common/test_cuda_dr_utils.cc
- Parse `nvidia-smi` query to check system driver version.
todo:
Close https://github.com/dmlc/xgboost/issues/11397 .
=> Allow fallback for CUDA virtual memory.

src/common/cuda_rt_utils.h, src/common/io.cc, src/common/io.h, src/common/nvtx_utils.h, src/common/timer.cc, src/data/extmem_quantile_dmatrix.cu, src/data/gradient_index_format.cc, src/data/proxy_dmatrix.h, src/data/quantile_dmatrix.cu, src/data/sparse_page_source.h, src/tree/hist/histogram.h, src/tree/updater_quantile_hist.cc, tests/cpp/common/test_io.cc, tests/cpp/data/test_gradient_index_page_raw_format.cc
Planning to experiment with combining mmap and normal file read.
- Add a new stream backend that directly reads files in addition to the existing `mmap`.
- Some refactoring to the `nvtx` wrappers.
=> [EM] Add file read stream.

python-package/xgboost/dask/__init__.py
Upstream https://github.com/dmlc/xgboost/pull/11429 to the master branch.
- Extract the fixes.
- Set @TomAugspurger as the author.
=> [dask] Workarounds for different Dask versions.

src/data/ellpack_page.cu, src/data/ellpack_page.cuh, src/data/ellpack_page_source.h, src/data/extmem_quantile_dmatrix.cu, src/tree/gpu_hist/histogram.cu, tests/cpp/data/test_ellpack_page.cu
Branching is quite expensive on Hopper. This PR tries to reduce the amount of runtime branching.
=> Specialize for GPU dense histogram.

src/common/cuda_pinned_allocator.cc, src/common/cuda_pinned_allocator.cu, src/common/cuda_pinned_allocator.h, src/common/cuda_rt_utils.cc, src/common/cuda_rt_utils.h, src/common/io.h, src/common/ref_resource_view.cuh, src/common/resource.cuh, tests/cpp/common/test_ref_resource_view.cu
Related https://github.com/dmlc/xgboost/pull/10932 .
Also need this for the decompression engine.
=> Add wrapper for CUDA host pinned memory pool.

src/common/cuda_stream_pool.cuh, src/data/ellpack_page_source.cu, src/data/ellpack_page_source.h, tests/cpp/common/test_cuda_rt_utils.cu
Prepare for parallel decompression and copy.
Related https://github.com/dmlc/xgboost/pull/11453 .
=> Add CUDA stream pool.

CMakeLists.txt, cmake/Utils.cmake, src/common/common.h, src/common/cuda_dr_utils.cc, src/common/cuda_dr_utils.h, src/common/cuda_pinned_allocator.cu, src/common/device_compression.cu, src/common/device_compression.cuh, src/common/device_compression.h, src/common/device_helpers.cuh, src/common/ref_resource_view.cuh, src/common/ref_resource_view.h, tests/cpp/common/test_device_compression.cu
No integration yet. This PR implements basic compression and decompression.
Will update the CI image after all integration is completed.
=> Optional support for nvcomp.

src/common/cuda_dr_utils.cc, src/common/cuda_dr_utils.h, src/common/device_compression.cu, src/common/device_helpers.cu
Close https://github.com/dmlc/xgboost/issues/11463 .
=> Check nvidia smi version before loading decomp API.

python-package/xgboost/testing/updater.py
Starting with scikit-learn 1.7, the `sklearn.utils.stats._weighted_percentile` method changed its function signature. Instead of `percentile` parameter, it now expects `percentile_rank`. See https://github.com/scikit-learn/scikit-learn/pull/29034. Such incompatible changes are expected, as we are using an internal method.
This should fix errors like
```
tree_method = 'hist', weighted = True, device = 'cpu'
def run_adaptive(tree_method: str, weighted: bool, device: Device) -> None:
"""Test for adaptive trees."""
rng = np.random.RandomState(1994)
from sklearn.datasets import make_regression
from sklearn.utils import stats
n_samples = 256
X, y = make_regression(  # pylint: disable=unbalanced-tuple-unpacking
n_samples, 16, random_state=rng
)
if weighted:
w = rng.normal(size=n_samples)
w -= …
```
=> Make xgboost.testing compatible with scikit-learn 1.7

src/common/cuda_rt_utils.cc, src/common/cuda_rt_utils.h, src/common/device_compression.cu, src/common/device_compression.cuh, src/common/device_compression.h, src/data/sparse_page_source.h, tests/cpp/common/test_device_compression.cu
- Use memory pool for result allocation.
- Copy the parameters.
- Fix for numa node ID.
=> [EM] Small fixes for hardware decompression.

plugin/sycl/data/gradient_index.cc, plugin/sycl/data/gradient_index.h, tests/cpp/plugin/test_sycl_partition_builder.cc
This PR remove some unused code, and simplify internal logic for sycl::GHistIndexMatrix.
=> SYCL. Minor GHistIndexMatrix refactoring.

include/xgboost/data.h, src/c_api/c_api.cu, src/common/cuda_dr_utils.h, src/common/cuda_pinned_allocator.cu, src/common/device_compression.cu, src/common/device_compression.cuh, src/common/io.cc, src/common/io.h, src/data/ellpack_page_raw_format.cu, src/data/ellpack_page_source.cu, src/data/ellpack_page_source.h, src/data/extmem_quantile_dmatrix.cu, tests/cpp/common/test_io.cc, tests/cpp/data/test_extmem_quantile_dmatrix.cu, tests/cpp/helpers.cc, tests/cpp/helpers.h
This PR implements basic support for snappy compression with sparse data. I will follow up with an auto policy.
*todo*
=> [EM] Initial support for using snappy with sparse data.

jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java
https://github.com/dmlc/xgboost/actions/runs/15841763871/job/44655679174
Fixes parameter name errors in https://github.com/dmlc/xgboost/pull/11508 .
=> [jvm][doc] Fix param name in booster.java.

python-package/xgboost/core.py, src/data/data.cc, tests/cpp/data/test_ellpack_page_raw_format.cu, tests/cpp/data/test_extmem_quantile_dmatrix.cu
- Update document for the new adaptive cache.
=> [EM] Small tests for the no-concat option.

src/tree/gpu_hist/feature_groups.cuh, src/tree/gpu_hist/histogram.cu, tests/cpp/tree/gpu_hist/test_histogram.cu
=> Fix check in GPU histogram.

src/common/pseudo_huber.cc, src/common/pseudo_huber.h, src/metric/elementwise_metric.cu, src/objective/quantile_obj.cu, src/objective/regression_loss.h, src/objective/regression_obj.cu
Close https://github.com/dmlc/xgboost/issues/11442 .
- Split up the implementation.
=> Avoid using mean intercept for rmsle.

.github/workflows/python_wheels_winarm64.yml
=> Fix wheel upload with WoA

src/common/cuda_dr_utils.cc, src/common/resource.cu, src/tree/gpu_hist/histogram.cu, tests/cpp/common/test_cuda_host_allocator.cu, tests/cpp/common/test_device_vector.cu
- Support CTK13 in C++, run C++ tests.
- No Python test yet. We need an update from rapids.
=> Compile with CTK13.

ops/pipeline/build-variant-wheels-impl.sh
* Use the latest versions of packages
* Use CUDA range specifiers (`cuda_version_lower_bound`, `cuda_version_upper_bound`)
=> [CI] Fix variant wheel build

demo/guide-python/gpu_tree_shap.py, demo/guide-python/sklearn_examples.py, demo/guide-python/sklearn_parallel.py, demo/guide-python/update_process.py, ops/script/lint_python.py, python-package/xgboost/plotting.py, python-package/xgboost/testing/data.py, python-package/xgboost/testing/with_skl.py, tests/python/test_predict.py, tests/python/test_with_shap.py, tests/python/test_with_sklearn.py, tests/test_distributed/test_with_dask/test_with_dask.py
Avoid errors caused by internet connection https://github.com/dmlc/xgboost/actions/runs/17426781017/job/49475553158?pr=11671
Parameters are estimated using `sklearn.GaussianMixture` and `scipy.stats.norm`.
=> [test] Synthesize the California housing dataset.

ops/pipeline/build-r-docs.sh, ops/pipeline/get-image-tag.sh
ref https://github.com/dmlc/xgboost-devops/pull/44
=> Use updated R doc image.

python-package/pyproject.toml.in
=> Fix pyproject toml template.

doc/tutorials/kubernetes.rst
Kubeflow XGBoost Operator has been merged into Kubeflow Trainer https://github.com/kubeflow/trainer
=> Update references from XGBoost Operator to Kubeflow Trainer

plugin/sycl/data/gradient_index.cc, plugin/sycl/predictor/predictor.cc
Co-authored-by: Dmitry Razdoburdin <>
=> [backport][sycl] Fix set device (#11712)
